INSERT INTO customer (c_customer_sk, c_birth_month, c_current_addr_sk, c_current_cdemo_sk) VALUES (1000, 1, 2000, 3000);
INSERT INTO customer (c_customer_sk, c_birth_month, c_current_addr_sk, c_current_cdemo_sk) VALUES (1001, 5, 2001, 3001);
INSERT INTO customer_address (ca_address_sk, ca_county) VALUES (2000, 'Grays Harbor County');
INSERT INTO customer_address (ca_address_sk, ca_county) VALUES (2001, 'Kootenai County');
INSERT INTO customer_demographics (cd_demo_sk, cd_gender, cd_marital_status, cd_education_status, cd_purchase_estimate, cd_credit_rating, cd_dep_count, cd_dep_employed_count, cd_dep_college_count) VALUES (3000, 'M', 'U', 'College', 500, 'Good', 2, 1, 1);
INSERT INTO customer_demographics (cd_demo_sk, cd_gender, cd_marital_status, cd_education_status, cd_purchase_estimate, cd_credit_rating, cd_dep_count, cd_dep_employed_count, cd_dep_college_count) VALUES (3001, 'M', 'U', 'College', 1000, 'Excellent', 3, 2, 2);
INSERT INTO date_dim (d_date_sk, d_moy, d_year) VALUES (4000, 8, 1999);
INSERT INTO date_dim (d_date_sk, d_moy, d_year) VALUES (4001, 8, 1999);
INSERT INTO date_dim (d_date_sk, d_moy, d_year) VALUES (4002, 8, 1999);
INSERT INTO date_dim (d_date_sk, d_moy, d_year) VALUES (4003, 8, 1999);
INSERT INTO date_dim (d_date_sk, d_moy, d_year) VALUES (4004, 8, 1999);
INSERT INTO date_dim (d_date_sk, d_moy, d_year) VALUES (4005, 8, 1999);
INSERT INTO item (i_item_sk, i_category, i_manager_id) VALUES (5000, 'Electronics', 70);
INSERT INTO item (i_item_sk, i_category, i_manager_id) VALUES (5001, 'Music', 68);
INSERT INTO store_sales (ss_customer_sk, ss_item_sk, ss_sold_date_sk, ss_list_price, ss_sales_price) VALUES (1000, 5000, 4000, 10.0, 2.5);
INSERT INTO store_sales (ss_customer_sk, ss_item_sk, ss_sold_date_sk, ss_list_price, ss_sales_price) VALUES (1001, 5001, 4001, 10.0, 2.5);
INSERT INTO web_sales (ws_bill_customer_sk, ws_item_sk, ws_sold_date_sk, ws_list_price, ws_sales_price) VALUES (1000, 5000, 4002, 10.0, 2.5);
INSERT INTO web_sales (ws_bill_customer_sk, ws_item_sk, ws_sold_date_sk, ws_list_price, ws_sales_price) VALUES (1001, 5001, 4003, 10.0, 2.5);
INSERT INTO catalog_sales (cs_ship_customer_sk, cs_item_sk, cs_sold_date_sk, cs_list_price, cs_sales_price) VALUES (1000, 5000, 4004, 10.0, 2.5);
INSERT INTO catalog_sales (cs_ship_customer_sk, cs_item_sk, cs_sold_date_sk, cs_list_price, cs_sales_price) VALUES (1001, 5001, 4005, 10.0, 2.5);