table 'Benchmark Portfolio Mapping'
	lineageTag: 325eff0d-0a4c-482b-8be7-a218552b9ad2

	column Portfolio_Inv_Obj_Code
		dataType: string
		lineageTag: 62fd37a5-1d1d-4741-81ee-ae9a4167f5c3
		summarizeBy: none
		sourceColumn: Portfolio_Inv_Obj_Code

		annotation SummarizationSetBy = Automatic

	column BP_KEY
		dataType: string
		lineageTag: e55a35a1-da97-40b1-b98a-93564eea9b0a
		summarizeBy: none
		sourceColumn: BP_KEY

		annotation SummarizationSetBy = Automatic

	column Valuation_Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 75a4db05-e924-445f-a0d2-c984167eac37
		summarizeBy: none
		sourceColumn: Valuation_Date

		variation Variation
			isDefault
			relationship: 032ac76f-d9ad-4cef-9a5c-cec067cbe8b4
			defaultHierarchy: LocalDateTable_a46a36d2-675a-4020-a91b-c3549909ec25.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Position_Type
		dataType: string
		lineageTag: c641ca74-7b0e-4f47-810d-ee0f6cb90ace
		summarizeBy: none
		sourceColumn: Position_Type

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: string
		lineageTag: dd2b2360-a1ad-4724-bffb-8a8d256b3a79
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column Sub_Sector
		dataType: string
		lineageTag: d994427e-6af6-4cfa-9ec6-bc266ff02886
		summarizeBy: none
		sourceColumn: Sub_Sector

		annotation SummarizationSetBy = Automatic

	column Benchmark_Name
		dataType: string
		lineageTag: c03907ae-2e56-401b-bd0b-6e49e08356e4
		summarizeBy: none
		sourceColumn: Benchmark_Name

		annotation SummarizationSetBy = Automatic

	column Portfolio_Name
		dataType: string
		lineageTag: ba246a0c-36e9-4357-b419-ece9a1ae82e5
		summarizeBy: none
		sourceColumn: Portfolio_Name

		annotation SummarizationSetBy = Automatic

	column BM_PO_Obj_Code = IF('Benchmark Portfolio Mapping'[Position_Type] = "Portfolio", 'Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code], 'Benchmark Portfolio Mapping'[Benchmark_Name])
		lineageTag: 393267e7-2f5b-4b27-bf7f-aeff19cff121
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column BM_PO_Name = IF('Benchmark Portfolio Mapping'[Position_Type] = "Portfolio", 'Benchmark Portfolio Mapping'[Portfolio_Name], 'Benchmark Portfolio Mapping'[Benchmark_Name])
		lineageTag: 76d5711d-6ebb-4f2a-a399-5f821dccb9de
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Benchmark_Manager
		dataType: string
		lineageTag: 55c99350-e4f7-4875-b8e8-6037fd8fb7b6
		summarizeBy: none
		sourceColumn: Benchmark_Manager

		annotation SummarizationSetBy = Automatic

	column Portfolio_Manager
		dataType: string
		lineageTag: 086fef3e-d8ff-47b5-a9b0-bdacfe049547
		summarizeBy: none
		sourceColumn: Portfolio_Manager

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: e8288c12-40c0-433b-b5f6-23f4be6c9920
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	column Investment_Object
		dataType: string
		lineageTag: 2fef25c0-d909-4e8b-9fe0-6952589d9fca
		summarizeBy: none
		sourceColumn: Investment_Object

		annotation SummarizationSetBy = Automatic

	column TAA_Benchmark
		dataType: string
		lineageTag: ec96388b-eef0-4b51-b751-9785c177d725
		summarizeBy: none
		sourceColumn: TAA_Benchmark

		annotation SummarizationSetBy = Automatic

	column Fund
		dataType: string
		lineageTag: b13faf74-a6f3-4fb6-80a2-6e0aead5de7e
		summarizeBy: none
		sourceColumn: Fund

		annotation SummarizationSetBy = Automatic

	column BP_KEY_hashed
		dataType: int64
		formatString: 0
		lineageTag: 61ae1228-d2cb-4796-9455-299627f2e07e
		summarizeBy: none
		sourceColumn: BP_KEY_hashed

		annotation SummarizationSetBy = Automatic

	partition 'Benchmark Portfolio Mapping' = m
		mode: import
		queryGroup: Sustainalytics
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(hive_metastore_Database, each ([Name] =p_sustainalytics_database)),
				    sustainalytics_prod_Schema = #"Filtered Rows"{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_benchmark_portfolio_mapping_Table = sustainalytics_prod_Schema{[Name="semantic_benchmark_portfolio_mapping",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(semantic_benchmark_portfolio_mapping_Table,{{"Valuation_Date", type date}}),
				    #"Limit Rows" = if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				       #"Changed Type", 
				      100
				     )
				 else 
				      #"Changed Type"
				in
				    #"Limit Rows"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

