table 'Country Risk Ratings'
	lineageTag: f4192840-f519-4098-857f-ebc0ce042f5a

	measure '# of Country Risk Ratings' = COUNTROWS('Country Risk Ratings')
		formatString: 0
		lineageTag: 7eb370d7-c9c3-466d-99a4-01e97eea8ac5

	column Country
		dataType: string
		lineageTag: ccb54256-255a-4bdb-bf4f-13cf62d08fa7
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		displayFolder: Modern Slavery
		lineageTag: 954b3d53-ef10-4811-b021-8032c219365e
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	/// Population data from UN
	column Population
		dataType: string
		displayFolder: Modern Slavery
		lineageTag: 18f9c324-4efa-4c3d-9734-a1b8264dc640
		summarizeBy: none
		sourceColumn: Population

		annotation SummarizationSetBy = Automatic

	/// Est. prevalence of population in modern slavery (victims per 1,000 population) - from Global Slavery Index
	column 'Modern Slavery Prevalence Percent'
		dataType: string
		displayFolder: Modern Slavery
		lineageTag: 6ebd26ea-0247-461a-b4d4-18924e8ec842
		summarizeBy: none
		sourceColumn: Modern Slavery Prevalence Percent

		annotation SummarizationSetBy = Automatic

	/// Est. number of people in modern slavery - from Global Slavery Index
	column 'Modern Slavery Population'
		dataType: string
		displayFolder: Modern Slavery
		lineageTag: ed48f61a-6567-49ec-8205-9ed9b85f8760
		summarizeBy: none
		sourceColumn: Modern Slavery Population

		annotation SummarizationSetBy = Automatic

	/// Modern Slavery Prevalence Score Based on Modern Slavery Prevalence Percent:
	/// >7 = 5
	/// 7-6.5 = 4
	/// 6.4-4 = 3
	/// 3.9-2.5 = 2
	/// <2.5 = 1
	column 'Modern Slavery Prevalence'
		dataType: int64
		formatString: 0
		displayFolder: Modern Slavery
		lineageTag: 57fa200d-82bf-4c5b-9df4-be80032fe4d6
		summarizeBy: sum
		sourceColumn: Modern Slavery Prevalence

		annotation SummarizationSetBy = Automatic

	/// Weighting to calculate MSA combined Score
	column 'Prevalence Weighting'
		dataType: int64
		formatString: 0
		displayFolder: Modern Slavery
		lineageTag: ffc807cb-bae9-4994-8d85-99da6e54d696
		summarizeBy: sum
		sourceColumn: Prevalence Weighting

		annotation SummarizationSetBy = Automatic

	/// Vulnerability Rating from Global Slavery Index
	column 'Vulnerabiltiy Rating'
		dataType: string
		displayFolder: Modern Slavery
		lineageTag: 6b8119f1-f8d5-4319-b4d2-bb93366daa00
		summarizeBy: none
		sourceColumn: Vulnerabiltiy Rating

		annotation SummarizationSetBy = Automatic

	/// Modern Slavery Vulnerability Scores based on Vulnerability Rating from Global Slavery Index:
	/// 
	/// >55 = 5
	/// 54-45 = 4
	/// 44-35 = 3
	/// 34-25 = 2
	/// <25 = 1
	column 'Modern Slavery Vulnerability Rating'
		dataType: int64
		formatString: 0
		displayFolder: Modern Slavery
		lineageTag: 59e77d12-2039-443c-8aaa-64813371eb6d
		summarizeBy: sum
		sourceColumn: Modern Slavery Vulnerability Rating

		annotation SummarizationSetBy = Automatic

	/// Weighting to calculate MSA combined Score
	column 'Vulnerability Weighting'
		dataType: int64
		formatString: 0
		displayFolder: Modern Slavery
		lineageTag: 2b557ebe-6702-41c2-8066-762e42250c55
		summarizeBy: sum
		sourceColumn: Vulnerability Weighting

		annotation SummarizationSetBy = Automatic

	/// Government Response Rating from Global Slavery Index
	column 'Government Response Rating'
		dataType: string
		displayFolder: Modern Slavery
		lineageTag: 3a6892ac-c1d4-4090-bf99-3a2a6ff702fa
		summarizeBy: none
		sourceColumn: Government Response Rating

		annotation SummarizationSetBy = Automatic

	/// Modern Slavery Government Response Score based on Government Response Rating from Global Slavery Index: 
	/// 
	/// AAA, AA, A = 1
	/// BBB, BB = 2
	/// B, CCC = 3
	/// CC, C = 4
	/// D = 5
	column 'Modern Slavery Response'
		dataType: int64
		formatString: 0
		displayFolder: Modern Slavery
		lineageTag: 8199e3d4-4000-413a-89f3-5792fb623b88
		summarizeBy: sum
		sourceColumn: Modern Slavery Response

		annotation SummarizationSetBy = Automatic

	/// Weighting to calculate MSA combined Score
	column 'Government Response Weighting'
		dataType: double
		displayFolder: Modern Slavery
		lineageTag: d0303c95-81c1-40b7-887c-44363e834dca
		summarizeBy: sum
		sourceColumn: Government Response Weighting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Average of Prevalence; Vulnerability and Government Response Rating
	column 'COMBINED SCORE'
		dataType: double
		displayFolder: Modern Slavery
		lineageTag: 45472e01-f40e-4923-bba6-4e6f2ff1a158
		summarizeBy: sum
		sourceColumn: COMBINED SCORE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Overall Country Rating based on Country Score:
	/// 
	/// 1 = Low
	/// 
	/// 2-3 = Moderate
	/// 
	/// 4-5 = High 
	column 'Overall Country Rating'
		dataType: string
		displayFolder: Modern Slavery
		lineageTag: 8860c457-84a3-4dab-82b4-2229f29665be
		summarizeBy: none
		sourceColumn: Overall Country Rating

		annotation SummarizationSetBy = Automatic

	column 'Allens Score'
		dataType: string
		displayFolder: Modern Slavery
		lineageTag: 3252b21c-4a21-4af2-804f-b4d756911b8a
		summarizeBy: none
		sourceColumn: Allens Score

		annotation SummarizationSetBy = Automatic

	column 'Valid From'
		dataType: dateTime
		formatString: Short Date
		displayFolder: Modern Slavery
		lineageTag: 414f70e5-f523-4832-826e-4b9d05a9e140
		summarizeBy: none
		sourceColumn: Valid From

		variation Variation
			isDefault
			relationship: 8948e56f-5f04-42ea-be13-6851174bc0db
			defaultHierarchy: LocalDateTable_422864dd-5080-436f-96ae-63419802844d.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Valid To'
		dataType: dateTime
		formatString: Long Date
		displayFolder: Modern Slavery
		lineageTag: dbeae767-f6c0-4a7e-8c15-d9f68aeb2988
		summarizeBy: none
		sourceColumn: Valid To

		variation Variation
			isDefault
			relationship: 33d79194-4cf8-442a-954f-9cd4e019f089
			defaultHierarchy: LocalDateTable_40b0cd5a-e511-4df0-bc52-6943393c6dce.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Type of Rating (e.g. Modern Slavery)
	column 'ESG Metric'
		dataType: string
		lineageTag: 06e2ac1d-f6e3-4d48-aad4-c040cd9b5a88
		summarizeBy: none
		sourceColumn: ESG Metric

		annotation SummarizationSetBy = Automatic

	column Is_Current
		dataType: string
		lineageTag: e52caea4-bf21-4071-8cf7-4d87ca3dd6d2
		summarizeBy: none
		sourceColumn: Is_Current

		annotation SummarizationSetBy = Automatic

	column Is_Deleted
		dataType: string
		lineageTag: 2837ddf3-3660-4e3a-9ae3-5158254fcef1
		summarizeBy: none
		sourceColumn: Is_Deleted

		annotation SummarizationSetBy = Automatic

	column Row_SHA2
		dataType: string
		lineageTag: 5d5b1b24-59d0-407a-8e1c-5c77f6b22a85
		summarizeBy: none
		sourceColumn: Row_SHA2

		annotation SummarizationSetBy = Automatic

	column Country_Code
		dataType: string
		lineageTag: dfe8600e-90c1-4988-972c-bd0fb8eb7391
		summarizeBy: none
		sourceColumn: Country_Code

		annotation SummarizationSetBy = Automatic

	/// Country proxied if not in Global Slavery Index
	column Proxies
		dataType: string
		displayFolder: Modern Slavery
		lineageTag: 0a447105-8cf8-4384-bec6-26912eeb3c7b
		summarizeBy: none
		sourceColumn: Proxies

		annotation SummarizationSetBy = Automatic

	/// Country from Goods: Child and Forced Labour source
	column gcl_CountryArea
		dataType: string
		displayFolder: Goods and Labour
		lineageTag: 0e85761d-78c0-4549-86dc-577fa23e1da4
		summarizeBy: none
		sourceColumn: gcl_CountryArea

		annotation SummarizationSetBy = Automatic

	column gcl_OfficialName
		dataType: string
		displayFolder: Goods and Labour
		lineageTag: fe8e0285-3107-4c58-9040-8c83920fdd23
		summarizeBy: none
		sourceColumn: gcl_OfficialName

		annotation SummarizationSetBy = Automatic

	column gcl_IsoAlpha2Code
		dataType: string
		displayFolder: Goods and Labour
		lineageTag: 200d596e-773f-4f20-b7a6-e778c7398903
		summarizeBy: none
		sourceColumn: gcl_IsoAlpha2Code

		annotation SummarizationSetBy = Automatic

	column gcl_Valid_From
		dataType: dateTime
		formatString: Long Date
		displayFolder: Goods and Labour
		lineageTag: 39514405-651c-4a3d-a1b4-894c59375f1c
		summarizeBy: none
		sourceColumn: gcl_Valid_From

		variation Variation
			isDefault
			relationship: 8a407899-0079-49e0-a082-add4f32b3923
			defaultHierarchy: LocalDateTable_311d2db5-9046-4060-8311-9eeac3735665.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column gcl_Valid_To
		dataType: dateTime
		formatString: Long Date
		displayFolder: Goods and Labour
		lineageTag: 354ec7d5-b859-4b0c-b4b3-d490044d2901
		summarizeBy: none
		sourceColumn: gcl_Valid_To

		variation Variation
			isDefault
			relationship: 2e1d748d-3b0d-48da-a525-806198fe190e
			defaultHierarchy: LocalDateTable_be4c65be-a85e-47f2-9b2f-2dc8ecc45338.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Goods identified to utilise Child Labor
	column 'Goods: Child Labor'
		dataType: string
		displayFolder: Goods and Labour
		lineageTag: a22b9ed1-6635-4672-8ed9-8ba1c750e2c7
		summarizeBy: none
		sourceColumn: Goods: Child Labor

		annotation SummarizationSetBy = Automatic

	/// Goods identified to utilise Forced Labor
	column 'Goods: Forced Labor'
		dataType: string
		displayFolder: Goods and Labour
		lineageTag: 7d532b66-27df-4e72-b205-4db6c7f6b1d5
		summarizeBy: none
		sourceColumn: Goods: Forced Labor

		annotation SummarizationSetBy = Automatic

	/// Additional Notes on Modern Slavery Assessment
	column Notes
		dataType: string
		displayFolder: Modern Slavery
		lineageTag: bf29afb1-d28e-4f67-87fe-a3e136c9c567
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column 'Goods: Child and Forced Labour Concate' = CONCATENATE('Country Risk Ratings'[Goods: Child Labor],CONCATENATE(", ",'Country Risk Ratings'[Goods: Forced Labor]))
		displayFolder: Goods and Labour
		lineageTag: b1d519a3-2c8b-4546-8717-36ccac28e0d9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Market Value' = CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), CROSSFILTER('Country Risk Ratings'[Country_Code], 'ESG Country'[IsoAlpha2Code], Both),'Daily Position'[Is Latest] = "Y",'Daily Position'[Position_Type]= "Portfolio")
		lineageTag: 765b186d-a67e-4fa7-9d22-a2127e09e42b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Country Risk Ratings-45818e42-cb43-45c9-95c5-2eb44016853f' = m
		mode: import
		queryGroup: Sustainalytics
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=p_databricks_catalog,Kind="Database"]}[Data],
				    sustainalytics_Schema = hive_metastore_Database{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_esg_country_risk_rating_v1_Table = sustainalytics_Schema{[Name="semantic_esg_country_risk_rating_v1",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(semantic_esg_country_risk_rating_v1_Table,{{"Modern_Slavery_Prevalence_Percent", "Modern Slavery Prevalence Percent"}, {"Modern_Slavery_Population", "Modern Slavery Population"}, {"Modern_Slavery_Prevalence_Score", "Modern Slavery Prevalence"}, {"Prevalence_Weighting", "Prevalence Weighting"}, {"Vulnerabiltiy_Rating", "Vulnerabiltiy Rating"}, {"Modern_Slavery_Vulnerability_Rating_Score", "Modern Slavery Vulnerability Rating"}, {"Vulnerability_Weighting", "Vulnerability Weighting"}, {"Government_Response_Rating", "Government Response Rating"}, {"Esg_Metric", "ESG Metric"}, {"Valid_To", "Valid To"}, {"Valid_From", "Valid From"}, {"Allens_Score", "Allens Score"}, {"Overall_Country_Rating", "Overall Country Rating"}, {"Combined_Score", "COMBINED SCORE"}, {"Government_Response_Weighting", "Government Response Weighting"}, {"Modern_Slavery_Response", "Modern Slavery Response"}, {"Good_ChildLabor", "Goods: Child Labor"}, {"Good_ForcedLabor", "Goods: Forced Labor"} })
				      ,FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				      #"Renamed Columns", 
				      100
				     )
				 else 
				     #"Renamed Columns" 
				     in
				  FilterLogic
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

