table 'Daily Position'
	lineageTag: d5d33b5d-4d1b-4226-856f-005922e6c24d

	measure 'Active/Strategic Number of records' =
			
			CALCULATE(
			    COUNTROWS(SUMMARIZE('Daily Position','Daily Position'[Entity_Date_Key])
			    )
			)
		formatString: 0
		displayFolder: Active/Strategic
		lineageTag: c3a772d2-99a4-4dd7-b71b-b75f3e70a440

	/// Explicit measure to be used in Excel Pivot Table
	measure MARKET_VALUE_BASE_SUM = ```
			SUM('Daily Position'[MARKET VALUE BASE]) // Explicit measure to used in Excel Pivot Table
			
			```
		displayFolder: Market Value
		lineageTag: c7362add-d5df-4ffc-a5b0-d726a76eda49

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Explicit measure to be used in Excel Pivot Table
	measure QUANTITY_SUM = SUM('Daily Position'[QUANTITY]) // Explicit measure to be used in Excel Pivot Table
		lineageTag: 39a8e00a-e4f9-4716-8ebf-e3569da10526

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Portfolio MV BASE' = ```
			
			VAR Portfolio_MV_Base = CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), 
			                            ALLEXCEPT('Daily Position', 
			                            'Fund Hierarchy'[SUBSECTOR],
			                            'Daily Position'[NT_Manager], 
			                            'Daily Position'[Investment Object], 
			                            'Daily Position'[Valuation Date]),
			                            'GS Asset'[CLIENT_INSTRUMENT_MAJOR_TYPE] IN {"Collective Investment", "Equity"},
			                            NOT('GS Asset'[CLIENT_INSTRUMENT_ISSUE_TYPE] IN {"Cash", "Equity Index Futures", "Fee Accruals", "Money Market fund", "Recoverable Taxes", "Rights Issue", "Variation Margin"})
			                            )
			
			VAR Benchmark_MV_Base =  CALCULATE(CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), 
			                            ALLEXCEPT('Daily Position', 
			                            'Fund Hierarchy'[SUBSECTOR],
			                            'Daily Position'[NT_Manager], 
			                            'Daily Position'[Investment Object], 
			                            'Daily Position'[Valuation Date]),
			                            'GS Asset'[CLIENT_INSTRUMENT_MAJOR_TYPE] IN {"Collective Investment", "Equity"},
			                            NOT('GS Asset'[CLIENT_INSTRUMENT_ISSUE_TYPE] IN {"Cash", "Equity Index Futures", "Fee Accruals", "Money Market fund", "Recoverable Taxes", "Rights Issue", "Variation Margin"})
			                            ),
			                            ALLSELECTED('Daily Position'[NT_Manager], 'Daily Position'[Investment Object]), 'Daily Position'[SK ASSET], 
			                            ALLSELECTED('Fund Hierarchy'[SUBSECTOR])
			                            ) // Taking Portfolio_MV_Base and using that value for benchmarks
			                            
			                            // CROSSFILTER ( 'Daily Position'[SK ASSET], 'GS Asset'[SK_ASSET], None)) // Disabling filtering with Asset table so that Details table populates for benchmarks
			
			RETURN
			IF( SELECTEDVALUE('Daily Position'[Position_Type]) = "Portfolio",
			    Portfolio_MV_Base,
			    Benchmark_MV_Base
			)
			
			//Total Portfolio MV BASE test = CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), ALLSELECTED())
			
			```
		displayFolder: Market Value
		lineageTag: 4c043fc6-cd47-4d04-aabe-0b0c665f2788

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Portfolio_weight = ```
			
			
			VAR port_MV_base = [MARKET_VALUE_BASE_SUM]
			VAR bench_MV_base = DIVIDE (SUM('Daily Position'[BENCHMARK_WEIGHT_EOD]),100,0)*[Benchmark_MV]
			
			RETURN
			IF(
			    SELECTEDVALUE('Daily Position'[Position_Type]) = "Portfolio",
			    DIVIDE( port_MV_base, [Total Portfolio MV BASE],0),
			    DIVIDE( bench_MV_base, [Total Benchmark MV],0)
			)
			
			
			```
		formatString: 0.0000000000
		lineageTag: 5dd07830-b2d6-4c21-b897-195fad1e65af

	measure 'GS Ownership' = ```
			
			VAR Ownership_port = DIVIDE([QUANTITY_SUM], [SHARES_OUTSTANDING_SUM],0)
			
			RETURN
			IF (
			    SELECTEDVALUE('Daily Position'[Position_Type]) = "Portfolio", 
			    Ownership_port 
			    )
			
			
			```
		formatString: 0.00000000
		displayFolder: Ownership
		lineageTag: f22aadb5-857f-4311-a6a9-0e006e36b123

	measure 'MV Ownership' = ```
			
			
			VAR Accounts_owning_asset = CALCULATE(COUNT('Daily Position'[ACCOUNT REPORT NAME]), GROUPBY('Daily Position', 'Daily Position'[ACCOUNT REPORT NAME]))
			VAR asset_level_market_cap = DIVIDE([MARKET_CAP_BASE_SUM], Accounts_owning_asset)
			
			VAR Ownership_port = SUM('Daily Position'[MV_OWNERSHIP])
			VAR Ownership_bench_num = DIVIDE (SUM('Daily Position'[BENCHMARK_WEIGHT_EOD]),100,0)*[Benchmark_MV]
			VAR Ownership_bench_denom = asset_level_market_cap
			
			VAR Bloomberg_ownership = IF (
			    SELECTEDVALUE('Daily Position'[Position_Type]) = "Portfolio", // if position_type = portfolio
			    Ownership_port, 
			    DIVIDE( Ownership_bench_num, Ownership_bench_denom,0) // else if position_type = benchmark
			    )
			
			RETURN
			
			IF (
			    AND(Bloomberg_ownership = 0, [MARKET_VALUE_BASE_SUM] > 0), 
			    [GS Ownership], // Taking GS ownership if bloomberg ownership is 0% AND MV is not 0
			    Bloomberg_ownership
			    )
			
			
			```
		formatString: 0.0000%;-0.0000%;0.0000%
		displayFolder: Ownership
		lineageTag: 0d20313e-4515-415b-8827-572449c894ba

	measure MARKET_CAP_BASE_SUM = ```
			SUM('Daily Position'[Market_Cap_Base]) // Explicit measure to used in Excel Pivot Table and Bloomberg MV Ownership
			
			```
		displayFolder: Market Cap
		lineageTag: bdb440b7-b956-4446-b6a4-d2743c00ec7e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Benchmark_MV = ```
			
			
			VAR MSCI_EM_subsector = "EM"
			VAR MSCI_World_subsector = "DE"
			VAR MSCI_WorldCore_subsector = "Infrastructure - Listed"
			VAR FTSE_ASFA_subsector = "AE"
			VAR FTSE_EPRA_subsector = "Property - Developed Listed"
			VAR DJ_subsector = "Infrastructure - Listed"
			
			
			// Calculating Benchmark related MVs
			VAR MSCI_EM_MV = CALCULATE(CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), 
			                            ALLEXCEPT('Daily Position', 
			                            'Daily Position'[NT_Manager], 
			                            'Daily Position'[Investment Object],
			                            'Daily Position'[Valuation Date]),
			                            'GS Asset'[CLIENT_INSTRUMENT_MAJOR_TYPE] IN {"Collective Investment", "Equity"},
			                            NOT('GS Asset'[CLIENT_INSTRUMENT_ISSUE_TYPE] IN {"Cash", "Equity Index Futures", "Fee Accruals", "Money Market fund", "Recoverable Taxes", "Rights Issue", "Variation Margin"}),
			                            'Fund Hierarchy'[SUBSECTOR] = MSCI_EM_subsector
			                            ),
			                            ALLSELECTED('Daily Position'[NT_Manager], 'Daily Position'[Investment Object])//, 'Daily Position'[SK ASSET]
			)
			
			VAR MSCI_World_MV = CALCULATE(CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), 
			                            ALLEXCEPT('Daily Position', 
			                            'Daily Position'[NT_Manager], 
			                            'Daily Position'[Investment Object], 
			                            'Daily Position'[Valuation Date]),
			                            'GS Asset'[CLIENT_INSTRUMENT_MAJOR_TYPE] IN {"Collective Investment", "Equity"},
			                            NOT('GS Asset'[CLIENT_INSTRUMENT_ISSUE_TYPE] IN {"Cash", "Equity Index Futures", "Fee Accruals", "Money Market fund", "Recoverable Taxes", "Rights Issue", "Variation Margin"}),
			                            'Fund Hierarchy'[SUBSECTOR] = MSCI_World_subsector
			                            ),
			                            ALLSELECTED('Daily Position'[NT_Manager], 'Daily Position'[Investment Object])//, 'Daily Position'[SK ASSET]
			)
			
			
			VAR MSCI_WorldCore_MV = CALCULATE(CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), 
			                            ALLEXCEPT('Daily Position', 
			                            'Daily Position'[NT_Manager], 
			                            'Daily Position'[Investment Object],
			                            'Daily Position'[Valuation Date]),
			                            'GS Asset'[CLIENT_INSTRUMENT_MAJOR_TYPE] IN {"Collective Investment", "Equity"},
			                            NOT('GS Asset'[CLIENT_INSTRUMENT_ISSUE_TYPE] IN {"Cash", "Equity Index Futures", "Fee Accruals", "Money Market fund", "Recoverable Taxes", "Rights Issue", "Variation Margin"}),
			                            'Fund Hierarchy'[SUBSECTOR] = MSCI_WorldCore_subsector
			                            ),
			                            ALLSELECTED('Daily Position'[NT_Manager], 'Daily Position'[Investment Object])//, 'Daily Position'[SK ASSET]
			)
			
			
			VAR FTSE_ASFA_MV = CALCULATE(CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), 
			                            ALLEXCEPT('Daily Position', 
			                            'Daily Position'[NT_Manager], 
			                            'Daily Position'[Investment Object],
			                            'Daily Position'[Valuation Date]),
			                            'GS Asset'[CLIENT_INSTRUMENT_MAJOR_TYPE] IN {"Collective Investment", "Equity"},
			                            NOT('GS Asset'[CLIENT_INSTRUMENT_ISSUE_TYPE] IN {"Cash", "Equity Index Futures", "Fee Accruals", "Money Market fund", "Recoverable Taxes", "Rights Issue", "Variation Margin"}),
			                            'Fund Hierarchy'[SUBSECTOR] = FTSE_ASFA_subsector
			                            ),
			                            ALLSELECTED('Daily Position'[NT_Manager], 'Daily Position'[Investment Object])//, 'Daily Position'[SK ASSET]
			)
			
			VAR FTSE_EPRA_MV = CALCULATE(CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), 
			                            ALLEXCEPT('Daily Position', 
			                            'Daily Position'[NT_Manager], 
			                            'Daily Position'[Investment Object],
			                            'Daily Position'[Valuation Date]),
			                            'GS Asset'[CLIENT_INSTRUMENT_MAJOR_TYPE] IN {"Collective Investment", "Equity"},
			                            NOT('GS Asset'[CLIENT_INSTRUMENT_ISSUE_TYPE] IN {"Cash", "Equity Index Futures", "Fee Accruals", "Money Market fund", "Recoverable Taxes", "Rights Issue", "Variation Margin"}),
			                            'Fund Hierarchy'[SUBSECTOR] = FTSE_EPRA_subsector
			                            ),
			                            ALLSELECTED('Daily Position'[NT_Manager], 'Daily Position'[Investment Object])//, 'Daily Position'[SK ASSET]
			)
			
			VAR DJ_MV = CALCULATE(CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), 
			                            ALLEXCEPT('Daily Position', 
			                            'Daily Position'[NT_Manager], 
			                            'Daily Position'[Investment Object], 
			                            'Daily Position'[Valuation Date]),
			                            'GS Asset'[CLIENT_INSTRUMENT_MAJOR_TYPE] IN {"Collective Investment", "Equity"},
			                            NOT('GS Asset'[CLIENT_INSTRUMENT_ISSUE_TYPE] IN {"Cash", "Equity Index Futures", "Fee Accruals", "Money Market fund", "Recoverable Taxes", "Rights Issue", "Variation Margin"}),
			                            'Fund Hierarchy'[SUBSECTOR] = DJ_subsector
			                            ),
			                           ALLSELECTED('Daily Position'[NT_Manager], 'Daily Position'[Investment Object])//, 'Daily Position'[SK ASSET]
			)
			
			RETURN
			SWITCH(SELECTEDVALUE('Daily Position'[Investment Object]),
			"[BM] ^MSCI EM ex China ex Selected Securities", MSCI_EM_MV,
			"[BM] MSCI EM (Emerging Markets) ex China ex Selected Securities Index", MSCI_EM_MV,
			"[BM] MSCI EM ex Selected Securities", MSCI_EM_MV,
			"[BM] MSCI World ex AU ex Selected Securities", MSCI_World_MV,
			"[BM] MSCI World Core Infrastructure", MSCI_WorldCore_MV,
			"[BM] FTSE ASFA L/M 200 Tax Exempt ex REITs Index", FTSE_ASFA_MV,
			"[BM] FTSE EPRA Nareit Developed", FTSE_EPRA_MV,
			"[BM] DJ Brookfield Global Infrastructure", DJ_MV,
			"[BM] MSCI Japan ex Select Securities", [Total Portfolio MV BASE] // no mapping for Japan asset class at the moment
			)
			
			```
		displayFolder: Benchmark
		lineageTag: 00afb906-be4f-41ab-ab67-d3d7f3a15a6a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Portfolio_weight_without_benchmarkMV = ```
			
			
			VAR port_MV_base = CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]))
			
			VAR bench_weight = DIVIDE (SUM('Daily Position'[BENCHMARK_WEIGHT_EOD]),100,0)
			                    
			
			RETURN
			IF(
			    SELECTEDVALUE('Daily Position'[Position_Type]) = "Portfolio",
			    DIVIDE( port_MV_base, [Total Portfolio MV BASE],0),
			    bench_weight
			)
			
			
			```
		lineageTag: 8e64e31f-332d-4708-84e0-02dab637e8a5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Benchmark MV' = ```
			
			
			VAR account_MV = [Benchmark_MV]
			VAR manager_MV = CALCULATE(CALCULATE(SUMX('Fund Hierarchy', [Benchmark_MV]), 
			                                                ALLEXCEPT('Daily Position', 
			                                                'Daily Position'[NT_Manager], 
			                                                'Daily Position'[Investment Object],
			                                                'Daily Position'[Valuation Date])
			                                    ),
			                            ALLSELECTED('Daily Position'[Investment Object])
			)
			
			VAR subsector_MV = CALCULATE(CALCULATE(SUMX('Fund Hierarchy', [Benchmark_MV]), 
			                                                ALLEXCEPT('Daily Position', 
			                                                'Daily Position'[NT_Manager], 
			                                                'Daily Position'[Investment Object],
			                                                'Daily Position'[Valuation Date])
			                                    ),
			                            ALLSELECTED('Daily Position'[NT_Manager],'Daily Position'[Investment Object])
			)
			VAR total_benchmark_MV = CALCULATE(CALCULATE(SUMX('Fund Hierarchy', [Benchmark_MV]), 
			                                                ALLEXCEPT('Daily Position', 
			                                                'Daily Position'[NT_Manager], 
			                                                'Daily Position'[Investment Object],
			                                                'Daily Position'[Valuation Date])
			                                    ),
			                            ALLSELECTED('Daily Position'[NT_Manager],'Daily Position'[Investment Object])
			)
			
			RETURN 
			SWITCH(TRUE(),
			    ISINSCOPE('Daily Position'[Investment Object]), account_MV,
			    ISINSCOPE('Daily Position'[NT_Manager]), manager_MV,
			    ISINSCOPE('Fund Hierarchy'[SUBSECTOR]), subsector_MV,
			    ISINSCOPE('Daily Position'[Position_Type]), total_benchmark_MV
			)
			
			```
		lineageTag: b4716194-27d9-46e2-b67b-be23f0f80330

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure BP_Ownership = ```
			
			
			If( [MARKET_CAP_BASE_SUM] <> 0 , [QUANTITY_SUM] / [SHARES_OUTSTANDING_SUM] , [MARKET_VALUE_BASE_SUM]/ [MARKET_CAP_BASE_SUM] )
			
			/*
			
			CASE   
			                              WHEN (isnull(MARKET_CAP_BASE) OR p.MARKET_CAP_BASE = 0) AND MARKET_VALUE_BASE != 0
			                              THEN CAST(p.quantity/a.SHARES_OUTSTANDING_QUANTITY AS DECIMAL(20,8))
			                              ELSE CAST(coalesce(MARKET_VALUE_BASE,0)/MARKET_CAP_BASE AS DECIMAL(20,8))
			                        END AS Ownership, */
			```
		formatString: 0.0000%;-0.0000%;0.0000%
		displayFolder: Ownership
		lineageTag: 16c18963-05af-4c91-9ef9-eecbb656ba13

	measure 'Updated Benchmark_MV' = ```
			/*CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]),
			                                ALLEXCEPT('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]))*/
			
			                        CALCULATE(CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), 
			                            ALLEXCEPT('Daily Position', 
			                            'Daily Position'[NT_Manager], 
			                            'Daily Position'[Investment Object],
			                            'Daily Position'[Valuation Date]),
			                            'GS Asset'[CLIENT_INSTRUMENT_MAJOR_TYPE] IN {"Collective Investment", "Equity"},
			                            NOT('GS Asset'[CLIENT_INSTRUMENT_ISSUE_TYPE] IN {"Cash", "Equity Index Futures", "Fee Accruals", "Money Market fund", "Recoverable Taxes", "Rights Issue", "Variation Margin"})
			                            --,
			                            --'Benchmark Portfolio Mapping'[Sub_Sector] = SELECTEDVALUE('Benchmark Portfolio Mapping'[Sub_Sector])
			                            ))
			                            --,
			                            --ALLSELECTED('Daily Position'[NT_Manager], 'Daily Position'[Investment Object])//, 'Daily Position'[SK ASSET]
			--)
			                    
			```
		displayFolder: Benchmark
		lineageTag: 80c15f14-cc81-4398-b122-b8cc9cbf9be3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Ownership_BM' = ```
			
			
			VAR Accounts_owning_asset = CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]), 'Daily Position'[Position_Type] = "Benchmark")
			
			VAR asset_level_market_cap = DIVIDE([Market_Cap_BM], Accounts_owning_asset)
			
			VAR Ownership_port = if (SELECTEDVALUE('Market Cap Type'[Market_Cap_Code]) = 1,  SUM('Daily Position'[MV_OWNERSHIP]),
			                                        if ( [Market_Cap_BM] = BLANK() || [Market_Cap_BM] = 0 ,0,([MARKET_VALUE_BASE_SUM] / [Market_Cap_BM]) * 1000000000   ))
			
			
			--SUM('Daily Position'[MV_OWNERSHIP]) 
			VAR Ownership_bench_num = DIVIDE ([Benchmark_Weight_BM],100,0)*[Market_Value_BM]
			
			
			--VAR Ownership_bench_denom = asset_level_market_cap
			
			VAR Bloomberg_ownership = IF (
			    SELECTEDVALUE('Daily Position'[Position_Type] )= "Portfolio", // if position_type = portfolio
			    Ownership_port  / 1000000000  ,     DIVIDE( Ownership_bench_num, asset_level_market_cap,0) // else if position_type = benchmark
			    )
			
			RETURN 
			IF (
			    AND( Bloomberg_ownership = 0 || ISBLANK(Bloomberg_ownership), [Market_Value_BM] > 0), 
			    [GS Ownership], // Taking GS ownership if bloomberg ownership is 0% AND MV is not 0
			    Bloomberg_ownership
			    ) 
			
			```
		formatString: 0.000000
		displayFolder: Ownership
		lineageTag: f1ca6dd9-945a-4b40-b1e3-c8db1680bd86

	measure Market_Cap_BM = ```
			
			        Var MC_Benchmark = CALCULATE(sum('Daily Position'[Market_Cap_Base]),'Daily Position'[Position_Type]= "Benchmark" )
			        Var MC_Portfolio = CALCULATE(sum('Daily Position'[Market_Cap_Base]), 'Daily Position'[Position_Type] = "Portfolio")
			        Var MC_Portfolio_MF = CALCULATE(MAX('Daily Position'[Market_Cap_Base]), 'Daily Position'[Position_Type] = "Portfolio")
			
			        Var EVIC_MC_Benchmark = CALCULATE(sum('Daily Position'[EVIC_Base]),'Daily Position'[Position_Type]= "Benchmark" )
			        Var EVIC_MC_Portfolio = CALCULATE(sum('Daily Position'[EVIC_Base]), 'Daily Position'[Position_Type] = "Portfolio")
			        Var EVIC_MC_Portfolio_MF = CALCULATE(MAX('Daily Position'[EVIC_Base]), 'Daily Position'[Position_Type] = "Portfolio")
			
			        RETURN
			
			            SWITCH(TRUE,
			                    SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" 
			                        && [Market_Cap_Switch] =1 , MC_Benchmark/1000000,
			
			                     SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio" 
			                        && [Market_Cap_Switch] = 1 && [Market_Cap_BM_Fund_Count] = 1 ,MC_Portfolio,
			
			                     SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio" 
			                        && [Market_Cap_Switch] = 1 && [Market_Cap_BM_Fund_Count] > 1 ,MC_Portfolio_MF,
			
			                     SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" 
			                        && [Market_Cap_Switch] = 2  , EVIC_MC_Benchmark/1000000,
			
			                    SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio" 
			                        && [Market_Cap_Switch]= 2  && [Market_Cap_BM_Fund_Count] = 1, EVIC_MC_Portfolio,
			
			                    SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio" 
			                        && [Market_Cap_Switch]= 2  && [Market_Cap_BM_Fund_Count] > 1, EVIC_MC_Portfolio_MF   )
			                        
			            
			```
		formatString: 0
		displayFolder: Market Cap
		lineageTag: 92af4f58-7b44-49ab-9b99-723bbca6afdb

	measure Market_Value_BM = ```
			
			        Var Benchmark = CALCULATE(sum('Daily Position'[MARKET VALUE BASE]),
			                        ALLEXCEPT('Daily Position','Daily Position'[INVESTMENT OBJECT CODE],'Daily Position'[Valuation Date]),
			                        'GS Asset'[CLIENT_INSTRUMENT_MAJOR_TYPE] IN {"Collective Investment", "Equity"},
			                         NOT('GS Asset'[CLIENT_INSTRUMENT_ISSUE_TYPE] IN {"Cash", "Equity Index Futures", "Fee Accruals", "Money Market fund", "Recoverable Taxes", "Rights Issue", "Variation Margin"}))
			
			       -- Var Benchmark = CALCULATE(sum('Daily Position'[MARKET VALUE BASE]),'Benchmark Portfolio Mapping'[Position_Type] = "Benchmark")                 
			
			        Var Portfolio = CALCULATE(sum('Daily Position'[MARKET VALUE BASE]),'Benchmark Portfolio Mapping'[Position_Type] = "Portfolio")
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark/1000000,Portfolio/1000000)
			```
		displayFolder: Market Cap
		lineageTag: 4b77b0a1-40a7-4f2a-b4c4-1ef334ff47e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Benchmark_Weight_BM = ```
			
			        Var Benchmark = CALCULATE(sum('Daily Position'[BENCHMARK_WEIGHT_EOD]),'Daily Position'[Position_Type]= "Benchmark" )
			        Var Portfolio = CALCULATE(sum('Daily Position'[BENCHMARK_WEIGHT_EOD]), 'Daily Position'[Position_Type] = "Portfolio")
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
			```
		formatString: 0.000000000
		displayFolder: Market Cap
		lineageTag: d9f8477d-deb6-4dd6-8d1f-48718dc41508

	measure Carbon_Scope_1_tonnes_CO2e_BM = ```
			
			        Var Benchmark = CALCULATE(sum('ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]), 'Daily Position'[Position_Type]= "Benchmark" )
			        Var Portfolio = CALCULATE(sum('ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]), 'Daily Position'[Position_Type] = "Portfolio")
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
			```
		formatString: 0.00
		displayFolder: Market Cap
		lineageTag: c34b52b0-cb1e-4ea1-a6d5-17001e7b7a5a

	measure Carbon_Scope_2_tonnes_CO2e_BM = ```
			
			        Var Benchmark = CALCULATE(sum('ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e]),'Daily Position'[Position_Type]= "Benchmark" )
			        Var Portfolio = CALCULATE(sum('ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e]), 'Daily Position'[Position_Type] = "Portfolio")
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
			```
		formatString: 0.00
		displayFolder: Market Cap
		lineageTag: aa56cc0a-72b3-4b99-ad47-26944e4c718f

	measure Accounts_owning_asset_BM = CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]), 'Daily Position'[Position_Type] = "Benchmark")
		formatString: 0
		displayFolder: Ownership
		lineageTag: ba61ed45-9ab8-4c78-bdbc-23d3a39f0afe

	measure Portfolio_weight_BM = ```
			
			
			VAR port_MV_base = [MARKET_VALUE_BASE_SUM]
			VAR bench_MV_base = DIVIDE (SUM('Daily Position'[BENCHMARK_WEIGHT_EOD]),100,0)*[Total Portfolio MV BASE]
			
			RETURN
			
			IF(
			    SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio",
			    DIVIDE( port_MV_base,  [Total Portfolio MV BASE],0),
			    DIVIDE( bench_MV_base, [Total Portfolio MV BASE],0)
			) 
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a297933b-b13a-4791-9549-6b1a6056e3df

	measure bench_MV_base_BM = DIVIDE (SUM('Daily Position'[BENCHMARK_WEIGHT_EOD]),100,0)*[Market_Value_BM]
		lineageTag: 028a8a6d-6481-4264-b5ba-c2301be4b9c7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Carbon_Scope_3_tonnes_CO2e_BM = ```
			
			        Var Benchmark = CALCULATE(sum('ESG Trucost Climate'[Carbon_Scope_3_tonnes_CO2e]),'Daily Position'[Position_Type]= "Benchmark" )
			        Var Portfolio = CALCULATE(sum('ESG Trucost Climate'[Carbon_Scope_3_tonnes_CO2e]), 'Daily Position'[Position_Type] = "Portfolio")
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
			```
		displayFolder: Market Cap
		lineageTag: e83db69b-fbb0-4bac-b661-6cdb3b61fbf6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV_BM' = [MARKET_VALUE_BASE_SUM] / 1000000
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Market Value
		lineageTag: 2eaebce3-3c62-419e-b051-a311ae37eeaf

	measure Portfolio_Ownership_BM =
			
			
			If( [MARKET_CAP_BASE_SUM] <> 0 || ISBLANK([MARKET_CAP_BASE_SUM]), [QUANTITY_SUM] / [SHARES_OUTSTANDING_SUM] , [MARKET_VALUE_BASE_SUM]/ [Market_Cap_BM] )
			
			--RETURN
			/*
			CASE   (TRUE,
			         WHEN (isnull(MARKET_CAP_BASE) OR p.MARKET_CAP_BASE = 0) AND MARKET_VALUE_BASE != 0
			                              THEN CAST(p.quantity/a.SHARES_OUTSTANDING_QUANTITY AS DECIMAL(20,8))
			          ELSE CAST(coalesce(MARKET_VALUE_BASE,0)/Market_Cap_BM AS DECIMAL(20,8))
			                        END AS Ownership) */
		displayFolder: Ownership
		lineageTag: 3c9c9706-7661-4e1f-97a8-6b99a83439fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Port_Ownership_BM = ```
			
			
			
			VAR Ownership_port = if (SELECTEDVALUE('Market Cap Type'[Market_Cap_Code]) = 1,  SUM('Daily Position'[MV_OWNERSHIP]),
			                                        if ( [Market_Cap_BM] = BLANK() ,0,[Market_Value_BM] / [Market_Cap_BM]))
			
			RETURN Ownership_port
			/*
			
			VAR Accounts_owning_asset = CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]), 'Daily Position'[Position_Type] = "Benchmark")
			
			VAR asset_level_market_cap = DIVIDE([Market_Cap_BM], Accounts_owning_asset)
			
			
			
			
			--SUM('Daily Position'[MV_OWNERSHIP]) 
			VAR Ownership_bench_num = DIVIDE ([Benchmark_Weight_BM],100,0)*[Market_Value_BM]
			
			
			--VAR Ownership_bench_denom = asset_level_market_cap
			
			VAR Bloomberg_ownership = IF (
			    SELECTEDVALUE('Daily Position'[Position_Type] )= "Portfolio", // if position_type = portfolio
			    Ownership_port,     DIVIDE( Ownership_bench_num, asset_level_market_cap,0) // else if position_type = benchmark
			    )
			
			RETURN
			
			IF (
			    AND( Bloomberg_ownership = 0 || ISBLANK(Bloomberg_ownership), [Market_Value_BM] > 0), 
			    [GS Ownership], // Taking GS ownership if bloomberg ownership is 0% AND MV is not 0
			    Bloomberg_ownership
			    ) */
			```
		formatString: 0.000000
		displayFolder: Ownership
		lineageTag: 99d148dc-7748-4876-92e1-5d65f91d941e

	measure Bmk_Ownership_BM = ```
			
			
			VAR Accounts_owning_asset = CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]), 'Daily Position'[Position_Type] = "Benchmark")
			
			VAR asset_level_market_cap = DIVIDE([Market_Cap_BM], Accounts_owning_asset)
			
			--SUM('Daily Position'[MV_OWNERSHIP]) 
			VAR Ownership_bench_num = DIVIDE ([Benchmark_Weight_BM],100,0)*[Market_Value_BM]
			
			VAR Ownership_bench =  DIVIDE( Ownership_bench_num, asset_level_market_cap,0)
			--VAR Ownership_bench_denom = asset_level_market_cap
			
			Return Ownership_bench
			/*
			VAR Bloomberg_ownership = IF (
			    SELECTEDVALUE('Daily Position'[Position_Type] )= "Portfolio", // if position_type = portfolio
			    Ownership_port,     DIVIDE( Ownership_bench_num, asset_level_market_cap,0) // else if position_type = benchmark
			    )
			
			RETURN
			
			IF (
			    AND( Bloomberg_ownership = 0 || ISBLANK(Bloomberg_ownership), [Market_Value_BM] > 0), 
			    [GS Ownership], // Taking GS ownership if bloomberg ownership is 0% AND MV is not 0
			    Bloomberg_ownership
			    )*/
			```
		formatString: 0.000000
		displayFolder: Ownership
		lineageTag: e0d062ec-6b13-4b34-87db-d1f9f87020a7

	measure Portfolio_Asset_weight_BM = ```
			--CALCULATE([Portfolio_weight_BM] , 'Benchmark Portfolio Mapping'[Position_Type] ="Portfolio")
			
			
			VAR port_MV_base = [MARKET_VALUE_BASE_SUM]
			RETURN 
			     DIVIDE( port_MV_base,  [Total Portfolio MV BASE],0)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4b6180e4-8ff4-4d3a-8a53-e061661996ca

	measure Benchmark_Asset_weight_BM = ```
			--CALCULATE([Portfolio_weight_BM] , 'Benchmark Portfolio Mapping'[Position_Type] ="Benchmark")
			
			            var Benchmark_Total =  CALCULATE(sum('Daily Position'[BENCHMARK_WEIGHT_EOD]),
			                                            ALLEXCEPT('Daily Position','Daily Position'[Position_Type])) 
			                                       
			
			        Var Asset_level =    sum('Daily Position'[BENCHMARK_WEIGHT_EOD])
			 
			
			        RETURN IFERROR( Asset_level/Benchmark_Total ,BLANK())
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 73e1c420-b89c-4a89-af5a-e38598ea5942

	measure Asset_Benchmark_Market_Value_BM = ```
			
			        Var Benchmark = CALCULATE(sum('Daily Position'[MARKET VALUE BASE]),ALLSELECTED('GS Asset'[LONG_ASSET_DESC]))
			        
			        Return 
			                Benchmark/1000000
			                
			```
		displayFolder: Market Cap
		lineageTag: 2608ca38-ceba-43b6-8d25-287b42e321f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Market_Cap_BM_Fund_Count = CALCULATE(DISTINCTCOUNT('Daily Position'[FUND] ),'Daily Position'[Position_Type] ="Portfolio")
		formatString: 0
		displayFolder: Market Cap
		lineageTag: a8e59568-6ee5-4b3c-8825-4722ca4a66de

	measure Scope1and2WeightedDataQualityScore =
			
			DIVIDE(
			    SUMX(
			        FILTER(
			            'Daily Position',
			            'Daily Position'[MARKET VALUE BASE] > 0 &&
			            NOT(ISBLANK(RELATED('ESG Trucost Climate'[Scope_1_2_PCAF_Financed_GHG_Data_Quality])))
			        ),
			        'Daily Position'[MARKET VALUE BASE] * RELATED('ESG Trucost Climate'[Scope_1_2_PCAF_Financed_GHG_Data_Quality])
			    ),
			    SUMX(
			        FILTER(
			            'Daily Position',
			            'Daily Position'[MARKET VALUE BASE] > 0 &&
			            NOT(ISBLANK(RELATED('ESG Trucost Climate'[Scope_1_2_PCAF_Financed_GHG_Data_Quality])))
			        ),
			        'Daily Position'[MARKET VALUE BASE]
			    )
			)
		displayFolder: PCAF
		lineageTag: 064ce18a-9b31-4cb2-a79f-6630e1decd61

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scope3DownstreamWeightedDataQualityScore =
			
			DIVIDE(
			    SUMX(
			        FILTER(
			            'Daily Position',
			            'Daily Position'[MARKET VALUE BASE] > 0 &&
			            NOT(ISBLANK(RELATED('ESG Trucost Climate'[Scope_3_Downstream_PCAF_Financed_GHG_Data_Quality])))
			        ),
			        'Daily Position'[MARKET VALUE BASE] * RELATED('ESG Trucost Climate'[Scope_3_Downstream_PCAF_Financed_GHG_Data_Quality])
			    ),
			    SUMX(
			        FILTER(
			            'Daily Position',
			            'Daily Position'[MARKET VALUE BASE] > 0 &&
			            NOT(ISBLANK(RELATED('ESG Trucost Climate'[Scope_3_Downstream_PCAF_Financed_GHG_Data_Quality])))
			        ),
			        'Daily Position'[MARKET VALUE BASE]
			    )
			)
		displayFolder: PCAF
		lineageTag: be93a0a6-6992-44bb-94be-db73c11827ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Scope3UpstreamWeightedDataQualityScore = ```
			
			DIVIDE(
			    SUMX(
			        FILTER(
			            'Daily Position',
			            'Daily Position'[MARKET VALUE BASE] > 0 &&
			            NOT(ISBLANK(RELATED('ESG Trucost Climate'[Scope_3_Upstream_PCAF_Financed_GHG_Data_Quality])))
			        ),
			        'Daily Position'[MARKET VALUE BASE] * RELATED('ESG Trucost Climate'[Scope_3_Upstream_PCAF_Financed_GHG_Data_Quality])
			    ),
			    SUMX(
			        FILTER(
			            'Daily Position',
			            'Daily Position'[MARKET VALUE BASE] > 0 &&
			            NOT(ISBLANK(RELATED('ESG Trucost Climate'[Scope_3_Upstream_PCAF_Financed_GHG_Data_Quality])))
			        ),
			        'Daily Position'[MARKET VALUE BASE]
			    )
			) 
			```
		displayFolder: PCAF
		lineageTag: 64e1be5c-5df6-46db-8b4d-5e1e5b2b854a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Percentage =
			
			DIVIDE(
			    SUM('Daily Position'[MARKET VALUE BASE]),
			    CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), ALL(semantic_gics_sasb_v1[SASB_Issue]))
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Market Value
		lineageTag: 4dc3779d-27c3-4e29-a0f9-4ef19d000fc9

	measure MarketValueAndPercentage =
			
			VAR mvRaw = SUM ( 'Daily Position'[MARKET VALUE BASE] )
			VAR mvBillions = DIVIDE ( mvRaw, 1000000000 )
			VAR pct = [Percentage]
			RETURN
			IF (
				OR ( ISBLANK ( mvRaw ), ISBLANK ( pct ) ),
				BLANK (),
				FORMAT ( mvBillions, "$#,##0.0" ) & " bn (" & FORMAT ( pct, "0.00%" ) & ")"
			)
		displayFolder: Market Value
		lineageTag: 3c27b18b-0e89-4914-a81d-e3f15cd880f4

	measure 'MV Country Risk Ratings' = SUM('Daily Position'[MARKET VALUE BASE])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Market Value
		lineageTag: a80e6748-8531-4faa-b238-8d5e02566b03

	measure Market_Value_Country =
			
			VAR _mv =
			    CALCULATE(
			        SUM( 'Daily Position'[MARKET VALUE BASE] )
			    )
			RETURN
			COALESCE( _mv, 0 )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Market Value
		lineageTag: 8cbe431e-f720-40c6-b478-7dc982d11ebb

	column 'Valuation Date'
		dataType: dateTime
		formatString: d/mm/yyyy
		lineageTag: 7b8c57a9-cb21-444a-a155-a9317b50bffd
		summarizeBy: none
		sourceColumn: Valuation Date

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	/// from IDM
	column 'Is Latest'
		dataType: string
		lineageTag: 5427bf85-6423-435b-ae7d-e59442222de0
		summarizeBy: none
		sourceColumn: Is Latest

		annotation SummarizationSetBy = Automatic

	/// from IDM
	column 'INVESTMENT OBJECT CODE'
		dataType: string
		lineageTag: 91d1b29e-8633-48d2-afea-a450f528bf91
		summarizeBy: none
		sourceColumn: INVESTMENT OBJECT CODE

		annotation SummarizationSetBy = Automatic

	/// from IDM
	column 'ACCOUNT REPORT NAME'
		dataType: string
		lineageTag: 35a5a508-ad50-421e-8260-2f530d6b1a48
		summarizeBy: none
		sourceColumn: ACCOUNT REPORT NAME

		annotation SummarizationSetBy = Automatic

	column 'SK NODE ID EFFECTIVE DATE'
		dataType: string
		displayFolder: Mapping
		lineageTag: 97bfafee-5400-416b-b5cc-a4db5dad1001
		summarizeBy: none
		sourceColumn: SK NODE ID EFFECTIVE DATE

		annotation SummarizationSetBy = Automatic

	column 'SK ASSET'
		dataType: string
		displayFolder: Mapping
		lineageTag: 77309b05-766c-4d14-bb31-a4b88f468e29
		summarizeBy: none
		sourceColumn: SK ASSET

		annotation SummarizationSetBy = Automatic

	/// from IDM
	column 'ACCOUNT BASE CURRENCY CODE'
		dataType: string
		lineageTag: 58258a5a-c373-4c5d-a5ec-048ed50a30c3
		summarizeBy: none
		sourceColumn: ACCOUNT BASE CURRENCY CODE

		annotation SummarizationSetBy = Automatic

	column 'SK OUTPUT ACCOUNT'
		dataType: string
		displayFolder: Mapping
		lineageTag: cb7e18ea-7675-4734-a4f8-054ace3640ae
		summarizeBy: none
		sourceColumn: SK OUTPUT ACCOUNT

		annotation SummarizationSetBy = Automatic

	column NT_Manager
		dataType: string
		lineageTag: 5fe7f8a7-6e30-499e-b896-022b1efec88a
		summarizeBy: none
		sourceColumn: NT_Manager

		annotation SummarizationSetBy = Automatic

	column ASSET_CLASS
		dataType: string
		lineageTag: cf7a84f8-ce9f-4d79-9265-8be376606b21
		summarizeBy: none
		sourceColumn: ASSET_CLASS

		annotation SummarizationSetBy = Automatic

	column STRATEGY
		dataType: string
		lineageTag: bc283720-b19d-40f1-b96a-4c1210bb6da1
		summarizeBy: none
		sourceColumn: STRATEGY

		annotation SummarizationSetBy = Automatic

	/// from IDM
	column FUND
		dataType: string
		lineageTag: 02d9b121-a88c-4d98-bb3e-833500e63477
		summarizeBy: none
		sourceColumn: FUND

		annotation SummarizationSetBy = Automatic

	/// from IDM
	column 'MARKET VALUE BASE'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Market Value
		lineageTag: b2ba3439-9c7b-4317-8422-139b5199e06d
		summarizeBy: sum
		sourceColumn: MARKET VALUE BASE

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Investment Object' = 'Daily Position'[ACCOUNT REPORT NAME] & IF(ISBLANK('Daily Position'[INVESTMENT OBJECT CODE]),"", ": " & 'Daily Position'[INVESTMENT OBJECT CODE])
		lineageTag: e7ba2f85-61e4-44d2-8dbb-8b2df3c5950c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Entity_Id
		dataType: string
		displayFolder: Mapping
		lineageTag: b216d4ba-e0c4-48f5-a08f-dcf19fc5464e
		summarizeBy: none
		sourceColumn: Entity_Id

		annotation SummarizationSetBy = Automatic

	column Entity_Date_Key
		dataType: string
		displayFolder: Mapping
		lineageTag: 5439db6b-ec75-4616-a6cc-c841e86d13d9
		summarizeBy: none
		sourceColumn: Entity_Date_Key

		annotation SummarizationSetBy = Automatic

	/// Security identifier mapping type (e.g. Sedol/ISIN) to Sustainalytics
	column Mapping_Type
		dataType: string
		displayFolder: Mapping
		lineageTag: e5aa7151-5762-42a6-bc68-8c9a1d9b562b
		summarizeBy: none
		sourceColumn: Mapping_Type

		annotation SummarizationSetBy = Automatic

	column 'Valuation Date - Copy'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2df01c79-b65f-497f-9454-e8069ef04935
		summarizeBy: none
		sourceColumn: Valuation Date - Copy

		variation Variation
			isDefault
			relationship: fa0c515f-1e83-4b88-a03d-887e7d7cbf29
			defaultHierarchy: LocalDateTable_f38cc27d-c93e-45bb-99b7-2d3b90702bfc.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 95c43e05-09e5-4c8d-a008-a347c5adbb9f
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 2e8c272f-3726-4ffe-8294-b1662a098102
			defaultHierarchy: LocalDateTable_42cece29-877c-4e67-8f44-ad3df9b98395.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Is the security mapped to Sustainalytics
	column Mapping_Status
		dataType: string
		displayFolder: Mapping
		lineageTag: 06394037-9a97-4251-b126-4b1fc92d3985
		summarizeBy: none
		sourceColumn: Mapping_Status

		annotation SummarizationSetBy = Automatic

	column 'MV - Country Risk Rating' =
			
			CALCULATE(Sum('Daily Position'[MARKET VALUE BASE]),'Daily Position'[Is Latest]="Y",'Daily Position'[Position_Type] = "Portfolio", ISBLANK('Fund Hierarchy'[SECTOR]) <> TRUE)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Market Value
		lineageTag: bdb10528-9993-4915-95a0-7e050e1350c4
		summarizeBy: sum

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	/// from IDM
	column HEDGING_CURRENCY
		dataType: string
		lineageTag: 67835758-d438-4c96-9fc3-5f23e1e8e1b0
		summarizeBy: none
		sourceColumn: HEDGING_CURRENCY

		annotation SummarizationSetBy = Automatic

	/// from IDM
	column HEDGING_CURRENCY_CODE
		dataType: string
		lineageTag: 08a1aeb5-6a74-44ed-b9b2-d88d8691737a
		summarizeBy: none
		sourceColumn: HEDGING_CURRENCY_CODE

		annotation SummarizationSetBy = Automatic

	column Weights
		dataType: double
		formatString: 0
		lineageTag: 3251b459-3df5-40c1-9f97-11bd744f8504
		summarizeBy: sum
		sourceColumn: Weights

		annotation SummarizationSetBy = Automatic

	column QUANTITY
		dataType: double
		lineageTag: af1286d5-7bf0-41a3-8d8d-73bf3cde9c8a
		summarizeBy: sum
		sourceColumn: QUANTITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// from IDM
	column MARKET_VALUE_LOCAL
		dataType: double
		displayFolder: Market Value
		lineageTag: c9bfe58a-ba2c-4b0e-bee4-fdbf348b311c
		summarizeBy: sum
		sourceColumn: MARKET_VALUE_LOCAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Market Value (Text)' = 'Daily Position'[MARKET VALUE BASE]
		dataType: string
		displayFolder: Market Value
		lineageTag: 59d6e1be-f75f-4de1-8457-8505dc695c0a
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	/// Position of AU holding based on size
	column asx_rank
		dataType: int64
		formatString: 0
		lineageTag: 02f649e6-0476-4a56-9f68-02cd0e3459fa
		summarizeBy: sum
		sourceColumn: asx_rank

		annotation SummarizationSetBy = Automatic

	column strategic_classification
		dataType: string
		displayFolder: Active/Strategic
		lineageTag: a7ac2024-ef74-417a-92d8-9ab74bdb3c19
		summarizeBy: none
		sourceColumn: strategic_classification

		annotation SummarizationSetBy = Automatic

	column Active/Strategic = ```
			
			IF (
			    'Daily Position'[Is Latest] ="Y", -- Getting latest classification
			    IF('Daily Position'[strategic_classification] = "",
			    "View AU Strategic Active Holdings",
			    'Daily Position'[strategic_classification]
			    ),
			    "View AU Strategic Active Holdings"
			)
			
			```
		displayFolder: Active/Strategic
		lineageTag: 1a253d9b-93f3-47c2-847e-629c8b875f10
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column strategic_class_valid_From
		dataType: dateTime
		formatString: Short Date
		displayFolder: Active/Strategic
		lineageTag: 959cc477-969d-4492-9690-7637a4ca6d6b
		summarizeBy: none
		sourceColumn: strategic_class_valid_From

		variation Variation
			isDefault
			relationship: 99be3b44-6ec4-47a6-af8e-8b0619f6a05d
			defaultHierarchy: LocalDateTable_8ba8196b-7ea6-4d07-8be2-f3d661204b92.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Active/Strategic List Updated' = IF('Daily Position'[strategic_class_valid_From] = 'Daily Position'[Date],"Y","N")
		displayFolder: Active/Strategic
		lineageTag: d25838a8-1db5-4e46-8d11-a75e1335ebda
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Vigeo_Key
		dataType: string
		displayFolder: Mapping
		lineageTag: 94e1f0fc-49a3-48a7-92aa-25f6916c7339
		summarizeBy: none
		sourceColumn: Vigeo_Key

		annotation SummarizationSetBy = Automatic

	column Vigeo_Date_Key
		dataType: string
		displayFolder: Mapping
		lineageTag: 6b14b588-91b9-4737-a19b-184361c62422
		summarizeBy: none
		sourceColumn: Vigeo_Date_Key

		annotation SummarizationSetBy = Automatic

	column TCUID
		dataType: string
		displayFolder: Mapping
		lineageTag: 9898cecb-44af-4985-bb4d-7f7da7e60c50
		summarizeBy: none
		sourceColumn: TCUID

		annotation SummarizationSetBy = Automatic

	column Position_Type
		dataType: string
		lineageTag: 8e9d2f80-04af-46e5-b85a-4d7ebee65fa0
		summarizeBy: none
		sourceColumn: Position_Type

		annotation SummarizationSetBy = Automatic

	column Eiris_Mapping_Type
		dataType: string
		displayFolder: Mapping
		lineageTag: 4482db2b-3269-4ba5-9769-4a1cd1049284
		summarizeBy: none
		sourceColumn: Eiris_Mapping_Type

		annotation SummarizationSetBy = Automatic

	column Eiris_Mapping_Status
		dataType: string
		displayFolder: Mapping
		lineageTag: 38e35f3d-81e3-4025-afa7-bc8dfdc07561
		summarizeBy: none
		sourceColumn: Eiris_Mapping_Status

		annotation SummarizationSetBy = Automatic

	column Trucost_Mapping_Type
		dataType: string
		displayFolder: Mapping
		lineageTag: 2c235c64-ba3a-42e1-b136-1a2ae98e08ee
		summarizeBy: none
		sourceColumn: Trucost_Mapping_Type

		annotation SummarizationSetBy = Automatic

	column Trucost_Mapping_Status
		dataType: string
		displayFolder: Mapping
		lineageTag: 03986de0-eafa-4fc2-9d9e-88ee01b66cf1
		summarizeBy: none
		sourceColumn: Trucost_Mapping_Status

		annotation SummarizationSetBy = Automatic

	column BENCHMARK_WEIGHT_EOD
		dataType: double
		formatString: 0.0000000000
		displayFolder: Benchmark
		lineageTag: 0832a1de-437d-4ec4-9091-d8163579cadc
		summarizeBy: sum
		sourceColumn: BENCHMARK_WEIGHT_EOD

		annotation SummarizationSetBy = Automatic

	/// For portfolio, % ownership of company based on quantity held and shares outstanding. 
	/// 
	/// For benchmark, % ownership based on the proportion of benchmark weight x total MV Base to Market cap base.
	column 'Ownership filter' = ```
			
			// VAR Total_Portfolio_MV_BASE = CALCULATE(SUM('Daily Position'[MARKET VALUE BASE]), ALLSELECTED())
			VAR Ownership_port = DIVIDE('Daily Position'[QUANTITY], [SHARES_OUTSTANDING_SUM],0)
			VAR Ownership_bench_num = DIVIDE ('Daily Position'[BENCHMARK_WEIGHT_EOD],100,0)*[Total Portfolio MV BASE]
			VAR Ownership_bench_denom ='Daily Position'[Market_Cap_Base]
			
			RETURN
			IF (
			    'Daily Position'[Position_Type] = "Portfolio",
			    Ownership_port, 
			    /*IF (
			    'Daily Position'[Position_Type] = "Benchmark",
			    DIVIDE( Ownership_bench_num, Ownership_bench_denom,0),
			    [Total Portfolio MV BASE], */ // [Total Portfolio MV BASE] measure not calculating correctly with calc column
			    0
			    
			) 
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Ownership
		lineageTag: 3f3ec433-81b5-49b2-9384-b566fb5de892
		summarizeBy: none

		annotation SummarizationSetBy = User

	column TCUID_Date_Key
		dataType: string
		displayFolder: Mapping
		lineageTag: c7441b09-7dab-441e-bd25-877f1c0f9883
		summarizeBy: none
		sourceColumn: TCUID_Date_Key

		annotation SummarizationSetBy = Automatic

	column MV_OWNERSHIP
		dataType: double
		formatString: 0.0000000000
		displayFolder: Ownership
		lineageTag: 82ff0f8d-8760-47ff-b37c-0b55d326b49b
		summarizeBy: sum
		sourceColumn: MV_OWNERSHIP

		annotation SummarizationSetBy = Automatic

	column original_mapping_status
		dataType: string
		displayFolder: Mapping
		lineageTag: 7b31ccf3-4595-40bb-8cfb-2634eb842fc8
		summarizeBy: none
		sourceColumn: original_mapping_status

		annotation SummarizationSetBy = Automatic

	column original_eiris_mapping_status
		dataType: string
		displayFolder: Mapping
		lineageTag: e4c067be-678d-4029-9560-0d72fc4fb52e
		summarizeBy: none
		sourceColumn: original_eiris_mapping_status

		annotation SummarizationSetBy = Automatic

	column original_Trucost_Mapping_Status
		dataType: string
		displayFolder: Mapping
		lineageTag: 81431ee9-78b2-410e-bda0-1cce51c78de0
		summarizeBy: none
		sourceColumn: original_Trucost_Mapping_Status

		annotation SummarizationSetBy = Automatic

	column Market_Cap_Base
		dataType: double
		lineageTag: 05c50c1e-6c31-40f5-837b-5fa230868c06
		summarizeBy: sum
		sourceColumn: Market_Cap_Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EVIC_Base
		dataType: double
		lineageTag: 44c05a46-ae79-476c-82f5-b45ad9388ebb
		summarizeBy: sum
		sourceColumn: EVIC_Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BP_KEY
		dataType: string
		lineageTag: 929c3c39-dac4-4eaf-a4b3-235d15eeb348
		summarizeBy: none
		sourceColumn: BP_KEY

		annotation SummarizationSetBy = Automatic

	column BP_KEY_hashed
		dataType: int64
		formatString: 0
		lineageTag: d3326ebd-82a4-41ea-8aec-0ac47d5741ce
		summarizeBy: none
		sourceColumn: BP_KEY_hashed

		annotation SummarizationSetBy = Automatic

	column IS_MRP_TRS_ACCOUNT
		dataType: string
		lineageTag: a5ee93e1-248c-499c-bb80-b3ce589a07df
		summarizeBy: none
		sourceColumn: IS_MRP_TRS_ACCOUNT

		annotation SummarizationSetBy = Automatic

	column COMPONENT_ACCOUNT_ID
		dataType: string
		lineageTag: 0e5daff5-ee75-4100-b91f-770ba488dca0
		summarizeBy: none
		sourceColumn: COMPONENT_ACCOUNT_ID

		annotation SummarizationSetBy = Automatic

	column COMPONENT_ACCOUNT_NAME
		dataType: string
		lineageTag: d6d0b18d-9edc-454f-96b0-d9df1249513a
		summarizeBy: none
		sourceColumn: COMPONENT_ACCOUNT_NAME

		annotation SummarizationSetBy = Automatic

	column SOURCE_METADATA
		dataType: string
		lineageTag: 1c144843-cc8e-4689-bb73-23222e1c6b8f
		summarizeBy: none
		sourceColumn: SOURCE_METADATA

		annotation SummarizationSetBy = Automatic

	column iLEVEL_FUND
		dataType: string
		lineageTag: b2bf2703-d144-4617-9181-8ad3ceac4b66
		summarizeBy: none
		sourceColumn: iLEVEL_FUND

		annotation SummarizationSetBy = Automatic

	column WEIGHTING_PERCENTAGE
		dataType: double
		lineageTag: c8aea7f2-ec22-4d62-8515-20edbe49691c
		summarizeBy: sum
		sourceColumn: WEIGHTING_PERCENTAGE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WEIGHTING_PERCENTAGE_EXCL_BAL_ITEM
		dataType: double
		lineageTag: aebc0044-0870-4003-8e30-7ba9aefc1bc9
		summarizeBy: sum
		sourceColumn: WEIGHTING_PERCENTAGE_EXCL_BAL_ITEM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SK_DATE
		dataType: double
		lineageTag: b3bfdc19-2c07-447c-8a8e-9113766da9da
		summarizeBy: sum
		sourceColumn: SK_DATE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LPA_Fund_Level_Date_Key
		dataType: string
		lineageTag: c9611d4e-bd29-4ed6-b3db-3e1f52c7c2bc
		summarizeBy: none
		sourceColumn: LPA_Fund_Level_Date_Key

		annotation SummarizationSetBy = Automatic

	column LPA_Company_Level_Date_Key
		dataType: string
		lineageTag: 9f4d2852-82ea-4a7b-ac4c-cfb465804fab
		summarizeBy: none
		sourceColumn: LPA_Company_Level_Date_Key

		annotation SummarizationSetBy = Automatic

	partition 'Daily Position-2944d73a-f9db-4cee-9504-fcbf26b5e159' = m
		mode: import
		queryGroup: Sustainalytics
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    sustainalytics_dev_Schema = hive_metastore_Database{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_gs_daily_position_v1_Table = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    Schema = Table.SelectRows(hive_metastore_Database, each ([Name] =p_sustainalytics_database)),
				    sustainalytics_test_Schema = Schema{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_gs_daily_position_v1_Table1 = sustainalytics_test_Schema{[Name="semantic_gs_daily_position_v1",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(semantic_gs_daily_position_v1_Table1,{{"VALUATION_DATE", "Valuation Date"}, {"INVESTMENT_OBJECT_CODE", "INVESTMENT OBJECT CODE"}, {"ACCOUNT_REPORT_NAME", "ACCOUNT REPORT NAME"}, {"SK_NODE_ID_EFFECTIVE_DATE", "SK NODE ID EFFECTIVE DATE"}, {"SK_ASSET", "SK ASSET"}, {"ACCOUNT_BASE_CURRENCY_CODE", "ACCOUNT BASE CURRENCY CODE"}, {"SK_OUTPUT_ACCOUNT", "SK OUTPUT ACCOUNT"}, {"MARKET_VALUE_BASE", "MARKET VALUE BASE"}, {"Is_Latest", "Is Latest"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Valuation Date", type date}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Valuation Date", "Valuation Date - Copy"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Duplicated Column",{"Valuation Date", "Valuation Date - Copy", "Is Latest", "INVESTMENT OBJECT CODE", "ACCOUNT REPORT NAME", "SK NODE ID EFFECTIVE DATE", "SK ASSET", "ACCOUNT BASE CURRENCY CODE", "SK OUTPUT ACCOUNT", "NT_Manager", "ASSET_CLASS", "STRATEGY", "FUND", "MARKET VALUE BASE"}),
				    #"Inserted Date" = Table.AddColumn(#"Reordered Columns", "Date", each DateTime.Date([#"Valuation Date - Copy"]), type date),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Date",{{"Valuation Date", type date}}),
				    #"Limit Rows" = if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				       #"Changed Type1", 
				      100
				     )
				 else 
				      #"Changed Type1"
				in
				    #"Limit Rows"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

