table dim_table_load_history
	lineageTag: 0e32c3e0-e11e-485c-a388-ab1594d885d2

	column source_system
		dataType: string
		lineageTag: a6359ba5-7b34-4c41-be3a-7c00045c20c5
		summarizeBy: none
		sourceColumn: source_system

		annotation SummarizationSetBy = Automatic

	column table_name
		dataType: string
		lineageTag: d2f1e880-e378-4765-bfd9-72b2faa7a937
		summarizeBy: none
		sourceColumn: table_name

		annotation SummarizationSetBy = Automatic

	column last_data_update_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 20668526-8a04-4663-bd92-e404f0ac8554
		summarizeBy: none
		sourceColumn: last_data_update_date

		variation Variation
			isDefault
			relationship: bd466068-558c-476d-b067-3c82dc3a9dcf
			defaultHierarchy: LocalDateTable_ea28a814-9be7-4538-821b-0bc8ec4a7319.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column operation
		dataType: string
		lineageTag: 50c2f49b-ad38-444b-b8d4-772ec151ec29
		summarizeBy: none
		sourceColumn: operation

		annotation SummarizationSetBy = Automatic

	column job_name
		dataType: string
		lineageTag: 8155f416-ed57-4a22-850a-fdb9d00eb86e
		summarizeBy: none
		sourceColumn: job_name

		annotation SummarizationSetBy = Automatic

	column affected_row_count
		dataType: string
		lineageTag: 94854e22-bcc7-4c44-9e86-e4fd684aea1a
		summarizeBy: none
		sourceColumn: affected_row_count

		annotation SummarizationSetBy = Automatic

	partition dim_table_load_history = m
		mode: import
		queryGroup: 'Load History'
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    Schema = Table.SelectRows(hive_metastore_Database, each ([Name] =p_sustainalytics_database)),
				    #"Sustainalytics Schema" = Schema{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    #"Load Table" = #"Sustainalytics Schema"{[Name="semantic_esg_source_tables_load_history",Kind="Table"]}[Data]
				in
				    #"Load Table"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

