table dp_lpa_esg_company_level_v1
	lineageTag: 11856fb1-0594-4e9c-81e8-46d7dd9dfa24

	column LPA_Company_Level_Date_Key
		dataType: string
		lineageTag: 66f8a0e1-25f0-41d1-8071-ce52fcb896f5
		summarizeBy: none
		sourceColumn: LPA_Company_Level_Date_Key

		annotation SummarizationSetBy = Automatic

	column LPA_Fund_Id
		dataType: string
		lineageTag: 4743efd4-36ba-4376-910b-40d710c321d9
		summarizeBy: none
		sourceColumn: LPA_Fund_Id

		annotation SummarizationSetBy = Automatic

	column LPA_Company_Id
		dataType: string
		lineageTag: d059974c-e06c-49d5-b7fc-5d72c4d6eec7
		summarizeBy: none
		sourceColumn: LPA_Company_Id

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: 985fb36a-2e9d-4c69-b2f3-e9afb29ee2d1
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column LPA_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 87a753b9-eae2-4444-8784-938f8abb324d
		summarizeBy: none
		sourceColumn: LPA_Date

		variation Variation
			isDefault
			relationship: 89d36cb6-a39d-4b2b-803d-6fbb3c9b2726
			defaultHierarchy: LocalDateTable_ab03f776-ee01-4e99-a81c-76a7098b9e76.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EDCI_Year
		dataType: string
		lineageTag: f7787df8-0acd-4bb0-8b07-2574ad1b910d
		summarizeBy: none
		sourceColumn: EDCI_Year

		annotation SummarizationSetBy = Automatic

	column FFCo_Year
		dataType: string
		lineageTag: 8a163ad9-ad4c-4298-9441-9328fe497995
		summarizeBy: none
		sourceColumn: FFCo_Year

		annotation SummarizationSetBy = Automatic

	column DATE_VALUE
		dataType: dateTime
		formatString: General Date
		lineageTag: 3c313e51-0e4f-4c53-9527-85979c56b7cb
		summarizeBy: none
		sourceColumn: DATE_VALUE

		variation Variation
			isDefault
			relationship: a510efdc-a5a9-4802-8daa-b777737b5464
			defaultHierarchy: LocalDateTable_c2c416a1-fc17-4799-a3df-366a8d7063cd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column SK_DATE
		dataType: double
		lineageTag: 38da9ea4-31a5-4876-af98-094d3fb67de8
		summarizeBy: sum
		sourceColumn: SK_DATE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Year_Initial_Investment
		dataType: string
		lineageTag: 8be4786d-5775-420b-8b0d-332625de35c7
		summarizeBy: none
		sourceColumn: EDCI_Year_Initial_Investment

		annotation SummarizationSetBy = Automatic

	column LPA_Fund_Short_Name
		dataType: string
		lineageTag: ed648cf5-2d1e-4c71-9515-918775f7f90a
		summarizeBy: none
		sourceColumn: LPA_Fund_Short_Name

		annotation SummarizationSetBy = Automatic

	column EDCI_Company_ID
		dataType: string
		lineageTag: c3d8be0b-433d-4f2d-96f4-a8c9e0524f36
		summarizeBy: none
		sourceColumn: EDCI_Company_ID

		annotation SummarizationSetBy = Automatic

	column EDCI_Company_Name
		dataType: string
		lineageTag: 93f76052-cd09-4b2d-9ff0-533c93bfa8f0
		summarizeBy: none
		sourceColumn: EDCI_Company_Name

		annotation SummarizationSetBy = Automatic

	column EDCI_Company_Comment_General
		dataType: string
		lineageTag: c7ca1d68-31ff-42ba-a4d1-d043215fce99
		summarizeBy: none
		sourceColumn: EDCI_Company_Comment_General

		annotation SummarizationSetBy = Automatic

	column EDCI_General_Partner
		dataType: string
		lineageTag: b76b9ac9-482c-4dcf-b52f-82f4127d3bee
		summarizeBy: none
		sourceColumn: EDCI_General_Partner

		annotation SummarizationSetBy = Automatic

	column EDCI_Fund_ID
		dataType: string
		lineageTag: 81d21c3b-8149-4d89-8810-d2636510e22c
		summarizeBy: none
		sourceColumn: EDCI_Fund_ID

		annotation SummarizationSetBy = Automatic

	column EDCI_Country_Domicile
		dataType: string
		lineageTag: 2c410488-4870-489d-bfb1-2730db6cf9de
		summarizeBy: none
		sourceColumn: EDCI_Country_Domicile

		annotation SummarizationSetBy = Automatic

	column EDCI_Country_Operations
		dataType: string
		lineageTag: 0977dd8a-4376-4c31-aa6f-f85e3fbf03d9
		summarizeBy: none
		sourceColumn: EDCI_Country_Operations

		annotation SummarizationSetBy = Automatic

	column EDCI_Company_Structure
		dataType: string
		lineageTag: 2c2f5d6c-7dfe-42b9-9449-1e79c7e160e8
		summarizeBy: none
		sourceColumn: EDCI_Company_Structure

		annotation SummarizationSetBy = Automatic

	column EDCI_Growth_Stage
		dataType: string
		lineageTag: 0cffeece-224e-4e7f-ae3b-3837fca5cd6d
		summarizeBy: none
		sourceColumn: EDCI_Growth_Stage

		annotation SummarizationSetBy = Automatic

	column EDCI_Percent_Ownership_GP
		dataType: double
		lineageTag: ad5afb86-ef23-4234-a713-6fddcdba0a38
		summarizeBy: sum
		sourceColumn: EDCI_Percent_Ownership_GP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Percent_Ownership_Fund
		dataType: double
		lineageTag: 5523b7e9-deb7-49d5-b0d1-3de1e78b9005
		summarizeBy: sum
		sourceColumn: EDCI_Percent_Ownership_Fund

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Primary_Sector_SICS_Name
		dataType: string
		lineageTag: 6a97c032-c1d7-4810-8d77-b90efb13dc0d
		summarizeBy: none
		sourceColumn: EDCI_Primary_Sector_SICS_Name

		annotation SummarizationSetBy = Automatic

	column EDCI_Primary_Industry_SICS_Name
		dataType: string
		lineageTag: fd73f5b6-ec13-4a83-8b04-c47ec9cd2de3
		summarizeBy: none
		sourceColumn: EDCI_Primary_Industry_SICS_Name

		annotation SummarizationSetBy = Automatic

	column EDCI_Primary_Sector_Industry_SICS_Comment
		dataType: string
		lineageTag: baba7555-fa17-468b-be74-a05337dabeb9
		summarizeBy: none
		sourceColumn: EDCI_Primary_Sector_Industry_SICS_Comment

		annotation SummarizationSetBy = Automatic

	column EDCI_Primary_SubIndustry_GICS_Name
		dataType: string
		lineageTag: b67c5da9-89c2-4fcc-a56f-bfbd64e55b1a
		summarizeBy: none
		sourceColumn: EDCI_Primary_SubIndustry_GICS_Name

		annotation SummarizationSetBy = Automatic

	column EDCI_Metrics_Currency
		dataType: string
		lineageTag: f82a64f9-7f39-4830-8791-71a42dfff43a
		summarizeBy: none
		sourceColumn: EDCI_Metrics_Currency

		annotation SummarizationSetBy = Automatic

	column EDCI_Revenue
		dataType: double
		lineageTag: 35ec912f-6cdc-43e6-8e01-708b134f7abe
		summarizeBy: sum
		sourceColumn: EDCI_Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Revenue_Comment
		dataType: string
		lineageTag: 7d6f9bb8-98a8-4c56-a04b-b4938eca8e82
		summarizeBy: none
		sourceColumn: EDCI_Revenue_Comment

		annotation SummarizationSetBy = Automatic

	column EDCI_FTE_Current_Year
		dataType: double
		lineageTag: 2d857938-6612-4fbc-9aba-203973082ff5
		summarizeBy: sum
		sourceColumn: EDCI_FTE_Current_Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_FTE_Prior_Year
		dataType: double
		lineageTag: 14afe79c-2be2-47a2-a8a2-5a52f19dfa4b
		summarizeBy: sum
		sourceColumn: EDCI_FTE_Prior_Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Scope_1_Emissions
		dataType: double
		lineageTag: ed0f4654-71d8-4013-be74-fc62edc89e89
		summarizeBy: sum
		sourceColumn: EDCI_Scope_1_Emissions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Scope_1_Methodology
		dataType: string
		lineageTag: 8b289b42-459e-4bad-b8b7-fe81c2b35573
		summarizeBy: none
		sourceColumn: EDCI_Scope_1_Methodology

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_2_Emissions
		dataType: double
		lineageTag: 23099104-65c4-4ba9-8519-024851f99549
		summarizeBy: sum
		sourceColumn: EDCI_Scope_2_Emissions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Scope_2_Methodology
		dataType: string
		lineageTag: a64e358a-dd2a-4f4f-8894-2ac163bf6f3a
		summarizeBy: none
		sourceColumn: EDCI_Scope_2_Methodology

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Emissions
		dataType: double
		lineageTag: 2556236e-0e7c-4c1b-830a-9993dd6ed982
		summarizeBy: sum
		sourceColumn: EDCI_Scope_3_Emissions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Scope_3_Methodology
		dataType: string
		lineageTag: e940db9e-30bd-428d-95fd-e3fdd11404e7
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Methodology

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_1
		dataType: string
		lineageTag: 6fbf7b1f-b9cc-4988-88cf-25e01f799967
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_1

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_2
		dataType: string
		lineageTag: 19a5f8b8-25a3-4890-865b-f57290d00675
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_2

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_3
		dataType: string
		lineageTag: 8170d4b7-6373-4f4d-b343-bce83ae0f9f7
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_3

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_4
		dataType: string
		lineageTag: 0c1ae9c5-8913-4eb0-901f-5e2396b61987
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_4

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_5
		dataType: string
		lineageTag: 0e200914-5377-422a-b6d1-6996fe795d11
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_5

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_6
		dataType: string
		lineageTag: c3807a2b-5c4d-4694-8945-0d293d5b4259
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_6

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_7
		dataType: string
		lineageTag: cb852082-2b36-424e-8825-e00e10fc46f1
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_7

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_8
		dataType: string
		lineageTag: 0023e447-e50b-4680-a22a-1fb808b6ad56
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_8

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_9
		dataType: string
		lineageTag: 5cadf85b-21e5-47e3-bb4c-97af21e4d8b6
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_9

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_10
		dataType: string
		lineageTag: d125a865-1594-4fbf-a16a-d6514a935c62
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_10

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_11
		dataType: string
		lineageTag: 8d85a35e-d73c-4e1d-931b-bb6266258403
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_11

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_12
		dataType: string
		lineageTag: 6223b3e8-c9f4-4da6-8dee-7ae3e67edb7c
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_12

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_13
		dataType: string
		lineageTag: b0e5831b-956b-4ad2-93f5-a1b7fca3062e
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_13

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_14
		dataType: string
		lineageTag: 29caede3-6176-4e14-bf71-981beb82d1d3
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_14

		annotation SummarizationSetBy = Automatic

	column EDCI_Scope_3_Category_15
		dataType: string
		lineageTag: e407bd7a-ff85-4558-aed5-ff30ab2c8d61
		summarizeBy: none
		sourceColumn: EDCI_Scope_3_Category_15

		annotation SummarizationSetBy = Automatic

	column EDCI_Representative_Total_Scope_3_Emissions
		dataType: double
		lineageTag: 1f46246f-4f5d-42c2-b971-16f5195aa2eb
		summarizeBy: sum
		sourceColumn: EDCI_Representative_Total_Scope_3_Emissions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Commentary_On_Primary_Methodology
		dataType: string
		lineageTag: 5baeed1a-3954-452b-b31b-69f16e6a93b2
		summarizeBy: none
		sourceColumn: EDCI_Commentary_On_Primary_Methodology

		annotation SummarizationSetBy = Automatic

	column EDCI_Primary_Methodology_Additional_Comment
		dataType: string
		lineageTag: 65dde5aa-f956-48d0-9efc-79e249a5692b
		summarizeBy: none
		sourceColumn: EDCI_Primary_Methodology_Additional_Comment

		annotation SummarizationSetBy = Automatic

	column EDCI_Commentary_Emissions_ThirdParty_Review
		dataType: string
		lineageTag: 531dde6c-6b14-47d7-98ce-77dba53f1ad9
		summarizeBy: none
		sourceColumn: EDCI_Commentary_Emissions_ThirdParty_Review

		annotation SummarizationSetBy = Automatic

	column EDCI_Decarbonization_Strategy
		dataType: string
		lineageTag: 63b73c06-6ddb-448b-9af3-7aae464cf8bb
		summarizeBy: none
		sourceColumn: EDCI_Decarbonization_Strategy

		annotation SummarizationSetBy = Automatic

	column EDCI_ShortTerm_GHG_Emission_Reduction_Target
		dataType: string
		lineageTag: c94198fd-a0a0-455b-8165-9cc9812496bb
		summarizeBy: none
		sourceColumn: EDCI_ShortTerm_GHG_Emission_Reduction_Target

		annotation SummarizationSetBy = Automatic

	column EDCI_LongTerm_Net_Zero_Goal
		dataType: string
		lineageTag: 1f315d44-c839-436b-bbe5-92ff9a732513
		summarizeBy: none
		sourceColumn: EDCI_LongTerm_Net_Zero_Goal

		annotation SummarizationSetBy = Automatic

	column EDCI_Methodology_Comment
		dataType: string
		lineageTag: e46f447b-c196-4feb-b831-de54a94295c3
		summarizeBy: none
		sourceColumn: EDCI_Methodology_Comment

		annotation SummarizationSetBy = Automatic

	column EDCI_Energy_Consumption_Total
		dataType: double
		lineageTag: f25a87fa-33ed-442f-95eb-7b2adc9518b6
		summarizeBy: sum
		sourceColumn: EDCI_Energy_Consumption_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Energy_Consumption_Total_Comment
		dataType: string
		lineageTag: 96cd6a65-a90e-4ae4-a08a-07b88d611f37
		summarizeBy: none
		sourceColumn: EDCI_Energy_Consumption_Total_Comment

		annotation SummarizationSetBy = Automatic

	column EDCI_Energy_Consumption_Renewable
		dataType: double
		lineageTag: 9cb628a1-868c-412b-b8c9-9c96112897c3
		summarizeBy: sum
		sourceColumn: EDCI_Energy_Consumption_Renewable

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Energy_Consumption_Renewable_Comment
		dataType: string
		lineageTag: 3f415813-f41c-465a-ae19-385f0e80fa50
		summarizeBy: none
		sourceColumn: EDCI_Energy_Consumption_Renewable_Comment

		annotation SummarizationSetBy = Automatic

	column EDCI_Board_Members_Total
		dataType: int64
		formatString: 0
		lineageTag: 34bcbd0c-960b-4af0-a091-920be18e797a
		summarizeBy: sum
		sourceColumn: EDCI_Board_Members_Total

		annotation SummarizationSetBy = Automatic

	column EDCI_Board_Members_Women
		dataType: int64
		formatString: 0
		lineageTag: 3d848951-71a6-485a-877e-ba307b91e642
		summarizeBy: sum
		sourceColumn: EDCI_Board_Members_Women

		annotation SummarizationSetBy = Automatic

	column EDCI_Board_Members_LGBTQ
		dataType: int64
		formatString: 0
		lineageTag: 6cac1c97-a172-4e54-922d-5431b38e650d
		summarizeBy: sum
		sourceColumn: EDCI_Board_Members_LGBTQ

		annotation SummarizationSetBy = Automatic

	column EDCI_Board_Members_UnderRepresented
		dataType: int64
		formatString: 0
		lineageTag: 32a24fa8-5d84-45be-8b81-8a78825c4050
		summarizeBy: sum
		sourceColumn: EDCI_Board_Members_UnderRepresented

		annotation SummarizationSetBy = Automatic

	column EDCI_CSuite_Employees_Total
		dataType: int64
		formatString: 0
		lineageTag: 9e3a435a-ffa8-4b53-a555-67dcc0b91135
		summarizeBy: sum
		sourceColumn: EDCI_CSuite_Employees_Total

		annotation SummarizationSetBy = Automatic

	column EDCI_CSuite_Employees_Women
		dataType: int64
		formatString: 0
		lineageTag: d05b601c-51cd-4cf3-abc6-01c8ba55c792
		summarizeBy: sum
		sourceColumn: EDCI_CSuite_Employees_Women

		annotation SummarizationSetBy = Automatic

	column EDCI_WorkRelated_Injuries
		dataType: int64
		formatString: 0
		lineageTag: 2c140509-d29d-4bdd-989a-9982cf6f7210
		summarizeBy: sum
		sourceColumn: EDCI_WorkRelated_Injuries

		annotation SummarizationSetBy = Automatic

	column EDCI_WorkRelated_Injuries_Comment
		dataType: string
		lineageTag: 900cc75c-cd20-4ae9-a7dc-e7d6b61df844
		summarizeBy: none
		sourceColumn: EDCI_WorkRelated_Injuries_Comment

		annotation SummarizationSetBy = Automatic

	column EDCI_WorkRelated_Fatalities
		dataType: int64
		formatString: 0
		lineageTag: b17b3e15-533c-40cb-b8d5-36db03c3b127
		summarizeBy: sum
		sourceColumn: EDCI_WorkRelated_Fatalities

		annotation SummarizationSetBy = Automatic

	column EDCI_WorkRelated_Days_Lost_Injury
		dataType: double
		lineageTag: ce4a7387-5600-4bd3-9ec0-7194f57fae58
		summarizeBy: sum
		sourceColumn: EDCI_WorkRelated_Days_Lost_Injury

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_FTE_Current_Year_Calculated
		dataType: double
		lineageTag: 21393008-7f48-49e4-b463-d2e07e63cf9f
		summarizeBy: sum
		sourceColumn: EDCI_FTE_Current_Year_Calculated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_FTE_Current_Year_Calculated_Format
		dataType: string
		lineageTag: 725812fa-2895-4d05-9e2d-a590842fdf6f
		summarizeBy: none
		sourceColumn: EDCI_FTE_Current_Year_Calculated_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_FTE_Prior_Year_Calculated
		dataType: double
		lineageTag: 88ea015a-753d-43ef-92a9-3919e5231e6a
		summarizeBy: sum
		sourceColumn: EDCI_FTE_Prior_Year_Calculated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_FTE_Prior_Year_Calculated_Format
		dataType: string
		lineageTag: 4b23a4ad-f1dd-4dbf-9d95-6eb41180c35a
		summarizeBy: none
		sourceColumn: EDCI_FTE_Prior_Year_Calculated_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_FTE_Prior_Year_Calculated_Comment
		dataType: string
		lineageTag: 8b961089-ea42-4f1f-aea2-bc048a0b9a66
		summarizeBy: none
		sourceColumn: EDCI_FTE_Prior_Year_Calculated_Comment

		annotation SummarizationSetBy = Automatic

	column EDCI_FTE_Change_MA
		dataType: double
		lineageTag: 61c04d87-699f-4b8a-ae8f-4f529c3d211a
		summarizeBy: sum
		sourceColumn: EDCI_FTE_Change_MA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_FTE_Net_New_Hires_Organic
		dataType: double
		lineageTag: 5ecf3778-918e-4cb8-93ad-b661dd75f882
		summarizeBy: sum
		sourceColumn: EDCI_FTE_Net_New_Hires_Organic

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_FTE_Net_New_Hires_Organic_Format
		dataType: string
		lineageTag: 237bda13-966a-40ca-9f12-e4451912489e
		summarizeBy: none
		sourceColumn: EDCI_FTE_Net_New_Hires_Organic_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_FTE_Net_New_Hires_Total
		dataType: double
		lineageTag: cc674e4e-9aa3-48aa-a370-40c9e8078238
		summarizeBy: sum
		sourceColumn: EDCI_FTE_Net_New_Hires_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_FTE_Net_New_Hires_Total_Format
		dataType: string
		lineageTag: 3551c9e9-9d07-4df4-998b-864476bb7585
		summarizeBy: none
		sourceColumn: EDCI_FTE_Net_New_Hires_Total_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Annual_Percent_Turnover_FTE
		dataType: double
		lineageTag: b541f7aa-881f-441d-946e-9acd1911d572
		summarizeBy: sum
		sourceColumn: EDCI_Annual_Percent_Turnover_FTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Employee_Survey
		dataType: string
		lineageTag: c2db360b-94a6-4a08-b137-107a33f04835
		summarizeBy: none
		sourceColumn: EDCI_Employee_Survey

		annotation SummarizationSetBy = Automatic

	column EDCI_Employee_Survey_Response_Percent
		dataType: double
		lineageTag: 98842e07-04db-449f-b775-7841abe6cb03
		summarizeBy: sum
		sourceColumn: EDCI_Employee_Survey_Response_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Current_Value_All_Investments
		dataType: double
		lineageTag: 6775ac01-6f4a-498f-8bd2-73c1a35fabf6
		summarizeBy: sum
		sourceColumn: EDCI_Current_Value_All_Investments

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Enterprise_Value
		dataType: double
		lineageTag: f3d142f9-93ed-4148-bc99-07f0b00e4a69
		summarizeBy: sum
		sourceColumn: EDCI_Enterprise_Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Fund_Currency
		dataType: string
		lineageTag: acfeac31-75d8-4738-8273-822793867e02
		summarizeBy: none
		sourceColumn: EDCI_Fund_Currency

		annotation SummarizationSetBy = Automatic

	column EDCI_Current_Fund_Value
		dataType: double
		lineageTag: a3918529-6224-4096-b401-2373f7d5abc8
		summarizeBy: sum
		sourceColumn: EDCI_Current_Fund_Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Current_Fund_Value_Format
		dataType: string
		lineageTag: b1292367-3ab2-483a-9b26-81dda6dc78c8
		summarizeBy: none
		sourceColumn: EDCI_Current_Fund_Value_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Current_Fund_Value_Comment
		dataType: string
		lineageTag: fa8e586d-fc85-4f2c-a2f4-0a260d7d3079
		summarizeBy: none
		sourceColumn: EDCI_Current_Fund_Value_Comment

		annotation SummarizationSetBy = Automatic

	column EDCI_GHG_Scope_1_Financed
		dataType: double
		lineageTag: c25b2301-20e7-48a3-a6ae-1cbc76860bc7
		summarizeBy: sum
		sourceColumn: EDCI_GHG_Scope_1_Financed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_GHG_Scope_1_Financed_Format
		dataType: string
		lineageTag: 263e7c23-8f86-47b0-b49a-e7424682f719
		summarizeBy: none
		sourceColumn: EDCI_GHG_Scope_1_Financed_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_GHG_Scope_2_Financed
		dataType: double
		lineageTag: fb6c5ada-0924-4f63-ab6b-fbd7ed4b636a
		summarizeBy: sum
		sourceColumn: EDCI_GHG_Scope_2_Financed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_GHG_Scope_2_Financed_Format
		dataType: string
		lineageTag: c9843636-86de-42f9-9420-2e0a453c7188
		summarizeBy: none
		sourceColumn: EDCI_GHG_Scope_2_Financed_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_GHG_Scope_3_Financed
		dataType: double
		lineageTag: 3244baa7-df5f-4ff6-b899-9e1b5f4b2722
		summarizeBy: sum
		sourceColumn: EDCI_GHG_Scope_3_Financed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_GHG_Scope_3_Financed_Format
		dataType: string
		lineageTag: e5f4a862-a3dd-4734-9465-adbcfce4c1b2
		summarizeBy: none
		sourceColumn: EDCI_GHG_Scope_3_Financed_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_GHG_Total_Financed
		dataType: double
		lineageTag: 34ab7e6b-0f15-4e62-a19e-ae2a4c43cbdb
		summarizeBy: sum
		sourceColumn: EDCI_GHG_Total_Financed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_GHG_Total_Financed_Format
		dataType: string
		lineageTag: e60fc225-ace0-4832-98ab-afe0eb7a100c
		summarizeBy: none
		sourceColumn: EDCI_GHG_Total_Financed_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Active_Fossil_Fuels
		dataType: string
		lineageTag: 3912fdb3-f529-4ce9-b263-44d00600f4e9
		summarizeBy: none
		sourceColumn: EDCI_Active_Fossil_Fuels

		annotation SummarizationSetBy = Automatic

	column EDCI_Active_In_High_Impact_Climate_Sector
		dataType: string
		lineageTag: 13266236-aeaf-4231-9c23-f89abca6c201
		summarizeBy: none
		sourceColumn: EDCI_Active_In_High_Impact_Climate_Sector

		annotation SummarizationSetBy = Automatic

	column EDCI_Energy_Consumption_Intensity_High_Impact_Climate_Sector
		dataType: double
		lineageTag: b748c733-450a-499e-894e-472489deb933
		summarizeBy: sum
		sourceColumn: EDCI_Energy_Consumption_Intensity_High_Impact_Climate_Sector

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Energy_Consumption_Intensity_High_Impact_Climate_Sector_Format
		dataType: string
		lineageTag: cd7abe4e-c74c-4178-bb2f-c3b4c14fa2e6
		summarizeBy: none
		sourceColumn: EDCI_Energy_Consumption_Intensity_High_Impact_Climate_Sector_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Activities_Negatively_Affecting_BioSensitive
		dataType: string
		lineageTag: 11f6e77e-26a3-4aab-a095-a92984d6da4e
		summarizeBy: none
		sourceColumn: EDCI_Activities_Negatively_Affecting_BioSensitive

		annotation SummarizationSetBy = Automatic

	column EDCI_Emissions_to_Water
		dataType: string
		lineageTag: e23f6236-0f80-4ef3-9b66-c87bf8318574
		summarizeBy: none
		sourceColumn: EDCI_Emissions_to_Water

		annotation SummarizationSetBy = Automatic

	column EDCI_Hazardous_Waste_Generated
		dataType: string
		lineageTag: da155b44-704e-46fb-a4dd-4de98fb15a31
		summarizeBy: none
		sourceColumn: EDCI_Hazardous_Waste_Generated

		annotation SummarizationSetBy = Automatic

	column EDCI_Violations_UN_OECD
		dataType: string
		lineageTag: 65d27500-c034-46a2-b52d-ec5732cf49c0
		summarizeBy: none
		sourceColumn: EDCI_Violations_UN_OECD

		annotation SummarizationSetBy = Automatic

	column EDCI_Violations_UN_OECD_Comment
		dataType: string
		lineageTag: 5a09fec7-c962-4c31-95ba-0c1dc2b281f8
		summarizeBy: none
		sourceColumn: EDCI_Violations_UN_OECD_Comment

		annotation SummarizationSetBy = Automatic

	column EDCI_Lack_of_Mech_Monitor_Compliance_UN_OECD
		dataType: string
		lineageTag: 2685de8b-ca42-4d9e-b00c-b159c236b024
		summarizeBy: none
		sourceColumn: EDCI_Lack_of_Mech_Monitor_Compliance_UN_OECD

		annotation SummarizationSetBy = Automatic

	column EDCI_Gender_Pay_Gap_Unadjusted
		dataType: double
		lineageTag: 4569ae64-59ee-4b4a-a0de-180ba122c0ed
		summarizeBy: sum
		sourceColumn: EDCI_Gender_Pay_Gap_Unadjusted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Board_Gender_Diversity
		dataType: double
		lineageTag: 87726dd7-5e83-4752-b6ac-2739d3594f2f
		summarizeBy: sum
		sourceColumn: EDCI_Board_Gender_Diversity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Board_Gender_Diversity_Format
		dataType: string
		lineageTag: b9fb566f-e237-47d2-903e-22ceac527eae
		summarizeBy: none
		sourceColumn: EDCI_Board_Gender_Diversity_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Board_Gender_Diversity_Comment
		dataType: string
		lineageTag: c4f90932-c52b-4f33-9cf9-cb2cee6be044
		summarizeBy: none
		sourceColumn: EDCI_Board_Gender_Diversity_Comment

		annotation SummarizationSetBy = Automatic

	column EDCI_Controversial_Weapons
		dataType: string
		lineageTag: 88c02c7c-d6f0-43dd-bfe6-1babe1a347ff
		summarizeBy: none
		sourceColumn: EDCI_Controversial_Weapons

		annotation SummarizationSetBy = Automatic

	column EDCI_Carbon_Footprint
		dataType: double
		lineageTag: 5dc72a22-a11f-415b-9ff7-6715cdcbb55c
		summarizeBy: sum
		sourceColumn: EDCI_Carbon_Footprint

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Carbon_Footprint_Format
		dataType: string
		lineageTag: b300cca6-ea1d-44ba-895d-f16c4968510f
		summarizeBy: none
		sourceColumn: EDCI_Carbon_Footprint_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_GHG_Intensity_Weight
		dataType: double
		lineageTag: 6ba34adb-75a8-41ee-adf2-ea5877deb145
		summarizeBy: sum
		sourceColumn: EDCI_GHG_Intensity_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_GHG_Intensity_Weight_Format
		dataType: string
		lineageTag: 9e094349-c48d-43db-9a9a-79724d06367d
		summarizeBy: none
		sourceColumn: EDCI_GHG_Intensity_Weight_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Active_Fossil_Fuels_Weight
		dataType: double
		lineageTag: e08e22b9-e646-42f3-a5fc-8cbc2896b123
		summarizeBy: sum
		sourceColumn: EDCI_Active_Fossil_Fuels_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Active_Fossil_Fuels_Weight_Format
		dataType: string
		lineageTag: 8f5f3eb0-5df8-453f-a793-3110b3cee116
		summarizeBy: none
		sourceColumn: EDCI_Active_Fossil_Fuels_Weight_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_NonRenewable_Energy_Consumption_Weight
		dataType: double
		lineageTag: 9f933282-cb46-43e9-8a80-0dcc90c617dc
		summarizeBy: sum
		sourceColumn: EDCI_NonRenewable_Energy_Consumption_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_NonRenewable_Energy_Consumption_Weight_Format
		dataType: string
		lineageTag: 3e0bb3d8-cd5f-4e03-afb7-1ab4d07cf4a3
		summarizeBy: none
		sourceColumn: EDCI_NonRenewable_Energy_Consumption_Weight_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Activities_Negatively_Affecting_BioSensitive_Weight
		dataType: double
		lineageTag: 3743b719-3a29-4f64-9f13-27af48be94c6
		summarizeBy: sum
		sourceColumn: EDCI_Activities_Negatively_Affecting_BioSensitive_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Activities_Negatively_Affecting_BioSensitive_Weight_Format
		dataType: string
		lineageTag: 5025e3c9-19f8-4077-b633-b3a4097814b0
		summarizeBy: none
		sourceColumn: EDCI_Activities_Negatively_Affecting_BioSensitive_Weight_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Emissions_to_Water_Weight
		dataType: double
		lineageTag: bd613f86-587d-42bc-bde7-58c665e9e6f5
		summarizeBy: sum
		sourceColumn: EDCI_Emissions_to_Water_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Emissions_to_Water_Weight_Format
		dataType: string
		lineageTag: f85d4d38-f631-4e8b-a175-f317b3447e6d
		summarizeBy: none
		sourceColumn: EDCI_Emissions_to_Water_Weight_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Hazardous_Waste_Generated_Weight
		dataType: double
		lineageTag: e816aa9b-a043-4051-b99e-a5b7a8ed8158
		summarizeBy: sum
		sourceColumn: EDCI_Hazardous_Waste_Generated_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Hazardous_Waste_Generated_Weight_Format
		dataType: string
		lineageTag: 587a828b-a961-4382-84b7-57e3d713f889
		summarizeBy: none
		sourceColumn: EDCI_Hazardous_Waste_Generated_Weight_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Violations_UN_OECD_Weight
		dataType: double
		lineageTag: 92fbc16d-cc5c-417c-8a02-30e808665aed
		summarizeBy: sum
		sourceColumn: EDCI_Violations_UN_OECD_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Violations_UN_OECD_Weight_Format
		dataType: string
		lineageTag: 4ea4b088-1536-4c1c-85ab-8bee1969531e
		summarizeBy: none
		sourceColumn: EDCI_Violations_UN_OECD_Weight_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Lack_of_Mech_Monitor_Compliance_UN_OECD_Weight
		dataType: double
		lineageTag: c33494f1-4a8a-4858-8533-dcbeb73f4337
		summarizeBy: sum
		sourceColumn: EDCI_Lack_of_Mech_Monitor_Compliance_UN_OECD_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Lack_of_Mech_Monitor_Compliance_UN_OECD_Weight_Format
		dataType: string
		lineageTag: 87cc2527-fdfc-4a8f-a670-45ee8dd23afb
		summarizeBy: none
		sourceColumn: EDCI_Lack_of_Mech_Monitor_Compliance_UN_OECD_Weight_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Gender_Pay_Gap_Unadjusted_Weight
		dataType: double
		lineageTag: 300f2efb-33c1-4206-9bf4-b72de942bf33
		summarizeBy: sum
		sourceColumn: EDCI_Gender_Pay_Gap_Unadjusted_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Gender_Pay_Gap_Unadjusted_Weight_Format
		dataType: string
		lineageTag: 7ea486d7-d98f-43c9-8009-19ed1738f9b4
		summarizeBy: none
		sourceColumn: EDCI_Gender_Pay_Gap_Unadjusted_Weight_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Board_Gender_Diversity_Weight
		dataType: double
		lineageTag: 2d31bf3f-d7da-4774-b0f3-3e0196cecd14
		summarizeBy: sum
		sourceColumn: EDCI_Board_Gender_Diversity_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Board_Gender_Diversity_Weight_Format
		dataType: string
		lineageTag: d196baad-6572-41f0-8046-fb8f375c0fbb
		summarizeBy: none
		sourceColumn: EDCI_Board_Gender_Diversity_Weight_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Controversial_Weapons_Weight
		dataType: double
		lineageTag: 39d1755d-a82a-4e07-b811-4817fc0bcc1d
		summarizeBy: sum
		sourceColumn: EDCI_Controversial_Weapons_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EDCI_Controversial_Weapons_Weight_Format
		dataType: string
		lineageTag: f2912e4c-fb3a-4b82-b575-9ef7f2d6c4e3
		summarizeBy: none
		sourceColumn: EDCI_Controversial_Weapons_Weight_Format

		annotation SummarizationSetBy = Automatic

	column EDCI_Comment_General
		dataType: string
		lineageTag: 1549d167-454e-4d60-877a-780e0814ff4f
		summarizeBy: none
		sourceColumn: EDCI_Comment_General

		annotation SummarizationSetBy = Automatic

	column FFCo_Company_ID
		dataType: string
		lineageTag: 08b26a7a-4e30-4fa9-8455-179c18580e9d
		summarizeBy: none
		sourceColumn: FFCo_Company_ID

		annotation SummarizationSetBy = Automatic

	column FFCo_Company_Name
		dataType: string
		lineageTag: c5a5e47d-9673-455b-b2b6-397fb03ab61d
		summarizeBy: none
		sourceColumn: FFCo_Company_Name

		annotation SummarizationSetBy = Automatic

	column FFCo_Company_Comment_General
		dataType: string
		lineageTag: 4c6032cc-89ea-4bc9-a641-dd58fc7037c6
		summarizeBy: none
		sourceColumn: FFCo_Company_Comment_General

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Baseline_Year
		dataType: string
		lineageTag: 8ac90479-bda0-442f-b6ad-c0db1c8fd131
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Baseline_Year

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Baseline_Year_Comment
		dataType: string
		lineageTag: 844c2792-d2e6-4a6e-9725-186e3b0c0a44
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Baseline_Year_Comment

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Report_Standards
		dataType: string
		lineageTag: 980cbdf3-cd24-46ce-b22f-a1b067916286
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Report_Standards

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Report_Standards_Comment
		dataType: string
		lineageTag: 08c94c26-41c9-4823-a903-c4a7f78463d8
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Report_Standards_Comment

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Roadmap_Target
		dataType: string
		lineageTag: 0d065e65-d794-4fed-8828-8e18faeff907
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Roadmap_Target

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Roadmap_Target_Comment
		dataType: string
		lineageTag: 84b51668-b264-4a5e-9ef4-869d34651d2d
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Roadmap_Target_Comment

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Climate_Scenario_Analysis
		dataType: string
		lineageTag: 0379e4ac-d0ff-4293-b28d-cc354bdd5bcc
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Climate_Scenario_Analysis

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Climate_Scenario_Analysis_Comment
		dataType: string
		lineageTag: 1472528a-b37a-4746-9598-3d4e373efa54
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Climate_Scenario_Analysis_Comment

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Capital_Allocations_Target
		dataType: string
		lineageTag: 93216251-8dcb-4db1-bd1a-128bfa123c4d
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Capital_Allocations_Target

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Capital_Allocations_Target_Comment
		dataType: string
		lineageTag: afbcbfd3-e918-4b9d-9839-82546ed3784e
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Capital_Allocations_Target_Comment

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Interim_Target
		dataType: string
		lineageTag: 8a4bcf06-2ee9-48d2-92aa-2c06986a368a
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Interim_Target

		annotation SummarizationSetBy = Automatic

	column FFCo_Net_Zero_Interim_Target_Comment
		dataType: string
		lineageTag: f93fd603-3992-4970-b213-5fdb83322f96
		summarizeBy: none
		sourceColumn: FFCo_Net_Zero_Interim_Target_Comment

		annotation SummarizationSetBy = Automatic

	column FFCo_Modern_Slavery_Training
		dataType: string
		lineageTag: f7425995-07c5-4db6-a810-f9e49a1bcf8c
		summarizeBy: none
		sourceColumn: FFCo_Modern_Slavery_Training

		annotation SummarizationSetBy = Automatic

	column FFCo_Modern_Slavery_Training_Comment
		dataType: string
		lineageTag: 2a239324-d564-4f7b-84da-115f33adde9f
		summarizeBy: none
		sourceColumn: FFCo_Modern_Slavery_Training_Comment

		annotation SummarizationSetBy = Automatic

	column FFCo_Modern_Slavery_Due_Diligence
		dataType: string
		lineageTag: d204b29f-fda7-40f3-8122-5d9905c3a018
		summarizeBy: none
		sourceColumn: FFCo_Modern_Slavery_Due_Diligence

		annotation SummarizationSetBy = Automatic

	column FFCo_Modern_Slavery_Due_Diligence_Comment
		dataType: string
		lineageTag: fb32d758-4cfa-4e8a-a6ba-2153468bef3a
		summarizeBy: none
		sourceColumn: FFCo_Modern_Slavery_Due_Diligence_Comment

		annotation SummarizationSetBy = Automatic

	column FFCo_Modern_Slavery_Instances
		dataType: string
		lineageTag: deafdc17-db22-4a27-a695-54fafd0b01df
		summarizeBy: none
		sourceColumn: FFCo_Modern_Slavery_Instances

		annotation SummarizationSetBy = Automatic

	column FFCo_Modern_Slavery_Instances_Comment
		dataType: string
		lineageTag: 88f200aa-f78f-48ae-a41e-29ce21fee9a7
		summarizeBy: none
		sourceColumn: FFCo_Modern_Slavery_Instances_Comment

		annotation SummarizationSetBy = Automatic

	column FFCo_Modern_Slavery_Whistleblower
		dataType: string
		lineageTag: c16e96ee-25b1-48a9-b96f-8d9cd6255f2f
		summarizeBy: none
		sourceColumn: FFCo_Modern_Slavery_Whistleblower

		annotation SummarizationSetBy = Automatic

	column FFCo_Modern_Slavery_Whistleblower_Comment
		dataType: string
		lineageTag: 4ed61737-74bf-4199-9fd9-f472f381a507
		summarizeBy: none
		sourceColumn: FFCo_Modern_Slavery_Whistleblower_Comment

		annotation SummarizationSetBy = Automatic

	column FFCo_Work_Related_Injuries_Heath_Safety_Policy
		dataType: string
		lineageTag: 0d823aea-9cdb-40b7-a916-de85826113ce
		summarizeBy: none
		sourceColumn: FFCo_Work_Related_Injuries_Heath_Safety_Policy

		annotation SummarizationSetBy = Automatic

	column FFCo_Work_Related_Injuries_Heath_Safety_Policy_Comment
		dataType: string
		lineageTag: 22c57ea9-b24f-4b87-9af2-12510df6d373
		summarizeBy: none
		sourceColumn: FFCo_Work_Related_Injuries_Heath_Safety_Policy_Comment

		annotation SummarizationSetBy = Automatic

	column FFCo_Work_Related_Injuries_Risk_Assessment
		dataType: string
		lineageTag: da305a75-b3b5-4f79-8c12-611a092ef4ab
		summarizeBy: none
		sourceColumn: FFCo_Work_Related_Injuries_Risk_Assessment

		annotation SummarizationSetBy = Automatic

	column FFCo_Work_Related_Injuries_Risk_Assessment_Comment
		dataType: string
		lineageTag: d062440d-bbc1-41e8-ad8b-30c50ee64b95
		summarizeBy: none
		sourceColumn: FFCo_Work_Related_Injuries_Risk_Assessment_Comment

		annotation SummarizationSetBy = Automatic

	column Comment_General
		dataType: string
		lineageTag: ccfdd5e0-2017-43f6-b62b-3168438c11f3
		summarizeBy: none
		sourceColumn: Comment_General

		annotation SummarizationSetBy = Automatic

	partition dp_lpa_esg_company_level_v1 = m
		mode: import
		queryGroup: 'LP Analyst'
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    Schema = Table.SelectRows(hive_metastore_Database, each ([Name] =p_lpa_database)),
				    lpa_Schema = Schema{[Name=p_lpa_database,Kind="Schema"]}[Data],
				    dp_lpa_esg_company_level_Table = lpa_Schema{[Name="dp_lpa_esg_company_level",Kind="Table"]}[Data],
				    #"Removed Duplicates" = Table.Distinct(dp_lpa_esg_company_level_Table, {"LPA_Company_Level_Date_Key"}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Blank Rows", each [LPA_Company_Level_Date_Key] <> null),
				    FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				      dp_lpa_esg_company_level_Table, 
				      100
				     )
				 else 
				    dp_lpa_esg_company_level_Table
				     in
				  FilterLogic
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

