table 'ESG Trucost Climate History'
	lineageTag: ef697cf8-4849-4d65-a1a2-ef6d5d06893e

	measure 'Renewables history (GWH)' = ```
			
			CALCULATE (SUMX (
			            'ESG Trucost Climate History',
			            'ESG Trucost Climate History'[Wind_Power_Generation_GWh] + 'ESG Trucost Climate History'[Solar_Power_Generation_GWh] + 'ESG Trucost Climate History'[Wave_And_Tidal_Power_Generation_GWh] + 'ESG Trucost Climate History'[Geothermal_Power_Generation_GWh]
			        )
			)
			
			```
		lineageTag: 3d46f069-ca5e-464f-9adf-29b8df2ac6ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Others (incl. landfill gas) Power Generation (GWH) history' =
			
			CALCULATE (SUMX (
			            'ESG Trucost Climate History',
			            'ESG Trucost Climate History'[Other_Power_Generation_GWh] + 'ESG Trucost Climate History'[Landfill_Gas_Power_Generation_GWh]
			        )
			)
		lineageTag: a3a72997-21e2-4775-a7e9-62536efda196

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 2) - no ownership' =
			
			CALCULATE(SUMX('ESG Trucost Climate History', DIVIDE('ESG Trucost Climate History'[Carbon_Scope_2_tonnes_CO2e], 'ESG Trucost Climate History'[Revenue_AUD_mn history])), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		lineageTag: 4c48a387-cf7d-4480-8751-8239587a7d18

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 1) - no ownership' = ```
			
			CALCULATE(
			    SUMX('ESG Trucost Climate History', 
			        DIVIDE('ESG Trucost Climate History'[Carbon_Scope_1_tonnes_CO2e], 'ESG Trucost Climate History'[Revenue_AUD_mn history])), 
			        LASTDATE('ESG Trucost Climate History'[Date_Value]))
			```
		lineageTag: b3a89ec3-75ae-4760-85e8-4b0f6595f807

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Natural Gas (GWH)' = ```
			
			SUMX ('ESG Trucost Climate', 'ESG Trucost Climate'[Natural_Gas_Power_Generation_GWh] + 'ESG Trucost Climate'[LPG_Power_Generation_GWh] + 'ESG Trucost Climate'[LNG_Power_Generation_GWh] )
			
			```
		lineageTag: c3c9a2dc-baa5-48f3-8bcc-9710ed0d6ef0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Carbon Scope 1 tonnes CO2e' = ```
			
			CALCULATE(SUM('ESG Trucost Climate History'[Carbon_Scope_1_tonnes_CO2e] ), 
			LASTDATE( 'ESG Trucost Climate History'[Date_Value] )
			)
			// LASTNONBLANKVALUE('ESG Events'[Valid_From], MAX('ESG Events'[Score (GSS Num)]))
			
			```
		displayFolder: End-of-date Measures
		lineageTag: 22553b42-b73a-4ac3-b32f-af585302cbfa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Carbon Scope 2 tonnes CO2e' = ```
			
			CALCULATE(SUM('ESG Trucost Climate History'[Carbon_Scope_2_tonnes_CO2e] ), 
			LASTDATE( 'ESG Trucost Climate History'[Date_Value] )
			)
			```
		displayFolder: End-of-date Measures
		lineageTag: 616b8a95-369e-4553-8711-021aa31933e8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Carbon Scope 3 tonnes CO2e' = ```
			
			CALCULATE(SUM('ESG Trucost Climate History'[Carbon_Scope_3_tonnes_CO2e] ), 
			LASTDATE( 'ESG Trucost Climate History'[Date_Value] )
			)
			```
		displayFolder: End-of-date Measures
		lineageTag: f0b61c3e-4ba4-4d19-85df-e83f61454cbb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Coal Power Generation (GWh)' =
			
			CALCULATE(SUM('ESG Trucost Climate History'[Coal_Power_Generation_GWh]), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		displayFolder: End-of-date Measures
		lineageTag: ffcc241d-8e5e-4a78-b806-6ce13ed089b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Nuclear Power Generation (GWh)' =
			
			CALCULATE(SUM('ESG Trucost Climate History'[Nuclear_Power_Generation_GWh]), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		displayFolder: End-of-date Measures
		lineageTag: eb44e058-8f16-4641-99d1-42ed8f2c2e2c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Hydroelectric Power Generation (GWh)' =
			
			CALCULATE(SUM('ESG Trucost Climate History'[Hydroelectric_Power_Generation_GWh]), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		displayFolder: End-of-date Measures
		lineageTag: dcfebef7-a092-4ec9-a695-e7f0abd146ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Others Power Generation (GWh)' =
			
			CALCULATE(SUMX('ESG Trucost Climate History', 'ESG Trucost Climate History'[Others (incl. landfill gas) Power Generation (GWH) history]), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		displayFolder: End-of-date Measures
		lineageTag: 8eb62ebe-9df2-488d-aed6-c7698ec3b728

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Natural Gas Power Generation (GWh)' =
			
			CALCULATE(SUMX('ESG Trucost Climate History', 'ESG Trucost Climate History'[Natural Gas (GWH)]), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		formatString: 0
		displayFolder: End-of-date Measures
		lineageTag: 0bb98eb8-9ca5-4cfe-be30-9adc6bb3a036

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Petroleum Power Generation (GWh)' =
			
			CALCULATE(SUM('ESG Trucost Climate History'[Petroleum_Power_Generation_GWh]), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		displayFolder: End-of-date Measures
		lineageTag: fbc786b4-48e7-44b3-a51c-8bb34b3ea479

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Biomass Power Generation (GWh)' =
			
			CALCULATE(SUM('ESG Trucost Climate History'[Biomass_Power_Generation_GWh]), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		displayFolder: End-of-date Measures
		lineageTag: 186ebef5-ff81-428a-99ee-9c2395fdbd4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Renewables Power Generation (GWh)' =
			
			CALCULATE(SUMX('ESG Trucost Climate History', [Renewables history (GWH)]), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		displayFolder: End-of-date Measures
		lineageTag: e4889638-e877-4543-b306-133a968d703b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Thermal Coal Mining Sector Revenue Percent' =
			
			CALCULATE(SUM('ESG Trucost Climate History'[Thermal_Coal_Mining_Sector_Revenue_Percent]), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		displayFolder: End-of-date Measures
		lineageTag: d653355d-aff2-4ece-80b1-bef806138bfa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Geothermal Power Generation Revenue Percent' =
			
			CALCULATE(SUM('ESG Trucost Climate History'[Geothermal_Power_Generation_Revenue_Percent]), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		displayFolder: End-of-date Measures
		lineageTag: fddc9288-d939-4f8f-9750-cbfa2500ec08

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Display data as of the end of the selected date period. i.e. end of year, end of quarter etc.
	measure 'End-Of-Date Bituminous Coal Underground Mining Sector Revenue Percent' =
			
			CALCULATE(SUM('ESG Trucost Climate History'[Bituminous_Coal_Underground_Mining_Revenue_Percent]), LASTDATE('ESG Trucost Climate History'[Date_Value]))
		displayFolder: End-of-date Measures
		lineageTag: 9537609f-bc88-4159-b16c-b061efc29a49

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No Thermal Energy Mix msg' = ```
			
			
			IF(
			 // All data is blank 
			ISBLANK(SUMX('ESG Trucost Climate History', [End-Of-Date Geothermal Power Generation Revenue Percent] + [End-Of-Date Bituminous Coal Underground Mining Sector Revenue Percent] + [End-Of-Date Thermal Coal Mining Sector Revenue Percent]))
			|| 
			// or all data is zero
			SUMX('ESG Trucost Climate History', [End-Of-Date Geothermal Power Generation Revenue Percent] + [End-Of-Date Bituminous Coal Underground Mining Sector Revenue Percent] + [End-Of-Date Thermal Coal Mining Sector Revenue Percent]) = 0 ,
			
			
			"No thermal energy mix in data",
			 ""
			 
			)
			```
		lineageTag: e4574ddb-7335-4852-ae75-2eae8eac0116

	measure 'No Carbon Emissions msg' = ```
			
			
			IF(
			 // All data is blank 
			ISBLANK(SUMX('ESG Trucost Climate History', [End-Of-Date Carbon Scope 1 tonnes CO2e] + [End-Of-Date Carbon Scope 2 tonnes CO2e] + [End-Of-Date Carbon Scope 3 tonnes CO2e]))
			|| 
			// or all data is zero
			SUMX('ESG Trucost Climate History', [End-Of-Date Carbon Scope 1 tonnes CO2e] + [End-Of-Date Carbon Scope 2 tonnes CO2e] + [End-Of-Date Carbon Scope 3 tonnes CO2e]) = 0 ,
			
			
			"No carbon emissions data",
			 ""
			 
			)
			```
		lineageTag: 51010ce0-6024-4bfd-8c48-d80b80cb5931

	measure 'No Energy Mix History msg' = ```
			
			
			IF(
			 // All data is blank 
			ISBLANK(SUMX('ESG Trucost Climate History', [End-Of-Date Coal Power Generation (GWh)] + [End-Of-Date Biomass Power Generation (GWh)] + [End-Of-Date Hydroelectric Power Generation (GWh)] + [End-Of-Date Natural Gas Power Generation (GWh)] + [End-Of-Date Nuclear Power Generation (GWh)] + [End-Of-Date Others Power Generation (GWh)] + [End-Of-Date Petroleum Power Generation (GWh)] + [End-Of-Date Renewables Power Generation (GWh)]))
			|| 
			// or all data is zero
			SUMX('ESG Trucost Climate History', [End-Of-Date Coal Power Generation (GWh)] + [End-Of-Date Biomass Power Generation (GWh)] + [End-Of-Date Hydroelectric Power Generation (GWh)] + [End-Of-Date Natural Gas Power Generation (GWh)] + [End-Of-Date Nuclear Power Generation (GWh)] + [End-Of-Date Others Power Generation (GWh)] + [End-Of-Date Petroleum Power Generation (GWh)] + [End-Of-Date Renewables Power Generation (GWh)]) = 0 ,
			
			
			"No energy mix in data",
			 ""
			 
			)
			
			
			```
		lineageTag: f7449890-1f11-4111-8faa-123f319c30ea

	measure 'End-Of-Date Carbon Scope 3 Upstream tonnes CO2e' = ```
			
			CALCULATE(SUM('ESG Trucost Climate History'[Absolute_GHG_Scope_3_Upstream_Total] ), 
			LASTDATE( 'ESG Trucost Climate History'[Date_Value] )
			)
			```
		displayFolder: End-of-date Measures
		lineageTag: e010e026-9224-44fb-8253-8dd5c650f27d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'End-Of-Date Carbon Scope 3 Downstream tonnes CO2e' = ```
			
			CALCULATE(SUM('ESG Trucost Climate History'[Absolute_GHG_Scope_3_Downstream_Total] ), 
			LASTDATE( 'ESG Trucost Climate History'[Date_Value] )
			)
			```
		displayFolder: End-of-date Measures
		lineageTag: 123ad4cc-9e16-4387-9d96-424fbc8db31a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 3 Upstream) - no ownership' = ```
			
			CALCULATE(
			    SUMX('ESG Trucost Climate History', 
			        DIVIDE('ESG Trucost Climate History'[Absolute_GHG_Scope_3_Upstream_Total], 'ESG Trucost Climate History'[Revenue_AUD_mn history])), 
			        LASTDATE('ESG Trucost Climate History'[Date_Value]))
			```
		lineageTag: ae698042-5415-49cb-a948-b0d00190ee91

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 3 Downstream) - no ownership' = ```
			
			CALCULATE(
			    SUMX('ESG Trucost Climate History', 
			        DIVIDE('ESG Trucost Climate History'[Absolute_GHG_Scope_3_Downstream_Total], 'ESG Trucost Climate History'[Revenue_AUD_mn history])), 
			        LASTDATE('ESG Trucost Climate History'[Date_Value]))
			```
		lineageTag: 465fab99-6b54-4952-932b-3799dab52f91

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TCUID_Date_Key
		dataType: string
		lineageTag: ba24924a-d5a9-467e-b936-2f46b2551547
		summarizeBy: none
		sourceColumn: TCUID_Date_Key

		annotation SummarizationSetBy = Automatic

	column Date_Value
		dataType: dateTime
		formatString: General Date
		lineageTag: ad417ba5-3620-4e8c-9780-d194bbd2fdec
		summarizeBy: none
		sourceColumn: Date_Value

		variation Variation
			isDefault
			relationship: 8f539fe8-60a6-4ac2-b4a7-ca86ca1ef531
			defaultHierarchy: LocalDateTable_024a572b-e072-4aea-b824-5091fedde839.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column sk_date
		dataType: double
		lineageTag: a8be1152-de99-4411-9ced-f3df34f37793
		summarizeBy: sum
		sourceColumn: sk_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TCUID
		dataType: int64
		formatString: 0
		lineageTag: d7e9ef44-9775-458d-8b1f-2f97655a8f66
		summarizeBy: count
		sourceColumn: TCUID

		annotation SummarizationSetBy = Automatic

	column ISIN
		dataType: string
		lineageTag: 34072ba1-5767-44ad-8f96-c8ed7e2e7c24
		summarizeBy: none
		sourceColumn: ISIN

		annotation SummarizationSetBy = Automatic

	column Financial_Year
		dataType: string
		lineageTag: 8792b7e9-c9a0-4f7c-b2f9-697a222db5ed
		summarizeBy: none
		sourceColumn: Financial_Year

		annotation SummarizationSetBy = Automatic

	column Accounting_Year_End
		dataType: dateTime
		formatString: Long Date
		lineageTag: cc36d926-77fc-4f17-bcbd-8a2c7a07989f
		summarizeBy: none
		sourceColumn: Accounting_Year_End

		variation Variation
			isDefault
			relationship: e9947fd7-17b5-4aa8-8a08-230cc7375917
			defaultHierarchy: LocalDateTable_f2f6b08a-9038-410f-af00-a16f5d6ef769.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Effective_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c8cbf5dd-ac1f-48b2-b171-dde7e7150fd2
		summarizeBy: none
		sourceColumn: Effective_Date

		variation Variation
			isDefault
			relationship: 45e456d4-57a8-41dd-a93f-7a088b9ca22b
			defaultHierarchy: LocalDateTable_d903522f-715f-43fa-b32f-e0512328ba76.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Carbon_Scope_1_tonnes_CO2e
		dataType: double
		lineageTag: 69bd6491-d3f6-4ea8-a167-36cebd6f8330
		summarizeBy: none
		sourceColumn: Carbon_Scope_1_tonnes_CO2e

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Scope_2_tonnes_CO2e
		dataType: double
		lineageTag: ff025aa9-6e35-4a2a-a894-0ba700ecda6c
		summarizeBy: none
		sourceColumn: Carbon_Scope_2_tonnes_CO2e

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Scope_3_tonnes_CO2e
		dataType: double
		lineageTag: 442481bb-a28c-416f-8c57-76230aa61e25
		summarizeBy: none
		sourceColumn: Carbon_Scope_3_tonnes_CO2e

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Direct_tonnes_CO2e
		dataType: double
		lineageTag: f11f7c6b-c1b6-431b-8889-80660db42165
		summarizeBy: sum
		sourceColumn: Carbon_Direct_tonnes_CO2e

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_First_Tier_Indirect_tonnes_CO2e
		dataType: double
		lineageTag: e26b72fc-8131-437a-a5ed-ded7060b314e
		summarizeBy: sum
		sourceColumn: Carbon_First_Tier_Indirect_tonnes_CO2e

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Direct_And_First_Tier_Indirect_tonnes_CO2e
		dataType: double
		lineageTag: b788b57a-6dd8-4cf9-98d5-82cebe98ede0
		summarizeBy: sum
		sourceColumn: Carbon_Direct_And_First_Tier_Indirect_tonnes_CO2e

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_Scope_1_tonnes_CO2e_USD_mn
		dataType: double
		lineageTag: 645aeee5-2c49-4d6e-9328-b5180ea8a282
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_Scope_1_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_Scope_2_tonnes_CO2e_USD_mn
		dataType: double
		lineageTag: 97dcc034-4076-4cf4-a862-87e2724e95f7
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_Scope_2_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_Scope_3_tonnes_CO2e_USD_mn
		dataType: double
		lineageTag: d9eb2810-72b1-4722-b750-76aea6bdfd70
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_Scope_3_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_Direct_tonnes_CO2e_USD_mn
		dataType: double
		lineageTag: 52747214-ce6e-4e15-8645-f841604e0ea2
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_Direct_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_First_Tier_Indirect_tonnes_CO2e_USD_mn
		dataType: double
		lineageTag: f27d2900-9abf-4626-96f5-98a10d02c837
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_First_Tier_Indirect_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_Direct_And_First_Tier_Indirect_tonnes_CO2e_USD_mn
		dataType: double
		lineageTag: 06233e65-2b5d-41bb-af4c-93e96bf6e504
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_Direct_And_First_Tier_Indirect_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Direct_USD_mn
		dataType: double
		lineageTag: 3ab8c6df-36e7-4ae1-86f9-5eff104b7c2b
		summarizeBy: sum
		sourceColumn: GHG_Direct_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Indirect_USD_mn
		dataType: double
		lineageTag: e5d6b5fe-1209-459b-a507-8439db7b85fb
		summarizeBy: sum
		sourceColumn: GHG_Indirect_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Total_USD_mn
		dataType: double
		lineageTag: a8290597-f181-4a1b-84cf-c871982db4f0
		summarizeBy: sum
		sourceColumn: GHG_Total_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Direct_Impact_Ratio_Percent
		dataType: double
		lineageTag: ef31a8a1-6c70-44ff-844e-60e12f7a32fa
		summarizeBy: sum
		sourceColumn: GHG_Direct_Impact_Ratio_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Indirect_Impact_Ratio_Percent
		dataType: double
		lineageTag: 92f46fab-a879-497f-88f3-e6422d3bfc52
		summarizeBy: sum
		sourceColumn: GHG_Indirect_Impact_Ratio_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Total_Impact_Ratio_Percent
		dataType: double
		lineageTag: e980f47a-bacc-4170-8bfb-6d822c99ed16
		summarizeBy: sum
		sourceColumn: GHG_Total_Impact_Ratio_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Disclosure
		dataType: string
		lineageTag: ec8f1713-c405-480e-9f06-c4fa9c310d02
		summarizeBy: none
		sourceColumn: Carbon_Disclosure

		annotation SummarizationSetBy = Automatic

	column Revenue_USD_mn
		dataType: double
		lineageTag: a2b93485-dbcb-4606-9230-0e8bb5511ab7
		summarizeBy: sum
		sourceColumn: Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Currency_Code
		dataType: string
		lineageTag: 95363425-050f-45c6-81ec-de3762832706
		summarizeBy: none
		sourceColumn: Currency_Code

		annotation SummarizationSetBy = Automatic

	column Effective_Date_Start
		dataType: dateTime
		formatString: General Date
		lineageTag: ecb8dec6-7ca8-483a-a1fd-71f699417d49
		summarizeBy: none
		sourceColumn: Effective_Date_Start

		variation Variation
			isDefault
			relationship: eae1d87c-8280-4adf-9b29-bfa3706d1837
			defaultHierarchy: LocalDateTable_16b7802a-c1b8-493f-b062-5e007f99695e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Bituminous_Coal_and_Lignite_Surface_Mining_Revenue_USD_mn
		dataType: double
		lineageTag: e85d333e-a80a-42c4-aed4-1933a9a506d9
		summarizeBy: sum
		sourceColumn: Bituminous_Coal_and_Lignite_Surface_Mining_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Bituminous_Coal_and_Lignite_Surface_Mining_Revenue_Percent
		dataType: double
		lineageTag: d2d29878-b957-4e79-947e-ab711930732b
		summarizeBy: sum
		sourceColumn: Bituminous_Coal_and_Lignite_Surface_Mining_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Bituminous_Coal_Underground_Mining_Revenue_USD_mn
		dataType: double
		lineageTag: 2fa0b994-6e16-4809-8356-1e8ab9bf10b9
		summarizeBy: sum
		sourceColumn: Bituminous_Coal_Underground_Mining_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Bituminous_Coal_Underground_Mining_Revenue_Percent
		dataType: double
		lineageTag: 1707b1e3-0e86-4854-b0a6-6f2a71de7d6e
		summarizeBy: sum
		sourceColumn: Bituminous_Coal_Underground_Mining_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Crude_Petroleum_and_Natural_Gas_Extraction_Revenue_USD_mn
		dataType: double
		lineageTag: b0516206-3976-499d-9588-9b6b18966df5
		summarizeBy: sum
		sourceColumn: Crude_Petroleum_and_Natural_Gas_Extraction_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Crude_Petroleum_and_Natural_Gas_Extraction_Revenue_Percent
		dataType: double
		lineageTag: d3cbde50-c0fb-4ba8-982d-9970ba7dffa9
		summarizeBy: sum
		sourceColumn: Crude_Petroleum_and_Natural_Gas_Extraction_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Natural_Gas_Liquid_Extraction_Revenue_USD_mn
		dataType: double
		lineageTag: 91478ba7-47ae-4e3a-8979-88a7364b9b8b
		summarizeBy: sum
		sourceColumn: Natural_Gas_Liquid_Extraction_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Natural_Gas_Liquid_Extraction_Revenue_Percent
		dataType: double
		lineageTag: 6da9c38f-4ebf-45e9-9884-0fb134875429
		summarizeBy: sum
		sourceColumn: Natural_Gas_Liquid_Extraction_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tar_Sands_Extraction_Revenue_USD_mn
		dataType: double
		lineageTag: 030dc8de-9f39-43ba-b4ee-4c2da378b0de
		summarizeBy: sum
		sourceColumn: Tar_Sands_Extraction_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tar_Sands_Extraction_Revenue_Percent
		dataType: double
		lineageTag: 79fbe3c1-fb12-41d5-a37c-b7538a57f964
		summarizeBy: sum
		sourceColumn: Tar_Sands_Extraction_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Support_Activities_For_Oil_And_Gas_Operations_Revenue_USD_mn
		dataType: double
		lineageTag: 107d9f25-8053-4bd5-93d9-a8c8d912145f
		summarizeBy: sum
		sourceColumn: Support_Activities_For_Oil_And_Gas_Operations_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Support_Activities_For_Oil_And_Gas_Operations_Revenue_Percent
		dataType: double
		lineageTag: c48ae7e1-6b8f-40c0-8810-2dcd27501a0f
		summarizeBy: sum
		sourceColumn: Support_Activities_For_Oil_And_Gas_Operations_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: c1962bc8-4370-49de-956b-72c43f304b92
		summarizeBy: sum
		sourceColumn: Coal_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: aa5e4c97-f781-4c34-bb25-cc17c0707020
		summarizeBy: sum
		sourceColumn: Coal_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Natural_Gas_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: 964a268e-9c16-4c15-8867-a8b98b6d79f0
		summarizeBy: sum
		sourceColumn: Natural_Gas_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Natural_Gas_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: 750213d3-8f00-44ab-a737-8abdcb818c43
		summarizeBy: sum
		sourceColumn: Natural_Gas_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Petroleum_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: f03ef1c2-365e-4c29-a09b-38ef8d3fa0ce
		summarizeBy: sum
		sourceColumn: Petroleum_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Petroleum_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: cb7a48d1-793b-46a7-a195-eaea129e3cec
		summarizeBy: sum
		sourceColumn: Petroleum_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Solar_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: cd4381a7-cba0-43e9-91d4-8198fce88b8f
		summarizeBy: sum
		sourceColumn: Solar_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Solar_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: fd9d6709-0a34-4ed2-9148-a9ab67d70a64
		summarizeBy: sum
		sourceColumn: Solar_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wind_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: 0f45d0fd-4389-4ca0-a619-19ef5f257621
		summarizeBy: sum
		sourceColumn: Wind_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wind_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: bcb055cf-a8fe-4878-89c9-44ff4af60e3f
		summarizeBy: sum
		sourceColumn: Wind_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Geothermal_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: 87ce3655-f9b7-4a44-933e-434c3c573cfd
		summarizeBy: sum
		sourceColumn: Geothermal_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Geothermal_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: e4691f53-5b0f-4c1d-9248-2d5c3061a6f0
		summarizeBy: sum
		sourceColumn: Geothermal_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wave_And_Tidal_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: f00cc3f6-7798-4c0d-ab3a-e3744c948ecf
		summarizeBy: sum
		sourceColumn: Wave_And_Tidal_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wave_And_Tidal_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: 0ae1e1b2-9169-45c2-b7c2-876aa3760e96
		summarizeBy: sum
		sourceColumn: Wave_And_Tidal_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Biomass_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: de8f488f-a2d9-445c-a096-9f2afa44b7fa
		summarizeBy: sum
		sourceColumn: Biomass_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Biomass_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: 7eab0a40-2649-4c45-93fb-09bfcbb5966b
		summarizeBy: sum
		sourceColumn: Biomass_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Landfill_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: f6233705-8633-4194-90e3-5fc4f0c7e784
		summarizeBy: sum
		sourceColumn: Landfill_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Landfill_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: a270d583-c77c-4818-bdd6-4ca45df43cda
		summarizeBy: sum
		sourceColumn: Landfill_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Hydroelectric_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: c8db9c14-0822-4985-8263-a1db39bcf4ea
		summarizeBy: sum
		sourceColumn: Hydroelectric_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Hydroelectric_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: d519968e-edfe-44a5-ab73-dd5567d98b3e
		summarizeBy: sum
		sourceColumn: Hydroelectric_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Nuclear_Electric_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: 8282939a-ac5f-41c8-94cf-55bc754edd43
		summarizeBy: sum
		sourceColumn: Nuclear_Electric_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Nuclear_Electric_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: fab87f94-a4c6-44ba-90c9-65d80dccbd48
		summarizeBy: sum
		sourceColumn: Nuclear_Electric_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Eletric_Power_Generation_Revenue_USD_mn
		dataType: double
		lineageTag: 94b85533-31e3-4c65-be4f-a910cd033069
		summarizeBy: sum
		sourceColumn: Other_Eletric_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Eletric_Power_Generation_Revenue_Percent
		dataType: double
		lineageTag: 2f10500a-9471-4e60-af58-8fb64463fd75
		summarizeBy: sum
		sourceColumn: Other_Eletric_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_CO2_emissions_from_Coal_m_tonnes
		dataType: double
		lineageTag: efe66f4a-e1c4-45e7-82be-ac2b98046c9e
		summarizeBy: sum
		sourceColumn: Reserves_CO2_emissions_from_Coal_m_tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_CO2_emissions_from_Oil_m_tonnes
		dataType: double
		lineageTag: 2813e9ae-f202-4b68-b7d1-d6453c7665f9
		summarizeBy: sum
		sourceColumn: Reserves_CO2_emissions_from_Oil_m_tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_CO2_emissions_from_Gas_m_tonnes
		dataType: double
		lineageTag: fbea4725-dfc6-4b20-864d-026d792aa63d
		summarizeBy: sum
		sourceColumn: Reserves_CO2_emissions_from_Gas_m_tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Reserves_CO2_emissions_m_tonnes
		dataType: double
		lineageTag: cdf031d2-a5ee-47c4-b6a1-f100f46aeb09
		summarizeBy: sum
		sourceColumn: Total_Reserves_CO2_emissions_m_tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CAPEX_Coal_m_USD
		dataType: double
		lineageTag: 448eeef0-31bc-4ae9-89fe-e9a732771bad
		summarizeBy: sum
		sourceColumn: CAPEX_Coal_m_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CAPEX_Gas_m_USD
		dataType: double
		lineageTag: 85d7cabd-abbd-4dac-a597-7c5814b6a5a9
		summarizeBy: sum
		sourceColumn: CAPEX_Gas_m_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CAPEX_Oil_And_Gas_m_USD
		dataType: double
		lineageTag: ba3850f6-86ff-45a0-83c1-79ec16b0984d
		summarizeBy: sum
		sourceColumn: CAPEX_Oil_And_Gas_m_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CAPEX_Other_exploration_m_USD
		dataType: double
		lineageTag: 6338cfbb-b54e-440f-ad85-158ebd2a8c75
		summarizeBy: sum
		sourceColumn: CAPEX_Other_exploration_m_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Power_Generation_GWh
		dataType: double
		lineageTag: cdf82f44-eaa9-466d-84d9-3eeafc380efd
		summarizeBy: sum
		sourceColumn: Coal_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Petroleum_Power_Generation_GWh
		dataType: double
		lineageTag: ca200174-18c6-4330-b4ab-32d9bffae73e
		summarizeBy: sum
		sourceColumn: Petroleum_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Natural_Gas_Power_Generation_GWh
		dataType: double
		lineageTag: ae665966-b318-4770-8989-6fdc2c296f1a
		summarizeBy: sum
		sourceColumn: Natural_Gas_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LPG_Power_Generation_GWh
		dataType: double
		lineageTag: 49f0aff7-6d18-4af3-808c-84fb45e4dffd
		summarizeBy: sum
		sourceColumn: LPG_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LNG_Power_Generation_GWh
		dataType: double
		lineageTag: 4c5a17f6-c02b-48b6-9d0c-370687629093
		summarizeBy: sum
		sourceColumn: LNG_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wind_Power_Generation_GWh
		dataType: double
		lineageTag: e124fb57-b423-45e7-8536-6bd07488f714
		summarizeBy: sum
		sourceColumn: Wind_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Solar_Power_Generation_GWh
		dataType: double
		lineageTag: 5c6dd3c8-2bb3-49da-b710-bcb21b74b2e9
		summarizeBy: sum
		sourceColumn: Solar_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Biomass_Power_Generation_GWh
		dataType: double
		lineageTag: a3669b10-ddd8-4bd1-91e1-bab778273703
		summarizeBy: sum
		sourceColumn: Biomass_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Geothermal_Power_Generation_GWh
		dataType: double
		lineageTag: e49e2fd3-feb0-4d45-a389-29a43fb7bb70
		summarizeBy: sum
		sourceColumn: Geothermal_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wave_And_Tidal_Power_Generation_GWh
		dataType: double
		lineageTag: f6a8bd7f-29da-4013-a9f9-779140cf141b
		summarizeBy: sum
		sourceColumn: Wave_And_Tidal_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Hydroelectric_Power_Generation_GWh
		dataType: double
		lineageTag: 55e92968-2875-4c2b-9a00-e34570995f95
		summarizeBy: sum
		sourceColumn: Hydroelectric_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Nuclear_Power_Generation_GWh
		dataType: double
		lineageTag: 8ce23129-fb6c-4d89-b455-64b2a2f2393f
		summarizeBy: sum
		sourceColumn: Nuclear_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Landfill_Gas_Power_Generation_GWh
		dataType: double
		lineageTag: cc29f591-9377-4013-8282-4a724d56b3ff
		summarizeBy: sum
		sourceColumn: Landfill_Gas_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Power_Generation_GWh
		dataType: double
		lineageTag: decad674-d804-42f3-b7cb-acf02142af89
		summarizeBy: sum
		sourceColumn: Other_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_1P_Metallurgical_Coal_m_Tonnes
		dataType: double
		lineageTag: 1b35b26c-79a2-45f3-98ed-241fa8a37538
		summarizeBy: sum
		sourceColumn: Reserves_1P_Metallurgical_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_2P_Metallurgical_Coal_m_Tonnes
		dataType: double
		lineageTag: 30af228f-b925-4483-89e9-d39d163994f4
		summarizeBy: sum
		sourceColumn: Reserves_2P_Metallurgical_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_1P_Thermal_Coal_m_Tonnes
		dataType: double
		lineageTag: 5b0a0eba-8a7f-46ad-8505-bdcb0fca8801
		summarizeBy: sum
		sourceColumn: Reserves_1P_Thermal_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_2P_Thermal_Coal_m_Tonnes
		dataType: double
		lineageTag: 590f45f2-766b-4724-b970-b4032e0f57f7
		summarizeBy: sum
		sourceColumn: Reserves_2P_Thermal_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_1P_Other_Coal_m_Tonnes
		dataType: double
		lineageTag: d6a66710-1f49-4b31-923d-9427de4421ce
		summarizeBy: sum
		sourceColumn: Reserves_1P_Other_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_2P_Other_Coal_m_Tonnes
		dataType: double
		lineageTag: 1b89b3c1-955d-405b-9c05-4a5b31b71543
		summarizeBy: sum
		sourceColumn: Reserves_2P_Other_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Extraction_Deep_Mined_Coal_Tonnes
		dataType: double
		lineageTag: f2fcc2b8-43eb-4f07-80e8-6085028c5602
		summarizeBy: sum
		sourceColumn: Coal_Extraction_Deep_Mined_Coal_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Extraction_Open_Cast_Coal_Tonnes
		dataType: double
		lineageTag: 75174286-7820-4516-abde-e936291655b0
		summarizeBy: sum
		sourceColumn: Coal_Extraction_Open_Cast_Coal_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Extraction_Unknown_Type_Tonnes
		dataType: double
		lineageTag: 64d1ecce-1311-4932-9bbe-013e36916b5f
		summarizeBy: sum
		sourceColumn: Coal_Extraction_Unknown_Type_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Thermal_Coal_Mining_Sector_Revenue_Percent
		dataType: double
		lineageTag: aed57c1b-5332-49e3-80bd-08db192b9edf
		summarizeBy: sum
		sourceColumn: Thermal_Coal_Mining_Sector_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Thermal_Coal_Mining_Sector_Revenue_USD_mn
		dataType: double
		lineageTag: 5bcd2fe0-1656-4dcb-bcff-7f3a4df275e4
		summarizeBy: sum
		sourceColumn: Thermal_Coal_Mining_Sector_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Metallurgical_Coal_Mining_Sector_Revenue_Percent
		dataType: double
		lineageTag: 1e825b1d-fcc5-400c-ab38-6a8aeaded8c7
		summarizeBy: sum
		sourceColumn: Metallurgical_Coal_Mining_Sector_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Metallurgical_Coal_Mining_Sector_Revenue_USD_mn
		dataType: double
		lineageTag: 515bcf4b-9951-4be6-926c-25a52c7d2e2a
		summarizeBy: sum
		sourceColumn: Metallurgical_Coal_Mining_Sector_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Coal_Mining_Sector_Revenue_Percent
		dataType: double
		lineageTag: 4cec194a-1527-46b8-91ac-b91d2c1aa385
		summarizeBy: sum
		sourceColumn: Other_Coal_Mining_Sector_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Coal_Mining_Sector_Revenue_USD_mn
		dataType: double
		lineageTag: cb3e7bda-b850-4fde-872d-fd0a26649995
		summarizeBy: sum
		sourceColumn: Other_Coal_Mining_Sector_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Coal_Mining_Revenue_Percent
		dataType: double
		lineageTag: 0a34fd56-8b70-4a9e-a1c4-db4394e5ba8c
		summarizeBy: sum
		sourceColumn: Total_Coal_Mining_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Coal_Mining_Revenue_USD_mn
		dataType: double
		lineageTag: 453c5c52-f352-4420-bdd7-26e90df84186
		summarizeBy: sum
		sourceColumn: Total_Coal_Mining_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Mining_Calculation_Methodology
		dataType: double
		lineageTag: 5a896d0b-26d4-469f-a15d-9b880af8401f
		summarizeBy: sum
		sourceColumn: Coal_Mining_Calculation_Methodology

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Mining_Data_source
		dataType: double
		lineageTag: 4563b2d3-b7ac-4a72-aeb0-c1ce734893da
		summarizeBy: sum
		sourceColumn: Coal_Mining_Data_source

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Power_Generation_Pct_of_Total_Power_Generation_GWh
		dataType: double
		lineageTag: a1a38407-2318-4d90-b819-9077d8781f92
		summarizeBy: sum
		sourceColumn: Coal_Power_Generation_Pct_of_Total_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Power_Generation_Data_Source
		dataType: double
		lineageTag: 3beb8c51-56c2-4473-94b2-ba3f9232931a
		summarizeBy: sum
		sourceColumn: Power_Generation_Data_Source

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Power_Generation_GHG_Tonnes_CO2e
		dataType: double
		lineageTag: 1e495a5b-74fb-417d-8684-97d9784b8dcc
		summarizeBy: sum
		sourceColumn: Coal_Power_Generation_GHG_Tonnes_CO2e

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Gasification
		dataType: string
		lineageTag: 305b4cf2-88bf-4f07-a61f-1542d529bb86
		summarizeBy: none
		sourceColumn: Coal_Gasification

		annotation SummarizationSetBy = Automatic

	column Coal_Liquefaction
		dataType: string
		lineageTag: 6adf64db-bc06-4ad9-8911-6961d17cd01c
		summarizeBy: none
		sourceColumn: Coal_Liquefaction

		annotation SummarizationSetBy = Automatic

	column SPOT_MID_RATE
		dataType: double
		lineageTag: 472eb717-82cd-47f6-b6ef-1c477fcb61b5
		summarizeBy: sum
		sourceColumn: SPOT_MID_RATE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Min_FX_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 8b86369c-5b80-4b83-a337-2fd63e7a9187
		summarizeBy: none
		sourceColumn: Min_FX_DATE

		variation Variation
			isDefault
			relationship: 3472edcc-1924-4e4c-809c-c5bc67a725c1
			defaultHierarchy: LocalDateTable_b1974b7d-12f6-4704-9b26-6418405cf124.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Max_FX_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 4adbfdb6-4933-4c6d-af68-12b079ad0b45
		summarizeBy: none
		sourceColumn: Max_FX_Date

		variation Variation
			isDefault
			relationship: 42b96828-1ad9-4132-8a4b-f1972c742526
			defaultHierarchy: LocalDateTable_311a7314-54df-42a4-92d3-277ed3c4390d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Renewable_Energy_Revenue_USD_mn
		dataType: double
		lineageTag: 30967060-d661-42e3-8c9e-d1d997c20722
		summarizeBy: sum
		sourceColumn: Renewable_Energy_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fossil_Fuel_Energy_Revenue_USD_mn
		dataType: double
		lineageTag: 33267035-ba3c-408b-b43d-a98499af52ec
		summarizeBy: sum
		sourceColumn: Fossil_Fuel_Energy_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Renewable_Energy_Revenue_Percent
		dataType: double
		lineageTag: 4dbe7e90-5a7e-4b0f-8fb4-e4ed84281fea
		summarizeBy: sum
		sourceColumn: Renewable_Energy_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fossil_Fuel_Energy_Revenue_Percent
		dataType: double
		lineageTag: a5d36a5e-daf7-4fc3-ab47-3e85258387f7
		summarizeBy: sum
		sourceColumn: Fossil_Fuel_Energy_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Energy_Revenue_USD_mn
		dataType: double
		lineageTag: e3878543-155e-4c68-b4fe-4c9793d81cc1
		summarizeBy: sum
		sourceColumn: Other_Energy_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Energy_Revenue_Percent
		dataType: double
		lineageTag: 6616ffd5-af98-4e10-8e2d-efec42d76365
		summarizeBy: sum
		sourceColumn: Other_Energy_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Extractives_Revenue_Exposure_Percent
		dataType: double
		lineageTag: 1fa40b26-c6ae-484b-b818-6e7fb818679b
		summarizeBy: sum
		sourceColumn: Extractives_Revenue_Exposure_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Energy_Revenue_Percent
		dataType: double
		lineageTag: 1505c9da-9f52-4776-85d3-279eef939582
		summarizeBy: sum
		sourceColumn: Total_Energy_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Renewable_Engery_Share_Percent
		dataType: double
		lineageTag: 19cbb3ef-ee59-439a-9a32-44206a5c1d2b
		summarizeBy: sum
		sourceColumn: Renewable_Engery_Share_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fossil_Fuel_Engery_Share_Percent
		dataType: double
		lineageTag: 23d8f60f-58a2-4991-a078-ea3af846fb72
		summarizeBy: sum
		sourceColumn: Fossil_Fuel_Engery_Share_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Revenue_AUD_mn history' = DIVIDE( 'ESG Trucost Climate History'[Revenue_USD_mn], 'ESG Trucost Climate History'[SPOT_MID_RATE] )
		lineageTag: 73c38620-4bbd-4e3e-a9b8-e7caad121672
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Absolute_GHG_Scope_3_Upstream_Total
		dataType: double
		lineageTag: b3cbaae6-d18f-41fd-896f-042ed8bec041
		summarizeBy: sum
		sourceColumn: Absolute_GHG_Scope_3_Upstream_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Absolute_GHG_Scope_3_Downstream_Total
		dataType: double
		lineageTag: 108d9ce9-f7c2-42a0-873e-4ab4c73d6515
		summarizeBy: sum
		sourceColumn: Absolute_GHG_Scope_3_Downstream_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Scope_3_GHG_Upstream_Total_Disclosure
		dataType: string
		lineageTag: de2522d5-9812-4c0f-a286-05cb46332f31
		summarizeBy: none
		sourceColumn: Scope_3_GHG_Upstream_Total_Disclosure

		annotation SummarizationSetBy = Automatic

	column Scope_3_GHG_Downstream_Total_Disclosure
		dataType: string
		lineageTag: b01df344-5b31-4542-bf2c-438b6008d5d2
		summarizeBy: none
		sourceColumn: Scope_3_GHG_Downstream_Total_Disclosure

		annotation SummarizationSetBy = Automatic

	column Intensity_GHG_Scope_3_Upstream
		dataType: double
		lineageTag: bb31c358-61d8-4658-840c-cfeadf5be582
		summarizeBy: sum
		sourceColumn: Intensity_GHG_Scope_3_Upstream

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Intensity_GHG_Scope_3_Downstream_Total
		dataType: double
		lineageTag: 9b9b2921-36d7-4fb0-855e-5ac7af88f869
		summarizeBy: sum
		sourceColumn: Intensity_GHG_Scope_3_Downstream_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Scope_1_2_PCAF_Financed_GHG_Data_Quality
		dataType: string
		lineageTag: 5e57e643-367e-4420-be28-fed419f1ada9
		summarizeBy: none
		sourceColumn: Scope_1_2_PCAF_Financed_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	column Scope_1_2_PCAF_Insured_GHG_Data_Quality
		dataType: string
		lineageTag: e0f2a8e5-2caf-40b5-b06d-504f7f303055
		summarizeBy: none
		sourceColumn: Scope_1_2_PCAF_Insured_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	column Scope_3_Upstream_PCAF_Financed_GHG_Data_Quality
		dataType: string
		lineageTag: d82e73a1-f91c-4697-bc94-00cedcd74cae
		summarizeBy: none
		sourceColumn: Scope_3_Upstream_PCAF_Financed_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	column Scope_3_Upstream_PCAF_Insured_GHG_Data_Quality
		dataType: string
		lineageTag: fba9a594-5d3d-4f9f-9ab7-f83fdd656b44
		summarizeBy: none
		sourceColumn: Scope_3_Upstream_PCAF_Insured_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	column Scope_3_Downstream_PCAF_Financed_GHG_Data_Quality
		dataType: string
		lineageTag: e6f3200e-b8ba-4515-a278-d752c6e45431
		summarizeBy: none
		sourceColumn: Scope_3_Downstream_PCAF_Financed_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	column Scope_3_Downstream_PCAF_Insured_GHG_Data_Quality
		dataType: string
		lineageTag: 37708492-4dc2-4fb0-bc15-0e081df54ddc
		summarizeBy: none
		sourceColumn: Scope_3_Downstream_PCAF_Insured_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	partition 'ESG Trucost Climate History-1ec93b3c-92cb-4a5e-96a3-d5a64bc7b115' = m
		mode: import
		queryGroup: Trucost
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=p_databricks_catalog,Kind="Database"]}[Data],
				    climate_Schema = hive_metastore_Database{[Name=p_trucost_database, Kind="Schema"]}[Data],
				    semantic_trucost_carbon_historical_v1_Table = climate_Schema{[Name="semantic_trucost_carbon_historical_v1",Kind="Table"]}[Data],
				    FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				      semantic_trucost_carbon_historical_v1_Table, 
				      100
				     )
				 else 
				   
				     semantic_trucost_carbon_historical_v1_Table
				in
				  FilterLogic
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

