table 'ESG Controversy'
	lineageTag: d92695a0-397d-4387-98ed-506a0469ae28

	column Entity_Id
		dataType: int64
		formatString: 0
		lineageTag: b1c12282-eb02-4ca9-a54d-5703ef34e24c
		summarizeBy: count
		sourceColumn: Entity_Id

		annotation SummarizationSetBy = Automatic

	/// Sustainalytics Category
	column Category
		dataType: string
		lineageTag: 6ece3b78-d27b-4f1d-9db6-9b131cee6e2a
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Score
		dataType: string
		lineageTag: 104fe176-16ba-4286-bcd3-991606873d04
		summarizeBy: none
		sourceColumn: Score

		annotation SummarizationSetBy = Automatic

	column Valid_From
		dataType: dateTime
		formatString: Long Date
		lineageTag: ffcf129d-0878-47b9-a840-1d91a6ceccaf
		summarizeBy: none
		sourceColumn: Valid_From

		variation Variation
			isDefault
			relationship: 61caabe2-4dbe-4de8-b389-03f4bcc2212e
			defaultHierarchy: LocalDateTable_7cd3337e-78d1-4d5e-828a-b29b05b232ef.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Valid_To
		dataType: dateTime
		formatString: Long Date
		lineageTag: 378870b3-0242-44e9-9586-bbaaf3b9660a
		summarizeBy: none
		sourceColumn: Valid_To

		variation Variation
			isDefault
			relationship: 445f1f2f-42d8-41d1-bda7-7e91f44d8026
			defaultHierarchy: LocalDateTable_ad700cda-05e0-4e26-b998-8331f234a518.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Is the Sustainalytics Score current/latest
	column Is_Current
		dataType: string
		lineageTag: 3383d7ce-24c3-458f-b784-36b4160f6e4c
		summarizeBy: none
		sourceColumn: Is_Current

		annotation SummarizationSetBy = Automatic

	/// Field used for charting. Default to 5
	column 'Radar Chart Max' = 5
		formatString: 0
		lineageTag: e5060820-bfb1-4225-8abf-88984e1861c7
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// ESG Category (E = Environmental ; S = Social; G = Governance)
	column 'ESG Category'
		dataType: string
		lineageTag: b1483240-7733-4816-8fd6-f7e085c7e78d
		summarizeBy: none
		sourceColumn: ESG Category

		annotation SummarizationSetBy = Automatic

	/// Sustainalytics Topic
	column Entity_Topic_Key
		dataType: string
		lineageTag: 25fe638f-1c67-481e-a641-448d2db27835
		summarizeBy: none
		sourceColumn: Entity_Topic_Key

		annotation SummarizationSetBy = Automatic

	/// Sustainalytics Topic based on Category
	column Vendor_Topic
		dataType: string
		lineageTag: b3361de9-d75d-4239-80c1-c94ddec08643
		summarizeBy: none
		sourceColumn: Vendor_Topic

		annotation SummarizationSetBy = Automatic

	/// Sustainalytics Score for Category
	column 'Current Score' = if('ESG Controversy'[Is_Current] = "Y",'ESG Controversy'[Score],"0")
		lineageTag: 64e8a8da-a3c6-4281-a169-5bb760ec4c0c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score - Num'
		dataType: int64
		formatString: 0
		lineageTag: 0d77a01b-8d1f-42ae-b78b-4b1c838c65f1
		summarizeBy: none
		sourceColumn: Score - Num

		annotation SummarizationSetBy = User

	column 'Score Label' = CONCATENATE(" (Score: ",CONCATENATE('ESG Controversy'[Score],")"))
		lineageTag: da1f6efa-00d9-4df2-9442-7485a746ad58
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'ESG Controversy-8a8c2fea-4ec5-4d76-932e-166f83b0240b' = m
		mode: import
		queryGroup: Sustainalytics
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=p_databricks_catalog,Kind="Database"]}[Data],
				    sustainalytics_Schema = hive_metastore_Database{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_esg_sustainalytics_controversy_v1_Table = sustainalytics_Schema{[Name="semantic_esg_sustainalytics_controversy_v1",Kind="Table"]}[Data],
				    #"Changed Type1" = Table.TransformColumnTypes(semantic_esg_sustainalytics_controversy_v1_Table,{{"Score", type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type1", "Score", "Score - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"Score - Copy", "Score - Num"}, {"ESG_Category", "ESG Category"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Score - Num", Int64.Type}})
				    ,  FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				       #"Changed Type", 
				      100
				     )
				 else 
				      #"Changed Type" 
				     in
				  FilterLogic
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

