table 'ESG Trucost Climate'
	lineageTag: f3c5d40b-fae3-4421-b2fe-16e7ea339dff

	measure 'Apportioned EV Revenue AUD mn' = ```
			
			CALCULATE ( [MV Ownership] * SUM ( 'ESG Trucost Climate'[Revenue_AUD_mn] ) )
			
			```
		displayFolder: Revenue
		lineageTag: 6656d36a-09d6-4497-80a5-bb655faa2e9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Hydroelectric (GWH)' =
			
			CALCULATE (
			    SUMX ('ESG Trucost Climate', [MV Ownership] * 'ESG Trucost Climate'[Hydroelectric_Power_Generation_GWh] )
			)
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: c8b05059-899c-493a-82e9-3327520e85b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Biomass (GWH)' =
			
			CALCULATE (
			    SUMX ('ESG Trucost Climate', [MV Ownership] * 'ESG Trucost Climate'[Biomass_Power_Generation_GWh] )
			)
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: e5206b1c-2743-44c9-b64f-b30f57805eca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Others (GWH)' =
			
			CALCULATE (
			    SUMX (
			            'ESG Trucost Climate',
			            [MV Ownership]
			        * ('ESG Trucost Climate'[Other_Power_Generation_GWh] + 'ESG Trucost Climate'[Landfill_Gas_Power_Generation_GWh])
			        )
			)
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: 376e3c7d-8a17-4cac-a24f-356d9aa80a03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No. of Companies' =
			
			CALCULATE ( DISTINCTCOUNT ( 'GS Asset'[ASSET_ID] ), REMOVEFILTERS('Daily Position'[Trucost_Mapping_Status] )
			)
		formatString: 0
		displayFolder: Visual Measures
		lineageTag: ec872bc6-fb2e-4904-815d-bf3a204db6cc

	measure 'No. of Companies Analyzed' = ```
			
			CALCULATE (
			    DISTINCTCOUNT ( 'GS Asset'[ASSET_ID] ),
			    'Daily Position'[Trucost_Mapping_Status] = "Match"
			)
			
			```
		formatString: 0
		displayFolder: Visual Measures
		lineageTag: f4269461-c94e-48f8-8651-d153ddc5dc98

	measure 'Coverage Rate %' = DIVIDE([No. of Companies Analyzed], [No. of Companies],0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Visual Measures
		lineageTag: 77d2fd03-ba95-4fc1-9345-a256af4b1aa6

	measure 'WACI (Scope 1 & 2)' = ```
			
			VAR WACI_num = [Portfolio_weight]*(SUMX('ESG Trucost Climate', 'ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e] + 'ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e]))
			
			VAR WACI_denom = SUM('ESG Trucost Climate'[Revenue_AUD_mn])
			
			RETURN 
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 715bbba4-e08d-46b4-b62e-062d1e14f2a6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate WACI (Scope 1 & 2)' = ```
			SUMX('GS Asset', [WACI (Scope 1 & 2)])
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: e66a7723-e6f6-43f9-add7-b76c57d23045

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Apportioned Carbon (Scope 1 & 2)' =
			
			CALCULATE( [MV Ownership]
			            *(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]+ 'ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e])
			            )
			        )
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 3f7de76b-9b3a-4678-952e-bd6fc5810e35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV Apportioned Carbon (Scope 1 & 2)' = ```
			
			SUMX('GS Asset', [MV Apportioned Carbon (Scope 1 & 2)])
			
			
			
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 8c56862d-e5af-4403-965c-cc87dedbc353

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Revenue AUD mn' =
			
			CALCULATE ( SUMX('ESG Trucost Climate', [MV Ownership]*'ESG Trucost Climate'[Revenue_AUD_mn] )
			)
		displayFolder: Revenue
		lineageTag: 2da46090-5d5f-44d0-abb3-0e4ef65c8653

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Coal (GWH)' =
			
			CALCULATE (
			    SUMX ('ESG Trucost Climate', [MV Ownership] * 'ESG Trucost Climate'[Coal_Power_Generation_GWh] )
			)
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: 65ee81e7-931c-4c10-a7a8-3018f3ccab4d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Natural Gas (GWH)' =
			
			CALCULATE (
			    SUMX ('ESG Trucost Climate', [MV Ownership] *('ESG Trucost Climate'[Natural_Gas_Power_Generation_GWh] + 'ESG Trucost Climate'[LPG_Power_Generation_GWh] + 'ESG Trucost Climate'[LNG_Power_Generation_GWh]) )
			)
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: ba591505-143a-4272-9be7-bab6f6e8537f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Nuclear (GWH)' =
			
			CALCULATE (
			    SUMX('ESG Trucost Climate', [MV Ownership] *'ESG Trucost Climate'[Nuclear_Power_Generation_GWh] )
			)
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: 6acdb163-85b4-4046-ad55-2c96c9bac05a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Petrol (GWH)' = ```
			
			CALCULATE (
			    SUMX ('ESG Trucost Climate',  [MV Ownership] * 'ESG Trucost Climate'[Petroleum_Power_Generation_GWh] )
			)
			
			```
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: 3de13634-88ef-4d17-b674-992db50e3eb1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Renewables (GWH)' = ```
			
			CALCULATE (
			    SUMX (
			            'ESG Trucost Climate',
			            [MV Ownership]*
			            ('ESG Trucost Climate'[Wind_Power_Generation_GWh] + 'ESG Trucost Climate'[Solar_Power_Generation_GWh] + 'ESG Trucost Climate'[Wave_And_Tidal_Power_Generation_GWh] + 'ESG Trucost Climate'[Geothermal_Power_Generation_GWh])
			        )
			)
			
			```
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: e5e7f6fe-42ad-42af-a0dd-8a3f8d9fc644

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 1 & 2)' =
			
			CALCULATE (
			    DIVIDE ( [MV Apportioned Carbon (Scope 1 & 2)], [Apportioned MV Revenue AUD mn] )
			)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 98694109-5d88-4f8a-aafc-a97217870152

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV CR Intensity (Scope 1 & 2)' = ```
			
			
			DIVIDE([Aggregate MV Apportioned Carbon (Scope 1 & 2)], SUMX('GS Asset', [Apportioned MV Revenue AUD mn]))
			
			
			
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 31249bd4-d1e4-4d51-b9c1-e87bcebb9fbb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix WACI (Scope 1 & 2)' = ```
			
			
			IF(SELECTEDVALUE('Daily Position'[Position_Type]) = "Benchmark",
			
			// Benchmark aggregates
			IF (
			    // At matrix level - Investment Object
			    ISINSCOPE('Daily Position'[Investment Object]), 
			    IF(ISBLANK([Benchmark_MV]),
			    "No relevant portfolio selected",
			    [Aggregate WACI (Scope 1 & 2)]), // No benchmark weighting applied
			
			    // At other levels of matrix
			    IF(ISBLANK([Total Benchmark MV]),
			    "No relevant portfolio selected",
			    [Aggregate WACI (Scope 1 & 2)]))
			,
			
			// Portfolio aggregates
			IF( 
			    // At matrix level - Investment Object
			    ISINSCOPE('Daily Position'[Investment Object]) ,
			    CALCULATE([Aggregate WACI (Scope 1 & 2)], 'Daily Position'[Investment Object] = SELECTEDVALUE('Daily Position'[Investment Object])),
			
			    // At other matrix levels
			    [Aggregate WACI (Scope 1 & 2)]
			    )
			
			     
			)
			
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: b69254d4-220b-4903-9534-d11822ad8771

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV CR Intensity (Scope 1 & 2)' = ```
			
			
			IF(SELECTEDVALUE('Daily Position'[Position_Type]) = "Benchmark",
			
			// Benchmark aggregates
			IF (
			    // At matrix level - Investment Object
			    ISINSCOPE('Daily Position'[Investment Object]), 
			    IF(ISBLANK([Benchmark_MV]),
			    "No relevant portfolio selected",
			    [Aggregate MV CR Intensity (Scope 1 & 2)]),
			
			    // At other levels of matrix
			    IF(ISBLANK([Total Benchmark MV]),
			    "No relevant portfolio selected",
			    [Aggregate MV CR Intensity (Scope 1 & 2)])
			  
			),
			
			
			// Portfolio aggregates
			IF (
			    // At matrix level - Investment Object
			    ISINSCOPE('Daily Position'[Investment Object]), 
			    CALCULATE([Aggregate MV CR Intensity (Scope 1 & 2)], 'Daily Position'[Investment Object] = SELECTEDVALUE('Daily Position'[Investment Object])),
			
			    // At other levels of matrix
			    [Aggregate MV CR Intensity (Scope 1 & 2)]
			
			)
			)
			```
		displayFolder: Visual Measures
		lineageTag: ca2cbed4-023d-4d6b-b150-64b800aa5967

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No Energy Mix msg' = ```
			
			IF(
			 // All data is blank 
			ISBLANK(SUMX('ESG Trucost Climate',[Apportioned MV Coal (GWH)] + [Apportioned MV Biomass (GWH)] + [Apportioned MV Hydroelectric (GWH)] + [Apportioned MV Natural Gas (GWH)] + [Apportioned MV Nuclear (GWH)] + [Apportioned MV Others (GWH)] + [Apportioned MV Petrol (GWH)] + [Apportioned MV Renewables (GWH)]))
			|| 
			// or all data is zero
			SUMX('ESG Trucost Climate',[Apportioned MV Coal (GWH)] + [Apportioned MV Biomass (GWH)] + [Apportioned MV Hydroelectric (GWH)] + [Apportioned MV Natural Gas (GWH)] + [Apportioned MV Nuclear (GWH)] + [Apportioned MV Others (GWH)] + [Apportioned MV Petrol (GWH)] + [Apportioned MV Renewables (GWH)]) = 0 ,
			
			
			"No energy mix in data",
			 ""
			 
			)
			```
		displayFolder: Visual Measures
		lineageTag: ebb12dbe-f54e-4b51-a328-7d8feaede04a

	measure 'Make visual transparent' = ```
			
			      IF(
			         [No Energy Mix msg] = "" ,
			         "#FFFFFF00", -- returns transparent if there is energy mix data
			         "White"
			        )
			```
		isHidden
		displayFolder: Visual Measures
		lineageTag: 787ed76c-3a26-411e-949b-b1e93b22fd0f

		changedProperty = IsHidden

	measure 'Others (incl. landfill gas) Power Generation (GWH)' =
			
			CALCULATE (SUMX (
			            'ESG Trucost Climate',
			            'ESG Trucost Climate'[Other_Power_Generation_GWh] + 'ESG Trucost Climate'[Landfill_Gas_Power_Generation_GWh]
			        )
			)
		displayFolder: Energy Mix Measures
		lineageTag: 33ff2fc7-80f9-462d-b214-79f6cf1cac14

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Renewables (GWH)' = ```
			
			CALCULATE (SUMX (
			            'ESG Trucost Climate',
			            'ESG Trucost Climate'[Wind_Power_Generation_GWh] + 'ESG Trucost Climate'[Solar_Power_Generation_GWh] + 'ESG Trucost Climate'[Wave_And_Tidal_Power_Generation_GWh] + 'ESG Trucost Climate'[Geothermal_Power_Generation_GWh]
			        )
			)
			
			```
		displayFolder: Energy Mix Measures
		lineageTag: 7d87512a-2583-4033-823a-6b3fbdb70814

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 1)' =
			
			CALCULATE (
			    DIVIDE ( [MV Apportioned Carbon (Scope 1)], [Apportioned MV Revenue AUD mn] )
			)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: dd3f0896-4bd7-4a35-8429-5dc67e1d25c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Apportioned Carbon (Scope 1)' = CALCULATE([MV Ownership]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e])))
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: c8046c41-c94d-4982-a56c-54a64407a3f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Apportioned Carbon (Scope 2)' = CALCULATE([MV Ownership]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e])))
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 3d6f07d8-19c2-4ba6-9a97-114273e4bf0f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 2)' =
			
			CALCULATE (
			    DIVIDE ( [MV Apportioned Carbon (Scope 2)], [Apportioned MV Revenue AUD mn] )
			)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 38cf2d76-0506-4309-8ae2-c784e9825e7d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV Apportioned Carbon (Scope 1)' = ```
			
			SUMX('GS Asset', [MV Apportioned Carbon (Scope 1)])
			
			
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 986a4e1b-0a98-40db-a69b-eb042cbcd5c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV Apportioned Carbon (Scope 2)' = ```
			
			SUMX('GS Asset', [MV Apportioned Carbon (Scope 2)])
			
			
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 1ee7e99c-fbc5-418a-a6d3-a62c43018c39

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV CR Intensity (Scope 1)' = ```
			
			
			VAR numerator = [Aggregate MV Apportioned Carbon (Scope 1)]
			VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn])
			
			RETURN
			DIVIDE(numerator, denominator)
			
			
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 4d98f236-c117-4211-94a1-e1ffa0dfbb68

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV CR Intensity (Scope 2)' = ```
			
			
			VAR numerator = [Aggregate MV Apportioned Carbon (Scope 2)]
			VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn])
			
			RETURN
			DIVIDE(numerator, denominator)
			
			
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 3688b1e7-1502-4c59-b310-8e9e9ee06b62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI (Scope 1)' = ```
			
			VAR WACI_num = [Portfolio_weight]*(SUMX('ESG Trucost Climate', 'ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]))
			
			VAR WACI_denom = SUM('ESG Trucost Climate'[Revenue_AUD_mn])
			
			RETURN 
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: f90a85a7-0e7d-4552-9550-7523478800b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI (Scope 2)' = ```
			
			VAR WACI_num = [Portfolio_weight]*(SUMX('ESG Trucost Climate', 'ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e]))
			
			VAR WACI_denom = SUM('ESG Trucost Climate'[Revenue_AUD_mn])
			
			RETURN 
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 346421db-0603-4243-9d34-a7ab13f8195d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate WACI (Scope 1)' = ```
			
			SUMX('ESG Trucost Climate', [WACI (Scope 1)])
			
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: abd27153-90ed-44d5-be50-94d8dd1d36f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate WACI (Scope 2)' = ```
			
			SUMX('ESG Trucost Climate', [WACI (Scope 2)])
			
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 21ae14ef-e8cc-4803-8514-ec64735bd371

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Latest Carbon Disclosure' =
			
			CALCULATE (
			    SELECTEDVALUE ( 'ESG Trucost Climate'[Carbon_Disclosure] ) & ", "
			        & SELECTEDVALUE ( 'ESG Trucost Climate'[Accounting_Year_End] ),
			    LASTDATE('Daily Position'[Valuation Date])
			)
		displayFolder: Visual measures
		lineageTag: 983f04d7-84b2-45e0-b5f9-7c4a75ce1fd8

	measure 'Select one benchmark msg' = IF(SELECTEDVALUE('Daily Position'[Investment Object]) = "[BM] DJ Brookfield Global Infrastructure" && SELECTEDVALUE('Daily Position'[Investment Object]) = "[BM] MSCI World Core Infrastructure", "Please deselect one of the following Benchmarks: [BM] DJ Brookfield Global Infrastructure, [BM] MSCI World Core Infrastructure. These two benchmarks cannot be selected together.", "")
		displayFolder: Visual Measures
		lineageTag: fdc11f3e-f3d6-495e-8bb4-4ebaa6f48609

	measure 'Matrix MV Apportioned Carbon (Scope 1 & 2)' = ```
			
			IF(SELECTEDVALUE('Daily Position'[Position_Type]) = "Benchmark",
			
			// Benchmark aggregates
			IF (
			    // At matrix level - Investment Object
			    ISINSCOPE('Daily Position'[Investment Object]), 
			    IF(ISBLANK([Benchmark_MV]),
			    "No relevant portfolio selected",
			    [Aggregate MV Apportioned Carbon (Scope 1 & 2)]),
			
			    // At other levels of matrix
			    IF(ISBLANK([Total Benchmark MV]),
			    "No relevant portfolio selected",
			    [Aggregate MV Apportioned Carbon (Scope 1 & 2)])
			    
			),
			
			// Portfolio aggregates
			IF (
			    // At matrix level - Investment Object
			    ISINSCOPE('Daily Position'[Investment Object]), 
			    CALCULATE([Aggregate MV Apportioned Carbon (Scope 1 & 2)], 'Daily Position'[Investment Object] = SELECTEDVALUE('Daily Position'[Investment Object])),
			
			    // At other levels of matrix
			    [Aggregate MV Apportioned Carbon (Scope 1 & 2)]
			     
			)
			)
			
			```
		displayFolder: Visual Measures
		lineageTag: 909685f2-8200-4de9-b9b3-e25df8f893c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV' =
			
			// Measure to populate MV for benchmarks using the mapping between a benchmark and portfolio asset class (mapping baked in the Benchmark_MV measure)
			IF ( SELECTEDVALUE('Daily Position'[Position_Type]) = "Benchmark",
			[Total Benchmark MV],
			[MARKET_VALUE_BASE_SUM]
			)
		displayFolder: Visual Measures
		lineageTag: 789d5e48-aa36-47f7-9cbf-3ffd9884896a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI (Scope 1 & 2) without benchmark MV' = ```
			
			VAR WACI_num = [Portfolio_weight_without_benchmarkMV]*(SUMX('ESG Trucost Climate', 'ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e] + 'ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e]))
			
			VAR WACI_denom = SUM('ESG Trucost Climate'[Revenue_AUD_mn])
			
			RETURN 
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: cf315834-fdea-4af9-8fb3-88b37a9a3936

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate WACI (Scope 1 & 2) without benchmark MV' =
			
			SUMX('GS Asset', [WACI (Scope 1 & 2) without benchmark MV])
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 01f36957-7eb6-46d8-ad4d-d72495f6a89b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Apportioned Carbon (Scope 1 & 2)_BM' = ```
			
			
			CALCULATE( [MV Ownership_BM]
			            *(SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM])
			            )
			        ) 
			```
		formatString: 0.0000
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: ad86042f-bfb3-4f2e-be0b-3025e0070959

	measure 'Aggregate MV Apportioned Carbon (Scope 1 & 2)_BM' = ```
			SUMX('GS Asset',[MV Apportioned Carbon (Scope 1 & 2)_BM])
			        
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: b48215f1-86ff-4d7b-b030-b42dbb3f3ff0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Revenue AUD mn_BM' =
			
			
			Var Benchmark = CALCULATE ( SUMX('ESG Trucost Climate', [MV Ownership_BM]*'ESG Trucost Climate'[Revenue_AUD_mn] ),'Daily Position'[Position_Type] = "Benchmark")
			Var Portfolio = CALCULATE ( SUMX('ESG Trucost Climate', [MV Ownership_BM]*'ESG Trucost Climate'[Revenue_AUD_mn] ),'Daily Position'[Position_Type] = "Portfolio")
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
		displayFolder: Revenue
		lineageTag: fa09eb34-c43c-48bd-859d-9b35082ebf10

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Apportioned Carbon (Scope 1)_BM' =
			-- CALCULATE([MV Ownership_BM]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e])))
			
			        Var Benchmark = CALCULATE([MV Ownership_BM]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]))
			                        ,'Daily Position'[Position_Type]= "Benchmark" )
			
			
			        Var Portfolio = CALCULATE([MV Ownership_BM]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]))
			                        ,'Daily Position'[Position_Type]= "Portfolio" )
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 3c4401e2-bebc-4ac9-8e70-7ba8557278d6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Apportioned Carbon (Scope 2)_BM' = ```
			
			
			        Var Benchmark = CALCULATE([MV Ownership_BM]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e]))
			                        ,'Daily Position'[Position_Type]= "Benchmark" )
			
			
			        Var Portfolio = CALCULATE([MV Ownership_BM]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e]))
			                        ,'Daily Position'[Position_Type]= "Portfolio" )
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 429776cd-b4e9-4a76-988b-23b99c1598b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 1)_BM' =
			
			CALCULATE (
			    DIVIDE ( [MV Apportioned Carbon (Scope 1)_BM], [Apportioned MV Revenue AUD mn_BM] )
			)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 48f7daf0-71a5-483d-83a5-87f68d558bf5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 2)_BM' =
			
			CALCULATE (
			    DIVIDE ( [MV Apportioned Carbon (Scope 2)_BM], [Apportioned MV Revenue AUD mn_BM] )
			)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 2fba0ec9-3cff-4923-ac74-b4f27cc0cfdf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 1 & 2)_BM' =
			
			CALCULATE (
			    DIVIDE ( [MV Apportioned Carbon (Scope 1 & 2)_BM], [Apportioned MV Revenue AUD mn_BM] )
			)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 9ab44d7a-4a59-476d-b572-c834cfac6188

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV CR Intensity (Scope 1 & 2)_BM' = ```
			
			
			DIVIDE([Aggregate MV Apportioned Carbon (Scope 1 & 2)_BM], SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM]))
			
			
			
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 7b75693d-65cb-49e3-ab00-f456eb113bd2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI (Scope 1)_BM' =
			
			--VAR WACI_num = if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*(SUMX('ESG Trucost Climate', 'ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]))
			
			VAR WACI_num = --if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*([Carbon_Scope_1_tonnes_CO2e_BM])
			[Portfolio_weight_BM]*(SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]))
			
			VAR WACI_denom = [Revenue_AUD_mn_BM]
			--SUM('ESG Trucost Climate'[Revenue_AUD_mn_])
			
			RETURN --WACI_num
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 5aea7746-df83-4972-94ad-83f60bfe40a2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Revenue_AUD_mn_BM =
			--DIVIDE( 'ESG Trucost Climate'[Revenue_USD_mn], 'ESG Trucost Climate'[SPOT_MID_RATE] )
			
			        Var Benchmark = CALCULATE(sum('ESG Trucost Climate'[Revenue_AUD_mn]),FILTER('Daily Position','Daily Position'[Position_Type]= "Benchmark" ))
			        Var Portfolio = CALCULATE(sum('ESG Trucost Climate'[Revenue_aud_mn]),FILTER('Daily Position','Daily Position'[Position_Type]= "Portfolio" ))
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
		displayFolder: Revenue
		lineageTag: 3f8ded42-452e-4732-8218-8806866a5adb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI (Scope 2)_BM' = ```
			
			--VAR WACI_num = if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*(SUMX('ESG Trucost Climate', 'ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]))
			
			VAR WACI_num = if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*([Carbon_Scope_2_tonnes_CO2e_BM])
			
			VAR WACI_denom = [Revenue_AUD_mn_BM]
			--SUM('ESG Trucost Climate'[Revenue_AUD_mn_])
			
			RETURN 
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: dd8fa74e-da44-4a13-808f-d3265cdf0c4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI (Scope 1 & 2)_BM' = ```
			
			
			
			VAR WACI_num = if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*([Carbon_Scope_1_tonnes_CO2e_BM] + [Carbon_Scope_2_tonnes_CO2e_BM])
			
			VAR WACI_denom = [Revenue_AUD_mn_BM]
			
			
			RETURN 
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: a6e43dff-3e98-4d4f-94e5-98300fe3213f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate WACI (Scope 1 & 2)_BM' = ```
			SUMX('GS Asset', [WACI (Scope 1 & 2)_BM])
			
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 7d1e0d9c-22ef-448b-8636-ede17cbb5fc6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No. of Companies Analyzed_BM' = ```
			
			Var Benchmark = CALCULATE (DISTINCTCOUNT ( 'Daily Position'[SK ASSET]),'Daily Position'[Trucost_Mapping_Status] = "Match",'Daily Position'[Position_Type]="Benchmark")
			Var Portfolio = CALCULATE (DISTINCTCOUNT ( 'Daily Position'[SK ASSET]),'Daily Position'[Trucost_Mapping_Status] = "Match",'Daily Position'[Position_Type]="Portfolio")
			
			RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
			
			```
		formatString: 0
		displayFolder: Visual Measures
		lineageTag: 66a1c944-9f3f-4885-87c8-b60f984cef87

	measure 'No. of Companies_BM' =
			
			Var Benchmark = CALCULATE ( DISTINCTCOUNT ( 'GS Asset'[ASSET_ID] ), REMOVEFILTERS('Daily Position'[Trucost_Mapping_Status] ),'Daily Position'[Position_Type] ="Benchmark")
			Var Portfolio = CALCULATE ( DISTINCTCOUNT ( 'GS Asset'[ASSET_ID] ), REMOVEFILTERS('Daily Position'[Trucost_Mapping_Status] ),'Daily Position'[Position_Type] ="Portfolio")
			
			
			RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
		formatString: 0
		displayFolder: Visual Measures
		lineageTag: 26ea2658-9e84-4eeb-a866-c3f236f448d5

	measure 'Coverage Rate %_BM' = DIVIDE([No. of Companies Analyzed_BM], [No. of Companies_BM],0)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Visual Measures
		lineageTag: 15b7b641-5898-42a2-8143-3f0e4d71e958

	measure 'Aggregate WACI (Scope 1)_BM' =
			
			SUMX('ESG Trucost Climate', [WACI (Scope 1)_BM])
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 499367ec-2098-472b-9621-59959ca38942

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate WACI (Scope 2)_BM' =
			
			SUMX('ESG Trucost Climate', [WACI (Scope 2)_BM])
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 1d581da1-bf74-47e2-8b36-71edb40aea29

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV CR Intensity (Scope 1)_BM' = ```
			
			
			VAR numerator = [Aggregate MV Apportioned Carbon (Scope 1)_BM]
			VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM])
			
			RETURN
			DIVIDE(numerator, denominator)
			
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 628b6aff-735e-492e-a1aa-74b99ba50e0d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV Apportioned Carbon (Scope 1)_BM' = ```
			
			SUMX('GS Asset', [MV Apportioned Carbon (Scope 1)_BM])
			
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 92c5f817-30d1-4a4a-ac6d-5fd29fbc5dd2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV Apportioned Carbon (Scope 2)_BM' = ```
			
			SUMX('GS Asset', [MV Apportioned Carbon (Scope 2)_BM])
			
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 1c065ff3-88c9-422c-a757-c9fabd7fffff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV CR Intensity (Scope 2)_BM' =
			
			
			VAR numerator = [Aggregate MV Apportioned Carbon (Scope 2)_BM]
			VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM])
			
			RETURN
			DIVIDE(numerator, denominator)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 31575b8b-7f7e-4bc6-9f5b-6b3efd2581bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Biomass (GWH)_BM' = ```
			
			CALCULATE (
			    SUMX ('ESG Trucost Climate', [MV Ownership_BM] * 'ESG Trucost Climate'[Biomass_Power_Generation_GWh]))
			
			  /*  * CALCULATE(sum('ESG Trucost Climate'[Biomass_Power_Generation_GWh]), 
			                not(AND( left('Daily Position'[BP_KEY],9) ="Portfolio",'Daily Position'[Position_Type] ="Benchmark"))  ))
			)*/
			```
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: a08d41a4-e435-4ca6-aabe-091558bd48d7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Coal (GWH)_BM' =
			
			CALCULATE (
			    SUMX ('ESG Trucost Climate', [MV Ownership_BM] * 'ESG Trucost Climate'[Coal_Power_Generation_GWh] ))
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: 92b31e17-1cb1-4acf-9aa0-32813e2f690b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Hydroelectric (GWH)_BM' =
			
			CALCULATE (
			    SUMX ('ESG Trucost Climate', [MV Ownership_BM] * 'ESG Trucost Climate'[Hydroelectric_Power_Generation_GWh] )
			)
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: 98fa6ed6-61b8-4656-bb0e-3fe383fd66dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Natural Gas (GWH)_BM' =
			
			CALCULATE (
			    SUMX ('ESG Trucost Climate', [MV Ownership_BM] *('ESG Trucost Climate'[Natural_Gas_Power_Generation_GWh] + 'ESG Trucost Climate'[LPG_Power_Generation_GWh] + 'ESG Trucost Climate'[LNG_Power_Generation_GWh]) ))
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: 8640f828-4b9b-4e93-8331-4dedbc30f7ce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Nuclear (GWH)_BM' =
			
			CALCULATE (
			    SUMX('ESG Trucost Climate', [MV Ownership_BM] *'ESG Trucost Climate'[Nuclear_Power_Generation_GWh] ))
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: 1a9d9684-1542-4345-805a-ded45a52f4f1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Others (GWH)_BM' =
			
			CALCULATE (
			    SUMX (
			            'ESG Trucost Climate',
			            [MV Ownership_BM]
			        * ('ESG Trucost Climate'[Other_Power_Generation_GWh] + 'ESG Trucost Climate'[Landfill_Gas_Power_Generation_GWh])
			        )
			)
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: 50fe57ca-37d5-4202-9b04-a417683249b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Petrol (GWH)_BM' =
			
			CALCULATE (
			    SUMX ('ESG Trucost Climate',  [MV Ownership_BM] * 'ESG Trucost Climate'[Petroleum_Power_Generation_GWh] )
			)
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: bb6db2b9-10b2-4ac4-8c55-15fa4f55f2c4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned MV Renewables (GWH)_BM' =
			
			CALCULATE (
			    SUMX (
			            'ESG Trucost Climate',
			            [MV Ownership_BM]*
			            ('ESG Trucost Climate'[Wind_Power_Generation_GWh] + 'ESG Trucost Climate'[Solar_Power_Generation_GWh] + 'ESG Trucost Climate'[Wave_And_Tidal_Power_Generation_GWh] + 'ESG Trucost Climate'[Geothermal_Power_Generation_GWh])
			        )
			)
		displayFolder: Energy Mix Measures\Market Value Apportion
		lineageTag: 21bee249-5b62-4b15-8d45-d7e11aafaae6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Sub_Sector (Scope 1 & 2)_BM' = SUMX(GROUPBY('Benchmark Portfolio Mapping', 'Benchmark Portfolio Mapping'[Sub_Sector]),[Aggregate WACI (Scope 1 & 2)_BM] )
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 21bcefce-f204-40eb-b956-2f1d5455863d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI (Scope 1 & 2)_BM' = ```
			
			        
			          //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			         -- /*
			            Var Result  = 
			            IF( ( ISINSCOPE('Benchmark Portfolio Mapping'[Manager])   ||
			                    ISINSCOPE('Benchmark Portfolio Mapping'[Sub_Sector]) ||
			                    ISINSCOPE('Benchmark Portfolio Mapping'[Investment_Object]) ) ,   
			
			                        [Aggregate WACI (Scope 1 & 2)_BM]
			                       , SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),[WACI Position (Scope 1 & 2)_BM]) )
			          
			            Return Result
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 07486e88-6093-494c-83a3-de78fa5db336

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Position (Scope 1 & 2)_BM' = ```
			[WACI Sub_Sector (Scope 1 & 2)_BM] * [WACI Sub_Sector (Scope 1 & 2)_Weighted_BM]
			
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: b8be4059-b918-44d4-90e5-75ffa0ab1958

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Sub_Sector (Scope 1 & 2)_Weighted_BM' = ( [Market_Value_BM] / [WACI_Sub_Sector_MV_BM] )
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 921bf6d3-375a-4f16-b617-025854a24e4b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure WACI_Sub_Sector_MV_BM = ```
			
			    
			        Var Portfolio = CALCULATE(sum('Daily Position'[MARKET VALUE BASE]),
			                        'Benchmark Portfolio Mapping'[Position_Type] = "Portfolio",
			                        ALLSELECTED('Benchmark Portfolio Mapping'[Sub_Sector]) )
			
			 RETURN Portfolio/1000000
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 78f0c417-ad49-48ce-a572-2e97880acaed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV Apportioned Carbon (Scope 1 & 2)_BM' = ```
			
			
			    //For Benchmark and portfolio top level aggregate sum of sub-sector levels         
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),[Aggregate MV Apportioned Carbon (Scope 1 & 2)_BM])
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV Apportioned Carbon (Scope 1 & 2)_BM])
			             
			
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 0a34c893-109d-4a02-9577-1a2f6343cb08

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV Apportioned Carbon (Scope 1)_BM' = ```
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),[Aggregate MV Apportioned Carbon (Scope 1)_BM])
			         
			         //Else part below -use normal aggregations
			              , [Aggregate MV Apportioned Carbon (Scope 1)_BM])
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 28f9aed5-3fb2-4a4f-a7b0-f383c4501e4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV Apportioned Carbon (Scope 2)_BM' = ```
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),[Aggregate MV Apportioned Carbon (Scope 2)_BM])
			         
			         //Else part below -use normal aggregations
			              , [Aggregate MV Apportioned Carbon (Scope 2)_BM])
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: b164ccc3-d0b4-4505-b1c5-ce75f16c9742

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned Carbon/CR (Scope 1 & 2) Sub_Sector_BM' = ```
			
			           
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
			                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
			                                [Aggregate MV Apportioned Carbon (Scope 1 & 2)_BM])
			                         
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 1 & 2)_BM])
			
			 Return Result    
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 31579776-0397-457f-b00d-fd02b9caa6c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned Revenue Sub_Sector_BM' = ```
			SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]), [Apportioned MV Revenue AUD mn_BM])
			
			              
			              
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 3e06c097-651c-4e97-8570-b30d608fb85a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV CR Intensity (Scope 1 & 2)_BM' = ```
			
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 1 & 2) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 1 & 2)_BM])
			
			Return Result
			
			
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 2a15a568-4aba-4438-a386-34fdd9405555

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned Carbon/CR (Scope 1) Sub_Sector_BM' = ```
			
			           
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
			                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
			                                [Aggregate MV Apportioned Carbon (Scope 1)_BM])
			                         
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 1)_BM])
			
			 Return Result   
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: ed373d19-968f-43ef-9cc3-de1862b60039

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned Carbon/CR (Scope 2) Sub_Sector_BM' = ```
			
			           
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
			                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
			                                [Aggregate MV Apportioned Carbon (Scope 2)_BM])
			                         
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 2)_BM])
			
			 Return Result    
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: f0e78101-e4c4-48d9-a744-a1bc24d3ea67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV CR Intensity (Scope 1)_BM' = ```
			
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 1) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 1)_BM])
			
			Return Result
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 595f2c03-cdb2-4a73-b440-e53b7abe42fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV CR Intensity (Scope 2)_BM' = ```
			
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 2) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 2)_BM])
			
			Return Result
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 695d3a99-33df-4ce5-952c-7453d11f04b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Sub_Sector (Scope 1)_BM' = SUMX(GROUPBY('Benchmark Portfolio Mapping', 'Benchmark Portfolio Mapping'[Sub_Sector]),[Aggregate WACI (Scope 1)_BM] )
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 0e83e2aa-0ac0-492e-908a-b5191ce6a108

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Sub_Sector (Scope 2)_BM' = SUMX(GROUPBY('Benchmark Portfolio Mapping', 'Benchmark Portfolio Mapping'[Sub_Sector]),[Aggregate WACI (Scope 2)_BM] )
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 32bf4243-1e39-49c5-9794-1e81b9088471

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Position (Scope 1)_BM' = [WACI Sub_Sector (Scope 1)_BM] * [WACI Sub_Sector (Scope 1 & 2)_Weighted_BM]
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 8e111694-0b2e-4cef-8c28-f6a34bf4506f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Position (Scope 2)_BM' = [WACI Sub_Sector (Scope 2)_BM] * [WACI Sub_Sector (Scope 1 & 2)_Weighted_BM]
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 891eee48-666c-4cca-9359-cba6e34ef81d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI (Scope 1)_BM' = ```
			
			        
			           Var BM_Count = CALCULATE( DISTINCTCOUNT('Benchmark Portfolio Mapping'[Benchmark_Name]))
			
			            //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,                           
			                        SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),[WACI Position (Scope 1)_BM]) 
			                       
			                      
			         
			             //Else part below -use normal aggregations
			              ,[Aggregate WACI (Scope 1)_BM] )
			
			            Return Result
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: e772781e-9a4c-4133-a33a-306d2a427700

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI (Scope 2)_BM' = ```
			
			        
			           Var BM_Count = CALCULATE( DISTINCTCOUNT('Benchmark Portfolio Mapping'[Benchmark_Name]))
			
			            //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,                           
			                        SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),[WACI Position (Scope 2)_BM]) 
			                       
			                      
			         
			             //Else part below -use normal aggregations
			              ,[Aggregate WACI (Scope 2)_BM] )
			
			            Return Result
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 454d1fdc-89bd-4489-898c-f47b4368e544

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure WACI_GS_Sector_MV_BM = ```
			
			
			        Var Result2 = SUMX('GS Asset',[MARKET_VALUE_BASE_SUM])
			    
			        Var Result = CALCULATE(sum('Daily Position'[MARKET VALUE BASE]),
			                        'Daily Position'[Position_Type] = "Portfolio",
			                        ALLSELECTED('GS Asset'[GICS_SECTORS_SHORT]) )
			
			        Var Result1 = SUMX(GROUPBY('GS Asset', 'GS Asset'[GICS_SECTORS_SHORT]),Result )
			
			 RETURN Result2/1000000
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: b9c7e2c0-42bd-4c36-b146-d3c94c531c34

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI_GS_Sector (Scope 1 & 2)_Weighted_BM' = [WACI_GS_Sector_MV_BM] / [Market_Value_BM]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: a5e15357-0c42-4628-b05f-1c96bb0ac8fd

	measure 'WACI_GS_Sector_Position (Scope 1 & 2)_BM' = ```
			IF(AND(ISINSCOPE('GS Asset'[GICS_SECTORS_SHORT]),
			                                                 SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type])="Benchmark") , 
			                                                 [Matrix MV WACI (Scope 1 & 2)_BM] *  [WACI_GS_Sector (Scope 1 & 2)_Weighted_BM],
			                                                 [Aggregate WACI (Scope 1 & 2)_BM])
			
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: af3c2294-5e0e-42e6-ba54-d94ca8b6c8b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI_With_GS_Sector_Country (Scope 1 & 2)_BM' = ```
			
			                                             Switch (TRUE(),
			                                             -- SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) ="Benchmark" && 
			                                                 CALCULATE(ISFILTERED( 'GS Asset'[GICS_SECTORS_SHORT] ),ALLSELECTED( 'GS Asset'[GICS_SECTORS_SHORT] )),
			                                                 SUMX(GROUPBY('GS Asset','GS Asset'[GICS_SECTORS_SHORT]),[WACI_GS_Sector_Position (Scope 1 & 2)_BM]),
			                                                 CALCULATE(ISFILTERED( 'ESG Country'[Country] ),ALLSELECTED( 'ESG Country'[Country] ) ),
			                                                 [Aggregate WACI (Scope 1 & 2)_BM],
			                                                 [Matrix MV WACI (Scope 1 & 2)_BM])
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 6150a2db-64c4-44d8-bfdc-eb8fd1a0acac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Carbon_Scope_3_tonnes_CO2e_Downstream_BM = ```
			
			        Var Benchmark = CALCULATE(sum('ESG Trucost Climate'[Absolute_GHG_Scope_3_Downstream_Total]),'Daily Position'[Position_Type]= "Benchmark" )
			        Var Portfolio = CALCULATE(sum('ESG Trucost Climate'[Absolute_GHG_Scope_3_Downstream_Total]), 'Daily Position'[Position_Type] = "Portfolio")
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
			```
		lineageTag: c7ddfbdc-eed8-4404-9bdb-a1004ca88c54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Carbon_Scope_3_tonnes_CO2e_Upstream_BM = ```
			
			        Var Benchmark = CALCULATE(sum('ESG Trucost Climate'[Absolute_GHG_Scope_3_Upstream_Total]),'Daily Position'[Position_Type]= "Benchmark" )
			        Var Portfolio = CALCULATE(sum('ESG Trucost Climate'[Absolute_GHG_Scope_3_Upstream_Total]), 'Daily Position'[Position_Type] = "Portfolio")
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
			```
		lineageTag: 2784929e-2b6a-447a-b005-877968f69234

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Apportioned Carbon (Scope 3 DS)_BM' =
			-- CALCULATE([MV Ownership_BM]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e])))
			
			        Var Benchmark = CALCULATE([MV Ownership_BM]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Absolute_GHG_Scope_3_Downstream_Total]))
			                        ,'Daily Position'[Position_Type]= "Benchmark" )
			
			
			        Var Portfolio = CALCULATE([MV Ownership_BM]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Absolute_GHG_Scope_3_Downstream_Total]))
			                        ,'Daily Position'[Position_Type]= "Portfolio" )
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 7042dedc-9267-4e82-a4a1-fcb94dad52ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Apportioned Carbon (Scope 3 US)_BM' =
			-- CALCULATE([MV Ownership_BM]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e])))
			
			        Var Benchmark = CALCULATE([MV Ownership_BM]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Absolute_GHG_Scope_3_Upstream_Total]))
			                        ,'Daily Position'[Position_Type]= "Benchmark" )
			
			
			        Var Portfolio = CALCULATE([MV Ownership_BM]*(SUMX('ESG Trucost Climate','ESG Trucost Climate'[Absolute_GHG_Scope_3_Upstream_Total]))
			                        ,'Daily Position'[Position_Type]= "Portfolio" )
			
			        RETURN
			
			        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: c9aae6c0-bd64-49ea-a400-d6fabc5ee26b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV Apportioned Carbon (Scope 3 DS)_BM' = SUMX('GS Asset', [MV Apportioned Carbon (Scope 3 DS)_BM])
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 29262a60-adc6-4568-aca8-2022737b908e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV Apportioned Carbon (Scope 3 US)_BM' = SUMX('GS Asset', [MV Apportioned Carbon (Scope 3 US)_BM])
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 657a5de7-501f-4644-b064-7821654e7ed3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV Apportioned Carbon (Scope 3 DS)_BM' = ```
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),[Aggregate MV Apportioned Carbon (Scope 3 DS)_BM])
			         
			         //Else part below -use normal aggregations
			              , [Aggregate MV Apportioned Carbon (Scope 3 DS)_BM])
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 056edace-e082-4bb3-b5ad-94594aae6bb6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV Apportioned Carbon (Scope 3 US)_BM' = ```
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),[Aggregate MV Apportioned Carbon (Scope 3 US)_BM])
			         
			         //Else part below -use normal aggregations
			              , [Aggregate MV Apportioned Carbon (Scope 3 US)_BM])
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 45c24f6f-148c-46a3-9235-5389d50f03ff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM' = ```
			
			
			CALCULATE( [MV Ownership_BM]
			            *(SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM] + [Carbon_Scope_3_tonnes_CO2e_Downstream_BM])
			            )
			        ) 
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 7be9d89b-046a-43e6-bfa0-0ec7405ed958

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM' = ```
			
			
			CALCULATE( [MV Ownership_BM]
			            *(SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM] + [Carbon_Scope_3_tonnes_CO2e_Upstream_BM])
			            )
			        ) 
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 35d8839e-fa47-489c-a628-e462d30e7360

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM' = SUMX('GS Asset',[MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM])
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 70715dbe-0bb7-467f-b408-a5997e9be2e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM' = SUMX('GS Asset',[MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM])
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 8d5dde98-b3ff-4272-8794-687ca9fef64f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM' = ```
			
			
			
			//For Benchmark and portfolio top level aggregate sum of sub-sector levels     
			            //For Benchmark and portfolio top level aggregate sum of sub-sector levels   
			
			    //For Benchmark and portfolio top level aggregate sum of sub-sector levels         
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),[Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM])
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM])
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: c07951da-f083-4e95-ad51-3b787d5256b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM' = ```
			
			
			
			//For Benchmark and portfolio top level aggregate sum of sub-sector levels     
			            //For Benchmark and portfolio top level aggregate sum of sub-sector levels   
			
			    //For Benchmark and portfolio top level aggregate sum of sub-sector levels         
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),[Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM])
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM])
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 3337fed6-0dab-46de-8e3c-0b63cefb23eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM' = ```
			
			
			CALCULATE( [MV Ownership_BM]
			            *(SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM] + [Carbon_Scope_3_tonnes_CO2e_Upstream_BM] + [Carbon_Scope_3_tonnes_CO2e_Downstream_BM])
			            )
			        ) 
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: df2fd393-18c4-4273-a423-56dad982b520

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM' = SUMX('GS Asset',[MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM])
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: dd5c4857-11c1-430b-89ba-0254b8522cce

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM' = ```
			
			
			
			//For Benchmark and portfolio top level aggregate sum of sub-sector levels     
			            //For Benchmark and portfolio top level aggregate sum of sub-sector levels   
			
			    //For Benchmark and portfolio top level aggregate sum of sub-sector levels         
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),[Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM])
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM])
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 42591296-cb1f-4732-835c-ef7ff9280bf2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 3 DS)_BM' =
			
			CALCULATE (
			    DIVIDE ( [MV Apportioned Carbon (Scope 3 DS)_BM] , [Apportioned MV Revenue AUD mn_BM] )
			)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 8d3608d0-8cae-4cba-8e36-78e0f26b8dda

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 3 US)_BM' =
			
			CALCULATE (
			    DIVIDE ( [MV Apportioned Carbon (Scope 3 US)_BM] , [Apportioned MV Revenue AUD mn_BM] )
			)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 6ba2f3b2-131e-4bcd-9732-f7d7ff67db66

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 1 & 2 & 3DS)_BM' =
			
			CALCULATE (
			    DIVIDE ( [MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM] , [Apportioned MV Revenue AUD mn_BM] )
			)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 7bab38ce-b4eb-42d0-8a16-9c1b9a93d949

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 1 & 2 & 3US)_BM' =
			
			CALCULATE (
			    DIVIDE ( [MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM] , [Apportioned MV Revenue AUD mn_BM] )
			)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 94fe7b5b-2dfa-4372-a9fd-af48e6b3c81d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MV CR Intensity AUD (Scope 1 & 2 & 3DS & 3US)_BM' =
			
			CALCULATE (
			    DIVIDE ( [MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM] , [Apportioned MV Revenue AUD mn_BM] )
			)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: b7e81cce-6a56-4d1e-a556-ded31237d71d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV CR Intensity (Scope 3 DS)_BM' =
			
			
			VAR numerator = [Aggregate MV Apportioned Carbon (Scope 3 DS)_BM]
			VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM])
			
			RETURN
			DIVIDE(numerator, denominator)
		formatString: 0
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 678c06c8-1cd0-4e48-92e6-9c6f46a4c38a

	measure 'Aggregate MV CR Intensity (Scope 3 US)_BM' =
			
			
			VAR numerator = [Aggregate MV Apportioned Carbon (Scope 3 US)_BM]
			VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM])
			
			RETURN
			DIVIDE(numerator, denominator)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 9dfde215-6757-434e-9054-d9d0c6c593bc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV CR Intensity (Scope 1 & 2 & 3DS)_BM' =
			
			
			VAR numerator = [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM]
			VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM])
			
			RETURN
			DIVIDE(numerator, denominator)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: fb7b923c-0bbc-43cb-adfb-6373bf03e877

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV CR Intensity (Scope 1 & 2 & 3US)_BM' =
			
			
			VAR numerator = [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM]
			VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM])
			
			RETURN
			DIVIDE(numerator, denominator)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 1824b045-9234-486d-a3c4-6efcb9651c37

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate MV CR Intensity (Scope 1 & 2 & 3DS & 3US)_BM' =
			
			
			VAR numerator = [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM]
			VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM])
			
			RETURN
			DIVIDE(numerator, denominator)
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 521ba164-6282-4f35-b95f-bcd1eff2d1b5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV CR Intensity (Scope 3 DS)_BM' = ```
			
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 3 DS) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 3 DS)_BM])
			
			Return Result
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 86bf7648-3cac-4470-9b05-523d08b1f167

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned Carbon/CR (Scope 3 DS) Sub_Sector_BM' = ```
			
			           
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
			                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
			                                [Aggregate MV Apportioned Carbon (Scope 3 DS)_BM])
			                         
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 3 DS)_BM])
			
			 Return Result    
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 0309152b-e34e-440a-aa1c-96abe3baa93d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned Carbon/CR (Scope 3 US) Sub_Sector_BM' = ```
			
			           
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
			                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
			                                [Aggregate MV Apportioned Carbon (Scope 3 US)_BM])
			                         
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 3 US)_BM])
			
			 Return Result   
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 54ab8ccb-15e2-40e2-965c-7d9cbfd6e6f3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned Carbon/CR (Scope 1 & 2 & 3DS) Sub_Sector_BM' = ```
			
			           
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
			                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
			                                [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM])
			                         
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3DS)_BM])
			
			 Return Result   
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: e575581c-46c4-4634-854f-4f99e2476e95

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned Carbon/CR (Scope 1 & 2 & 3US) Sub_Sector_BM' = ```
			
			           
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
			                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
			                                [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM])
			                         
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3US)_BM])
			
			 Return Result   
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 5d002409-dea2-4e6c-97ae-b0d1e3d0052a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Apportioned Carbon/CR (Scope 1 & 2 & 3DS & 3US) Sub_Sector_BM' = ```
			
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
			                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
			                                [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM])
			                         
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3DS & 3US)_BM])
			
			 Return Result   
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 1c243a98-9e09-4f07-9185-ef0d8557c14f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV CR Intensity (Scope 3 US)_BM' = ```
			
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 3 US) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 3 US)_BM])
			
			Return Result
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: b4e64a2e-0d6e-4965-8909-e37b88a0a3db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV CR Intensity (Scope 1 & 2 & 3DS)_BM' = ```
			
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 1 & 2 & 3DS) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3DS)_BM])
			
			Return Result
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 513b1222-4728-45f4-a4fc-20542fc4046c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV CR Intensity (Scope 1 & 2 & 3US)_BM' = ```
			
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 1 & 2 & 3US) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3US)_BM])
			
			Return Result
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 5aa16f0e-d0b9-4529-a8ae-d492837f1584

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV CR Intensity (Scope 1 & 2 & 3DS & 3US)_BM' = ```
			
			
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 1 & 2 & 3DS & 3US) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
			         
			         //Else part below -use normal aggregations
			              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3DS & 3US)_BM])
			
			Return Result
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: dff0deb4-c817-401d-b986-91fbf4ba2522

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI (Scope 3 DS)_BM' =
			
			--VAR WACI_num = if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*(SUMX('ESG Trucost Climate', 'ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]))
			
			VAR WACI_num = --if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*([Carbon_Scope_1_tonnes_CO2e_BM])
			[Portfolio_weight_BM]*(SUMX('ESG Trucost Climate', [Absolute_GHG_Scope_3_Downstream_Total]))
			
			VAR WACI_denom = [Revenue_AUD_mn_BM]
			--SUM('ESG Trucost Climate'[Revenue_AUD_mn_])
			
			RETURN --WACI_num
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 850d50fc-7cb4-4070-98ba-2dd7d645b3fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI (Scope 3 US)_BM' =
			
			--VAR WACI_num = if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*(SUMX('ESG Trucost Climate', 'ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]))
			
			VAR WACI_num = --if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*([Carbon_Scope_1_tonnes_CO2e_BM])
			[Portfolio_weight_BM]*(SUMX('ESG Trucost Climate', [Absolute_GHG_Scope_3_Upstream_Total]))
			
			VAR WACI_denom = [Revenue_AUD_mn_BM]
			--SUM('ESG Trucost Climate'[Revenue_AUD_mn_])
			
			RETURN --WACI_num
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 383e4936-a0c2-4c24-b2ab-69872f8efdd4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI (Scope 1 & 2 & 3DS)_BM' = ```
			
			
			
			VAR WACI_num = if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*([Carbon_Scope_1_tonnes_CO2e_BM] + [Carbon_Scope_2_tonnes_CO2e_BM] + [Carbon_Scope_3_tonnes_CO2e_Downstream_BM])
			
			VAR WACI_denom = [Revenue_AUD_mn_BM]
			
			
			RETURN 
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 37054db5-5c55-4121-b34d-57c07a1a4fb6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI (Scope 1 & 2 & 3US)_BM' = ```
			
			
			
			VAR WACI_num = if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*([Carbon_Scope_1_tonnes_CO2e_BM] + [Carbon_Scope_2_tonnes_CO2e_BM] + [Carbon_Scope_3_tonnes_CO2e_Upstream_BM])
			
			VAR WACI_denom = [Revenue_AUD_mn_BM]
			
			
			RETURN 
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 58613dda-8925-45da-a253-98ac2638bf6a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI (Scope 1 & 2 & 3DS & 3US)_BM' = ```
			
			
			
			VAR WACI_num = if(ISBLANK([Portfolio_weight_BM]),1,[Portfolio_weight_BM])*([Carbon_Scope_1_tonnes_CO2e_BM] + [Carbon_Scope_2_tonnes_CO2e_BM] + [Carbon_Scope_3_tonnes_CO2e_Upstream_BM] + [Carbon_Scope_3_tonnes_CO2e_Downstream_BM])
			
			VAR WACI_denom = [Revenue_AUD_mn_BM]
			
			
			RETURN 
			CALCULATE(DIVIDE(WACI_num, WACI_denom))
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: daccf2e0-edab-4829-a841-23daf283a6f9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate WACI (Scope 3 DS)_BM' =
			
			SUMX('ESG Trucost Climate', [WACI (Scope 3 DS)_BM])
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 830b8fd8-0144-4ddb-8a1f-9b6c307684bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate WACI (Scope 3 US)_BM' =
			
			SUMX('ESG Trucost Climate', [WACI (Scope 3 US)_BM])
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 74c8c78a-bf68-4423-b5bf-16f8bbad4718

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate WACI (Scope 1 & 2 & 3DS)_BM' = SUMX('ESG Trucost Climate', [WACI (Scope 1 & 2 & 3DS)_BM])
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 4a32247c-1300-4b2d-8563-dbe254431228

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Aggregate WACI (Scope 1 & 2 & 3US)_BM' = SUMX('ESG Trucost Climate', [WACI (Scope 1 & 2 & 3US)_BM])
		formatString: 0
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 4ee91af8-63a5-4d1d-85fc-9f172fcbbf1c

	measure 'Aggregate WACI (Scope 1 & 2 & 3DS & 3US)_BM' = SUMX('ESG Trucost Climate', [WACI (Scope 1 & 2 & 3DS & 3US)_BM])
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 40c63567-1e7b-435b-a1b3-e397e3c7fc04

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Sub_Sector (Scope 3 DS)_BM' = SUMX(GROUPBY('Benchmark Portfolio Mapping', 'Benchmark Portfolio Mapping'[Sub_Sector]),[Aggregate WACI (Scope 3 DS)_BM] )
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 5fb1bfb1-49b3-4ab8-ba91-2188f9541753

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Sub_Sector (Scope 3 US)_BM' = SUMX(GROUPBY('Benchmark Portfolio Mapping', 'Benchmark Portfolio Mapping'[Sub_Sector]),[Aggregate WACI (Scope 3 US)_BM] )
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 8ef3d0cf-973b-4292-b782-4d18718f61e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Sub_Sector (Scope 1 & 2 & 3DS)_BM' = SUMX(GROUPBY('Benchmark Portfolio Mapping', 'Benchmark Portfolio Mapping'[Sub_Sector]),[Aggregate WACI (Scope 1 & 2 & 3DS)_BM] )
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 07b8f855-e453-415c-848a-e7bff0bb8b9b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Sub_Sector (Scope 1 & 2 & 3US)_BM' = SUMX(GROUPBY('Benchmark Portfolio Mapping', 'Benchmark Portfolio Mapping'[Sub_Sector]),[Aggregate WACI (Scope 1 & 2 & 3US)_BM] )
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 8f9d2c05-708f-414c-b0ba-2b2104970b3b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Sub_Sector (Scope 1 & 2 & 3DS & 3US)_BM' = SUMX(GROUPBY('Benchmark Portfolio Mapping', 'Benchmark Portfolio Mapping'[Sub_Sector]),[Aggregate WACI (Scope 1 & 2 & 3DS & 3US)_BM] )
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 9f885653-e631-4d8b-a5a5-9e77cd327d18

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Position (Scope 3 DS)_BM' = [WACI Sub_Sector (Scope 3 DS)_BM] * [WACI Sub_Sector (Scope 1 & 2)_Weighted_BM]
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: ae333bc7-1c7e-4c99-9def-f6656bf647c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Position (Scope 3 US)_BM' = [WACI Sub_Sector (Scope 3 US)_BM] * [WACI Sub_Sector (Scope 1 & 2)_Weighted_BM]
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 17a2ade9-04af-4722-8d63-c73a3ece66c2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Position (Scope 1 & 2 & 3DS)_BM' = [WACI Sub_Sector (Scope 1 & 2 & 3DS)_BM] * [WACI Sub_Sector (Scope 1 & 2)_Weighted_BM]
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 492d7148-9125-42cc-aebd-740e4bf2b122

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Position (Scope 1 & 2 & 3US)_BM' = [WACI Sub_Sector (Scope 1 & 2 & 3US)_BM] * [WACI Sub_Sector (Scope 1 & 2)_Weighted_BM]
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: ae4bf1dc-1a33-4281-96b9-7e558724c6e4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI Position (Scope 1 & 2 & 3DS & 3US)_BM' = [WACI Sub_Sector (Scope 1 & 2 & 3DS & 3US)_BM] * [WACI Sub_Sector (Scope 1 & 2)_Weighted_BM]
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: e8dcb21c-8f99-4ad8-b73e-4197c61c640e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI (Scope 3 DS)_BM' = ```
			
			        
			           Var BM_Count = CALCULATE( DISTINCTCOUNT('Benchmark Portfolio Mapping'[Benchmark_Name]))
			
			            //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,                           
			                        SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),[WACI Position (Scope 3 DS)_BM]) 
			                       
			                      
			         
			             //Else part below -use normal aggregations
			              ,[Aggregate WACI (Scope 3 DS)_BM] )
			
			            Return Result
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: dded6834-2fa1-4a40-81a7-c6c1f0e97bc3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI (Scope 3 US)_BM' = ```
			
			        
			           Var BM_Count = CALCULATE( DISTINCTCOUNT('Benchmark Portfolio Mapping'[Benchmark_Name]))
			
			            //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,                           
			                        SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),[WACI Position (Scope 3 US)_BM]) 
			                       
			                      
			         
			             //Else part below -use normal aggregations
			              ,[Aggregate WACI (Scope 3 US)_BM] )
			
			            Return Result
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 56f658f4-56c4-469b-bf46-fc5f170c96ad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI (Scope 1 & 2 & 3DS)_BM' = ```
			
			
			     //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			         -- /*
			            Var Result  = 
			            IF( ( ISINSCOPE('Benchmark Portfolio Mapping'[Manager])   ||
			                    ISINSCOPE('Benchmark Portfolio Mapping'[Sub_Sector]) ||
			                    ISINSCOPE('Benchmark Portfolio Mapping'[Investment_Object]) ) ,   
			
			                        [Aggregate WACI (Scope 1 & 2 & 3DS)_BM]
			                       , SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),[WACI Position (Scope 1 & 2 & 3DS)_BM]) )
			          
			            Return Result
			
			        /*
			           Var BM_Count = CALCULATE( DISTINCTCOUNT('Benchmark Portfolio Mapping'[Benchmark_Name]))
			
			            //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,                           
			                        SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),[WACI Position (Scope 1 & 2 & 3DS)_BM]) 
			                       
			                      
			         
			             //Else part below -use normal aggregations
			              ,[Aggregate WACI (Scope 1 & 2 & 3DS)_BM] )
			
			            Return Result */
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 2584dd7e-b61c-4ff6-8e6e-0bca44c3cf40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI (Scope 1 & 2 & 3US)_BM' = ```
			
			
			            Var Result  = 
			            IF( ( ISINSCOPE('Benchmark Portfolio Mapping'[Manager])   ||
			                    ISINSCOPE('Benchmark Portfolio Mapping'[Sub_Sector]) ||
			                    ISINSCOPE('Benchmark Portfolio Mapping'[Investment_Object]) ) ,   
			
			                        [Aggregate WACI (Scope 1 & 2 & 3US)_BM]
			                       , SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),[WACI Position (Scope 1 & 2 & 3US)_BM]) )
			          
			            Return Result
			        /*
			           Var BM_Count = CALCULATE( DISTINCTCOUNT('Benchmark Portfolio Mapping'[Benchmark_Name]))
			
			            //For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,                           
			                        SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),[WACI Position (Scope 1 & 2 & 3US)_BM]) 
			                       
			                      
			         
			             //Else part below -use normal aggregations
			              ,[Aggregate WACI (Scope 1 & 2 & 3US)_BM] )
			
			            Return Result */
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: a160d855-0dd6-415b-8088-2537628ab513

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI (Scope 1 & 2 & 3DS & 3US)_BM' = ```
			
			        
			            Var Result  = 
			            IF( ( ISINSCOPE('Benchmark Portfolio Mapping'[Manager])   ||
			                    ISINSCOPE('Benchmark Portfolio Mapping'[Sub_Sector]) ||
			                    ISINSCOPE('Benchmark Portfolio Mapping'[Investment_Object]) ) ,   
			
			                        [Aggregate WACI (Scope 1 & 2 & 3DS & 3US)_BM]
			                       , SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),[WACI Position (Scope 1 & 2 & 3DS & 3US)_BM]) )
			          
			            Return Result
			           
			            
			            /*//For Benchmark and portfolio top level aggregate sum of sub-sector levels
			            Var Result  = 
			            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,                           
			                        SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),[WACI Position (Scope 1 & 2 & 3DS & 3US)_BM]) 
			                       
			                      
			         
			             //Else part below -use normal aggregations
			              ,[Aggregate WACI (Scope 1 & 2 & 3DS & 3US)_BM] )
			
			            Return Result */
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 9c0b68f6-f63c-474c-9d95-214e95596dc8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI_GS_Sector_Position (Scope 1 & 2 & 3DS)_BM' = ```
			IF(AND(ISINSCOPE('GS Asset'[GICS_SECTORS_SHORT]),
			                                                 SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type])="Benchmark") , 
			                                                 [Matrix MV WACI (Scope 1 & 2 & 3DS)_BM] *  [WACI_GS_Sector (Scope 1 & 2)_Weighted_BM],
			                                                 [Aggregate WACI (Scope 1 & 2 & 3DS)_BM])
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 41a320d8-6b1d-4aaf-bd30-7ac687a168aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI_GS_Sector_Position (Scope 1 & 2 & 3US)_BM' = ```
			IF(AND(ISINSCOPE('GS Asset'[GICS_SECTORS_SHORT]),
			                                                 SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type])="Benchmark") , 
			                                                 [Matrix MV WACI (Scope 1 & 2 & 3US)_BM] *  [WACI_GS_Sector (Scope 1 & 2)_Weighted_BM],
			                                                 [Aggregate WACI (Scope 1 & 2 & 3US)_BM])
			
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 5981f6e3-0491-40d9-b9b1-5cb79a375242

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WACI_GS_Sector_Position (Scope 1 & 2 & 3DS & 3US)_BM' = ```
			IF(AND(ISINSCOPE('GS Asset'[GICS_SECTORS_SHORT]),
			                                                 SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type])="Benchmark") , 
			                                                 [Matrix MV WACI (Scope 1 & 2 & 3DS & 3US)_BM] *  [WACI_GS_Sector (Scope 1 & 2)_Weighted_BM],
			                                                 [Aggregate WACI (Scope 1 & 2 & 3DS & 3US)_BM])
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 50258210-3ead-4bdc-85e1-39c4b096c904

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI_With_GS_Sector_Country (Scope 1 & 2 & 3DS)_BM' = ```
			
			                                             Switch (TRUE(),
			                                             -- SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) ="Benchmark" && 
			                                                 CALCULATE(ISFILTERED( 'GS Asset'[GICS_SECTORS_SHORT] ),ALLSELECTED( 'GS Asset'[GICS_SECTORS_SHORT] )),
			                                                 SUMX(GROUPBY('GS Asset','GS Asset'[GICS_SECTORS_SHORT]),[WACI_GS_Sector_Position (Scope 1 & 2 & 3DS)_BM]),
			                                                 CALCULATE(ISFILTERED( 'ESG Country'[Country] ),ALLSELECTED( 'ESG Country'[Country] ) ),
			                                                 [Aggregate WACI (Scope 1 & 2 & 3DS)_BM],
			                                                 [Matrix MV WACI (Scope 1 & 2 & 3DS)_BM])
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: fdb7765a-b088-41d1-8f5e-53779114cf4c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI_With_GS_Sector_Country (Scope 1 & 2 & 3US)_BM' = ```
			
			                                             Switch (TRUE(),
			                                             -- SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) ="Benchmark" && 
			                                                 CALCULATE(ISFILTERED( 'GS Asset'[GICS_SECTORS_SHORT] ),ALLSELECTED( 'GS Asset'[GICS_SECTORS_SHORT] )),
			                                                 SUMX(GROUPBY('GS Asset','GS Asset'[GICS_SECTORS_SHORT]),[WACI_GS_Sector_Position (Scope 1 & 2 & 3US)_BM]),
			                                                 CALCULATE(ISFILTERED( 'ESG Country'[Country] ),ALLSELECTED( 'ESG Country'[Country] ) ),
			                                                 [Aggregate WACI (Scope 1 & 2 & 3US)_BM],
			                                                 [Matrix MV WACI (Scope 1 & 2 & 3US)_BM])
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 2183fee8-a04c-4072-ad48-bdafe6157c2a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI_With_GS_Sector_Country (Scope 1 & 2 & 3DS & 3US)_BM' = ```
			
			                                             Switch (TRUE(),
			                                             -- SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) ="Benchmark" && 
			                                                 CALCULATE(ISFILTERED( 'GS Asset'[GICS_SECTORS_SHORT] ),ALLSELECTED( 'GS Asset'[GICS_SECTORS_SHORT] )),
			                                                 SUMX(GROUPBY('GS Asset','GS Asset'[GICS_SECTORS_SHORT]),[WACI_GS_Sector_Position (Scope 1 & 2 & 3DS & 3US)_BM]),
			                                                 CALCULATE(ISFILTERED( 'ESG Country'[Country] ),ALLSELECTED( 'ESG Country'[Country] ) ),
			                                                 [Aggregate WACI (Scope 1 & 2 & 3DS & 3US)_BM],
			                                                 [Matrix MV WACI (Scope 1 & 2 & 3DS & 3US)_BM])
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: fc994b90-4820-48c0-9e4a-f7cec64306f4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV Apportioned Carbon Switch_BM' = ```
			
			          
			            SWITCH  (TRUE()  , 
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  1 , [Matrix MV Apportioned Carbon (Scope 1 & 2)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  2 , [Matrix MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  3 , [Matrix MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  4 , [Matrix MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM],
			                    [Matrix MV Apportioned Carbon (Scope 1 & 2)_BM])
			  
			```
		formatString: #,0
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: cc8b79d4-7ce1-4665-827d-c5a81324f4b4

	measure 'Matrix MV CR Intensity Switch_BM' = ```
			
			          
			            SWITCH  (TRUE()  , 
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  1 , [Matrix MV CR Intensity (Scope 1 & 2)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  2 , [Matrix MV CR Intensity (Scope 1 & 2 & 3DS)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  3 , [Matrix MV CR Intensity (Scope 1 & 2 & 3US)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  4 , [Matrix MV CR Intensity (Scope 1 & 2 & 3DS & 3US)_BM],
			                    [Matrix MV CR Intensity (Scope 1 & 2)_BM])
			  
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 0d3d3a6e-95f7-4e51-889d-ab01d087d629

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix MV WACI Switch_BM' = ```
			
			          
			            SWITCH  (TRUE()  , 
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  1 , [Matrix MV WACI (Scope 1 & 2)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  2 , [Matrix MV WACI (Scope 1 & 2 & 3DS)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  3 , [Matrix MV WACI (Scope 1 & 2 & 3US)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  4 , [Matrix MV WACI (Scope 1 & 2 & 3DS & 3US)_BM],
			                    [Matrix MV WACI (Scope 1 & 2)_BM])
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 23d5f9c7-f8bf-443d-a171-46be7b55bae6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch_Matrix MV Apportioned Carbon (Scope 3 DS)_BM' = ```
			If (SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =1 
			                                                        || SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =3 ,
			                                                           BLANK(), [Matrix MV Apportioned Carbon (Scope 3 DS)_BM])
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: cf2f8f5b-53e0-404b-bc12-cfd6413e967c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Filter Measure' = ```
			SWITCH(true,
			                         [Aggregate MV Apportioned Carbon (Scope 1)_BM] > 1 && [Aggregate MV Apportioned Carbon (Scope 2)_BM] > 1 && [Switch_Matrix MV Apportioned Carbon (Scope 3 DS)_BM] =BLANK(), 1,0)
			
			```
		formatString: 0
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 20396e2a-3b73-4645-b79a-9ac164462788

	measure 'Switch_Matrix MV Apportioned Carbon (Scope 3 US)_BM' = ```
			If (SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =1 
			                                                      || SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =2 ,
			                                                       BLANK(), [Matrix MV Apportioned Carbon (Scope 3 US)_BM])
			```
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 15304021-b9d3-401d-8d22-2efd3759d769

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Matrix WACI_GS_Sector_Position_Switch_BM' = ```
			
			          
			            SWITCH  (TRUE()  , 
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  1 , [WACI_GS_Sector_Position (Scope 1 & 2)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  2 , [WACI_GS_Sector_Position (Scope 1 & 2 & 3DS)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  3 , [WACI_GS_Sector_Position (Scope 1 & 2 & 3US)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  4 , [WACI_GS_Sector_Position (Scope 1 & 2 & 3DS & 3US)_BM],
			                    [WACI_GS_Sector_Position (Scope 1 & 2)_BM])
			```
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: be59eeec-894d-4e58-881c-3a11e2133ad4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch_Matrix MV CR Intensity Carbon (Scope 3 DS)_BM' = ```
			If (SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =1 
			                                                       || SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =3 ,
			                                                          BLANK(), [Matrix MV CR Intensity (Scope 3 DS)_BM])
			```
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 7a48c87b-f3ca-46b3-a615-de1d19032c41

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch_Matrix MV CR Intensity Carbon (Scope 3 US)_BM' =
			If (SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =1
			                                                          || SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =2 ,
			                                                          BLANK(), [Matrix MV CR Intensity (Scope 3 US)_BM])
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 7ab1dc19-c589-46ce-a4a3-28ab5ab05ba0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch_Matrix MV WACI (Scope 3 DS)_BM' =
			If (SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =1
			                                        || SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =3 ,
			                                        BLANK(), [Matrix MV WACI (Scope 3 DS)_BM])
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 08e3b0cb-bbe3-4d09-9510-4a583b934e03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Switch_Matrix MV WACI (Scope 3 US)_BM' =
			If (SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =1
			                                        || SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =2 ,
			                                           BLANK(), [Matrix MV WACI (Scope 3 US)_BM])
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: e5c8a3cb-4d51-4e4a-ad55-886af398ceeb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Portfolio_Asset_Matrix MV Apportioned Carbon Switch_BM' = CALCULATE( [Matrix MV Apportioned Carbon Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] = "Portfolio")
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 5af71a45-1456-4bb7-b4ab-eace8cd39138

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Benchmark_Asset_Matrix MV Apportioned Carbon Switch_BM' = CALCULATE( [Matrix MV Apportioned Carbon Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] = "Benchmark")
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 83943b80-3737-425e-947a-c774f4c38256

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Portfolio_Asset_Matrix MV CR Intensity Switch_BM' = CALCULATE( [Matrix MV CR Intensity Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] = "Portfolio")
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: 976b313c-03e8-4e2e-937b-dd13ed06661b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Benchmark_Asset_Matrix MV CR Intensity Switch_BM' = CALCULATE( [Matrix MV CR Intensity Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] = "Benchmark")
		displayFolder: Carbon-Revenue Intensity\Market Value Apportion
		lineageTag: d405c704-b0b9-45c4-9a7a-d1249c1654d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Port_Asset_Matrix MV WACI Switch_BM' = CALCULATE([Matrix MV WACI Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] = "Portfolio")
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 7316e418-69b3-4b1a-b9cd-87999c0a6c7a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bmk_Asset_Matrix MV WACI Switch_BM' = CALCULATE([Matrix MV WACI Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] = "Benchmark")
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 775a1ebe-b49b-4685-8927-85db5f39daf8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Portfolio_Apportioned_Carbon_Matrix = CALCULATE([Matrix MV Apportioned Carbon Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] ="Portfolio")
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 7d17e7eb-8368-482b-9a3d-b0de154adbbf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Benchmark_Apportioned_Carbon_Matrix = CALCULATE([Matrix MV Apportioned Carbon Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] ="Benchmark")
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: b5c9f2ac-0e44-42ee-a51f-bcb11ffa2d40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Position_Relative_Difference_Apportioned_Carbon = ```
			
			 --[Benchmark_Apportioned_Carbon_Matrix]- [Portfolio_Apportioned_Carbon_Matrix]
			
			    Var Benchmark = CALCULATE([Matrix MV Apportioned Carbon Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] ="Benchmark")
			    Var Portfolio = CALCULATE([Matrix MV Apportioned Carbon Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] ="Portfolio")
			
			    Var Benchmark_BM = CALCULATE([Matrix MV Apportioned Carbon Switch_BM] ,
			                        'Benchmark Portfolio Mapping'[Position_Type] ="Benchmark" && ISINSCOPE('Benchmark Portfolio Mapping'[Investment_Object]) )
			
			    Return if(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" 
			                || ( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio" && ISINSCOPE('Benchmark Portfolio Mapping'[Investment_Object]))
			                    , BLANK(), ( 1+ Portfolio ) / (1+ Benchmark) - 1)
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 12f77355-c845-429b-ac1a-68f5e60d7674

	measure WACI_Asset_Portfolio = [Portfolio_Asset_Matrix MV CR Intensity Switch_BM] * [Portfolio_Asset_weight_BM]
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 789aded7-acaa-4be5-820e-204981c6c093

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure WACI_Asset_Benchmark = [Portfolio_Asset_Matrix MV CR Intensity Switch_BM] * [Benchmark_Asset_Weight_BM_BM]
		displayFolder: Weighted Avg Carbon Intensity
		lineageTag: 3c232bed-9dbf-4afb-9d37-bbf119b0dd8d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Matrix_Apportioned_Carbon_Consolidated = ```
			
			
			Var MV_Apportioned_Carbon_Scope_1_2_BM = CALCULATE([MV Ownership_BM] * 
			                                                   (SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM])
			                                                        )
			                                                   ) 
			                                                
			Var MV_Apportioned_Carbon_Scope_1_2_3DS_BM = CALCULATE([MV Ownership_BM] * 
			                                                   (SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM] + [Carbon_Scope_3_tonnes_CO2e_Downstream_BM]) 
			                                                        )
			                                                   ) 
			                                                
			Var MV_Apportioned_Carbon_Scope_1_2_3US_BM = CALCULATE([MV Ownership_BM] * 
			                                                   (SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM] +                            [Carbon_Scope_3_tonnes_CO2e_Upstream_BM]) 
			                                                        )
			                                                   ) 
			
			Var MV_Apportioned_Carbon_Scope_1_2_3DS_3US_BM = CALCULATE([MV Ownership_BM] * 
			                                                   (SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM] +      [Carbon_Scope_3_tonnes_CO2e_Downstream_BM]+ [Carbon_Scope_3_tonnes_CO2e_Upstream_BM]) 
			                                                        )
			                                                   ) 
			
			
			Var Aggregate_MV_Apportioned_Carbon_Scope_1_2_BM = SUMX('GS Asset',MV_Apportioned_Carbon_Scope_1_2_BM)
			Var Aggregate_MV_Apportioned_Carbon_Scope_1_2_3DS_BM = SUMX('GS Asset',MV_Apportioned_Carbon_Scope_1_2_3DS_BM)
			Var Aggregate_MV_Apportioned_Carbon_Scope_1_2_3US_BM = SUMX('GS Asset',MV_Apportioned_Carbon_Scope_1_2_3US_BM)
			Var Aggregate_MV_Apportioned_Carbon_Scope_1_2_3DS_3US_BM = SUMX('GS Asset',MV_Apportioned_Carbon_Scope_1_2_3DS_3US_BM)
			
			
			Var Matrix_MV_Apportioned_Carbon_Scope_1_2_BM = 
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels         
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),Aggregate_MV_Apportioned_Carbon_Scope_1_2_BM)         
			         //Else part below -use normal aggregations
			              ,Aggregate_MV_Apportioned_Carbon_Scope_1_2_BM)
			
			Var Matrix_MV_Apportioned_Carbon_Scope_1_2_3DS_BM = 
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels         
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),Aggregate_MV_Apportioned_Carbon_Scope_1_2_3DS_BM)         
			         //Else part below -use normal aggregations
			              ,Aggregate_MV_Apportioned_Carbon_Scope_1_2_3DS_BM)
			
			Var Matrix_MV_Apportioned_Carbon_Scope_1_2_3US_BM = 
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels         
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),Aggregate_MV_Apportioned_Carbon_Scope_1_2_3US_BM)         
			         //Else part below -use normal aggregations
			              ,Aggregate_MV_Apportioned_Carbon_Scope_1_2_3US_BM)
			
			Var Matrix_MV_Apportioned_Carbon_Scope_1_2_3DS_3US_BM = 
			         //For Benchmark and portfolio top level aggregate sum of sub-sector levels         
			            IF( OR(SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark"
			                  ,SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio"),
			               SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Portfolio_Inv_Obj_Code]),Aggregate_MV_Apportioned_Carbon_Scope_1_2_3DS_3US_BM)         
			         //Else part below -use normal aggregations
			              ,Aggregate_MV_Apportioned_Carbon_Scope_1_2_3DS_3US_BM)
			
			Var Matrix_MV_Apportioned_Carbon_Switch_BM = 
			          
			            SWITCH  (TRUE()  , 
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  1 , [Matrix MV Apportioned Carbon (Scope 1 & 2)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  2 , [Matrix MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  3 , [Matrix MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM],
			                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  4 , [Matrix MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM],
			                    [Matrix MV Apportioned Carbon (Scope 1 & 2)_BM])
			
			Return Matrix_MV_Apportioned_Carbon_Switch_BM
			
			
			
			```
		formatString: 0
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: a1c48cf3-749f-427f-a658-ddd780b40f87

	measure Position_App_Carbon_Portfolio_Only = CALCULATE([Matrix MV Apportioned Carbon Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] = "Portfolio")
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 7961f8fe-f088-41b9-b69c-fd6cd964c712

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Position_App_Carbon_Benchmark_Only = CALCULATE([Matrix MV Apportioned Carbon Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] = "Benchmark")
		displayFolder: Apportioned Carbon\Market Value Apportion
		lineageTag: 4b615a86-831c-482a-a4c9-9977a970de85

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ISIN
		dataType: string
		lineageTag: db332780-14e4-47ed-973e-c35f26d7dc04
		summarizeBy: none
		sourceColumn: ISIN

		annotation SummarizationSetBy = Automatic

	column Bituminous_Coal_and_Lignite_Surface_Mining_Revenue_USD_mn
		dataType: double
		displayFolder: Thermal Energy Mix
		lineageTag: e657b897-49d1-41b4-b0f4-91c15a7fa8c4
		summarizeBy: sum
		sourceColumn: Bituminous_Coal_and_Lignite_Surface_Mining_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Bituminous_Coal_and_Lignite_Surface_Mining_Revenue_Percent
		dataType: double
		displayFolder: Thermal Energy Mix
		lineageTag: 7340eba2-aa06-4ac5-8577-ca740e2e22ab
		summarizeBy: sum
		sourceColumn: Bituminous_Coal_and_Lignite_Surface_Mining_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Bituminous_Coal_Underground_Mining_Revenue_USD_mn
		dataType: double
		displayFolder: Thermal Energy Mix
		lineageTag: 626e53ff-a342-4693-89d1-782701402b1f
		summarizeBy: sum
		sourceColumn: Bituminous_Coal_Underground_Mining_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Bituminous_Coal_Underground_Mining_Revenue_Percent
		dataType: double
		displayFolder: Thermal Energy Mix
		lineageTag: a6e29c91-953e-4adf-a3bb-fff8d741707f
		summarizeBy: sum
		sourceColumn: Bituminous_Coal_Underground_Mining_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Crude_Petroleum_and_Natural_Gas_Extraction_Revenue_USD_mn
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: 527a07b6-ec8b-4568-aa1c-00887bbd72c4
		summarizeBy: sum
		sourceColumn: Crude_Petroleum_and_Natural_Gas_Extraction_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Crude_Petroleum_and_Natural_Gas_Extraction_Revenue_Percent
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: a5cb5349-ac11-49e0-ab50-dcdc28ce3319
		summarizeBy: sum
		sourceColumn: Crude_Petroleum_and_Natural_Gas_Extraction_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Natural_Gas_Liquid_Extraction_Revenue_USD_mn
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: 0fb25f4f-e402-4529-abf1-2b79e6f3162f
		summarizeBy: sum
		sourceColumn: Natural_Gas_Liquid_Extraction_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Natural_Gas_Liquid_Extraction_Revenue_Percent
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: 6a33baf6-ad85-48ac-a98e-e3a0a8abf54f
		summarizeBy: sum
		sourceColumn: Natural_Gas_Liquid_Extraction_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tar_Sands_Extraction_Revenue_USD_mn
		dataType: double
		displayFolder: Other
		lineageTag: 80faa0e9-d54c-4d5f-a4e8-b35ab95cc0d4
		summarizeBy: sum
		sourceColumn: Tar_Sands_Extraction_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tar_Sands_Extraction_Revenue_Percent
		dataType: double
		displayFolder: Other
		lineageTag: b59fd53c-1691-403f-8c51-3cf2ac2f7ef6
		summarizeBy: sum
		sourceColumn: Tar_Sands_Extraction_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Support_Activities_For_Oil_And_Gas_Operations_Revenue_USD_mn
		dataType: double
		displayFolder: Other
		lineageTag: 4790b790-2435-4514-81d7-96301d93705d
		summarizeBy: sum
		sourceColumn: Support_Activities_For_Oil_And_Gas_Operations_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Support_Activities_For_Oil_And_Gas_Operations_Revenue_Percent
		dataType: double
		displayFolder: Other
		lineageTag: 0daefcf8-ed00-46dc-82eb-12e7cc962872
		summarizeBy: sum
		sourceColumn: Support_Activities_For_Oil_And_Gas_Operations_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Coal
		lineageTag: feea9506-e633-454b-8c5c-b9b8469465a7
		summarizeBy: sum
		sourceColumn: Coal_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Coal
		lineageTag: 376b89ad-cc2d-4944-b503-a95fb9bba930
		summarizeBy: sum
		sourceColumn: Coal_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Natural_Gas_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: 7e801dc4-58ff-40c0-a051-30dcbc0a754c
		summarizeBy: sum
		sourceColumn: Natural_Gas_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Natural_Gas_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: f3346fb8-342e-46f8-b1f8-9b7defaf46cc
		summarizeBy: sum
		sourceColumn: Natural_Gas_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Petroleum_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: 3d6325ff-a920-455c-9ee7-2c139e9cea1f
		summarizeBy: sum
		sourceColumn: Petroleum_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Petroleum_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: 7082db27-0233-421e-a795-56840185f1eb
		summarizeBy: sum
		sourceColumn: Petroleum_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Solar_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Solar Power
		lineageTag: 50b6753c-da7c-457e-8370-ecf22a3a788c
		summarizeBy: sum
		sourceColumn: Solar_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Solar_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Solar Power
		lineageTag: df1af457-8e51-45aa-a7a9-6921fc293186
		summarizeBy: sum
		sourceColumn: Solar_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wind_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Wind and wave
		lineageTag: 615f5428-1269-47f4-940c-d69c97a72e35
		summarizeBy: sum
		sourceColumn: Wind_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wind_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Wind and wave
		lineageTag: e220fd7e-2273-4be2-9a6a-9e7d1eeef86b
		summarizeBy: sum
		sourceColumn: Wind_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Geothermal_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Thermal Energy Mix
		lineageTag: 88753dc3-3b05-4d50-a669-1a7f980c7c4c
		summarizeBy: sum
		sourceColumn: Geothermal_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Geothermal_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Thermal Energy Mix
		lineageTag: 782f4087-5874-465f-8294-e508f1b243e4
		summarizeBy: sum
		sourceColumn: Geothermal_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wave_And_Tidal_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Wind and wave
		lineageTag: c1b6c5cc-622a-4b97-b88d-405944f0a1b2
		summarizeBy: sum
		sourceColumn: Wave_And_Tidal_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wave_And_Tidal_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Wind and wave
		lineageTag: ffea4ebc-a3ea-4ee1-8b0c-9f8797a2f314
		summarizeBy: sum
		sourceColumn: Wave_And_Tidal_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Biomass_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Biomass
		lineageTag: 4ce80338-9c5f-4fb4-97da-967bb66d9ba5
		summarizeBy: sum
		sourceColumn: Biomass_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Biomass_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Biomass
		lineageTag: de537251-a69e-41b7-9ec9-528ab77b89e0
		summarizeBy: sum
		sourceColumn: Biomass_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Landfill_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Landfill
		lineageTag: 7c08081d-35f3-4e0d-af4e-0f68b8cf2e84
		summarizeBy: sum
		sourceColumn: Landfill_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Landfill_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Landfill
		lineageTag: f52cf985-d392-460c-a47b-24fe3678f8cf
		summarizeBy: sum
		sourceColumn: Landfill_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Hydroelectric_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Hydroelectric
		lineageTag: 9b88d1c8-20ba-4634-aca9-a4b3f143f3d5
		summarizeBy: sum
		sourceColumn: Hydroelectric_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Hydroelectric_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Hydroelectric
		lineageTag: a737376f-7a26-4c4b-a638-8f1eb0a0a2ad
		summarizeBy: sum
		sourceColumn: Hydroelectric_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Nuclear_Electric_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Nuclear
		lineageTag: ffb3dbf9-e09c-486b-9329-bfe165f84ca4
		summarizeBy: sum
		sourceColumn: Nuclear_Electric_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Nuclear_Electric_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Nuclear
		lineageTag: e5511f6f-1575-43e0-8403-b49b4dedc87a
		summarizeBy: sum
		sourceColumn: Nuclear_Electric_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Eletric_Power_Generation_Revenue_USD_mn
		dataType: double
		displayFolder: Other
		lineageTag: 03b843ab-8584-4536-95fe-aba42e43bb82
		summarizeBy: sum
		sourceColumn: Other_Eletric_Power_Generation_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Eletric_Power_Generation_Revenue_Percent
		dataType: double
		displayFolder: Other
		lineageTag: 9e4f7d94-bc9c-4bfc-b9f6-b1abe0bf6ab1
		summarizeBy: sum
		sourceColumn: Other_Eletric_Power_Generation_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Scope_1_tonnes_CO2e
		dataType: double
		displayFolder: Carbon
		lineageTag: 0ea2cb26-ccd8-4372-a4c9-98c604e9421b
		summarizeBy: sum
		sourceColumn: Carbon_Scope_1_tonnes_CO2e

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Scope_2_tonnes_CO2e
		dataType: double
		displayFolder: Carbon
		lineageTag: 4fdb2a1e-0082-453e-b8a1-950b62757d31
		summarizeBy: sum
		sourceColumn: Carbon_Scope_2_tonnes_CO2e

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Scope_3_tonnes_CO2e
		dataType: double
		displayFolder: Carbon
		lineageTag: db0fe004-1eca-44f1-89ea-6a06ca21a635
		summarizeBy: sum
		sourceColumn: Carbon_Scope_3_tonnes_CO2e

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Direct_tonnes_CO2e
		dataType: double
		displayFolder: Carbon
		lineageTag: daffe775-a6d4-4547-9f57-f61cad2fda47
		summarizeBy: sum
		sourceColumn: Carbon_Direct_tonnes_CO2e

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_First_Tier_Indirect_tonnes_CO2e
		dataType: double
		displayFolder: Carbon
		lineageTag: a23b8f8d-1a09-472d-8834-3fb9443192cf
		summarizeBy: sum
		sourceColumn: Carbon_First_Tier_Indirect_tonnes_CO2e

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Direct_And_First_Tier_Indirect_tonnes_CO2e
		dataType: double
		displayFolder: Carbon
		lineageTag: 19402791-2210-4a49-aaec-c9cd564f3c34
		summarizeBy: sum
		sourceColumn: Carbon_Direct_And_First_Tier_Indirect_tonnes_CO2e

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_Scope_1_tonnes_CO2e_USD_mn
		dataType: double
		displayFolder: Carbon
		lineageTag: 4ff43407-b44f-486c-b069-ab87bac409d2
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_Scope_1_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_Scope_2_tonnes_CO2e_USD_mn
		dataType: double
		displayFolder: Carbon
		lineageTag: 2437e0fe-8dc0-475d-a352-28c21f72174c
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_Scope_2_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_Scope_3_tonnes_CO2e_USD_mn
		dataType: double
		displayFolder: Carbon
		lineageTag: de0d0acc-93ba-4edc-9fdb-7998cbbfa4d8
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_Scope_3_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_Direct_tonnes_CO2e_USD_mn
		dataType: double
		displayFolder: Carbon
		lineageTag: 99adf402-462e-4f06-8f2e-0be18702a5d6
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_Direct_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_First_Tier_Indirect_tonnes_CO2e_USD_mn
		dataType: double
		displayFolder: Carbon
		lineageTag: 153c14ed-a4de-46c0-a850-dec1687c6d40
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_First_Tier_Indirect_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Intensity_Direct_And_First_Tier_Indirect_tonnes_CO2e_USD_mn
		dataType: double
		displayFolder: Carbon
		lineageTag: 37cec106-46f4-4a43-ad33-40dcaa439da1
		summarizeBy: sum
		sourceColumn: Carbon_Intensity_Direct_And_First_Tier_Indirect_tonnes_CO2e_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Direct_USD_mn
		dataType: double
		displayFolder: Greenhouse Gas
		lineageTag: c9d65b3a-2c71-4a6c-8260-adbc7c353f58
		summarizeBy: sum
		sourceColumn: GHG_Direct_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Indirect_USD_mn
		dataType: double
		displayFolder: Greenhouse Gas
		lineageTag: 7c573a20-9ad1-406c-b3a1-008bd728f794
		summarizeBy: sum
		sourceColumn: GHG_Indirect_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Total_USD_mn
		dataType: double
		displayFolder: Greenhouse Gas
		lineageTag: 4c3db276-dc64-4538-8dfd-a8d357951209
		summarizeBy: sum
		sourceColumn: GHG_Total_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Direct_Impact_Ratio_Percent
		dataType: double
		displayFolder: Greenhouse Gas
		lineageTag: a372cd8a-8c6e-442c-8e99-dafec1e02b26
		summarizeBy: sum
		sourceColumn: GHG_Direct_Impact_Ratio_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Indirect_Impact_Ratio_Percent
		dataType: double
		displayFolder: Greenhouse Gas
		lineageTag: 22e42520-0333-46b1-b074-a4e81a39360a
		summarizeBy: sum
		sourceColumn: GHG_Indirect_Impact_Ratio_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GHG_Total_Impact_Ratio_Percent
		dataType: double
		displayFolder: Greenhouse Gas
		lineageTag: 9f5bda09-b972-4b8c-898b-95cedab242df
		summarizeBy: sum
		sourceColumn: GHG_Total_Impact_Ratio_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Carbon_Disclosure
		dataType: string
		displayFolder: Carbon
		lineageTag: 9e02695c-6967-4b74-a1f8-aa37f31f7972
		summarizeBy: none
		sourceColumn: Carbon_Disclosure

		annotation SummarizationSetBy = Automatic

	column Revenue_USD_mn
		dataType: double
		displayFolder: Revenue
		lineageTag: 5038cbe6-a29b-48cc-a3f1-e0ed6757e9b6
		summarizeBy: sum
		sourceColumn: Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Currency_Code
		dataType: string
		lineageTag: 32419240-8ea5-4070-89bc-15cee04d25bb
		summarizeBy: none
		sourceColumn: Currency_Code

		annotation SummarizationSetBy = Automatic

	column Reserves_CO2_emissions_from_Coal_m_tonnes
		dataType: double
		displayFolder: Reserves
		lineageTag: de87809c-3fcc-4f96-baab-2e9f5fa4269d
		summarizeBy: sum
		sourceColumn: Reserves_CO2_emissions_from_Coal_m_tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_CO2_emissions_from_Oil_m_tonnes
		dataType: double
		displayFolder: Reserves
		lineageTag: 06ffca4e-1edb-4e74-86cd-4a91ef464096
		summarizeBy: sum
		sourceColumn: Reserves_CO2_emissions_from_Oil_m_tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_CO2_emissions_from_Gas_m_tonnes
		dataType: double
		displayFolder: Reserves
		lineageTag: 8af82e36-e0ad-4b43-8639-0e986c1d6035
		summarizeBy: sum
		sourceColumn: Reserves_CO2_emissions_from_Gas_m_tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Reserves_CO2_emissions_m_tonnes
		dataType: double
		displayFolder: Reserves
		lineageTag: 42e635ab-9713-47a0-94b9-dba0d2e57ea8
		summarizeBy: sum
		sourceColumn: Total_Reserves_CO2_emissions_m_tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Funds used by a company to acquire, upgrade, and maintain physical assets such as property, plants, buildings, technology etc.
	column CAPEX_Coal_m_USD
		dataType: double
		displayFolder: Capital Expenditure
		lineageTag: 5dd72d9d-affc-4b7d-946a-0bb83a47dfee
		summarizeBy: sum
		sourceColumn: CAPEX_Coal_m_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Funds used by a company to acquire, upgrade, and maintain physical assets such as property, plants, buildings, technology etc.
	column CAPEX_Gas_m_USD
		dataType: double
		displayFolder: Capital Expenditure
		lineageTag: 1d81c5e2-aace-4c93-88ec-238d89db8d8d
		summarizeBy: sum
		sourceColumn: CAPEX_Gas_m_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Funds used by a company to acquire, upgrade, and maintain physical assets such as property, plants, buildings, technology etc.
	column CAPEX_Oil_And_Gas_m_USD
		dataType: double
		displayFolder: Capital Expenditure
		lineageTag: e7d4a0dd-1c82-42b8-b1c4-f50148d48a0f
		summarizeBy: sum
		sourceColumn: CAPEX_Oil_And_Gas_m_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Funds used by a company to acquire, upgrade, and maintain physical assets such as property, plants, buildings, technology etc.
	column CAPEX_Other_exploration_m_USD
		dataType: double
		displayFolder: Capital Expenditure
		lineageTag: fc714069-d940-46f6-bc03-56eff208f4a3
		summarizeBy: sum
		sourceColumn: CAPEX_Other_exploration_m_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Power_Generation_GWh
		dataType: double
		displayFolder: Coal
		lineageTag: e267d6d2-1189-4305-9d37-2500f77b28eb
		summarizeBy: sum
		sourceColumn: Coal_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Petroleum_Power_Generation_GWh
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: edc3d645-1fdc-4c4f-aca7-e033537c9ec2
		summarizeBy: sum
		sourceColumn: Petroleum_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Natural_Gas_Power_Generation_GWh
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: 1e803bfd-a63b-43ee-a2a2-4088130ac988
		summarizeBy: sum
		sourceColumn: Natural_Gas_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LPG_Power_Generation_GWh
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: b084e6af-1270-4ed4-bd73-9beccf9ffca8
		summarizeBy: sum
		sourceColumn: LPG_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LNG_Power_Generation_GWh
		dataType: double
		displayFolder: Crude, Petroleum and Natural Gas
		lineageTag: a2ae9abc-f4b6-410f-bf71-d55c622a64f4
		summarizeBy: sum
		sourceColumn: LNG_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wind_Power_Generation_GWh
		dataType: double
		displayFolder: Wind and wave
		lineageTag: 3a473158-9fc6-4dbd-b3d9-6653d4f98b75
		summarizeBy: sum
		sourceColumn: Wind_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Solar_Power_Generation_GWh
		dataType: double
		displayFolder: Solar Power
		lineageTag: 7ddccdbe-5783-4f57-9d55-e061f8b68a15
		summarizeBy: sum
		sourceColumn: Solar_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Biomass_Power_Generation_GWh
		dataType: double
		displayFolder: Biomass
		lineageTag: 94704432-4f07-4555-837f-fbfab8f73c47
		summarizeBy: sum
		sourceColumn: Biomass_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Geothermal_Power_Generation_GWh
		dataType: double
		displayFolder: Thermal Energy Mix
		lineageTag: ea1ef349-7c7c-4fad-890b-df45575f0ba7
		summarizeBy: sum
		sourceColumn: Geothermal_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Wave_And_Tidal_Power_Generation_GWh
		dataType: double
		displayFolder: Wind and wave
		lineageTag: c79933da-f791-4a86-9453-969f0fc62b49
		summarizeBy: sum
		sourceColumn: Wave_And_Tidal_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Hydroelectric_Power_Generation_GWh
		dataType: double
		displayFolder: Hydroelectric
		lineageTag: cc12585c-f18e-4c47-babb-0e29f41646bf
		summarizeBy: sum
		sourceColumn: Hydroelectric_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Nuclear_Power_Generation_GWh
		dataType: double
		displayFolder: Nuclear
		lineageTag: 70e44ee9-2b7b-4d54-8a84-2a7fa95fd5c8
		summarizeBy: sum
		sourceColumn: Nuclear_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Landfill_Gas_Power_Generation_GWh
		dataType: double
		displayFolder: Landfill
		lineageTag: a7b1a5fa-f747-43f8-85b0-72cf917d4b04
		summarizeBy: sum
		sourceColumn: Landfill_Gas_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Power_Generation_GWh
		dataType: double
		displayFolder: Other
		lineageTag: 0b5e4b12-bc18-4a3a-860d-ded2926f7ec9
		summarizeBy: sum
		sourceColumn: Other_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_1P_Metallurgical_Coal_m_Tonnes
		dataType: double
		displayFolder: Reserves
		lineageTag: 91e0f36f-fcf8-413f-af58-0c22c086e5e6
		summarizeBy: sum
		sourceColumn: Reserves_1P_Metallurgical_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_2P_Metallurgical_Coal_m_Tonnes
		dataType: double
		displayFolder: Reserves
		lineageTag: 2cf9dea6-57fd-448a-9d2b-cf84cee1e948
		summarizeBy: sum
		sourceColumn: Reserves_2P_Metallurgical_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_1P_Thermal_Coal_m_Tonnes
		dataType: double
		displayFolder: Reserves
		lineageTag: 930fa5ab-b1ff-47fa-8e9b-4791bcb26bf7
		summarizeBy: sum
		sourceColumn: Reserves_1P_Thermal_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_2P_Thermal_Coal_m_Tonnes
		dataType: double
		displayFolder: Reserves
		lineageTag: 1467bb2f-6250-4f15-a7e6-527a362d4b07
		summarizeBy: sum
		sourceColumn: Reserves_2P_Thermal_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_1P_Other_Coal_m_Tonnes
		dataType: double
		displayFolder: Reserves
		lineageTag: 51509f0f-b105-4b64-aa20-4ff62c3c8dc3
		summarizeBy: sum
		sourceColumn: Reserves_1P_Other_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Reserves_2P_Other_Coal_m_Tonnes
		dataType: double
		displayFolder: Reserves
		lineageTag: 7b28bcaa-b52a-4bd6-ba7f-e613d029899e
		summarizeBy: sum
		sourceColumn: Reserves_2P_Other_Coal_m_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Extraction_Deep_Mined_Coal_Tonnes
		dataType: double
		displayFolder: Coal
		lineageTag: 8ce6b64c-a2a5-4268-897d-fef4d23cbb81
		summarizeBy: sum
		sourceColumn: Coal_Extraction_Deep_Mined_Coal_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Extraction_Open_Cast_Coal_Tonnes
		dataType: double
		displayFolder: Coal
		lineageTag: 518ab825-703a-4757-b900-e4eaa189dd1d
		summarizeBy: sum
		sourceColumn: Coal_Extraction_Open_Cast_Coal_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Extraction_Unknown_Type_Tonnes
		dataType: double
		displayFolder: Coal
		lineageTag: 71c58a6b-011d-4d65-934e-a2b23690dfd4
		summarizeBy: sum
		sourceColumn: Coal_Extraction_Unknown_Type_Tonnes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Thermal_Coal_Mining_Sector_Revenue_Percent
		dataType: double
		displayFolder: Thermal Energy Mix
		lineageTag: 61000c38-a45d-43bf-81a9-79ef17366a56
		summarizeBy: sum
		sourceColumn: Thermal_Coal_Mining_Sector_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Thermal_Coal_Mining_Sector_Revenue_USD_mn
		dataType: double
		displayFolder: Thermal Energy Mix
		lineageTag: 07693900-b70a-400b-81b8-d9afb608a820
		summarizeBy: sum
		sourceColumn: Thermal_Coal_Mining_Sector_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Metallurgical_Coal_Mining_Sector_Revenue_Percent
		dataType: double
		displayFolder: Coal
		lineageTag: 4ca1da9d-9127-433c-8aad-4dd9e83be669
		summarizeBy: sum
		sourceColumn: Metallurgical_Coal_Mining_Sector_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Metallurgical_Coal_Mining_Sector_Revenue_USD_mn
		dataType: double
		displayFolder: Coal
		lineageTag: 503ad98d-2668-43c0-8921-20a07876ae0f
		summarizeBy: sum
		sourceColumn: Metallurgical_Coal_Mining_Sector_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Coal_Mining_Sector_Revenue_Percent
		dataType: double
		displayFolder: Other
		lineageTag: e7da905e-1dae-4c76-9769-52783aed1920
		summarizeBy: sum
		sourceColumn: Other_Coal_Mining_Sector_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Coal_Mining_Sector_Revenue_USD_mn
		dataType: double
		displayFolder: Other
		lineageTag: c59daa85-d876-4063-985b-f1bc43a0f7ef
		summarizeBy: sum
		sourceColumn: Other_Coal_Mining_Sector_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Coal_Mining_Revenue_Percent
		dataType: double
		displayFolder: Coal
		lineageTag: 33d11a7f-7d16-41dc-b857-394aa73da747
		summarizeBy: sum
		sourceColumn: Total_Coal_Mining_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Coal_Mining_Revenue_USD_mn
		dataType: double
		displayFolder: Coal
		lineageTag: 9e160297-630e-4e50-b2ab-075acbf3c992
		summarizeBy: sum
		sourceColumn: Total_Coal_Mining_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Mining_Calculation_Methodology
		dataType: double
		displayFolder: Coal
		lineageTag: bb49c8b1-fb0b-4ae9-bced-b04126cf71aa
		summarizeBy: sum
		sourceColumn: Coal_Mining_Calculation_Methodology

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Mining_Data_source
		dataType: double
		displayFolder: Coal
		lineageTag: abb1d4f1-2305-43a9-b50a-f330fa312f9f
		summarizeBy: sum
		sourceColumn: Coal_Mining_Data_source

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Power_Generation_Pct_of_Total_Power_Generation_GWh
		dataType: double
		displayFolder: Coal
		lineageTag: 0a065d53-d968-4812-8465-2e8f1c1363d9
		summarizeBy: sum
		sourceColumn: Coal_Power_Generation_Pct_of_Total_Power_Generation_GWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Power_Generation_Data_Source
		dataType: double
		lineageTag: 486d9cbb-4f8f-4956-bf2e-a58d355be040
		summarizeBy: sum
		sourceColumn: Power_Generation_Data_Source

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Power_Generation_GHG_Tonnes_CO2e
		dataType: double
		displayFolder: Coal
		lineageTag: 42c50622-1bc6-4e5e-b7c8-44c2c06f3904
		summarizeBy: sum
		sourceColumn: Coal_Power_Generation_GHG_Tonnes_CO2e

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Coal_Gasification
		dataType: string
		displayFolder: Coal
		lineageTag: 3d987bc2-8cc2-4e3e-9519-355ba3ac603a
		summarizeBy: none
		sourceColumn: Coal_Gasification

		annotation SummarizationSetBy = Automatic

	column Coal_Liquefaction
		dataType: string
		displayFolder: Coal
		lineageTag: 6a5ac866-81dd-4f27-8565-d02db7527924
		summarizeBy: none
		sourceColumn: Coal_Liquefaction

		annotation SummarizationSetBy = Automatic

	column SPOT_MID_RATE
		dataType: double
		displayFolder: Revenue
		lineageTag: 7e5868f1-1e84-47ab-8bb9-b9456ad3d7ce
		summarizeBy: sum
		sourceColumn: SPOT_MID_RATE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Renewable_Energy_Revenue_USD_mn
		dataType: double
		displayFolder: Renewables
		lineageTag: 20a04002-499f-4caa-9ead-5871860a7fdb
		summarizeBy: sum
		sourceColumn: Renewable_Energy_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fossil_Fuel_Energy_Revenue_USD_mn
		dataType: double
		displayFolder: Fossil Fuel
		lineageTag: 6afad51b-09d6-483f-b49c-a0364fd3a72a
		summarizeBy: sum
		sourceColumn: Fossil_Fuel_Energy_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Renewable_Energy_Revenue_Percent
		dataType: double
		displayFolder: Renewables
		lineageTag: 2b7f808c-f56f-4b3f-ae91-b043ce9a8df3
		summarizeBy: sum
		sourceColumn: Renewable_Energy_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fossil_Fuel_Energy_Revenue_Percent
		dataType: double
		displayFolder: Fossil Fuel
		lineageTag: 58513770-9915-4fd0-9530-58a15f408756
		summarizeBy: sum
		sourceColumn: Fossil_Fuel_Energy_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Energy_Revenue_USD_mn
		dataType: double
		displayFolder: Other
		lineageTag: d655635d-d6ce-4e0b-a27e-edf32a893619
		summarizeBy: sum
		sourceColumn: Other_Energy_Revenue_USD_mn

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Other_Energy_Revenue_Percent
		dataType: double
		displayFolder: Other
		lineageTag: ba5d1a26-9f38-4814-bc9e-b63fc034fda8
		summarizeBy: sum
		sourceColumn: Other_Energy_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Extractives_Revenue_Exposure_Percent
		dataType: double
		lineageTag: 04ac9434-0c60-4890-8faf-75169cf97316
		summarizeBy: sum
		sourceColumn: Extractives_Revenue_Exposure_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Energy_Revenue_Percent
		dataType: double
		lineageTag: 7df2634f-3610-40fc-a049-96527703e0b7
		summarizeBy: sum
		sourceColumn: Total_Energy_Revenue_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Renewable_Engery_Share_Percent
		dataType: double
		displayFolder: Renewables
		lineageTag: 53f14ba0-36ac-4331-99d5-bced434527ed
		summarizeBy: sum
		sourceColumn: Renewable_Engery_Share_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fossil_Fuel_Engery_Share_Percent
		dataType: double
		displayFolder: Fossil Fuel
		lineageTag: 7ea7a3e6-25b7-4c84-ad91-8ff312fab9a3
		summarizeBy: sum
		sourceColumn: Fossil_Fuel_Engery_Share_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Revenue_AUD_mn = DIVIDE( 'ESG Trucost Climate'[Revenue_USD_mn], 'ESG Trucost Climate'[SPOT_MID_RATE] )
		displayFolder: Revenue
		lineageTag: d883632e-c0ae-4f51-9954-963676fd4b46
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TCUID_Date_Key
		dataType: string
		lineageTag: d90ef83d-3f6a-4113-a270-cd9dd3c7aa64
		summarizeBy: none
		sourceColumn: TCUID_Date_Key

		annotation SummarizationSetBy = Automatic

	column TCUID
		dataType: int64
		formatString: 0
		lineageTag: dc671f5a-fd50-43a2-b171-2185c27a51e6
		summarizeBy: count
		sourceColumn: TCUID

		annotation SummarizationSetBy = Automatic

	column Date_Value
		dataType: dateTime
		formatString: General Date
		lineageTag: 2c69b84a-ac8a-40e3-a8ae-67fc5a5787fc
		summarizeBy: none
		sourceColumn: Date_Value

		variation Variation
			isDefault
			relationship: 5fe3f1f6-ea23-4275-9152-737ac8ff79ae
			defaultHierarchy: LocalDateTable_fe2e1bc4-0a2e-4a0c-96c2-41d1ab28d903.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Effective_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1e265493-11af-48d7-aa7a-20ff2669f295
		summarizeBy: none
		sourceColumn: Effective_Date

		variation Variation
			isDefault
			relationship: a913ae43-d6dd-4a69-a03b-0ade5473ad09
			defaultHierarchy: LocalDateTable_954a6b9e-e977-4847-b6a0-245d08caab61.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Financial_Year
		dataType: string
		lineageTag: 008ba1df-128b-4b79-be3e-8cf967e04dc3
		summarizeBy: none
		sourceColumn: Financial_Year

		annotation SummarizationSetBy = Automatic

	column Effective_Date_Start
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9e398cd9-f779-4298-be6b-5b4c311d1c0c
		summarizeBy: none
		sourceColumn: Effective_Date_Start

		variation Variation
			isDefault
			relationship: 92a884f9-4bc4-4ec9-ad1f-3e81036c9f9f
			defaultHierarchy: LocalDateTable_79838638-6d79-4497-869b-b3c7d1f8b362.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Accounting_Year_End
		dataType: dateTime
		formatString: Long Date
		lineageTag: 955c3528-287c-42cd-8c9a-3edc620bd3b3
		summarizeBy: none
		sourceColumn: Accounting_Year_End

		variation Variation
			isDefault
			relationship: 8fe93827-6adb-4be9-864c-6fed0b76833e
			defaultHierarchy: LocalDateTable_ab6331b5-e9d5-4817-beb9-8f0af9ccd6fb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Min_FX_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: e137a3c6-61a7-4cbd-9485-2a4fd5fed87f
		summarizeBy: none
		sourceColumn: Min_FX_DATE

		variation Variation
			isDefault
			relationship: d3b51379-d815-45dc-88a3-bdbeaee1ad05
			defaultHierarchy: LocalDateTable_8a5da822-0b9d-44be-ba3d-1765424e3f02.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Max_FX_Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1896458b-56c1-48c8-8c6d-e876ae093b6a
		summarizeBy: none
		sourceColumn: Max_FX_Date

		variation Variation
			isDefault
			relationship: b40e74c6-f12d-4b9c-a568-eae7074474cb
			defaultHierarchy: LocalDateTable_b4e96276-f9c7-4956-848e-a5048c3375f7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column sk_date
		dataType: double
		lineageTag: bbb61aac-4e86-40ae-ba54-62307ea59294
		summarizeBy: sum
		sourceColumn: sk_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Absolute_GHG_Scope_3_Upstream_Total
		dataType: double
		lineageTag: 72800ad0-9d1c-4cda-80f4-cbf3b30e1162
		summarizeBy: sum
		sourceColumn: Absolute_GHG_Scope_3_Upstream_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Absolute_GHG_Scope_3_Downstream_Total
		dataType: double
		lineageTag: f0cd957a-17b9-41ae-bf66-6f159cc8c855
		summarizeBy: sum
		sourceColumn: Absolute_GHG_Scope_3_Downstream_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Scope_3_GHG_Upstream_Total_Disclosure
		dataType: string
		lineageTag: ead75a58-bb76-4cdd-b70c-0039ca0387e0
		summarizeBy: none
		sourceColumn: Scope_3_GHG_Upstream_Total_Disclosure

		annotation SummarizationSetBy = Automatic

	column Scope_3_GHG_Downstream_Total_Disclosure
		dataType: string
		lineageTag: 85620e2b-2a7f-4c9a-a42b-b375545ab5c1
		summarizeBy: none
		sourceColumn: Scope_3_GHG_Downstream_Total_Disclosure

		annotation SummarizationSetBy = Automatic

	column Intensity_GHG_Scope_3_Upstream
		dataType: double
		lineageTag: 7e490bd9-ec45-42e1-a6aa-ee33e5d01b0c
		summarizeBy: sum
		sourceColumn: Intensity_GHG_Scope_3_Upstream

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Intensity_GHG_Scope_3_Downstream_Total
		dataType: double
		lineageTag: 29cd13ae-58d6-469d-ba14-0406ec94a975
		summarizeBy: sum
		sourceColumn: Intensity_GHG_Scope_3_Downstream_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Scope_1_2_PCAF_Financed_GHG_Data_Quality
		dataType: string
		lineageTag: 0b9cb3a7-bf3a-46a6-9a82-a870a1d33dba
		summarizeBy: none
		sourceColumn: Scope_1_2_PCAF_Financed_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	column Scope_1_2_PCAF_Insured_GHG_Data_Quality
		dataType: string
		lineageTag: 31d1f885-0bbf-4b13-ba78-11f6c6aba54d
		summarizeBy: none
		sourceColumn: Scope_1_2_PCAF_Insured_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	column Scope_3_Upstream_PCAF_Financed_GHG_Data_Quality
		dataType: string
		lineageTag: a7b47431-5146-4e2a-bd48-3596151a88c8
		summarizeBy: none
		sourceColumn: Scope_3_Upstream_PCAF_Financed_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	column Scope_3_Upstream_PCAF_Insured_GHG_Data_Quality
		dataType: string
		lineageTag: e1eebbe7-ba90-4edf-86bf-7331ad433d0e
		summarizeBy: none
		sourceColumn: Scope_3_Upstream_PCAF_Insured_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	column Scope_3_Downstream_PCAF_Financed_GHG_Data_Quality
		dataType: string
		lineageTag: 6025cf1a-185c-49b8-84ac-d8366271dd07
		summarizeBy: none
		sourceColumn: Scope_3_Downstream_PCAF_Financed_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	column Scope_3_Downstream_PCAF_Insured_GHG_Data_Quality
		dataType: string
		lineageTag: 0475fe26-1dff-4450-b288-f8fd46c1795d
		summarizeBy: none
		sourceColumn: Scope_3_Downstream_PCAF_Insured_GHG_Data_Quality

		annotation SummarizationSetBy = Automatic

	partition 'ESG Trucost Climate-9a96de24-c9dc-4695-b67b-aa672ce40795' = m
		mode: import
		queryGroup: Trucost
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=p_databricks_catalog,Kind="Database"]}[Data],
				    climate_Schema = hive_metastore_Database{[Name=p_trucost_database, Kind="Schema"]}[Data],
				    semantic_trucost_carbon_v1_Table = climate_Schema{[Name="semantic_trucost_carbon_v1",Kind="Table"]}[Data],
				    FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				      semantic_trucost_carbon_v1_Table, 
				      100
				     )
				 else 
				   
				     semantic_trucost_carbon_v1_Table
				in
				  FilterLogic
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

