table 'ESG Exclusions'
	lineageTag: 5ed02618-f286-441b-8356-325b09e0a429

	column 'Data Source'
		dataType: string
		lineageTag: 4dec631e-821a-4b3b-bde9-79239e1dec79
		summarizeBy: none
		sourceColumn: Data Source

		annotation SummarizationSetBy = Automatic

	column Identifier
		dataType: string
		lineageTag: 79b59feb-f87b-4eaa-a4c0-648bc05581b8
		summarizeBy: none
		sourceColumn: Identifier

		annotation SummarizationSetBy = Automatic

	column 'Entity Name'
		dataType: string
		lineageTag: 35443a4b-7fad-4874-81df-75103ea834f9
		summarizeBy: none
		sourceColumn: Entity Name

		annotation SummarizationSetBy = Automatic

	column 'Weapon Type'
		dataType: string
		lineageTag: cff70ddf-975b-4b7a-8621-c64afc1f6e32
		summarizeBy: none
		sourceColumn: Weapon Type

		annotation SummarizationSetBy = Automatic

	column 'Main Product Type'
		dataType: string
		lineageTag: 45ae8d69-da51-4d57-a685-ec8956112468
		summarizeBy: none
		sourceColumn: Main Product Type

		annotation SummarizationSetBy = Automatic

	column 'Main Activity Type'
		dataType: string
		lineageTag: 685d44e5-f882-4bd6-b3da-7abc65f07085
		summarizeBy: none
		sourceColumn: Main Activity Type

		annotation SummarizationSetBy = Automatic

	column 'Majority Ownership'
		dataType: string
		lineageTag: fce064f3-699c-4d90-86bd-d2c00b844f45
		summarizeBy: none
		sourceColumn: Majority Ownership

		annotation SummarizationSetBy = Automatic

	column 'Production or Research Activity Flag'
		dataType: string
		lineageTag: e7cc2c68-7951-4c04-8347-873a698ea722
		summarizeBy: none
		sourceColumn: Production or Research Activity Flag

		annotation SummarizationSetBy = Automatic

	column 'Valid From'
		dataType: dateTime
		formatString: Short Date
		lineageTag: f088cec3-9807-4206-9fbd-b3427481a1ef
		summarizeBy: none
		sourceColumn: Valid From

		variation Variation
			isDefault
			relationship: 4cc86f04-6ff4-43b0-bce6-b6aff5fe7554
			defaultHierarchy: LocalDateTable_96b6d54c-8508-4e49-9375-7df1b49de6df.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Valid To'
		dataType: dateTime
		formatString: Short Date
		lineageTag: dbd4e8cc-87e7-48b7-afc5-51ea291dd0be
		summarizeBy: none
		sourceColumn: Valid To

		variation Variation
			isDefault
			relationship: 6ee5901d-bdff-4967-b3ad-f56d879d2422
			defaultHierarchy: LocalDateTable_22578b22-4154-4937-86c3-cc66da303585.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Summary of Involvement'
		dataType: string
		lineageTag: 3ae219cb-f017-411d-95c8-33f112b77cc4
		summarizeBy: none
		sourceColumn: Summary of Involvement

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 3e3a6b3d-a348-4374-a505-9cf5e775bcdd
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Evidence of Activity'
		dataType: string
		lineageTag: 67b472bb-8dd3-4ec7-890e-9866935ed8a3
		summarizeBy: none
		sourceColumn: Evidence of Activity

		annotation SummarizationSetBy = Automatic

	column 'Is Current'
		dataType: string
		lineageTag: 21d4b25a-1d6a-474c-8cd1-a4bec0c8cdfc
		summarizeBy: none
		sourceColumn: Is Current

		annotation SummarizationSetBy = Automatic

	column 'Is Above Threshold'
		dataType: string
		lineageTag: e7889dd2-b594-41aa-9d85-dff99418bc5e
		summarizeBy: none
		sourceColumn: Is Above Threshold

		annotation SummarizationSetBy = Automatic

	column SK_Asset
		dataType: string
		lineageTag: ef5fb9fc-8cf8-4470-bc9d-5421025d24c2
		summarizeBy: none
		sourceColumn: SK_Asset

		annotation SummarizationSetBy = Automatic

	column Ownership_Relationship
		dataType: string
		lineageTag: 8cb3c02e-63fa-44b5-af67-e41a4eacbef6
		summarizeBy: none
		sourceColumn: Ownership_Relationship

		annotation SummarizationSetBy = Automatic

	column Dedicated_vs_Non_dedicated
		dataType: string
		lineageTag: a428269f-1c02-40c2-b1a4-9e66540e05ea
		summarizeBy: none
		sourceColumn: Dedicated_vs_Non_dedicated

		annotation SummarizationSetBy = Automatic

	column Key_vs_Non_key
		dataType: string
		lineageTag: 0eb68cc1-9ca7-4c45-a193-79382c21386c
		summarizeBy: none
		sourceColumn: Key_vs_Non_key

		annotation SummarizationSetBy = Automatic

	column Ownership_Related_CompanyName
		dataType: string
		lineageTag: e755f492-1764-4c05-b2e9-1bdc62962c0a
		summarizeBy: none
		sourceColumn: Ownership_Related_CompanyName

		annotation SummarizationSetBy = Automatic

	column Category_of_Involvement
		dataType: string
		lineageTag: 5d1fe0a0-36dc-420b-8261-a3abdb9829ec
		summarizeBy: none
		sourceColumn: Category_of_Involvement

		annotation SummarizationSetBy = Automatic

	column Profile_Text_shareholder
		dataType: string
		lineageTag: 4a2089c6-aca6-464b-aecf-bf637fb43421
		summarizeBy: none
		sourceColumn: Profile_Text_shareholder

		annotation SummarizationSetBy = Automatic

	column Involvement_Shareholder
		dataType: string
		lineageTag: 96512b1c-bdae-4a58-9d94-b06a24c3c299
		summarizeBy: none
		sourceColumn: Involvement_Shareholder

		annotation SummarizationSetBy = Automatic

	column Evidence_Grade_Shareholder
		dataType: string
		lineageTag: 1565b987-89ad-4915-b0b8-311e8780327f
		summarizeBy: none
		sourceColumn: Evidence_Grade_Shareholder

		annotation SummarizationSetBy = Automatic

	column Shareholding_Pct
		dataType: string
		lineageTag: 80f0ce04-4bd5-4c50-bd6d-ca1235137aa2
		summarizeBy: none
		sourceColumn: Shareholding_Pct

		annotation SummarizationSetBy = Automatic

	column Evidence_Grade
		dataType: string
		lineageTag: 44691701-ef70-44f0-b277-b8b091e8145c
		summarizeBy: none
		sourceColumn: Evidence_Grade

		annotation SummarizationSetBy = Automatic

	column Prev_Evidence_Grade
		dataType: string
		lineageTag: 4c4b1675-357e-4a3e-87df-8bfd467922d1
		summarizeBy: none
		sourceColumn: Prev_Evidence_Grade

		annotation SummarizationSetBy = Automatic

	column Prev_Evidence_Of_Activity
		dataType: string
		lineageTag: d0ac748f-0ab0-4ee5-912e-28091184fea7
		summarizeBy: none
		sourceColumn: Prev_Evidence_Of_Activity

		annotation SummarizationSetBy = Automatic

	column ISIN
		dataType: string
		lineageTag: d1be13ac-d279-463f-844d-d911258fc494
		summarizeBy: none
		sourceColumn: ISIN

		annotation SummarizationSetBy = Automatic

	partition 'ESG Exclusions' = m
		mode: import
		queryGroup: Sustainalytics
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=p_databricks_catalog,Kind="Database"]}[Data],
				    sustainalytics_Schema = hive_metastore_Database{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_esg_exclusions_weapon_v1_Table = sustainalytics_Schema{[Name="semantic_esg_exclusions_weapon_v1",Kind="Table"]}[Data],
				    FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				      semantic_esg_exclusions_weapon_v1_Table, 
				      100
				     )
				 else 
				     semantic_esg_exclusions_weapon_v1_Table,
				    #"Renamed Columns" = Table.RenameColumns(FilterLogic,{{"Entity_Name", "Entity Name"}, {"Weapon_Type", "Weapon Type"}, {"Main_Product_Type", "Main Product Type"}, {"Main_Activity_Type", "Main Activity Type"}, {"Majority_Ownership", "Majority Ownership"}, {"Production_or_Research_Activity_Flag", "Production or Research Activity Flag"}, {"Valid_From", "Valid From"}, {"Valid_To", "Valid To"}, {"Summary_of_Involvement", "Summary of Involvement"}, {"Evidence_of_Activity", "Evidence of Activity"}, {"Is_Current", "Is Current"}, {"Is_Above_Threshold", "Is Above Threshold"}, {"DataSource", "Data Source"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

