table 'ESG Weapons'
	lineageTag: 31661fdc-2a98-4aca-8f23-209380360b41

	column 'Entity Name'
		dataType: string
		lineageTag: 5e191a9d-fabf-4d9d-8aed-79eeedb8b45c
		summarizeBy: none
		sourceColumn: Entity Name

		annotation SummarizationSetBy = Automatic

	column 'Weapon Type'
		dataType: string
		lineageTag: 79d2127a-cb2c-434b-9778-404beaf02508
		summarizeBy: none
		sourceColumn: Weapon Type

		annotation SummarizationSetBy = Automatic

	column 'Evidence of Activity'
		dataType: string
		lineageTag: bc860b09-b62e-44fb-8e3f-878fb789f181
		summarizeBy: none
		sourceColumn: Evidence of Activity

		annotation SummarizationSetBy = Automatic

	column 'Category of Involvement'
		dataType: string
		lineageTag: d1b897f2-ac35-452c-b4ae-c571f0acf5ca
		summarizeBy: none
		sourceColumn: Category of Involvement

		annotation SummarizationSetBy = Automatic

	column 'Summary of Involvement'
		dataType: string
		lineageTag: 454a2558-15f7-4d65-9c03-de121ab22d91
		summarizeBy: none
		sourceColumn: Summary of Involvement

		annotation SummarizationSetBy = Automatic

	column 'Ownership Relationship'
		dataType: string
		lineageTag: c4f1f93d-a54f-42e0-a564-a374ebb5c0be
		summarizeBy: none
		sourceColumn: Ownership Relationship

		annotation SummarizationSetBy = Automatic

	column 'Majority Ownership'
		dataType: string
		lineageTag: c8935587-497d-4fcd-aafe-057d51eeefec
		summarizeBy: none
		sourceColumn: Majority Ownership

		annotation SummarizationSetBy = Automatic

	column 'Ownership Related Company Name'
		dataType: string
		lineageTag: 331b6bc2-d505-492c-aef9-6fe8395f2f7e
		summarizeBy: none
		sourceColumn: Ownership Related Company Name

		annotation SummarizationSetBy = Automatic

	column 'Main Product Type'
		dataType: string
		lineageTag: b2ee94a3-6ad8-4f2d-a801-7585714ad168
		summarizeBy: none
		sourceColumn: Main Product Type

		annotation SummarizationSetBy = Automatic

	column 'Main Activity Type'
		dataType: string
		lineageTag: 7eb926c6-ccfa-4ad3-a487-36677a979662
		summarizeBy: none
		sourceColumn: Main Activity Type

		annotation SummarizationSetBy = Automatic

	column 'Dedicated vs Non-dedicated'
		dataType: string
		lineageTag: e2e33e1d-2497-4426-b79f-51633cceb66a
		summarizeBy: none
		sourceColumn: Dedicated vs Non-dedicated

		annotation SummarizationSetBy = Automatic

	column 'Key vs Non-key'
		dataType: string
		lineageTag: dc176b68-d4cf-4b9a-9679-2f04688d3da8
		summarizeBy: none
		sourceColumn: Key vs Non-key

		annotation SummarizationSetBy = Automatic

	column 'Valid From'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 64da637b-2c26-45bb-871f-a73293838a2c
		summarizeBy: none
		sourceColumn: Valid From

		variation Variation
			isDefault
			relationship: 3e13d8a2-2e7a-47fa-877d-51e8aa262a0d
			defaultHierarchy: LocalDateTable_9c4edb94-b962-40e6-b365-825eb24c1c2f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Valid To'
		dataType: dateTime
		formatString: Short Date
		lineageTag: b1c63137-794e-4277-8612-285e04729c1a
		summarizeBy: none
		sourceColumn: Valid To

		variation Variation
			isDefault
			relationship: 8767b407-573a-4ddc-9498-088b5fa67a62
			defaultHierarchy: LocalDateTable_9bbb6d9a-25f6-4c43-81a7-a7f7089e1752.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Source'
		dataType: string
		lineageTag: d13f270d-1f85-450f-bcdb-3abd98a1b13a
		summarizeBy: none
		sourceColumn: Data Source

		annotation SummarizationSetBy = Automatic

	column Identifier
		dataType: string
		lineageTag: fd79668c-637d-4f54-9d33-dcfe8225cd96
		summarizeBy: none
		sourceColumn: Identifier

		annotation SummarizationSetBy = Automatic

	column 'SK Asset'
		dataType: string
		lineageTag: 8128cb97-9ec9-44cb-8116-481f06aeb36b
		summarizeBy: none
		sourceColumn: SK Asset

		annotation SummarizationSetBy = Automatic

	column 'Production or Research Activity Flag'
		dataType: string
		lineageTag: 59dda312-6a38-425f-a320-1d62f96d65c0
		summarizeBy: none
		sourceColumn: Production or Research Activity Flag

		annotation SummarizationSetBy = Automatic

	column 'Old Score'
		dataType: string
		lineageTag: 64183c18-915d-4d9d-8e5b-72c3995aff8b
		summarizeBy: none
		sourceColumn: Old Score

		annotation SummarizationSetBy = Automatic

	column Score
		dataType: string
		lineageTag: df476e8b-5896-46e9-995f-a56cb4121d1a
		summarizeBy: none
		sourceColumn: Score

		annotation SummarizationSetBy = Automatic

	column 'Score Change'
		dataType: string
		lineageTag: 2965584b-5085-4e62-8475-4339400ee83e
		summarizeBy: none
		sourceColumn: Score Change

		annotation SummarizationSetBy = Automatic

	column 'Change Nature'
		dataType: string
		lineageTag: 8ec0c24b-9577-4dc2-a5d2-aaf3f378488f
		summarizeBy: none
		sourceColumn: Change Nature

		annotation SummarizationSetBy = Automatic

	column 'Profile Text Shareholder'
		dataType: string
		lineageTag: 5c907a1b-2fc8-4a70-a082-c84a35e430e2
		summarizeBy: none
		sourceColumn: Profile Text Shareholder

		annotation SummarizationSetBy = Automatic

	column 'Involvement Shareholder'
		dataType: string
		lineageTag: a2635f9a-8f6c-4daa-9765-7dde215db3db
		summarizeBy: none
		sourceColumn: Involvement Shareholder

		annotation SummarizationSetBy = Automatic

	column 'Evidence Grade Shareholder'
		dataType: string
		lineageTag: e70f754c-7229-432b-a423-e80424a53da8
		summarizeBy: none
		sourceColumn: Evidence Grade Shareholder

		annotation SummarizationSetBy = Automatic

	column 'Shareholding Pct'
		dataType: string
		lineageTag: 05c13b64-0bff-414c-bf26-19c85582c1c8
		summarizeBy: none
		sourceColumn: Shareholding Pct

		annotation SummarizationSetBy = Automatic

	column 'Evidence Grade'
		dataType: string
		lineageTag: 1af5f54f-6743-47bf-a393-ed90177a971d
		summarizeBy: none
		sourceColumn: Evidence Grade

		annotation SummarizationSetBy = Automatic

	column 'Previous Evidence Grade'
		dataType: string
		lineageTag: 1a4e6e15-4a5f-4267-bb3e-217b0f5444b0
		summarizeBy: none
		sourceColumn: Previous Evidence Grade

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 0cf64016-b6df-4aa7-a99c-3cb4b4c65c47
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Prev_Evidence_Of_Activity
		dataType: string
		lineageTag: aae72fd7-0d45-4842-a004-d6ebe02eec6b
		summarizeBy: none
		sourceColumn: Prev_Evidence_Of_Activity

		annotation SummarizationSetBy = Automatic

	column 'Is Current'
		dataType: string
		lineageTag: 08a90b7a-9be4-42dc-87b1-d4f8cb5697df
		summarizeBy: none
		sourceColumn: Is Current

		annotation SummarizationSetBy = Automatic

	column 'Is Above Threshold'
		dataType: string
		lineageTag: 9683e152-6603-47ba-9b5a-6318222eeaa7
		summarizeBy: none
		sourceColumn: Is Above Threshold

		annotation SummarizationSetBy = Automatic

	partition 'ESG Weapons' = m
		mode: import
		queryGroup: Sustainalytics
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=p_databricks_catalog,Kind="Database"]}[Data],
				    sustainalytics_Schema = hive_metastore_Database{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_esg_sustainalytics_weapon_v1_Table = sustainalytics_Schema{[Name="semantic_esg_weapon_v1",Kind="Table"]}[Data],
				    FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				      semantic_esg_sustainalytics_weapon_v1_Table, 
				      100
				     )
				 else 
				     semantic_esg_sustainalytics_weapon_v1_Table,
				    #"Renamed Columns" = Table.RenameColumns(FilterLogic,{{"SK_Asset", "SK Asset"}, {"Entity_Name", "Entity Name"}, {"Weapon_Type", "Weapon Type"}, {"Main_Product_Type", "Main Product Type"}, {"Main_Activity_Type", "Main Activity Type"}, {"Ownership_Relationship", "Ownership Relationship"}, {"Evidence_of_Activity", "Evidence of Activity"}, {"Dedicated_vs_Non_dedicated", "Dedicated vs Non-dedicated"}, {"Key_vs_Non_key", "Key vs Non-key"}, {"Ownership_Related_CompanyName", "Ownership Related Company Name"}, {"Category_of_Involvement", "Category of Involvement"}, {"Majority_Ownership", "Majority Ownership"}, {"Production_or_Research_Activity_Flag", "Production or Research Activity Flag"}, {"Valid_From", "Valid From"}, {"Valid_To", "Valid To"}, {"Old_Score", "Old Score"}, {"Score_Change", "Score Change"}, {"Change_Nature", "Change Nature"}, {"Summary_of_Involvement", "Summary of Involvement"}, {"Profile_Text_shareholder", "Profile Text Shareholder"}, {"Involvement_Shareholder", "Involvement Shareholder"}, {"Evidence_Grade_Shareholder", "Evidence Grade Shareholder"}, {"Shareholding_Pct", "Shareholding Pct"}, {"Evidence_Grade", "Evidence Grade"}, {"Prev_Evidence_Grade", "Previous Evidence Grade"}, {"DataSource", "Data Source"}, {"Is_Current", "Is Current"}, {"Is_Above_Threshold", "Is Above Threshold"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

