table 'ESG Events'
	lineageTag: c8064406-ceed-4eff-a48c-11f741c7442c

	measure 'Unique Records' = ```
			calculate( distinctcount('ESG Events'[Entity_Id]), 'ESG Events'[Entity_Id] <> BLANK())
			
			
			```
		formatString: 0
		lineageTag: 40b626e9-4bbb-4fe7-b8e9-197bd8800ed7

	measure 'Score Measure' = MAX('ESG Events'[Score])
		displayFolder: Score
		lineageTag: af937c0e-7f62-4ed9-9749-bb108b7ca59d

	measure 'Latest Score (GSS Num)' = ```
			
			// CALCULATE( MAX( 'ESG Events'[Score (GSS Num)] ), 
			// LASTDATE( 'ESG Events'[Valid_From] )
			// )
			LASTNONBLANKVALUE('ESG Events'[Valid_From], MAX('ESG Events'[Score (GSS Num)]))
			
			```
		formatString: 0
		displayFolder: Score
		lineageTag: 135c6e74-7c0f-49b7-a630-076a786c7245

	column Entity_Id
		dataType: int64
		formatString: 0
		lineageTag: f4335a04-248d-4eeb-900f-9333e11f11ab
		summarizeBy: count
		sourceColumn: Entity_Id

		annotation SummarizationSetBy = Automatic

	/// Sustainalytics Controversy Category 1
	column Category_Name
		dataType: string
		lineageTag: 629b799d-1092-4cb4-b8a9-b31045d612c5
		summarizeBy: none
		sourceColumn: Category_Name

		annotation SummarizationSetBy = Automatic

	column Alert_Category
		dataType: int64
		formatString: 0
		lineageTag: 205f833f-582b-4f7e-b2ff-2fae0b1f58e3
		summarizeBy: sum
		sourceColumn: Alert_Category

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: string
		lineageTag: 687cdb77-287f-4c63-866d-405e23f0bef2
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column 'Score Change Arrows' =
			
			CONCATENATE('ESG Events'[Score GSS Number Dot],CONCATENATE(" ", CONCATENATE(
			IF('ESG Events'[Change_Type] ="Outlook",'ESG Events'[Score Change Outlook],
			IF('ESG Events'[Change_Type] ="Weapon Type",'ESG Events'[Score Change Weapons],
			IF('ESG Events'[Change_Type] ="Controversy",'ESG Events'[Score Change Controversy],
			IF('ESG Events'[Change_Type] ="GSS",'ESG Events'[Score Change GSS])))),
			(IF('ESG Events'[Change_Type] ="Weapon Type","",
			if('ESG Events'[Old_Score] ="","",CONCATENATE(" From: ",CONCATENATE('ESG Events'[Old_Score],""))))))))
		displayFolder: Score
		lineageTag: 6101bfe2-003e-4bd1-a7a1-76b2704efa8d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Change' = 'ESG Events'[Change_Nature]
		displayFolder: Score
		lineageTag: 1a425304-76b1-41f6-b038-f23b924b841b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Title' = if('ESG Events'[Change_Type] ="Controversy", CONCATENATE(" (Score: ",CONCATENATE('ESG Events'[Score],")")),'ESG Events'[Score])
		displayFolder: Score
		lineageTag: 607d1a5e-c1f3-406f-9f6d-5c55f60b5415
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Change_Type
		dataType: string
		lineageTag: 8d8e6686-1ffd-43c5-97c9-8c5c138ee077
		summarizeBy: none
		sourceColumn: Change_Type

		annotation SummarizationSetBy = Automatic

	column Valid_From
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0b900204-86aa-4451-8fe2-78af9b51b0c9
		summarizeBy: none
		sourceColumn: Valid_From

		variation Variation
			isDefault
			relationship: 0400e4f6-d208-47bf-83f3-9d530fe7c637
			defaultHierarchy: LocalDateTable_f4e39f97-090d-4007-8377-f3f7f33ecc0a.'Date Hierarchy'

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Valid_To
		dataType: string
		lineageTag: 304b3cb6-d32f-420e-865f-ae655fa844fc
		summarizeBy: none
		sourceColumn: Valid_To

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column Old_Score
		dataType: string
		displayFolder: Score
		lineageTag: a24166d8-e9f9-46f1-ad5e-87c01b94f9cd
		summarizeBy: none
		sourceColumn: Old_Score

		annotation SummarizationSetBy = Automatic

	column Score
		dataType: string
		displayFolder: Score
		lineageTag: b2ffb290-f639-404e-a01e-fcb99045ca49
		summarizeBy: none
		sourceColumn: Score

		annotation SummarizationSetBy = Automatic

	column Old_Summary
		dataType: string
		lineageTag: 90c04d3f-a89f-42ec-b9f9-dd7bef5139e3
		summarizeBy: none
		sourceColumn: Old_Summary

		annotation SummarizationSetBy = Automatic

	column Old_Justification
		dataType: string
		lineageTag: 3febbc1a-25d9-498c-869f-0502d29a7c7c
		summarizeBy: none
		sourceColumn: Old_Justification

		annotation SummarizationSetBy = Automatic

	/// Rationale from Sustainalytics on Controversy Score 
	column Justification
		dataType: string
		lineageTag: 4cf4fced-9ca0-47d6-add1-fcbff996c9d5
		summarizeBy: none
		sourceColumn: Justification

		annotation SummarizationSetBy = Automatic

	column 'Score Up/Down Arrows' = (IF([Score]>[Old_Score],UNICHAR(9650),UNICHAR(9660)))
		displayFolder: Score
		lineageTag: 3354daf9-7f4c-4193-b04e-5457f6a53918
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// ESG Category (E = Environmental ; S = Social; G = Governance)
	column ESG_Category
		dataType: string
		lineageTag: db352bbb-4025-48be-89d8-b1eb67f97615
		summarizeBy: none
		sourceColumn: ESG_Category

		annotation SummarizationSetBy = Automatic

	column Vendor_Topic
		dataType: string
		lineageTag: 5be086e3-34f2-4373-8729-dd727bcdb881
		summarizeBy: none
		sourceColumn: Vendor_Topic

		annotation SummarizationSetBy = Automatic

	/// FF Category (e.g. Climate/Biodiversity/Weapon)
	column FF_Topic
		dataType: string
		lineageTag: 284930a0-0289-47f2-914b-c15bc9cc4d0a
		summarizeBy: none
		sourceColumn: FF_Topic

		annotation SummarizationSetBy = Automatic

	/// Controversy Category match to SASB Framework
	column SASB_Framework
		dataType: string
		lineageTag: 040c01f0-4a17-41b4-95a9-89a199f127c7
		summarizeBy: none
		sourceColumn: SASB_Framework

		annotation SummarizationSetBy = Automatic

	column Change_Nature
		dataType: string
		lineageTag: 744a0dae-57b5-4111-a5af-24f36c716d00
		summarizeBy: none
		sourceColumn: Change_Nature

		annotation SummarizationSetBy = Automatic

	column 'Score Change Controversy' =
			
			IF([Score]>[Old_Score],UNICHAR(9650), IF([Score]=[Old_Score], UNICHAR(9664), UNICHAR(9660)))
		displayFolder: Score
		lineageTag: b407c424-c728-4c7b-a565-91c782270be9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Change Outlook' = ```
			IF(AND('ESG Events'[Score] = "Positive",'ESG Events'[Old_Score]="Negative"),UNICHAR(9650),
			IF(AND('ESG Events'[Score] = "Positive",'ESG Events'[Old_Score]="Neutral"),UNICHAR(9650),
			IF(AND('ESG Events'[Score] = "Positive",'ESG Events'[Old_Score]="Positive"),UNICHAR(9664),
			IF(AND('ESG Events'[Score] = "Negative",'ESG Events'[Old_Score]="Positive"),UNICHAR(9660),
			IF(AND('ESG Events'[Score] = "Negative",'ESG Events'[Old_Score]="Neutral"),UNICHAR(9660),
			IF(AND('ESG Events'[Score] = "Negative",'ESG Events'[Old_Score]="Negative"),UNICHAR(9664),
			IF(AND('ESG Events'[Score] = "Neutral",'ESG Events'[Old_Score]="Positive"),UNICHAR(9660),
			IF(AND('ESG Events'[Score] = "Neutral",'ESG Events'[Old_Score]="Negative"),UNICHAR(9650),
			IF(AND('ESG Events'[Score] = "Neutral",'ESG Events'[Old_Score]="Neutral"),UNICHAR(9664)))))))))) 
			```
		displayFolder: Score
		lineageTag: 400d7365-e701-4c54-bb50-a2b98d3356e1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Change GSS' = ```
			
			
			IF(AND('ESG Events'[Score] = "Compliant",'ESG Events'[Old_Score]="Non-Compliant"),UNICHAR(9650),
			IF(AND('ESG Events'[Score] = "Compliant",'ESG Events'[Old_Score]="Watchlist"),UNICHAR(9650),
			IF(AND('ESG Events'[Score] = "Compliant",'ESG Events'[Old_Score]="Compliant"),UNICHAR(9664),
			IF(AND('ESG Events'[Score] = "Non-Compliant",'ESG Events'[Old_Score]="Compliant"),UNICHAR(9660),
			IF(AND('ESG Events'[Score] = "Non-Compliant",'ESG Events'[Old_Score]="Watchlist"),UNICHAR(9660),
			IF(AND('ESG Events'[Score] = "Non-Compliant",'ESG Events'[Old_Score]="Non-Compliant"),UNICHAR(9664),
			IF(AND('ESG Events'[Score] = "Watchlist",'ESG Events'[Old_Score]="Compliant"),UNICHAR(9660),
			IF(AND('ESG Events'[Score] = "Watchlist",'ESG Events'[Old_Score]="Non-Compliant"),UNICHAR(9650),
			IF(AND('ESG Events'[Score] = "Watchlist",'ESG Events'[Old_Score]="Watchlist"),UNICHAR(9664)))))))))) 
			
			```
		displayFolder: Score
		lineageTag: a34b2ec2-b1a6-41d3-a764-176964f40a73
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Int' = IF('ESG Events'[Change_Type]="Controversy",INT('ESG Events'[Score]),0)
		formatString: 0
		displayFolder: Score
		lineageTag: b5d1ec66-54ca-4ffa-bad2-dc7aec585ad6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Is_Current
		dataType: string
		lineageTag: 5769c004-3a8f-47fe-bb12-b4ea6e80c7f6
		summarizeBy: none
		sourceColumn: Is_Current

		annotation SummarizationSetBy = Automatic

	column 'GSS Score Num' = IF('ESG Events'[Score]="Compliant",1,IF('ESG Events'[Score]="Watchlist",0,if('ESG Events'[Score]="Not Compliant",-1,-2)))
		dataType: string
		displayFolder: Score
		lineageTag: 263f322b-d68d-4e94-bf37-952d17d27f6f
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Score (GSS Num)' = IF('ESG Events'[Change_Type]="GSS",'ESG Events'[GSS Score Num],if('ESG Events'[Change_Type]="Outlook",'ESG Events'[Outlook Score Num], IF('ESG Events'[Change_Type]="Weapon Type",'ESG Events'[Weapon Score Num], 'ESG Events'[Score])))
		dataType: int64
		formatString: 0
		displayFolder: Score
		lineageTag: 4dbd0234-acd0-4225-ac9e-0d5c1d7ca068
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	/// Sustainalytics Controversy Topic
	column Entity_Topic_Key
		dataType: string
		lineageTag: 307dca9e-6e16-4d90-9d96-649ccbb53394
		summarizeBy: none
		sourceColumn: Entity_Topic_Key

		annotation SummarizationSetBy = Automatic

	column 'Outlook Score Num' = IF('ESG Events'[Score]="Positive",1,IF('ESG Events'[Score]="Neutral",0,if('ESG Events'[Score]="Negative",-1,-2)))
		dataType: string
		displayFolder: Score
		lineageTag: 96f28cc4-3925-4231-b2a5-a20d3fdf40d5
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'GSS Font Colour Score Num' = IF('ESG Events'[Score]="Compliant",1,IF('ESG Events'[Score]="Watchlist",0,if('ESG Events'[Score]="Not Compliant",-1,-2)))
		formatString: 0
		displayFolder: Score
		lineageTag: 4520ff15-15a4-4c1b-9707-f573eca18d12
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Sustainalytics Controversy Category  2
	column Category_Name2
		dataType: string
		lineageTag: 18c5755e-05b1-4c76-9846-d7af9a8a0159
		summarizeBy: none
		sourceColumn: Category_Name2

		annotation SummarizationSetBy = Automatic

	/// Sustainalytics Controversy Category  3
	column Category_Name3
		dataType: string
		lineageTag: 9e132baa-7db8-413b-8da3-344939703aea
		summarizeBy: none
		sourceColumn: Category_Name3

		annotation SummarizationSetBy = Automatic

	column 'Table Status -  Num' = IF('ESG Events'[Score] = "Compliant",1,IF('ESG Events'[Score] = "Watchlist",0,IF('ESG Events'[Score] = "Non-Compliant",-1,9)))
		formatString: 0
		lineageTag: e8a539d9-06db-4814-add4-5d94e9772623
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Justification Tooltip' = if('ESG Events'[Change_Type] ="Controversy",'ESG Events'[Justification], IF('ESG Events'[Change_Type] = "Outlook", ('ESG Events'[Summary] & UNICHAR(10) & 'ESG Events'[Justification]),IF('ESG Events'[Change_Type] ="GSS", 'ESG Events'[Summary])))
		lineageTag: 022ef9fb-8444-4424-9d47-9e8180f4d20b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score GSS Table' = IF('ESG Events'[Score] ="Compliant","1. Compliant",IF('ESG Events'[Score] ="Non-Compliant","3. Non-Compliant",IF('ESG Events'[Score] ="Watchlist","2. Watchlist", 'ESG Events'[Score])))
		displayFolder: Score
		lineageTag: fd5ba529-2a68-4dc9-a3b6-a405e72e8805
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score GSS Number Dot' = ```
			
			 IF('ESG Events'[Score] ="Compliant","1. Compliant",
			IF('ESG Events'[Score] ="Non-Compliant","3. Non-Compliant",
			IF('ESG Events'[Score] ="Watchlist","2. Watchlist",
			
			IF('ESG Events'[Score] ="Involvement added","3. Involvement added",
			IF('ESG Events'[Score] ="Involvement updated","2. Involvement updated",
			IF('ESG Events'[Score] ="Involvement removed","1. Involvement removed",
			
			
			
			
			 'ESG Events'[Score]))))))
			```
		displayFolder: Score
		lineageTag: 25b59adf-1215-449b-8d1e-e55c553453c5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Score Change Weapons' =
			
			
			IF('ESG Events'[Score] = "Involvement removed",UNICHAR(9650),
			IF('ESG Events'[Score] = "Involvement added",UNICHAR(9660),
			IF('ESG Events'[Score] = "Involvement updated",UNICHAR(9664))
			))
		displayFolder: Score
		lineageTag: 0321a690-9fb4-4906-8ee5-a06eb7d47536
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Weapon Score Num' = IF('ESG Events'[Score]="Investment removed",1,IF('ESG Events'[Score]="Investment updated",0,if('ESG Events'[Score]="Investment added",-1,-2)))
		dataType: string
		displayFolder: Score
		lineageTag: 8eabe35f-434f-4293-b678-546d43954b3c
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Is_Deleted
		dataType: string
		lineageTag: 6fc5a0ba-b687-4721-a62f-75db8d3b59eb
		summarizeBy: none
		sourceColumn: Is_Deleted

		annotation SummarizationSetBy = Automatic

	partition 'ESG Events-d2a1ea28-67c4-4f96-af67-25fcefbf1fd5' = m
		mode: import
		queryGroup: Sustainalytics
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=p_databricks_catalog,Kind="Database"]}[Data],
				    sustainalytics_Schema = hive_metastore_Database{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_esg_sustainalytics_event_v1_Table = sustainalytics_Schema{[Name="semantic_esg_sustainalytics_event_v1",Kind="Table"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(semantic_esg_sustainalytics_event_v1_Table, each true)
				    ,  FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				      #"Filtered Rows", 
				      100
				     )
				 else 
				     #"Filtered Rows" 
				     in
				  FilterLogic
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

