table 'ESG Controversy Snapshot'
	lineageTag: 294b2ac8-3b1a-4410-a4a4-9268db7812ef

	column Snapshot_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 006b33f3-f79b-4654-a361-343a4af8c8ba
		summarizeBy: none
		sourceColumn: Snapshot_Date

		variation Variation
			isDefault
			relationship: 804fc887-e181-4482-ab40-91798047699d
			defaultHierarchy: LocalDateTable_4708650e-207d-43b0-aec2-36e7ff805b63.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Entity_Id
		dataType: int64
		formatString: 0
		lineageTag: a4a1c35e-6a16-4708-b5e4-dfb3ac927caf
		summarizeBy: count
		sourceColumn: Entity_Id

		annotation SummarizationSetBy = Automatic

	/// ESG Category (E = Environmental ; S = Social; G = Governance)
	column ESG_Category
		dataType: string
		lineageTag: 50d9896e-4839-43b5-b2dd-91fb4decefce
		summarizeBy: none
		sourceColumn: ESG_Category

		annotation SummarizationSetBy = Automatic

	column Vendor_Topic
		dataType: string
		lineageTag: 8bab718d-2f0b-473b-a031-93f3c1df749d
		summarizeBy: none
		sourceColumn: Vendor_Topic

		annotation SummarizationSetBy = Automatic

	column Entity_Topic_Key
		dataType: string
		lineageTag: a89ec2ae-54ce-44d7-94e2-fa344ccbb1b3
		summarizeBy: none
		sourceColumn: Entity_Topic_Key

		annotation SummarizationSetBy = Automatic

	/// Sustainalytics Category
	column Category
		dataType: string
		lineageTag: 9f3c42a4-a031-4adf-a520-b2a2fc587cba
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Score
		dataType: string
		lineageTag: 57996f8b-4fc0-452b-a52b-229fb8aa0b53
		summarizeBy: none
		sourceColumn: Score

		annotation SummarizationSetBy = Automatic

	column Valid_From
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6e61deca-9195-403f-b1f5-5d243fd8126d
		summarizeBy: none
		sourceColumn: Valid_From

		variation Variation
			isDefault
			relationship: 401936f4-f27a-43c4-be2d-371fcd4eb596
			defaultHierarchy: LocalDateTable_040c7234-2958-46e1-b009-d4567f67d022.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Valid_To
		dataType: dateTime
		formatString: Long Date
		lineageTag: d1ae06d6-6b02-480b-b0e8-35234a1df1d8
		summarizeBy: none
		sourceColumn: Valid_To

		variation Variation
			isDefault
			relationship: 6ba80bc6-fdce-4f09-b81e-f71f76d4c934
			defaultHierarchy: LocalDateTable_f07cbe99-0cc6-4f36-91ac-48d43824c589.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Is the Sustainalytics Score current/latest
	column Is_Current
		dataType: string
		lineageTag: 4da5fb98-0ee4-4eac-be58-489ce84eb995
		summarizeBy: none
		sourceColumn: Is_Current

		annotation SummarizationSetBy = Automatic

	column Entity_Date_Key
		dataType: string
		lineageTag: a7125b5e-1c81-4681-abf1-5ad21829f477
		summarizeBy: none
		sourceColumn: Entity_Date_Key

		annotation SummarizationSetBy = Automatic

	column 'Score - Num'
		dataType: int64
		formatString: 0
		lineageTag: 1cb6021d-9c6e-4066-8bfc-000d3a9fbaed
		summarizeBy: sum
		sourceColumn: Score - Num

		annotation SummarizationSetBy = Automatic

	partition 'ESG Controversy Snapshot-75d8b56c-4971-403e-8930-1293ff1cfe0e' = m
		mode: import
		queryGroup: Sustainalytics
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=p_databricks_catalog,Kind="Database"]}[Data],
				    sustainalytics_Schema = hive_metastore_Database{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_esg_sustainalytics_controversy_snapshot_v1_Table = sustainalytics_Schema{[Name="semantic_esg_sustainalytics_controversy_snapshot_v1",Kind="Table"]}[Data],
				    #"Duplicated Column" = Table.DuplicateColumn(semantic_esg_sustainalytics_controversy_snapshot_v1_Table, "Score", "Score - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"Score - Copy", "Score - Num"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Score - Num", Int64.Type}})
				    ,  FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				      #"Changed Type", 
				      100
				     )
				 else 
				   
				      #"Changed Type"
				     in
				  FilterLogic
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

