table 'ESG Country'
	lineageTag: 11c7bb54-1d5a-46b4-9e4f-cf2c2e9f9978

	column Country
		dataType: string
		lineageTag: 667e19f8-b1a2-4151-8c15-e96cedcdecdf
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column OfficialName
		dataType: string
		lineageTag: b28bd317-49da-482f-8f2b-de38a381c6f3
		summarizeBy: none
		sourceColumn: OfficialName

		annotation SummarizationSetBy = Automatic

	column IsoAlpha2Code
		dataType: string
		lineageTag: 8e14b395-6b85-4224-987f-1e2f7ac3a57c
		summarizeBy: none
		sourceColumn: IsoAlpha2Code

		annotation SummarizationSetBy = Automatic

	column IsoAlpha3Code
		dataType: string
		lineageTag: 34a85b52-3223-43ef-ba50-4651506ce929
		dataCategory: Country
		summarizeBy: none
		sourceColumn: IsoAlpha3Code

		annotation SummarizationSetBy = Automatic

	column IsoNumericCode
		dataType: int64
		formatString: 0
		lineageTag: 8db991cd-07a0-4f22-8ec8-dd27f2f61254
		summarizeBy: count
		sourceColumn: IsoNumericCode

		annotation SummarizationSetBy = Automatic

	column Valid_From
		dataType: dateTime
		formatString: Long Date
		lineageTag: ccc7cbfe-7fd6-46da-99d8-8df5beca3a2c
		summarizeBy: none
		sourceColumn: Valid_From

		variation Variation
			isDefault
			relationship: 23d6a755-ca46-4ab9-8b5f-514151956e3b
			defaultHierarchy: LocalDateTable_491783f1-4ddf-4404-baee-f9d6a971730b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Valid_To
		dataType: dateTime
		formatString: Long Date
		lineageTag: 990fde81-35e4-47f3-967a-2b17a66207c5
		summarizeBy: none
		sourceColumn: Valid_To

		variation Variation
			isDefault
			relationship: 110723c9-0301-4ec3-8953-b909903df150
			defaultHierarchy: LocalDateTable_594ce130-a4a2-4151-8315-8d184c2af13f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Is_Current
		dataType: string
		lineageTag: 74d7aad2-d0f9-4b72-a6ae-034eac7808bd
		summarizeBy: none
		sourceColumn: Is_Current

		annotation SummarizationSetBy = Automatic

	column Is_Deleted
		dataType: string
		lineageTag: 0fd82883-9d77-477e-a86a-d50de5dde5c7
		summarizeBy: none
		sourceColumn: Is_Deleted

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: cebcd098-4fbf-468e-8934-05e5d10cef8f
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition 'ESG Country-0c65dee4-802f-4cd3-895a-ccf55c511cc4' = m
		mode: import
		queryGroup: Sustainalytics
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=p_databricks_catalog,Kind="Database"]}[Data],
				    sustainalytics_Schema = hive_metastore_Database{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_esg_country_v1_Table = sustainalytics_Schema{[Name="semantic_esg_country_v1",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(semantic_esg_country_v1_Table,{"Row_SHA2"})
				    ,  FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				      #"Removed Columns", 
				      100
				     )
				 else 
				     #"Removed Columns"
				in
				    FilterLogic
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

