table fact_bipsync_dsu_tags
	lineageTag: f544bd87-40a8-465d-beaf-5dd3f71ee06c

	column Ticker
		dataType: string
		lineageTag: cd0bfe71-b51c-4bb0-ac1c-defc3821e2c7
		summarizeBy: none
		sourceColumn: Ticker

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 812e78c3-0792-4d8a-8ea2-1dd9526db9d2
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Note_Id
		dataType: string
		lineageTag: f0b9c1d5-3645-4d45-8c5d-4ed8d917bfa0
		summarizeBy: none
		sourceColumn: Note_Id

		annotation SummarizationSetBy = Automatic

	column Note_Title
		dataType: string
		lineageTag: 1e4f4174-e928-4088-9a16-76a67fb1a652
		summarizeBy: none
		sourceColumn: Note_Title

		annotation SummarizationSetBy = Automatic

	column Also_Known_As
		dataType: string
		lineageTag: eba7a8e2-b692-4492-9243-3a879cc97356
		summarizeBy: none
		sourceColumn: Also_Known_As

		annotation SummarizationSetBy = Automatic

	column Organisation_Type
		dataType: string
		lineageTag: 571711aa-edcb-4a8b-97ef-d6b40cef9732
		summarizeBy: none
		sourceColumn: Organisation_Type

		annotation SummarizationSetBy = Automatic

	column Date_Of_Meeting
		dataType: dateTime
		formatString: dd mmm yyyy
		lineageTag: ba396229-17f2-4864-9874-4e91a3162c0c
		summarizeBy: none
		sourceColumn: Date_Of_Meeting

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column RI_Engagement
		dataType: string
		lineageTag: e212f33a-858e-4aeb-9250-e31f1cd6ea65
		summarizeBy: none
		sourceColumn: RI_Engagement

		annotation SummarizationSetBy = Automatic

	column Note_Type
		dataType: string
		lineageTag: 92daf39d-6df4-42fb-a573-2cf57e8e2b04
		summarizeBy: none
		sourceColumn: Note_Type

		annotation SummarizationSetBy = Automatic

	column AGM
		dataType: int64
		formatString: 0
		lineageTag: e4565a10-4b65-45ab-bb6f-a6799ada61cb
		summarizeBy: sum
		sourceColumn: AGM

		annotation SummarizationSetBy = Automatic

	column ASX_Engagement
		dataType: int64
		formatString: 0
		lineageTag: 412473e9-b622-4768-a90f-1ccbfbdde211
		summarizeBy: sum
		sourceColumn: ASX_Engagement

		annotation SummarizationSetBy = Automatic

	column Board
		dataType: int64
		formatString: 0
		lineageTag: ec509760-cedd-4360-a2f8-ebcfcc210601
		summarizeBy: sum
		sourceColumn: Board

		annotation SummarizationSetBy = Automatic

	column Climate_Change
		dataType: int64
		formatString: 0
		lineageTag: 32fddb1a-5374-4fd5-8099-359d46953cf7
		summarizeBy: sum
		sourceColumn: Climate_Change

		annotation SummarizationSetBy = Automatic

	column Culture
		dataType: int64
		formatString: 0
		lineageTag: a9bc5688-ddfc-49ed-88a4-809d1b843d48
		summarizeBy: sum
		sourceColumn: Culture

		annotation SummarizationSetBy = Automatic

	column Cyber
		dataType: int64
		formatString: 0
		lineageTag: 29a3dc0d-e03d-426d-8a54-1cdfa3cfb9df
		summarizeBy: sum
		sourceColumn: Cyber

		annotation SummarizationSetBy = Automatic

	column Diversity_Equity_Inclusion
		dataType: int64
		formatString: 0
		lineageTag: 696456d7-19aa-473a-9150-7d5fdd895d06
		summarizeBy: sum
		sourceColumn: Diversity_Equity_Inclusion

		annotation SummarizationSetBy = Automatic

	column Governance_Considerations
		dataType: int64
		formatString: 0
		lineageTag: b4384fa0-1a52-4499-8afd-930f6e5ee88f
		summarizeBy: sum
		sourceColumn: Governance_Considerations

		annotation SummarizationSetBy = Automatic

	column Human_Rights
		dataType: int64
		formatString: 0
		lineageTag: 44523b62-7bd2-42df-9746-5410421e7ccc
		summarizeBy: sum
		sourceColumn: Human_Rights

		annotation SummarizationSetBy = Automatic

	column Indigenous
		dataType: int64
		formatString: 0
		lineageTag: 8069d863-29a9-4516-88a1-6472030c8118
		summarizeBy: sum
		sourceColumn: Indigenous

		annotation SummarizationSetBy = Automatic

	column Modern_Slavery
		dataType: int64
		formatString: 0
		lineageTag: c5bceb8e-2005-4fe5-a565-c5e0c2e2555a
		summarizeBy: sum
		sourceColumn: Modern_Slavery

		annotation SummarizationSetBy = Automatic

	column Nature
		dataType: int64
		formatString: 0
		lineageTag: b6a801bb-a705-4466-be50-d9a9c14d941b
		summarizeBy: sum
		sourceColumn: Nature

		annotation SummarizationSetBy = Automatic

	column Pay_Gap
		dataType: int64
		formatString: 0
		lineageTag: d57a365e-b1d6-4f82-a93a-b9a4865eb1dd
		summarizeBy: sum
		sourceColumn: Pay_Gap

		annotation SummarizationSetBy = Automatic

	column Remuneration
		dataType: int64
		formatString: 0
		lineageTag: 4c862f34-9084-43ee-bba6-547824762a51
		summarizeBy: sum
		sourceColumn: Remuneration

		annotation SummarizationSetBy = Automatic

	column Responsible_AI
		dataType: int64
		formatString: 0
		lineageTag: c057f54b-3156-43ec-b55b-46c64c166393
		summarizeBy: sum
		sourceColumn: Responsible_AI

		annotation SummarizationSetBy = Automatic

	column Safety
		dataType: int64
		formatString: 0
		lineageTag: 34b5d875-9014-4b5b-beb7-2f18f44fca96
		summarizeBy: sum
		sourceColumn: Safety

		annotation SummarizationSetBy = Automatic

	column Active_Strategic_Ticker
		dataType: string
		lineageTag: d8697a22-8ec4-46d3-9865-d31740fca78d
		summarizeBy: none
		sourceColumn: Active_Strategic_Ticker

		annotation SummarizationSetBy = Automatic

	column Engagement
		dataType: string
		lineageTag: 4b063280-d8ca-499b-a76b-e39f5e978332
		summarizeBy: none
		sourceColumn: Engagement

		annotation SummarizationSetBy = Automatic

	column Engagement_Plan
		dataType: string
		lineageTag: 70c8f2ec-cf48-46cb-912e-2820e5013f7f
		summarizeBy: none
		sourceColumn: Engagement_Plan

		annotation SummarizationSetBy = Automatic

	column Classification
		dataType: string
		lineageTag: e1f8c116-89e3-4177-8005-10dc5548fd97
		summarizeBy: none
		sourceColumn: Classification

		annotation SummarizationSetBy = Automatic

	column Reviewed_By
		dataType: string
		lineageTag: fc61a4a9-54da-498b-94a1-7e7a060eb7b7
		summarizeBy: none
		sourceColumn: Reviewed_By

		annotation SummarizationSetBy = Automatic

	column Analysis_By
		dataType: string
		lineageTag: 9e257f0c-b5b7-4865-a94f-fbea29ed418f
		summarizeBy: none
		sourceColumn: Analysis_By

		annotation SummarizationSetBy = Automatic

	column Is_Analysis_By_Available
		dataType: int64
		formatString: 0
		lineageTag: adf22c9b-ab04-477d-a78d-6de7a80da16c
		summarizeBy: sum
		sourceColumn: Is_Analysis_By_Available

		annotation SummarizationSetBy = Automatic

	column Is_Reviewed_By_Available
		dataType: int64
		formatString: 0
		lineageTag: a13a4b70-d1ec-422e-8a69-5b11c5c2c324
		summarizeBy: sum
		sourceColumn: Is_Reviewed_By_Available

		annotation SummarizationSetBy = Automatic

	column 'Engagement Status' = ```
			
			
			VAR CurrentTicker = fact_bipsync_dsu_tags[Ticker]
			VAR FYStart = RELATED('dim_engagement_status'[FYStartDate])
			VAR FYEnd = RELATED('dim_engagement_status'[FYEndDate])
			VAR HasWindow = NOT (ISBLANK(FYStart) || ISBLANK(FYEnd))
			
			VAR HasMeetingNotes = 
			    IF(
			        HasWindow,
			        CALCULATE(
			            COUNTROWS(fact_bipsync_dsu_tags) > 0,
			            fact_bipsync_dsu_tags[Ticker] = CurrentTicker,
			            fact_bipsync_dsu_tags[Date_Of_Meeting] >= FYStart,
			            fact_bipsync_dsu_tags[Date_Of_Meeting] <= FYEnd
			        ),
			        FALSE()
			    )
			
			VAR HasMeetingDate = 
			    IF(
			        HasWindow,
			        CALCULATE(
			            COUNTROWS(fact_bipsync_dsu_tags) > 0,
			            fact_bipsync_dsu_tags[Ticker] = CurrentTicker,
			            fact_bipsync_dsu_tags[Date_Of_Meeting] >= FYStart,
			            fact_bipsync_dsu_tags[Date_Of_Meeting] <= FYEnd,
			            fact_bipsync_dsu_tags[Date_Of_Meeting] <> BLANK()
			        ),
			        FALSE()
			    )
			
			VAR IsAnalysed = 
			    IF(
			        HasWindow,
			        CALCULATE(
			            COUNTROWS(fact_bipsync_dsu_tags) > 0,
			            fact_bipsync_dsu_tags[Ticker] = CurrentTicker,
			            fact_bipsync_dsu_tags[Date_Of_Meeting] >= FYStart,
			            fact_bipsync_dsu_tags[Date_Of_Meeting] <= FYEnd,
			            fact_bipsync_dsu_tags[Is_Analysis_By_Available] > 0
			        ),
			        FALSE()
			    )
			
			VAR IsReviewed = 
			    IF(
			        HasWindow,
			        CALCULATE(
			            COUNTROWS(fact_bipsync_dsu_tags) > 0,
			            fact_bipsync_dsu_tags[Ticker] = CurrentTicker,
			            fact_bipsync_dsu_tags[Date_Of_Meeting] >= FYStart,
			            fact_bipsync_dsu_tags[Date_Of_Meeting] <= FYEnd,
			            fact_bipsync_dsu_tags[Is_Reviewed_By_Available] > 0
			        ),
			        FALSE()
			    )
			
			RETURN
			    IF(
			        NOT HasMeetingNotes || NOT HasMeetingDate,
			        "Not engaged",
			        IF(
			            NOT IsAnalysed,
			            "Not analysed",
			            IF(
			                NOT IsReviewed,
			                "Not reviewed",
			                "Engaged"
			            )
			        )
			    )
			```
		lineageTag: 466ac8fe-b962-4e97-8c6b-762d87ba8075
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ffma_contact_team
		dataType: string
		lineageTag: 9849677d-a125-4fab-a552-49e30d0781b5
		summarizeBy: none
		sourceColumn: ffma_contact_team

		annotation SummarizationSetBy = Automatic

	column Investment_Note
		dataType: int64
		formatString: 0
		lineageTag: d7ddc0cf-5445-4b02-b839-349138700db7
		summarizeBy: sum
		sourceColumn: Investment_Note

		annotation SummarizationSetBy = Automatic

	column Responsible_Investment
		dataType: int64
		formatString: 0
		lineageTag: c3d5e2bc-4135-411e-bd22-e0a79a774dd8
		summarizeBy: sum
		sourceColumn: Responsible_Investment

		annotation SummarizationSetBy = Automatic

	column External_Attendees
		dataType: string
		lineageTag: a2990c05-0353-4d51-89c0-47535f674e96
		summarizeBy: none
		sourceColumn: External_Attendees

		annotation SummarizationSetBy = Automatic

	column Future_Fund_Attendees
		dataType: string
		lineageTag: 62efdfd9-a492-4bc7-8111-13c25cc0c987
		summarizeBy: none
		sourceColumn: Future_Fund_Attendees

		annotation SummarizationSetBy = Automatic

	column Is_External_Attendees_Available
		dataType: int64
		formatString: 0
		lineageTag: d0816d12-6348-4fd4-9eaf-3c9b5eac7877
		summarizeBy: sum
		sourceColumn: Is_External_Attendees_Available

		annotation SummarizationSetBy = Automatic

	column Is_Future_Fund_Attendees_Available
		dataType: int64
		formatString: 0
		lineageTag: 82f83079-774d-40c9-96e7-a0944dae3317
		summarizeBy: sum
		sourceColumn: Is_Future_Fund_Attendees_Available

		annotation SummarizationSetBy = Automatic

	column Future_Fund_Tag
		dataType: string
		lineageTag: efe058f7-0c97-4b85-9056-6fd3131c5976
		summarizeBy: none
		sourceColumn: Future_Fund_Tag

		annotation SummarizationSetBy = Automatic

	column bipsync_url
		dataType: string
		lineageTag: 207245ae-0d97-4f47-b45c-648211db2ee8
		summarizeBy: none
		sourceColumn: bipsync_url

		annotation SummarizationSetBy = Automatic

	partition fact_bipsync_dsu_tags = m
		mode: import
		queryGroup: BipSync
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    Schema = Table.SelectRows(hive_metastore_Database, each ([Name] =p_sustainalytics_database)),
				    sustainalytics_Schema = Schema{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    pub_fct_bipsync_notes_count_by_companies_and_tags_Table = sustainalytics_Schema{[Name="pub_fct_bipsync_notes_count_by_companies_and_tags",Kind="Table"]}[Data],
				    #"Capitalized Each Word" = Table.TransformColumns(pub_fct_bipsync_notes_count_by_companies_and_tags_Table,{{"Name", Text.Proper, type text}}),
				    #"Sorted Rows" = Table.Sort(#"Capitalized Each Word",{{"Date_Of_Meeting", Order.Descending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

