table 'Fund Hierarchy'
	lineageTag: aefc24c3-95b2-4ef3-8ba9-6c4eccc0867a

	column 'SK POLICY TREE'
		dataType: string
		lineageTag: f1e3a06d-eb4f-42e3-a1f5-d7f02887a51a
		summarizeBy: none
		sourceColumn: SK POLICY TREE

		annotation SummarizationSetBy = Automatic

	column 'POLICY TREE ID'
		dataType: string
		lineageTag: 72b9739d-f832-4da4-8da7-8885baa4d0b4
		summarizeBy: none
		sourceColumn: POLICY TREE ID

		annotation SummarizationSetBy = Automatic

	column 'NODE ID'
		dataType: string
		lineageTag: ae754b85-0c6b-41a9-9868-ff6600a1e5df
		summarizeBy: none
		sourceColumn: NODE ID

		annotation SummarizationSetBy = Automatic

	column 'EFFECTIVE DATE'
		dataType: dateTime
		formatString: General Date
		lineageTag: e2fdad8f-6032-4b07-b937-d90f63ca3965
		summarizeBy: none
		sourceColumn: EFFECTIVE DATE

		variation Variation
			isDefault
			relationship: decfce6d-72d8-4e16-bff0-b0c74e2a5159
			defaultHierarchy: LocalDateTable_9e233e06-f279-4143-9719-f0fa844bc489.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'SK CURRENT NODE ID'
		dataType: string
		lineageTag: cfa4fcb5-1b9e-4736-8893-f15927c1bb0c
		summarizeBy: none
		sourceColumn: SK CURRENT NODE ID

		annotation SummarizationSetBy = Automatic

	column 'SK NODE ID EFFECTIVE DATE'
		dataType: string
		lineageTag: fa699680-8c26-4735-b597-2bd44048b924
		summarizeBy: none
		sourceColumn: SK NODE ID EFFECTIVE DATE

		annotation SummarizationSetBy = Automatic

	column 'SK PARENT'
		dataType: string
		lineageTag: 7d513e7f-e0f1-461b-a310-cb7a6ba0776f
		summarizeBy: none
		sourceColumn: SK PARENT

		annotation SummarizationSetBy = Automatic

	column 'EFFECTIVE END DATE'
		dataType: dateTime
		formatString: General Date
		lineageTag: d7ce1f98-1166-4766-a02c-d4fe79b5c2a3
		summarizeBy: none
		sourceColumn: EFFECTIVE END DATE

		variation Variation
			isDefault
			relationship: e3a737b9-25f4-47be-9d96-2b4f82497400
			defaultHierarchy: LocalDateTable_422ad696-5425-4388-89a3-361710def2ed.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'EFFECTIVE START DATE'
		dataType: dateTime
		formatString: General Date
		lineageTag: bedfcae3-ab05-4025-bcc1-1bfa88406861
		summarizeBy: none
		sourceColumn: EFFECTIVE START DATE

		variation Variation
			isDefault
			relationship: 846e8ab7-43e7-47e0-af28-1b92407369d0
			defaultHierarchy: LocalDateTable_cff5c599-66a4-4eee-94ff-74e3d80028f0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'INVESTMENT OBJECT CODE'
		dataType: string
		lineageTag: 0f8a16f7-9e42-4f00-973f-cfd8a320e235
		summarizeBy: none
		sourceColumn: INVESTMENT OBJECT CODE

		annotation SummarizationSetBy = Automatic

	column 'IS CURRENT'
		dataType: string
		lineageTag: 343f0deb-df54-4d84-b315-c83d92ce6944
		summarizeBy: none
		sourceColumn: IS CURRENT

		annotation SummarizationSetBy = Automatic

	column NODE
		dataType: string
		lineageTag: a65aa72e-2d40-47bf-9aeb-469cc3130748
		summarizeBy: none
		sourceColumn: NODE

		annotation SummarizationSetBy = Automatic

	column 'NODE DEPTH'
		dataType: double
		lineageTag: 7b2569ad-e2d7-4293-90b2-e12babf926ae
		summarizeBy: sum
		sourceColumn: NODE DEPTH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'NODE ID PATH'
		dataType: string
		lineageTag: 81c41609-418d-41b1-99e4-766fbac59c8b
		summarizeBy: none
		sourceColumn: NODE ID PATH

		annotation SummarizationSetBy = Automatic

	column 'NODE PATH'
		dataType: string
		lineageTag: 4140b1bd-2012-4cca-9650-3ddf4b39be6e
		summarizeBy: none
		sourceColumn: NODE PATH

		annotation SummarizationSetBy = Automatic

	column 'NODE TYPE'
		dataType: string
		lineageTag: 1b1a551a-1bf2-4813-9496-d42ca3c7bf66
		summarizeBy: none
		sourceColumn: NODE TYPE

		annotation SummarizationSetBy = Automatic

	column 'PARENT INVESTMENT OBJECT CODE'
		dataType: string
		lineageTag: 6341af39-ae49-42a4-a3af-36f6d6fb7897
		summarizeBy: none
		sourceColumn: PARENT INVESTMENT OBJECT CODE

		annotation SummarizationSetBy = Automatic

	column 'PARENT NODE ID'
		dataType: string
		lineageTag: d61921ec-22f9-4bb1-a2e6-41e482a06588
		summarizeBy: none
		sourceColumn: PARENT NODE ID

		annotation SummarizationSetBy = Automatic

	column 'POLICY TREE'
		dataType: string
		lineageTag: be62f0de-4626-48d1-8d3b-52e7013dabd1
		summarizeBy: none
		sourceColumn: POLICY TREE

		annotation SummarizationSetBy = Automatic

	column 'POLICY TREE CODE'
		dataType: string
		lineageTag: 7c4df937-f17b-4cc3-89ed-6a60b9219da5
		summarizeBy: none
		sourceColumn: POLICY TREE CODE

		annotation SummarizationSetBy = Automatic

	column 'POLICY TREE STATUS'
		dataType: string
		lineageTag: 69091996-bc2a-4ce8-afba-d49d2911a433
		summarizeBy: none
		sourceColumn: POLICY TREE STATUS

		annotation SummarizationSetBy = Automatic

	column 'POLICY TREE TYPE'
		dataType: string
		lineageTag: 12aac7f7-5312-4d0e-913c-e29d7baec5ab
		summarizeBy: none
		sourceColumn: POLICY TREE TYPE

		annotation SummarizationSetBy = Automatic

	column SECTOR
		dataType: string
		lineageTag: 1c46e02c-78c7-43be-b93d-a26e7a2cfbdd
		summarizeBy: none
		sourceColumn: SECTOR

		annotation SummarizationSetBy = Automatic

	column 'SECTOR NODE ID'
		dataType: string
		lineageTag: 42ec22d9-c05e-4fa2-aee8-0fc08f1122c1
		summarizeBy: none
		sourceColumn: SECTOR NODE ID

		annotation SummarizationSetBy = Automatic

	column SUBSECTOR
		dataType: string
		lineageTag: ef6c4003-d99e-426c-8f63-d496f96b53e4
		summarizeBy: none
		sourceColumn: SUBSECTOR

		annotation SummarizationSetBy = Automatic

	column 'SUBSECTOR NODE ID'
		dataType: string
		lineageTag: eccdafa7-0860-49fa-af1e-0e1e273c9ee9
		summarizeBy: none
		sourceColumn: SUBSECTOR NODE ID

		annotation SummarizationSetBy = Automatic

	column 'MODIFIED TIME'
		dataType: dateTime
		formatString: General Date
		lineageTag: 155f75d3-cae8-4e72-9dfe-97a283e8c6bd
		summarizeBy: none
		sourceColumn: MODIFIED TIME

		variation Variation
			isDefault
			relationship: 854e48d6-d996-4aa4-9765-fbe8179e6d2a
			defaultHierarchy: LocalDateTable_1a417ea2-0a0d-4db1-8e59-9056c6dd6d02.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'INPUT MODIFIED TIME'
		dataType: dateTime
		formatString: General Date
		lineageTag: d694d885-8232-4170-b1ea-db8ee29f18ff
		summarizeBy: none
		sourceColumn: INPUT MODIFIED TIME

		variation Variation
			isDefault
			relationship: fca3b732-b2d3-4037-a4ce-6de41e9c27b9
			defaultHierarchy: LocalDateTable_3285b507-c430-4d46-a29c-ef8b1667c828.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'DELETED TIME'
		dataType: dateTime
		formatString: General Date
		lineageTag: db22ebef-2f97-4012-acac-2fc1d7c354ee
		summarizeBy: none
		sourceColumn: DELETED TIME

		variation Variation
			isDefault
			relationship: 9f9dc776-4740-4414-8acb-761241b5a169
			defaultHierarchy: LocalDateTable_4402ebaf-6ffa-4883-9b86-5291cabbc768.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'Fund Hierarchy-84afb8ed-ed9a-4dff-afc6-a6dddb2f6d55' = m
		mode: import
		queryGroup: Sustainalytics
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=p_databricks_catalog,Kind="Database"]}[Data],
				    sustainalytics_Schema = hive_metastore_Database{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_gs_fund_hierarchy_v1_Table = sustainalytics_Schema{[Name="semantic_gs_fund_hierarchy_v1",Kind="Table"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(semantic_gs_fund_hierarchy_v1_Table,
				{{"SK_POLICY_TREE", "SK POLICY TREE"},
				 {"POLICY_TREE_ID", "POLICY TREE ID"}, 
				 {"NODE_ID", "NODE ID"},
				 {"EFFECTIVE_DATE", "EFFECTIVE DATE"}, 
				 {"SK_CURRENT_NODE_ID", "SK CURRENT NODE ID"},
				 {"SK_NODE_ID_EFFECTIVE_DATE", "SK NODE ID EFFECTIVE DATE"},
				 {"SK_PARENT", "SK PARENT"},
				 {"EFFECTIVE_END_DATE", "EFFECTIVE END DATE"},
				 {"EFFECTIVE_START_DATE", "EFFECTIVE START DATE"},
				 {"INVESTMENT_OBJECT_CODE", "INVESTMENT OBJECT CODE"},
				 {"IS_CURRENT", "IS CURRENT"}, {"NODE_DEPTH", "NODE DEPTH"},
				 {"NODE_ID_PATH", "NODE ID PATH"}, {"NODE_PATH", "NODE PATH"},
				 {"NODE_TYPE", "NODE TYPE"},
				 {"PARENT_INVESTMENT_OBJECT_CODE", "PARENT INVESTMENT OBJECT CODE"},
				 {"PARENT_NODE_ID", "PARENT NODE ID"}, {"POLICY_TREE", "POLICY TREE"},
				 {"POLICY_TREE_CODE", "POLICY TREE CODE"},
				 {"POLICY_TREE_STATUS", "POLICY TREE STATUS"}, 
				 {"POLICY_TREE_TYPE", "POLICY TREE TYPE"}, 
				 {"SECTOR_NODE_ID", "SECTOR NODE ID"}, 
				 {"SUBSECTOR_NODE_ID", "SUBSECTOR NODE ID"},
				 {"MODIFIED_TIME", "MODIFIED TIME"}, 
				 {"INPUT_MODIFIED_TIME", "INPUT MODIFIED TIME"}, 
				{"DELETED_TIME", "DELETED TIME"}})
				    ,  FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				      #"Renamed Columns", 
				      100
				     )
				 else 
				     #"Renamed Columns" 
				     in
				  FilterLogic
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

