table 'GS Asset'
	lineageTag: 0104fa3c-65d0-41c9-97df-670d48b1dfa3

	/// Explicit measure to be used in Excel Pivot Table
	measure SHARES_OUTSTANDING_SUM = ```
			SUM('GS Asset'[SHARES_OUTSTANDING_QUANTITY]) // Explicit measure to be used in Excel Pivot Table
			
			```
		lineageTag: 375b1a9e-d68c-459d-a8a2-b4a551a40e5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Measure 2'
		lineageTag: aba2b2e7-3079-4aaa-aa8f-6141fdaf23bb

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure Matched_Assets_Sustain = CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]),'Daily Position'[Mapping_Status] = "Match")
		formatString: #,0
		lineageTag: ccc10f1d-d5fc-4a87-a980-c21e0c13d47d

	measure Unmatched_Assets_Sustain = CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]),'Daily Position'[Mapping_Status] = "No Match")
		formatString: #,0
		lineageTag: d792cc88-8a86-40d7-9284-055169e89146

	measure Matched_Assets_Percentage_Sustain = ```
			([Matched_Assets_Sustain] /[Total_Assets]) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a2a9e41b-369c-4fbd-b608-7bb807b0c64b

	measure Total_Assets = ```
			CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]))       
			```
		formatString: #,0
		lineageTag: 71d772aa-2616-4a99-acc6-2ef87eb6f253

	measure Matched_Assets_Trucost = CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]),'Daily Position'[Trucost_Mapping_Status] = "Match")
		formatString: #,0
		lineageTag: 5be1875e-9490-404b-83c3-28413335d53a

	measure Matched_Assets_Eiris = CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]),'Daily Position'[Eiris_Mapping_Status] = "Match")
		formatString: #,0
		lineageTag: 11af32dd-c94d-4d50-b5b9-b2ccd2e47ff8

	measure Unmatched_Assets_Trucost = CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]),'Daily Position'[Trucost_Mapping_Status] = "No Match")
		formatString: #,0
		lineageTag: aaa0daee-984c-4ec6-9e8d-97f21a5feff9

	measure Matched_Assets_Percentage_Trucost = ```
			([Matched_Assets_Trucost] /[Total_Assets]) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a6c18d4f-15dd-4e71-a7af-15fa712c1084

	measure Unmatched_Assets_Eiris = CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]),'Daily Position'[Eiris_Mapping_Status] = "No Match")
		formatString: #,0
		lineageTag: 2591eabc-10a9-4308-9222-3ba607e2823c

	measure Matched_Assets_Percentage_Eiris = ```
			([Matched_Assets_Eiris] /[Total_Assets]) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 778a071f-8e56-49bc-9f59-d78585053f74

	measure UnMatched_Assets_Percentage_Sustain = ```
			([Unmatched_Assets_Sustain] /[Total_Assets]) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d24916d6-a10f-4dff-b7a3-bc85a1b1719c

	measure UnMatched_Assets_Percentage_Trucost = ```
			([Unmatched_Assets_Trucost] /[Total_Assets]) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a7814635-27fb-4043-b0ff-5bf9ad61e62c

	measure UnMatched_Assets_Percentage_Eiris = ```
			([Unmatched_Assets_Eiris] /[Total_Assets]) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 768044b3-fc04-4b20-8d54-22281b90d8f9

	measure Unmatched_MV_Eiris = CALCULATE( SUM('Daily Position'[MARKET VALUE BASE]),'Daily Position'[Eiris_Mapping_Status] ="No Match")
		lineageTag: 6d0cfc10-e98b-4906-aea6-35f6c622632d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Unmatched_MV_Percent_Eiris = [Unmatched_MV_Eiris] / [MARKET_VALUE_BASE_SUM]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e9cdb1f1-51a8-4b15-8fa2-83cb1e766cab

	measure Unmatched_MV_Sustain = CALCULATE( SUM('Daily Position'[MARKET VALUE BASE]),'Daily Position'[Mapping_Status] ="No Match")
		lineageTag: 5624c083-dfbf-4249-afc5-8b32c1eae3b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Unmatched_MV_Percent_Sustain = [Unmatched_MV_Sustain] / [MARKET_VALUE_BASE_SUM]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2f68021b-70ea-4f45-9fd5-0b9de8f1d841

	measure Unmatched_MV_Trucost = CALCULATE( SUM('Daily Position'[MARKET VALUE BASE]),'Daily Position'[Trucost_Mapping_Status] ="No Match")
		lineageTag: 11bc9606-388a-434f-be0a-ef603e9d287c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Unmatched_MV_Percent_Trucost = [Unmatched_MV_Trucost] / [MARKET_VALUE_BASE_SUM]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b4c8b03d-64d9-4abe-9d35-cee0043fee8f

	column SK_ASSET
		dataType: string
		lineageTag: c72b5151-ccbe-4f74-a9e9-15ea7db427d1
		summarizeBy: none
		sourceColumn: SK_ASSET

		annotation SummarizationSetBy = Automatic

	column ASSET_ID
		dataType: string
		lineageTag: dd7bfcdc-0ad8-43fe-be7a-29f9c7775006
		summarizeBy: none
		sourceColumn: ASSET_ID

		annotation SummarizationSetBy = Automatic

	column BLOOMBERG_SECURITY_TYPE
		dataType: string
		lineageTag: 1ac0eded-612e-49cb-913f-9302ed7eee9f
		summarizeBy: none
		sourceColumn: BLOOMBERG_SECURITY_TYPE

		annotation SummarizationSetBy = Automatic

	column BLOOMBERG_TICKER
		dataType: string
		lineageTag: 361413c8-20f3-46fd-9f2a-db38bbfc182a
		summarizeBy: none
		sourceColumn: BLOOMBERG_TICKER

		annotation SummarizationSetBy = Automatic

	column CINS_ID
		dataType: string
		lineageTag: b994e363-3d04-4f6e-98a8-3bac37eea025
		summarizeBy: none
		sourceColumn: CINS_ID

		annotation SummarizationSetBy = Automatic

	column CLIENT_COUNTRY_OF_RISK_CODE
		dataType: string
		displayFolder: Country
		lineageTag: 772d6f13-41a8-4b71-a06c-999b1b202d89
		summarizeBy: none
		sourceColumn: CLIENT_COUNTRY_OF_RISK_CODE

		annotation SummarizationSetBy = Automatic

	column CLIENT_INSTRUMENT_ISSUE_TYPE
		dataType: string
		lineageTag: 7cb98a38-ebdf-415c-aeec-60b5ab53b88e
		summarizeBy: none
		sourceColumn: CLIENT_INSTRUMENT_ISSUE_TYPE

		annotation SummarizationSetBy = Automatic

	column CLIENT_INSTRUMENT_MAJOR_TYPE
		dataType: string
		lineageTag: 083b831d-904d-415c-ac5e-ceec4b5373f5
		summarizeBy: none
		sourceColumn: CLIENT_INSTRUMENT_MAJOR_TYPE

		annotation SummarizationSetBy = Automatic

	column CLIENT_INSTRUMENT_SUB_TYPE
		dataType: string
		lineageTag: caea87fe-d737-4ad0-a699-61ec79f48339
		summarizeBy: none
		sourceColumn: CLIENT_INSTRUMENT_SUB_TYPE

		annotation SummarizationSetBy = Automatic

	column COUNTERPARTY
		dataType: string
		lineageTag: a8a14bf5-fad1-4eec-91ba-12b2db30bf86
		summarizeBy: none
		sourceColumn: COUNTERPARTY

		annotation SummarizationSetBy = Automatic

	column COUNTERPARTY_ID
		dataType: string
		lineageTag: 8f13dab2-b5e5-4b1f-955c-b915ce57e88c
		summarizeBy: none
		sourceColumn: COUNTERPARTY_ID

		annotation SummarizationSetBy = Automatic

	column COUNTRY_OF_DOMICILE_CODE
		dataType: string
		displayFolder: Country
		lineageTag: f895467a-8b4f-4862-a6c6-0f057a88fac2
		summarizeBy: none
		sourceColumn: COUNTRY_OF_DOMICILE_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_OF_DOMICLE
		dataType: string
		displayFolder: Country
		lineageTag: 24f9a841-7e9b-4484-9b11-410806e8e117
		summarizeBy: none
		sourceColumn: COUNTRY_OF_DOMICLE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_OF_INCORPORATION
		dataType: string
		displayFolder: Country
		lineageTag: d39e9198-ee4c-476d-b214-15f5042c1e6f
		summarizeBy: none
		sourceColumn: COUNTRY_OF_INCORPORATION

		annotation SummarizationSetBy = Automatic

	column COUNTRY_OF_INCORPORATION_CODE
		dataType: string
		displayFolder: Country
		lineageTag: 00f5f158-85dc-400a-aea8-6869db5e0c77
		summarizeBy: none
		sourceColumn: COUNTRY_OF_INCORPORATION_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_OF_QUOTATION
		dataType: string
		displayFolder: Country
		lineageTag: 460502c8-61e8-4887-8125-c7565379fb6b
		summarizeBy: none
		sourceColumn: COUNTRY_OF_QUOTATION

		annotation SummarizationSetBy = Automatic

	column COUNTRY_OF_QUOTATION_CODE
		dataType: string
		displayFolder: Country
		lineageTag: c6ac93b9-9f5b-422a-b220-93e6a38af1d6
		summarizeBy: none
		sourceColumn: COUNTRY_OF_QUOTATION_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_OF_RISK
		dataType: string
		displayFolder: Country
		lineageTag: 3c7b89f0-b43b-4c3c-8616-21b45c4a2297
		summarizeBy: none
		sourceColumn: COUNTRY_OF_RISK

		annotation SummarizationSetBy = Automatic

	column COUNTRY_OF_RISK_CODE
		dataType: string
		displayFolder: Country
		lineageTag: 74b10e6e-f0e2-4368-a8f0-510d2fd2dfc4
		summarizeBy: none
		sourceColumn: COUNTRY_OF_RISK_CODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY_OF_RISK_CURRENCY
		dataType: string
		displayFolder: Country
		lineageTag: 1154f37a-9143-47c0-a4e2-3d7b3cc71bbb
		summarizeBy: none
		sourceColumn: COUNTRY_OF_RISK_CURRENCY

		annotation SummarizationSetBy = Automatic

	column COUNTRY_OF_RISK_CURRENCY_CODE
		dataType: string
		displayFolder: Country
		lineageTag: a92afc26-aecc-4bc8-81db-d79e5e2eb8cd
		summarizeBy: none
		sourceColumn: COUNTRY_OF_RISK_CURRENCY_CODE

		annotation SummarizationSetBy = Automatic

	column CUSIP
		dataType: string
		lineageTag: 9618e65c-1431-4d49-b3cf-408a6e553b42
		summarizeBy: none
		sourceColumn: CUSIP

		annotation SummarizationSetBy = Automatic

	column FACTSET_SECURITY_ID
		dataType: string
		lineageTag: 7a1c496d-05b9-4e6b-88a7-12150861691a
		summarizeBy: none
		sourceColumn: FACTSET_SECURITY_ID

		annotation SummarizationSetBy = Automatic

	column GICS_INDUSTRY
		dataType: string
		lineageTag: cbe7d7b7-7099-4239-afea-80985d86c10f
		summarizeBy: none
		sourceColumn: GICS_INDUSTRY

		annotation SummarizationSetBy = Automatic

	column GICS_INDUSTRY_CODE
		dataType: string
		lineageTag: ede0c45b-0175-4953-89ac-cd8248c3cf40
		summarizeBy: none
		sourceColumn: GICS_INDUSTRY_CODE

		annotation SummarizationSetBy = Automatic

	column GICS_INDUSTRY_GROUP
		dataType: string
		lineageTag: 8ea01ac6-c7c0-409e-bb14-bb6fe74c5bcb
		summarizeBy: none
		sourceColumn: GICS_INDUSTRY_GROUP

		annotation SummarizationSetBy = Automatic

	column GICS_INDUSTRY_GROUP_CODE
		dataType: string
		lineageTag: 72a7e438-62f7-4f17-97c5-b0f1eef2df81
		summarizeBy: none
		sourceColumn: GICS_INDUSTRY_GROUP_CODE

		annotation SummarizationSetBy = Automatic

	column GICS_SECTOR
		dataType: string
		lineageTag: 32e07fd5-0fd1-4ba0-a2c2-5d24555b1a6f
		summarizeBy: none
		sourceColumn: GICS_SECTOR

		annotation SummarizationSetBy = Automatic

	column GICS_SECTOR_CODE
		dataType: string
		lineageTag: 140cab16-0600-4dd2-8b41-081324009b7a
		summarizeBy: none
		sourceColumn: GICS_SECTOR_CODE

		annotation SummarizationSetBy = Automatic

	column GICS_SUB_INDUSTRY
		dataType: string
		lineageTag: e748405f-43dc-4bf2-a056-9f6adc7cc73e
		summarizeBy: none
		sourceColumn: GICS_SUB_INDUSTRY

		annotation SummarizationSetBy = Automatic

	column GICS_SUB_INDUSTRY_CODE
		dataType: string
		lineageTag: 779e0436-b7fc-4628-8a02-276d1d137219
		summarizeBy: none
		sourceColumn: GICS_SUB_INDUSTRY_CODE

		annotation SummarizationSetBy = Automatic

	column GLOBAL_PARENT_ISSUER
		dataType: string
		lineageTag: 5ce08762-bcff-4305-a877-da5b7b07517c
		summarizeBy: none
		sourceColumn: GLOBAL_PARENT_ISSUER

		annotation SummarizationSetBy = Automatic

	column ISIN
		dataType: string
		lineageTag: 33f3b528-606d-4732-9faf-f4b605dee1c8
		summarizeBy: none
		sourceColumn: ISIN

		annotation SummarizationSetBy = Automatic

	column ISSUE_LONG_TERM_FITCH_RATING
		dataType: string
		lineageTag: 0559ef12-5087-4415-b821-2b656f29b587
		summarizeBy: none
		sourceColumn: ISSUE_LONG_TERM_FITCH_RATING

		annotation SummarizationSetBy = Automatic

	column ISSUE_LONG_TERM_MOODY_RATING
		dataType: string
		lineageTag: 242b9e0c-a918-42d6-9fab-fcfaf4d2c2bf
		summarizeBy: none
		sourceColumn: ISSUE_LONG_TERM_MOODY_RATING

		annotation SummarizationSetBy = Automatic

	column ISSUE_LONG_TERM_SP_RATING
		dataType: string
		lineageTag: 375bb354-a70c-444f-90df-39656d03ea2d
		summarizeBy: none
		sourceColumn: ISSUE_LONG_TERM_SP_RATING

		annotation SummarizationSetBy = Automatic

	column ISSUE_SHORT_TERM_FITCH_RATING
		dataType: string
		lineageTag: 329dcdfa-ebbd-488a-afb6-eafd3399f5f4
		summarizeBy: none
		sourceColumn: ISSUE_SHORT_TERM_FITCH_RATING

		annotation SummarizationSetBy = Automatic

	column ISSUE_SHORT_TERM_MOODY_RATING
		dataType: string
		lineageTag: 24ef979f-c4b7-46a5-98f3-93fcf2087bb9
		summarizeBy: none
		sourceColumn: ISSUE_SHORT_TERM_MOODY_RATING

		annotation SummarizationSetBy = Automatic

	column ISSUE_SHORT_TERM_SP_RATING
		dataType: string
		lineageTag: 91578a30-e16c-4fa8-aa39-520a41838288
		summarizeBy: none
		sourceColumn: ISSUE_SHORT_TERM_SP_RATING

		annotation SummarizationSetBy = Automatic

	column ISSUER
		dataType: string
		lineageTag: 2abece32-ae85-440d-972c-268c9667fa4b
		summarizeBy: none
		sourceColumn: ISSUER

		annotation SummarizationSetBy = Automatic

	column ISSUER_LONG_TERM_FITCH_RATING
		dataType: string
		lineageTag: 3c162a03-8cd1-415d-8043-0e7191621f6a
		summarizeBy: none
		sourceColumn: ISSUER_LONG_TERM_FITCH_RATING

		annotation SummarizationSetBy = Automatic

	column ISSUER_LONG_TERM_MOODY_RATING
		dataType: string
		lineageTag: 16af7933-bf02-49a8-b46f-a51a9d806455
		summarizeBy: none
		sourceColumn: ISSUER_LONG_TERM_MOODY_RATING

		annotation SummarizationSetBy = Automatic

	column ISSUER_LONG_TERM_SP_RATING
		dataType: string
		lineageTag: 85adf992-b92c-4f18-8160-257f95ca18a2
		summarizeBy: none
		sourceColumn: ISSUER_LONG_TERM_SP_RATING

		annotation SummarizationSetBy = Automatic

	column ISSUER_SHORT_TERM_FITCH_RATING
		dataType: string
		lineageTag: e0cd73d2-f275-4375-aff1-65b0e0fb37a6
		summarizeBy: none
		sourceColumn: ISSUER_SHORT_TERM_FITCH_RATING

		annotation SummarizationSetBy = Automatic

	column ISSUER_SHORT_TERM_MOODY_RATING
		dataType: string
		lineageTag: cade688d-99e7-428d-8be5-31c0bd32ec6b
		summarizeBy: none
		sourceColumn: ISSUER_SHORT_TERM_MOODY_RATING

		annotation SummarizationSetBy = Automatic

	column ISSUER_SHORT_TERM_SP_RATING
		dataType: string
		lineageTag: ea1e0986-f7cb-4699-8036-39dac776e3ac
		summarizeBy: none
		sourceColumn: ISSUER_SHORT_TERM_SP_RATING

		annotation SummarizationSetBy = Automatic

	column LOAN_ID
		dataType: string
		lineageTag: 8f779c57-b594-44b3-a6d0-da6ed73644a1
		summarizeBy: none
		sourceColumn: LOAN_ID

		annotation SummarizationSetBy = Automatic

	column LONG_ASSET_DESC
		dataType: string
		lineageTag: 5cdbaa5e-152e-4baf-8e6a-4e80e791b068
		summarizeBy: none
		sourceColumn: LONG_ASSET_DESC

		annotation SummarizationSetBy = Automatic

	column LX_ID
		dataType: string
		lineageTag: 1801ff59-a36a-4030-b096-aeb9279604b4
		summarizeBy: none
		sourceColumn: LX_ID

		annotation SummarizationSetBy = Automatic

	column MATURITY_DATE
		dataType: dateTime
		formatString: General Date
		lineageTag: 3357bc53-abc0-4ff4-aef9-ebe72c98fb27
		summarizeBy: none
		sourceColumn: MATURITY_DATE

		variation Variation
			isDefault
			relationship: adc4277c-1384-4ceb-9f65-a90dfdb5534b
			defaultHierarchy: LocalDateTable_72a87172-ad22-46aa-b69d-9e7e830b1026.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column NORTHERN_TRUST_COUNTERPARTY_ID
		dataType: string
		lineageTag: ae1aba22-283a-4cf4-8a03-cd9d246cb782
		summarizeBy: none
		sourceColumn: NORTHERN_TRUST_COUNTERPARTY_ID

		annotation SummarizationSetBy = Automatic

	column PAYMENT_CURRENCY_CODE
		dataType: string
		lineageTag: 605879c2-d0c6-490f-8051-5b0996929b40
		summarizeBy: none
		sourceColumn: PAYMENT_CURRENCY_CODE

		annotation SummarizationSetBy = Automatic

	column PRICING_CURRENCY
		dataType: string
		lineageTag: eabaeb50-1c18-47a9-8b9f-db9193d07167
		summarizeBy: none
		sourceColumn: PRICING_CURRENCY

		annotation SummarizationSetBy = Automatic

	column PRICING_CURRENCY_CODE
		dataType: string
		lineageTag: 087fd285-e29b-4828-b770-94c3a787df3d
		summarizeBy: none
		sourceColumn: PRICING_CURRENCY_CODE

		annotation SummarizationSetBy = Automatic

	column PRIMARY_EXCHANGE_MARKET_ID
		dataType: string
		lineageTag: 668cc956-9d9c-43a4-b580-6da522b0aa22
		summarizeBy: none
		sourceColumn: PRIMARY_EXCHANGE_MARKET_ID

		annotation SummarizationSetBy = Automatic

	column REUTERS_ID
		dataType: string
		lineageTag: 1633763b-8743-4745-bf3a-06be31e9f49f
		summarizeBy: none
		sourceColumn: REUTERS_ID

		annotation SummarizationSetBy = Automatic

	column SEDOL
		dataType: string
		lineageTag: 32da6c7f-2154-42ba-9b3d-e55dade36975
		summarizeBy: none
		sourceColumn: SEDOL

		annotation SummarizationSetBy = Automatic

	column SHARES_OUTSTANDING_QUANTITY
		dataType: double
		lineageTag: 4a8e9861-f899-46c7-8fa3-dd04393ce6b6
		summarizeBy: sum
		sourceColumn: SHARES_OUTSTANDING_QUANTITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SHORT_ASSET_DESC
		dataType: string
		lineageTag: 5bbfda3a-c125-465a-b5ef-77f53b6934c3
		summarizeBy: none
		sourceColumn: SHORT_ASSET_DESC

		annotation SummarizationSetBy = Automatic

	column SOURCE_ASSET_SUB_NAME
		dataType: string
		lineageTag: 6226c832-f1c7-4ff1-a5f1-3027178467ec
		summarizeBy: none
		sourceColumn: SOURCE_ASSET_SUB_NAME

		annotation SummarizationSetBy = Automatic

	column SOURCE_ASSET_SUPER_NAME
		dataType: string
		lineageTag: 43ca4a36-6cd6-4b4a-846d-9e312ee591db
		summarizeBy: none
		sourceColumn: SOURCE_ASSET_SUPER_NAME

		annotation SummarizationSetBy = Automatic

	column SOURCE_ASSET_TYPE_CODE
		dataType: string
		lineageTag: 30c0c236-251a-4580-bbcf-683dfaff1c87
		summarizeBy: none
		sourceColumn: SOURCE_ASSET_TYPE_CODE

		annotation SummarizationSetBy = Automatic

	column SOURCE_INSTRUMENT_ID
		dataType: string
		lineageTag: 014d6670-7992-472b-a936-6b70a2d02d47
		summarizeBy: none
		sourceColumn: SOURCE_INSTRUMENT_ID

		annotation SummarizationSetBy = Automatic

	column SOURCE_ISSUE_ID
		dataType: string
		lineageTag: f4c37f55-818b-4f44-8c7a-bfdd9b086efb
		summarizeBy: none
		sourceColumn: SOURCE_ISSUE_ID

		annotation SummarizationSetBy = Automatic

	column SOURCE_UNDERLYING_ASSET_ID
		dataType: string
		lineageTag: fd9b4754-7109-42ab-9618-526c88aac688
		summarizeBy: none
		sourceColumn: SOURCE_UNDERLYING_ASSET_ID

		annotation SummarizationSetBy = Automatic

	column UNDERLYING_INSTRUMENT_DESC
		dataType: string
		lineageTag: dfb4ef34-ec5d-410d-a696-e7bb86dff89f
		summarizeBy: none
		sourceColumn: UNDERLYING_INSTRUMENT_DESC

		annotation SummarizationSetBy = Automatic

	column COUNTRY_CODE_RISK_RATING
		dataType: string
		displayFolder: Country
		lineageTag: 01038bb9-80f6-41bb-b821-aa80a7300e96
		summarizeBy: none
		sourceColumn: COUNTRY_CODE_RISK_RATING

		annotation SummarizationSetBy = Automatic

	column GICS_SECTORS_SHORT
		dataType: string
		lineageTag: a536c9ab-5e18-41f7-b135-6dac317d0f00
		summarizeBy: none
		sourceColumn: GICS_SECTORS_SHORT

		annotation SummarizationSetBy = Automatic

	partition 'GS Asset-7dbd9444-595c-4d67-9e58-b83a17ca1a22' = m
		mode: import
		queryGroup: Sustainalytics
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=p_databricks_catalog,Kind="Database"]}[Data],
				    sustainalytics_Schema = hive_metastore_Database{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_gs_asset_v1_Table = sustainalytics_Schema{[Name="semantic_gs_asset_v1",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(semantic_gs_asset_v1_Table,{"MODIFIED_TIME", "INPUT_MODIFIED_TIME"})
				    ,  FilterLogic = 
				    if 
				         p_limit_rows = "Y" 
				    then
				     Table.FirstN(
				      #"Removed Columns", 
				      100
				     )
				 else 
				     #"Removed Columns"
				in
				    FilterLogic
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

