table 'Market Cap Type'
	lineageTag: f1ea2914-bb7a-4808-8dff-ccb91e7e416f

	measure Market_Cap_Switch = SELECTEDVALUE('Market Cap Type'[Market_Cap_Code],1)
		formatString: 0
		lineageTag: 2d21224a-b046-4b6a-b319-681cf82aea8b

	column Market_Cap_Code
		dataType: int64
		formatString: 0
		lineageTag: a21af1a2-7378-4b3b-ae74-f8ac0c88e397
		summarizeBy: count
		sourceColumn: Market_Cap_Code

		annotation SummarizationSetBy = Automatic

	column Market_Cap_Name
		dataType: string
		lineageTag: b39881ac-8004-44d4-9883-e5baa6265466
		summarizeBy: none
		sourceColumn: Market_Cap_Name

		annotation SummarizationSetBy = Automatic

	partition 'Market Cap Type' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfJNLMpOLVFwTixQitWJVjICCrmGeTorxcYCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Market_Cap_Code = _t, Market_Cap_Name = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Market_Cap_Code", Int64.Type}, {"Market_Cap_Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

