table 'Scope Emission Types'
	lineageTag: bd4db744-f7d4-416a-b439-d03bb5a52b9a

	column Scope_Type_Code
		dataType: int64
		formatString: 0
		lineageTag: 90c7a182-5717-4f56-a662-12864513ebae
		summarizeBy: count
		sourceColumn: Scope_Type_Code

		annotation SummarizationSetBy = Automatic

	column Scope_Type_Desc
		dataType: string
		lineageTag: 07dea34f-bbf0-44c7-a0eb-224ccdb6efba
		summarizeBy: none
		sourceColumn: Scope_Type_Desc

		annotation SummarizationSetBy = Automatic

	partition 'Scope Emission Types' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQpOzi9IVTBU0FYwUorViVYyQhUDYmMFl/zyvOKSotTEXLASYyxKQguQFJjgNQNVeSwA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Scope_Type_Code = _t, Scope_Type_Desc = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Scope_Type_Code", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

