table semantic_ri_country_risk_v1
	lineageTag: 23a4b1d0-dcb1-406f-ae0e-840dfb9fc40e

	measure RI_Country_Risk_Context =
			
			VAR _risk =
			    CALCULATE(
			        SELECTEDVALUE( semantic_ri_country_risk_v1[RI_Country_Risk] ),
			        REMOVEFILTERS( 'Daily Position'[FUND], 'Daily Position'[Is Latest] )
			    )
			RETURN
			SWITCH(
			    _risk,
			    "Low", 1,
			    "Low-Medium", 2,
			    "Medium", 3,
			    "Medium-High", 4,
			    "High", 5,
			    BLANK()
			)
		formatString: 0
		lineageTag: a3e1df77-3861-4312-aac7-792c4b1709a8

	column Country_Code
		dataType: string
		lineageTag: d4706dbd-9a45-47be-ab38-42b9916f6877
		summarizeBy: none
		sourceColumn: Country_Code

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: efecf461-a7ef-4a81-9922-1ab90ff7c240
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 16edaa96-7b8f-4410-b252-914f6a884baa
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country_Score
		dataType: double
		lineageTag: 008197ad-70b9-4214-89d3-bef78ee6fd85
		summarizeBy: sum
		sourceColumn: Country_Score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Base_Country_Risk
		dataType: string
		lineageTag: e3723bf2-f66b-474a-a75c-331cce19c969
		summarizeBy: none
		sourceColumn: Base_Country_Risk

		annotation SummarizationSetBy = Automatic

	column Conflict_Score
		dataType: string
		lineageTag: 4eee4831-a014-46d7-aeed-80cc6f72c94f
		summarizeBy: none
		sourceColumn: Conflict_Score

		annotation SummarizationSetBy = Automatic

	column Base_Conflict_Risk
		dataType: string
		lineageTag: f419b687-be13-4462-ba28-4250080a783e
		summarizeBy: none
		sourceColumn: Base_Conflict_Risk

		annotation SummarizationSetBy = Automatic

	column RI_Country_Risk
		dataType: string
		lineageTag: bd9a0dd3-aba3-4946-97cf-6bbef921e497
		summarizeBy: none
		sourceColumn: RI_Country_Risk
		sortByColumn: RI_Country_Risk_Rank

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column RI_Country_Risk_Rank
		dataType: string
		lineageTag: 57a80278-e3bd-4844-93ec-7115551b8734
		summarizeBy: none
		sourceColumn: RI_Country_Risk_Rank

		annotation SummarizationSetBy = Automatic

	column Valid_From
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: c2cc7e34-2aec-4bbe-82ef-fdd465c02278
		summarizeBy: none
		sourceColumn: Valid_From

		variation Variation
			isDefault
			relationship: 4c3cac8d-f1cd-402d-a11f-efff6d2d1e70
			defaultHierarchy: LocalDateTable_79ece6e6-8e1d-42e5-88ca-de260ac593e2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Valid_To
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: ddffd737-dd50-4dda-aba9-d2371f52906b
		summarizeBy: none
		sourceColumn: Valid_To

		variation Variation
			isDefault
			relationship: 3e9c8aee-5f0d-4405-91a2-ebd68c3640f5
			defaultHierarchy: LocalDateTable_004e52da-6b0f-4122-82a6-e9587536a271.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Is_Current
		dataType: string
		lineageTag: a2e56bf6-e264-4f3c-ab15-0a77d6e20909
		summarizeBy: none
		sourceColumn: Is_Current

		annotation SummarizationSetBy = Automatic

	column Region_2
		dataType: string
		lineageTag: b2b1c613-b634-4668-afae-2e7eeadffb3d
		summarizeBy: none
		sourceColumn: Region_2

		annotation SummarizationSetBy = Automatic

	partition semantic_ri_country_risk_v1 = m
		mode: import
		queryGroup: Sustainalytics
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    Schema = Table.SelectRows(hive_metastore_Database, each ([Name] =p_sustainalytics_database)),
				    sustainalytics_Schema = Schema{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_ri_country_risk_v1_Table = sustainalytics_Schema{[Name="semantic_ri_country_risk_v1",Kind="Table"]}[Data],
				    #"Sorted Rows" = Table.Sort(semantic_ri_country_risk_v1_Table,{{"Valid_From", Order.Descending}}),
				    #"Merged Queries" = Table.NestedJoin(#"Sorted Rows", {"Country_Code"}, #"ESG Country", {"IsoAlpha2Code"}, "ESG Country", JoinKind.LeftOuter),
				    #"Expanded ESG Country" = Table.ExpandTableColumn(#"Merged Queries", "ESG Country", {"Region"}, {"ESG Country.Region"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded ESG Country",{{"ESG Country.Region", "Region_2"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

