table semantic_gics_sasb_v1
	lineageTag: 1fc1fbf9-674b-41c6-a84f-7d6ccac94adf

	column Unique_Key
		dataType: string
		lineageTag: ac673c11-9bbb-49db-9015-be521888322e
		summarizeBy: none
		sourceColumn: Unique_Key

		annotation SummarizationSetBy = Automatic

	column GICS_SubIndustry_Code
		dataType: string
		lineageTag: 89b39ff8-9471-4254-967d-f7a38cacf51b
		summarizeBy: none
		sourceColumn: GICS_SubIndustry_Code

		annotation SummarizationSetBy = Automatic

	column GICS_SubIndustry
		dataType: string
		lineageTag: bb35a3e9-3e4a-4db6-95e0-d3b163ba96b4
		summarizeBy: none
		sourceColumn: GICS_SubIndustry

		annotation SummarizationSetBy = Automatic

	column SASB_ID
		dataType: string
		lineageTag: 59c24592-8818-46e8-a0a5-3bf30a283822
		summarizeBy: none
		sourceColumn: SASB_ID

		annotation SummarizationSetBy = Automatic

	column SASB_Sector
		dataType: string
		lineageTag: 5124f60c-28ed-495b-b4a4-e35e7221cd69
		summarizeBy: none
		sourceColumn: SASB_Sector

		annotation SummarizationSetBy = Automatic

	column SASB_Industry
		dataType: string
		lineageTag: 528e52fd-b5b2-42bb-8c07-064a1ea6e40b
		summarizeBy: none
		sourceColumn: SASB_Industry

		annotation SummarizationSetBy = Automatic

	column SASB_Issue
		dataType: string
		lineageTag: 432162e6-1449-45ec-b254-1307593a13ce
		summarizeBy: none
		sourceColumn: SASB_Issue

		annotation SummarizationSetBy = Automatic

	column SASB_Dimension
		dataType: string
		lineageTag: fd4a5a6a-d2f7-4b48-8642-fff9a1dfc7db
		summarizeBy: none
		sourceColumn: SASB_Dimension

		annotation SummarizationSetBy = Automatic

	partition semantic_gics_sasb_v1 = m
		mode: import
		queryGroup: Sustainalytics
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    Schema = Table.SelectRows(hive_metastore_Database, each ([Name] =p_sustainalytics_database)),
				    sustainalytics_Schema = Schema{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_gics_sasb_v1_Table = sustainalytics_Schema{[Name="semantic_gics_sasb_v1",Kind="Table"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(semantic_gics_sasb_v1_Table,"_"," ",Replacer.ReplaceText,{"SASB_Issue"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

