table semantic_modern_slavery_ri_country_risk_v1
	lineageTag: 8c1599a7-cd23-43e3-97a2-56ac7eb2115c

	column Country_Code
		dataType: string
		lineageTag: 0fa91b98-2be3-4021-9418-859c087260dc
		summarizeBy: none
		sourceColumn: Country_Code

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 9559a245-a545-4fab-9dd5-15ecf101b3a1
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 396a2789-09ae-46e1-9d05-d1936ecd93af
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Population
		dataType: int64
		formatString: 0
		lineageTag: b03bfd46-1f89-40b7-abac-34510ac270e3
		summarizeBy: sum
		sourceColumn: Population

		annotation SummarizationSetBy = Automatic

	column Modern_Slavery_Prevalence_Percent
		dataType: double
		lineageTag: 46cc972a-191e-4aa1-829f-ec539ef1d1e5
		summarizeBy: sum
		sourceColumn: Modern_Slavery_Prevalence_Percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Modern_Slavery_Population
		dataType: int64
		formatString: 0
		lineageTag: 5da7cba2-98fa-4717-9eb0-b30701cc48a8
		summarizeBy: sum
		sourceColumn: Modern_Slavery_Population

		annotation SummarizationSetBy = Automatic

	column Modern_Slavery_Prevalence_Score
		dataType: int64
		formatString: 0
		lineageTag: 1caef96c-7637-446c-b9ad-da0ea96bd110
		summarizeBy: sum
		sourceColumn: Modern_Slavery_Prevalence_Score

		annotation SummarizationSetBy = Automatic

	column Prevalence_Weighting
		dataType: int64
		formatString: 0
		lineageTag: baf53b28-7846-4478-8a97-e284466052a0
		summarizeBy: sum
		sourceColumn: Prevalence_Weighting

		annotation SummarizationSetBy = Automatic

	column Vulnerabiltiy_Rating
		dataType: double
		lineageTag: cc73cf8e-eed2-4460-baa4-70a3c8a91971
		summarizeBy: sum
		sourceColumn: Vulnerabiltiy_Rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Modern_Slavery_Vulnerability_Rating_Score
		dataType: int64
		formatString: 0
		lineageTag: e5f3afbd-1b3e-47ed-8ef0-67a966b1aac0
		summarizeBy: sum
		sourceColumn: Modern_Slavery_Vulnerability_Rating_Score

		annotation SummarizationSetBy = Automatic

	column Vulnerability_Weighting
		dataType: int64
		formatString: 0
		lineageTag: 841cf002-70be-467d-963d-88e51a02cbe3
		summarizeBy: sum
		sourceColumn: Vulnerability_Weighting

		annotation SummarizationSetBy = Automatic

	column Government_Response_Rating
		dataType: double
		lineageTag: a96d4b4c-9bcb-41c2-9dd6-580b14cbfc32
		summarizeBy: sum
		sourceColumn: Government_Response_Rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Modern_Slavery_Response
		dataType: int64
		formatString: 0
		lineageTag: 37705cbc-dcb0-4315-b875-f6362bd4abdb
		summarizeBy: sum
		sourceColumn: Modern_Slavery_Response

		annotation SummarizationSetBy = Automatic

	column Government_Response_Weighting
		dataType: double
		lineageTag: a7562574-99e7-41ce-a40f-520bc4efd012
		summarizeBy: sum
		sourceColumn: Government_Response_Weighting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Combined_Score
		dataType: double
		lineageTag: 69579924-645b-4797-90fd-6321a3759d84
		summarizeBy: sum
		sourceColumn: Combined_Score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overall_Country_Rating
		dataType: string
		lineageTag: 2ee81f5e-b970-4a98-a10f-ddf6fc3d96d4
		summarizeBy: none
		sourceColumn: Overall_Country_Rating
		sortByColumn: Overall_Country_Rating_Rank

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Allens_Score
		dataType: string
		lineageTag: 07fc8739-b0fb-48a0-a567-911a87ce9c0d
		summarizeBy: none
		sourceColumn: Allens_Score

		annotation SummarizationSetBy = Automatic

	column Proxies
		dataType: string
		lineageTag: c1af0fd9-f1f2-40eb-84c8-45815b310845
		summarizeBy: none
		sourceColumn: Proxies

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: 41d7804b-d075-4a4e-80fc-60c53ec54359
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column Country_Score
		dataType: double
		lineageTag: f7c5f7dc-7465-415f-a125-7b70121d33dc
		summarizeBy: sum
		sourceColumn: Country_Score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Base_Country_Risk
		dataType: string
		lineageTag: 52426675-3b1f-4e83-b61d-ec287e2a3258
		summarizeBy: none
		sourceColumn: Base_Country_Risk

		annotation SummarizationSetBy = Automatic

	column Conflict_Score
		dataType: double
		lineageTag: 65fce8f2-6cb7-47ae-98dc-c20d64679a9e
		summarizeBy: sum
		sourceColumn: Conflict_Score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Base_Conflict_Risk
		dataType: string
		lineageTag: 5526aa8f-4633-4977-a7d5-376aeef62d85
		summarizeBy: none
		sourceColumn: Base_Conflict_Risk

		annotation SummarizationSetBy = Automatic

	column RI_Country_Risk
		dataType: string
		lineageTag: 001764d4-2215-4814-b4d9-d9183cf13409
		summarizeBy: none
		sourceColumn: RI_Country_Risk
		sortByColumn: RI_Country_Risk_Rank

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column RI_Country_Risk_Rank
		dataType: double
		lineageTag: 384b0951-d048-490b-a638-07f5842ebcb4
		summarizeBy: sum
		sourceColumn: RI_Country_Risk_Rank

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Valid_From
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: b8ff7756-2aa3-4b83-9c8e-fd724d7523b0
		summarizeBy: none
		sourceColumn: Valid_From

		variation Variation
			isDefault
			relationship: 60fbe27d-86e5-4cb3-b630-d350e5eb48db
			defaultHierarchy: LocalDateTable_094672e9-e115-43c1-b89e-ac3c02e0d192.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Valid_To
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 8c8818df-0e6e-4f8c-961a-9112649e2caf
		summarizeBy: none
		sourceColumn: Valid_To

		variation Variation
			isDefault
			relationship: 7ed438a0-91f2-4b50-acf5-f01e572e1f74
			defaultHierarchy: LocalDateTable_9f789bd3-c409-42c4-bce3-28cbcab776ad.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Is_Current
		dataType: string
		lineageTag: e79f2380-5c91-4173-990d-019aa17970fd
		summarizeBy: none
		sourceColumn: Is_Current

		annotation SummarizationSetBy = Automatic

	column Overall_Country_Rating_Rank
		dataType: double
		lineageTag: 80522a42-63c0-4410-8522-14729c7313ed
		summarizeBy: sum
		sourceColumn: Overall_Country_Rating_Rank

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Region_2
		dataType: string
		lineageTag: 6bb3ea7e-cc7f-4b51-baec-b02962f4bbbf
		summarizeBy: none
		sourceColumn: Region_2

		annotation SummarizationSetBy = Automatic

	partition semantic_modern_slavery_ri_country_risk_v1 = m
		mode: import
		queryGroup: Sustainalytics
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    Schema = Table.SelectRows(hive_metastore_Database, each ([Name] =p_sustainalytics_database)),
				    sustainalytics_Schema = Schema{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_modern_slavery_ri_country_risk_v1_Table = sustainalytics_Schema{[Name="semantic_modern_slavery_ri_country_risk_v1",Kind="Table"]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(semantic_modern_slavery_ri_country_risk_v1_Table, "Overall_Country_Rating_Rank", each if [Overall_Country_Rating] = "High" then 1 else if [Overall_Country_Rating] = "Medium-High" then 2 else if [Overall_Country_Rating] = "Medium" then 3 else if [Overall_Country_Rating] = "Moderate" then 3.5 else if [Overall_Country_Rating] = "Low-Medium" then 4 else if [Overall_Country_Rating] = "Low" then 5 else null),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Conditional Column",{"Country_Code", "Country", "Region", "Population", "Modern_Slavery_Prevalence_Percent", "Modern_Slavery_Population", "Modern_Slavery_Prevalence_Score", "Prevalence_Weighting", "Vulnerabiltiy_Rating", "Modern_Slavery_Vulnerability_Rating_Score", "Vulnerability_Weighting", "Government_Response_Rating", "Modern_Slavery_Response", "Government_Response_Weighting", "Combined_Score", "Overall_Country_Rating", "Overall_Country_Rating_Rank", "Allens_Score", "Proxies", "Notes", "Country_Score", "Base_Country_Risk", "Conflict_Score", "Base_Conflict_Risk", "RI_Country_Risk", "RI_Country_Risk_Rank", "Valid_From", "Valid_To"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Reordered Columns",{{"RI_Country_Risk_Rank", type number}, {"Overall_Country_Rating_Rank", type number}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Valid_From", Order.Descending}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Sorted Rows",{{"Country_Code", type text}, {"Population", Int64.Type}, {"Modern_Slavery_Prevalence_Percent", type number}, {"Modern_Slavery_Population", Int64.Type}, {"Vulnerabiltiy_Rating", type number}, {"Government_Response_Rating", type number}, {"Conflict_Score", type number}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type1", {{"Modern_Slavery_Population", 0}}),
				    #"Replaced Errors1" = Table.ReplaceErrorValues(#"Replaced Errors", {{"Modern_Slavery_Prevalence_Percent", 0}}),
				    #"Replaced Errors2" = Table.ReplaceErrorValues(#"Replaced Errors1", {{"Vulnerabiltiy_Rating", 0}}),
				    #"Replaced Errors3" = Table.ReplaceErrorValues(#"Replaced Errors2", {{"Government_Response_Rating", 0}}),
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Errors3", {"Country_Code"}, #"ESG Country", {"IsoAlpha2Code"}, "ESG Country", JoinKind.LeftOuter),
				    #"Expanded ESG Country" = Table.ExpandTableColumn(#"Merged Queries", "ESG Country", {"Region"}, {"ESG Country.Region"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded ESG Country",{{"ESG Country.Region", "Region_2"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

