table semantic_esg_country_risk_rating_v1
	lineageTag: 68ff8fb9-38a3-4141-ac38-610639ccfb87

	measure html_element_modern_slavery =
			
			VAR _Country = IF(ISBLANK(SELECTEDVALUE(semantic_esg_country_risk_rating_v1[Country])), "Australia", SELECTEDVALUE(semantic_esg_country_risk_rating_v1[Country]))
			VAR _ChildLabor = IF(ISBLANK(SELECTEDVALUE(semantic_esg_country_risk_rating_v1[Good_ChildLabor])), " ", SELECTEDVALUE(semantic_esg_country_risk_rating_v1[Good_ChildLabor]))
			VAR _ForcedLabor = IF(ISBLANK(SELECTEDVALUE(semantic_esg_country_risk_rating_v1[Good_ForcedLabor])), " ", SELECTEDVALUE(semantic_esg_country_risk_rating_v1[Good_ForcedLabor]))
			VAR _Notes = IF(ISBLANK(SELECTEDVALUE(semantic_esg_country_risk_rating_v1[Notes])), " ", SELECTEDVALUE(semantic_esg_country_risk_rating_v1[Notes]))
			
			RETURN
			"<div class='HtmlPanel'>
			<div class='CountryName'>" & _Country & "</div>
			<div class='Heading'>Goods: Child Labor</div>
			<div class='InfoSection'>" & _ChildLabor & "</div>
			<div class='Heading'>Goods: Forced Labor</div>
			<div class='InfoSection'>" & _ForcedLabor & "</div>
			<div class='Heading'>Notes</div>
			<div class='InfoSection'>" & _Notes & "</div>
			</div>"
		lineageTag: 6a7094d2-d964-4c43-be32-bdb4df53c674

	measure Overall_Country_Rating_Context =
			
			VAR _risk =
			    CALCULATE(
			        SELECTEDVALUE( semantic_esg_country_risk_rating_v1[Overall_Country_Rating] ),
			        REMOVEFILTERS( 'Daily Position'[FUND], 'Daily Position'[Is Latest] )
			    )
			RETURN
			SWITCH(
			    _risk,
			    "Low", 1,
			    "Low-Medium", 2,
			    "Medium", 3,
			    "Moderate", 3.5,
			    "Medium-High", 4,
			    "High", 5,
			    BLANK()
			)
		lineageTag: d856c6f3-4793-4201-985d-085092e36e76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Country_Code
		dataType: string
		lineageTag: 9d01a757-5996-4aab-ba57-87391daa4153
		summarizeBy: none
		sourceColumn: Country_Code

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 8e8b6c4d-21c1-4a18-961b-a7e5968f72af
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 6aed915d-b98f-4c4b-94b7-5821947962ba
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Population
		dataType: string
		lineageTag: e1daecd8-2504-4692-a2ff-e96f4991efed
		summarizeBy: none
		sourceColumn: Population

		annotation SummarizationSetBy = Automatic

	column Modern_Slavery_Prevalence_Percent
		dataType: string
		lineageTag: ad2ad701-bd82-48e3-a2e3-e401ff012682
		summarizeBy: none
		sourceColumn: Modern_Slavery_Prevalence_Percent

		annotation SummarizationSetBy = Automatic

	column Modern_Slavery_Population
		dataType: string
		lineageTag: 1caa43f7-e202-4e16-9bfa-e457c6969dfe
		summarizeBy: none
		sourceColumn: Modern_Slavery_Population

		annotation SummarizationSetBy = Automatic

	column Modern_Slavery_Prevalence_Score
		dataType: int64
		formatString: 0
		lineageTag: 59ad7aa7-fbca-4a2c-a482-a61142fa9b8e
		summarizeBy: sum
		sourceColumn: Modern_Slavery_Prevalence_Score

		annotation SummarizationSetBy = Automatic

	column Prevalence_Weighting
		dataType: int64
		formatString: 0
		lineageTag: 9e3e9e6e-7957-4cf1-8bf5-0cf22fac029e
		summarizeBy: sum
		sourceColumn: Prevalence_Weighting

		annotation SummarizationSetBy = Automatic

	column Vulnerabiltiy_Rating
		dataType: string
		lineageTag: 6abc5871-a8eb-4d8a-af8a-1f3030e8baf7
		summarizeBy: none
		sourceColumn: Vulnerabiltiy_Rating

		annotation SummarizationSetBy = Automatic

	column Modern_Slavery_Vulnerability_Rating_Score
		dataType: int64
		formatString: 0
		lineageTag: 9d655113-158a-4159-82a8-381a9bc72d37
		summarizeBy: sum
		sourceColumn: Modern_Slavery_Vulnerability_Rating_Score

		annotation SummarizationSetBy = Automatic

	column Vulnerability_Weighting
		dataType: int64
		formatString: 0
		lineageTag: 2a85b1f0-16f2-4882-8dea-a9e47d2d2897
		summarizeBy: sum
		sourceColumn: Vulnerability_Weighting

		annotation SummarizationSetBy = Automatic

	column Government_Response_Rating
		dataType: string
		lineageTag: 7659509e-c16d-478e-ae02-ca0c2460542b
		summarizeBy: none
		sourceColumn: Government_Response_Rating

		annotation SummarizationSetBy = Automatic

	column Modern_Slavery_Response
		dataType: int64
		formatString: 0
		lineageTag: 4c4fac66-fa50-45a7-9b48-198a0850e170
		summarizeBy: sum
		sourceColumn: Modern_Slavery_Response

		annotation SummarizationSetBy = Automatic

	column Government_Response_Weighting
		dataType: double
		lineageTag: 8483296d-a858-4482-a58f-9cef374ad52c
		summarizeBy: sum
		sourceColumn: Government_Response_Weighting

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Combined_Score
		dataType: double
		lineageTag: 1c85db06-4dd7-48ce-aad3-b0fa6809c188
		summarizeBy: sum
		sourceColumn: Combined_Score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Overall_Country_Rating
		dataType: string
		lineageTag: 1dee4fcc-cad2-4c8a-a15b-ad491c9e00f1
		summarizeBy: none
		sourceColumn: Overall_Country_Rating
		sortByColumn: Overall_Country_Rating_Rank

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Allens_Score
		dataType: string
		lineageTag: f1f0329e-2a44-49f5-a044-4ecff13abee7
		summarizeBy: none
		sourceColumn: Allens_Score

		annotation SummarizationSetBy = Automatic

	column Proxies
		dataType: string
		lineageTag: d317d4d5-f7c4-47e7-a529-b3fb98711352
		summarizeBy: none
		sourceColumn: Proxies

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: 3afed20b-5b82-4ecf-80f4-c3865f0d6224
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column Valid_From
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: ecbbbab1-db6a-4c49-a61c-99c2874fde4f
		summarizeBy: none
		sourceColumn: Valid_From

		variation Variation
			isDefault
			relationship: 41d3716b-e340-4a0b-926f-5c81666e611c
			defaultHierarchy: LocalDateTable_063cc571-0c71-4d2f-a804-4f6d23481aa7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Valid_To
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: ddf95fca-50d5-402e-94a4-5ef902af8f55
		summarizeBy: none
		sourceColumn: Valid_To

		variation Variation
			isDefault
			relationship: b8d0fbfb-41e7-4fd6-8804-92223c529953
			defaultHierarchy: LocalDateTable_f912ec4a-3546-4a26-9bab-7660d585fcc9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Is_Current
		dataType: string
		lineageTag: 303b08f3-58e8-44b0-a222-8d0d748e8637
		summarizeBy: none
		sourceColumn: Is_Current

		annotation SummarizationSetBy = Automatic

	column Is_Deleted
		dataType: string
		lineageTag: 3b9aaf4f-993b-4b57-abb3-ae407d2d96ba
		summarizeBy: none
		sourceColumn: Is_Deleted

		annotation SummarizationSetBy = Automatic

	column Row_SHA2
		dataType: string
		lineageTag: c55e313e-723b-4507-9c2e-912d9e67a77a
		summarizeBy: none
		sourceColumn: Row_SHA2

		annotation SummarizationSetBy = Automatic

	column Esg_Metric
		dataType: string
		lineageTag: a9d84604-e235-4530-b7e2-125174c0654b
		summarizeBy: none
		sourceColumn: Esg_Metric

		annotation SummarizationSetBy = Automatic

	column gcl_CountryArea
		dataType: string
		lineageTag: 1c902ef0-090e-4f1b-a7b6-67d5ed121da0
		summarizeBy: none
		sourceColumn: gcl_CountryArea

		annotation SummarizationSetBy = Automatic

	column gcl_OfficialName
		dataType: string
		lineageTag: 0137c19f-ead7-4bf8-a20a-cb837d678669
		summarizeBy: none
		sourceColumn: gcl_OfficialName

		annotation SummarizationSetBy = Automatic

	column gcl_IsoAlpha2Code
		dataType: string
		lineageTag: 28e9b0b3-fb85-4e79-96fe-bd9ad73230c2
		summarizeBy: none
		sourceColumn: gcl_IsoAlpha2Code

		annotation SummarizationSetBy = Automatic

	column gcl_Valid_From
		dataType: dateTime
		formatString: Long Date
		lineageTag: c54aeb4e-b6b4-4bf9-9229-61e6fece049d
		summarizeBy: none
		sourceColumn: gcl_Valid_From

		variation Variation
			isDefault
			relationship: e9d11cee-70cc-47eb-9562-640d83ba3237
			defaultHierarchy: LocalDateTable_926c1f78-6256-44e3-bd48-1b928a80672c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column gcl_Valid_To
		dataType: dateTime
		formatString: Long Date
		lineageTag: 21cb134f-87e6-4364-94b9-d67593328f3c
		summarizeBy: none
		sourceColumn: gcl_Valid_To

		variation Variation
			isDefault
			relationship: 2753fbf0-9728-496b-bfb3-8aed68857c9f
			defaultHierarchy: LocalDateTable_f3b91377-1755-4654-8bef-9b2a4b7f060c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Good_ChildLabor
		dataType: string
		lineageTag: 569e8fcb-3883-439b-84ef-3219cdbb57f0
		summarizeBy: none
		sourceColumn: Good_ChildLabor

		annotation SummarizationSetBy = Automatic

	column Good_ForcedLabor
		dataType: string
		lineageTag: 37069d10-a1c9-4a12-95f1-44637822b4a0
		summarizeBy: none
		sourceColumn: Good_ForcedLabor

		annotation SummarizationSetBy = Automatic

	column Overall_Country_Rating_Rank
		dataType: double
		lineageTag: 5e16aabe-b3f8-425c-b204-3a14c901a919
		summarizeBy: sum
		sourceColumn: Overall_Country_Rating_Rank

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Is_Current_2
		dataType: string
		lineageTag: 7fe129d9-7966-435f-97de-60528a41560d
		summarizeBy: none
		sourceColumn: Is_Current_2

		annotation SummarizationSetBy = Automatic

	column Region_2
		dataType: string
		lineageTag: 3c73fbaf-7b15-4ed1-8a77-2804f3604928
		summarizeBy: none
		sourceColumn: Region_2

		annotation SummarizationSetBy = Automatic

	partition semantic_esg_country_risk_rating_v1 = m
		mode: import
		queryGroup: Sustainalytics
		source =
				let
				    Source = DatabricksMultiCloud.Catalogs(p_databricks_host, p_databricks_path, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    Schema = Table.SelectRows(hive_metastore_Database, each ([Name] =p_sustainalytics_database)),
				    sustainalytics_Schema = Schema{[Name=p_sustainalytics_database,Kind="Schema"]}[Data],
				    semantic_esg_country_risk_rating_v1_Table = sustainalytics_Schema{[Name="semantic_esg_country_risk_rating_v1",Kind="Table"]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(semantic_esg_country_risk_rating_v1_Table, "Overall_Country_Rating_Rank", each if [Overall_Country_Rating] = "Low" then 5 else if [Overall_Country_Rating] = "Low-Medium" then 4 else if [Overall_Country_Rating] = "Moderate" then 3.5 else if [Overall_Country_Rating] = "Medium" then 3 else if [Overall_Country_Rating] = "Medium-High" then 2 else if [Overall_Country_Rating] = "High" then 1 else null),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Overall_Country_Rating_Rank", type number}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Valid_From", Order.Descending}}),
				    #"Added Custom" = Table.AddColumn(#"Sorted Rows", "Is_Current_2", each if [Valid_From] = List.Max(#"Sorted Rows"[Valid_From]) then "Y" else "N"),
				    #"Merged Queries" = Table.NestedJoin(#"Added Custom", {"Country_Code"}, #"ESG Country", {"IsoAlpha2Code"}, "ESG Country", JoinKind.LeftOuter),
				    #"Expanded ESG Country" = Table.ExpandTableColumn(#"Merged Queries", "ESG Country", {"Region"}, {"ESG Country.Region"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded ESG Country",{{"ESG Country.Region", "Region_2"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

