table 'Sigwatch Topic'
	lineageTag: 83ffccd6-2596-49c6-a21a-656b86a1cfcb

	column 'Topic Code'
		dataType: string
		lineageTag: ead9d9e3-56e6-42af-bb2a-a81d97bd1dff
		summarizeBy: none
		sourceColumn: Topic Code

		annotation SummarizationSetBy = Automatic

	column 'Topic Name'
		dataType: string
		lineageTag: 47479e9d-282f-442d-809b-d1217bcaeb38
		summarizeBy: none
		sourceColumn: Topic Name

		annotation SummarizationSetBy = Automatic

	partition 'Sigwatch Topic' = m
		mode: import
		queryGroup: Sigwatch
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(#"p_databricks_host", #"p_databricks_path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=#"p_databricks_catalog",Kind="Database"]}[Data],
				    sigwatch_Schema = hive_metastore_Database{[Name=p_sigwatch_database,Kind="Schema"]}[Data],
				    sigwatch_corporate_topic = sigwatch_Schema{[Name="pub_dim_corporate_topic",Kind="Table"]}[Data]
				      ,FilterLogic = 
				    if 
				         #"p_limit_rows" = "Y" 
				    then
				     Table.FirstN(
				      sigwatch_corporate_topic, 
				      100
				     )
				 else 
				     sigwatch_corporate_topic,
				    #"Renamed Columns" = Table.RenameColumns(FilterLogic,{{"topic_code", "Topic Code"}, {"topic_name", "Topic Name"}})
				     in
				  #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

