table 'Sigwatch Issue'
	lineageTag: a22fe571-3a6f-4e1a-822c-1b4012846d03

	column 'Issue Code'
		dataType: string
		lineageTag: a06b0809-c826-4765-b713-24994d93b523
		summarizeBy: none
		sourceColumn: Issue Code

		annotation SummarizationSetBy = Automatic

	column 'Issue Name'
		dataType: string
		lineageTag: ffa973eb-b090-4086-a093-b3db1d1b48b0
		summarizeBy: none
		sourceColumn: Issue Name

		annotation SummarizationSetBy = Automatic

	partition 'Sigwatch Issue' = m
		mode: import
		queryGroup: Sigwatch
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(#"p_databricks_host", #"p_databricks_path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=#"p_databricks_catalog",Kind="Database"]}[Data],
				    sigwatch_Schema = hive_metastore_Database{[Name=p_sigwatch_database,Kind="Schema"]}[Data],
				    sigwatch_corporate_issue = sigwatch_Schema{[Name="pub_dim_corporate_issue",Kind="Table"]}[Data]
				      ,FilterLogic = 
				    if 
				         #"p_limit_rows" = "Y" 
				    then
				     Table.FirstN(
				      sigwatch_corporate_issue, 
				      100
				     )
				 else 
				     sigwatch_corporate_issue,
				    #"Renamed Columns" = Table.RenameColumns(FilterLogic,{{"issue_code", "Issue Code"}, {"issue_name", "Issue Name"}})
				     in
				  #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

