table 'Sigwatch Topic Bridge'
	isHidden
	lineageTag: fe34a56d-7919-4408-a0ae-c42b1cb93192

	column 'SK Corporate Event'
		dataType: string
		isHidden
		lineageTag: cca7bc7a-332d-4a30-b282-9e131d13e44f
		summarizeBy: none
		sourceColumn: SK Corporate Event

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Topic Code'
		dataType: string
		isHidden
		lineageTag: 0405302c-aebe-4603-b066-2d3147e46ea8
		summarizeBy: none
		sourceColumn: Topic Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Sigwatch Topic Bridge' = m
		mode: import
		queryGroup: Sigwatch
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(#"p_databricks_host", #"p_databricks_path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=#"p_databricks_catalog",Kind="Database"]}[Data],
				    sigwatch_Schema = hive_metastore_Database{[Name=p_sigwatch_database,Kind="Schema"]}[Data],
				    sigwatch_corporate_topic_bridge = sigwatch_Schema{[Name="pub_bridge_corporate_events_corporate_topic",Kind="Table"]}[Data]
				      ,FilterLogic = 
				    if 
				         #"p_limit_rows" = "Y" 
				    then
				     Table.FirstN(
				      sigwatch_corporate_topic_bridge, 
				      100
				     )
				 else 
				     sigwatch_corporate_topic_bridge,
				    #"Renamed Columns" = Table.RenameColumns(FilterLogic,{{"topic_code", "Topic Code"}, {"sk_corporate_event", "SK Corporate Event"}})
				     in
				  #"Renamed Columns"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

