table 'Sigwatch External Mapping'
	lineageTag: 9d63618e-aeda-4ae4-846f-53a51bd23111

	column 'Company Code'
		dataType: string
		lineageTag: 281e6832-94a6-4d25-a5c4-570e5719cb8a
		summarizeBy: none
		sourceColumn: Company Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ISIN
		dataType: string
		lineageTag: c84a63d7-ba52-4385-9372-64044f0b2508
		summarizeBy: none
		sourceColumn: ISIN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'IDM Matching SK Asset'
		dataType: string
		lineageTag: 157cda90-8aa5-4322-b054-577c5d9e430e
		summarizeBy: none
		sourceColumn: IDM Matching SK Asset

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'IDM Matching Rule'
		dataType: string
		lineageTag: f8043b8e-ad15-4ee3-93db-0751530eb353
		summarizeBy: none
		sourceColumn: IDM Matching Rule

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Sigwatch External Mapping' = m
		mode: import
		queryGroup: Sigwatch
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(#"p_databricks_host", #"p_databricks_path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=#"p_databricks_catalog",Kind="Database"]}[Data],
				    sigwatch_Schema = hive_metastore_Database{[Name=p_sigwatch_database,Kind="Schema"]}[Data],
				    sigwatch_bridge_mapping = sigwatch_Schema{[Name="pub_bridge_idm_asset_external_id",Kind="Table"]}[Data]
				      ,FilterLogic = 
				    if 
				         #"p_limit_rows" = "Y" 
				    then
				     Table.FirstN(
				      sigwatch_bridge_mapping, 
				      100
				     )
				 else 
				     sigwatch_bridge_mapping,
				    #"Renamed Columns" = Table.RenameColumns(FilterLogic,{{"company_code", "Company Code"}, {"isin", "ISIN"}, {"idm_matching_sk_asset", "IDM Matching SK Asset"}, {"idm_matching_rule", "IDM Matching Rule"}})
				     in
				  #"Renamed Columns"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

