table 'Sigwatch Issue Bridge'
	isHidden
	lineageTag: 326d1235-4edc-4b11-83f6-8ca2592a36e6

	column 'SK Corporate Event'
		dataType: string
		isHidden
		lineageTag: e70be815-fad4-441b-bf46-bf6c4d5d7145
		summarizeBy: none
		sourceColumn: SK Corporate Event

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Issue Code'
		dataType: string
		isHidden
		lineageTag: 22ae2540-11eb-4333-9196-a100a6e6fd43
		summarizeBy: none
		sourceColumn: Issue Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Sigwatch Issue Bridge' = m
		mode: import
		queryGroup: Sigwatch
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(#"p_databricks_host", #"p_databricks_path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=#"p_databricks_catalog",Kind="Database"]}[Data],
				    sigwatch_Schema = hive_metastore_Database{[Name=p_sigwatch_database,Kind="Schema"]}[Data],
				    sigwatch_corporate_issue_bridge = sigwatch_Schema{[Name="pub_bridge_corporate_events_corporate_issue",Kind="Table"]}[Data]
				      ,FilterLogic = 
				    if 
				         #"p_limit_rows" = "Y" 
				    then
				     Table.FirstN(
				      sigwatch_corporate_issue_bridge, 
				      100
				     )
				 else 
				     sigwatch_corporate_issue_bridge,
				    #"Renamed Columns" = Table.RenameColumns(FilterLogic,{{"sk_corporate_event", "SK Corporate Event"}, {"issue_code", "Issue Code"}})
				     in
				  #"Renamed Columns"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

