table 'Sigwatch Fact Events'
	lineageTag: 0b1d9839-59c7-4735-aeff-888b06cc4aba

	measure NoHeadlines = COUNT('Sigwatch Fact Events'[Headline])
		formatString: 0
		displayFolder: NGO
		lineageTag: f0581daa-816b-4f4e-90a9-12902c77e4db

	measure RepImpactsSum = SUM('Sigwatch Fact Events'[Reputational Impacts])
		displayFolder: NGO
		lineageTag: 8d43e3a9-9fd1-46e9-bd97-c54f1e02a364

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'SK Corporate Event'
		dataType: string
		lineageTag: c4d8d730-7b30-4827-9fc5-c37220160075
		summarizeBy: none
		sourceColumn: SK Corporate Event

		annotation SummarizationSetBy = Automatic

	column UID
		dataType: string
		lineageTag: cdd61325-9b0b-4fe8-9116-0eda839fec77
		summarizeBy: none
		sourceColumn: UID

		annotation SummarizationSetBy = Automatic

	column 'UID Archive'
		dataType: string
		lineageTag: dda089ff-fb42-4b71-a6b5-24f2987a840c
		summarizeBy: none
		sourceColumn: UID Archive

		annotation SummarizationSetBy = Automatic

	column 'Company Code'
		dataType: string
		isHidden
		lineageTag: 046092db-497b-4856-96b8-6f4b0cfbcd62
		summarizeBy: none
		sourceColumn: Company Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		isHidden
		lineageTag: a1700135-2818-4aa8-8f65-195e54657867
		summarizeBy: none
		sourceColumn: Company

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Company Type'
		dataType: string
		isHidden
		lineageTag: adfbd1cd-05d4-4b7e-92e8-4ce98273bb46
		summarizeBy: none
		sourceColumn: Company Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Company Parent Code'
		dataType: string
		isHidden
		lineageTag: 73f816e0-c2de-4e0c-bb78-88a1e7237b29
		summarizeBy: none
		sourceColumn: Company Parent Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Company Parent'
		dataType: string
		isHidden
		lineageTag: 9f2498ae-2d9c-45e8-8ad1-ef9543d5e125
		summarizeBy: none
		sourceColumn: Company Parent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Company Parent Country Code'
		dataType: string
		isHidden
		lineageTag: 24851f2d-7432-4973-9d0b-c653e398aedc
		summarizeBy: none
		sourceColumn: Company Parent Country Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Company Parent Country'
		dataType: string
		isHidden
		lineageTag: 6e921e30-6f8f-422c-a5f6-48d3a728b748
		summarizeBy: none
		sourceColumn: Company Parent Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sentiment
		dataType: string
		lineageTag: f0032296-afec-45d3-be67-b93616f19be3
		summarizeBy: none
		sourceColumn: Sentiment

		annotation SummarizationSetBy = Automatic

	column Prominence
		dataType: string
		lineageTag: 8fafc625-df2e-44b0-b9f3-be295f0155e3
		summarizeBy: none
		sourceColumn: Prominence

		annotation SummarizationSetBy = Automatic

	column Partnership
		dataType: string
		lineageTag: 37b766c1-9ca2-4b12-8d90-ae29959ba376
		summarizeBy: none
		sourceColumn: Partnership

		annotation SummarizationSetBy = Automatic

	column 'Issue Code 1'
		dataType: string
		lineageTag: 351e8c12-bb96-4a0f-b94b-ef5e5ef07f62
		summarizeBy: none
		sourceColumn: Issue Code 1

		annotation SummarizationSetBy = Automatic

	column 'Issue Name 1'
		dataType: string
		lineageTag: bd93e5c6-2d89-4859-bc8c-c40d6edbba90
		summarizeBy: none
		sourceColumn: Issue Name 1

		annotation SummarizationSetBy = Automatic

	column 'Issue Code 2'
		dataType: string
		lineageTag: f1da11bd-76ee-4f26-b0e7-c0d661a0d6fc
		summarizeBy: none
		sourceColumn: Issue Code 2

		annotation SummarizationSetBy = Automatic

	column 'Issue Name 2'
		dataType: string
		lineageTag: 2a8c0a2b-9ba5-4273-a252-1d1550667f49
		summarizeBy: none
		sourceColumn: Issue Name 2

		annotation SummarizationSetBy = Automatic

	column 'Active Country Code 1'
		dataType: string
		lineageTag: 024bb652-162a-446b-9d18-4f33cfe4680d
		summarizeBy: none
		sourceColumn: Active Country Code 1

		annotation SummarizationSetBy = Automatic

	column 'Active Country 1'
		dataType: string
		lineageTag: cb10af49-2d3d-4fc6-895a-e5076da7eb56
		summarizeBy: none
		sourceColumn: Active Country 1

		annotation SummarizationSetBy = Automatic

	column 'Active Country Code 2'
		dataType: string
		lineageTag: d1fb55f3-93ee-4baf-8a48-cfa501207390
		summarizeBy: none
		sourceColumn: Active Country Code 2

		annotation SummarizationSetBy = Automatic

	column 'Active Country 2'
		dataType: string
		lineageTag: 25d08dcb-d7bd-4d90-8cab-8786c6a4db1c
		summarizeBy: none
		sourceColumn: Active Country 2

		annotation SummarizationSetBy = Automatic

	column 'Active Country Code 3'
		dataType: string
		lineageTag: d55b2096-fe93-4f5a-963d-665987309eaf
		summarizeBy: none
		sourceColumn: Active Country Code 3

		annotation SummarizationSetBy = Automatic

	column 'Active Country 3'
		dataType: string
		lineageTag: 804344ae-9e2b-4947-9701-f549150eb9bd
		summarizeBy: none
		sourceColumn: Active Country 3

		annotation SummarizationSetBy = Automatic

	column 'Active Country Code 4'
		dataType: string
		lineageTag: 5f682d7a-1420-4631-a41d-767612d92420
		summarizeBy: none
		sourceColumn: Active Country Code 4

		annotation SummarizationSetBy = Automatic

	column 'Active Country 4'
		dataType: string
		lineageTag: 4894635a-a5ee-4696-ad90-be2c6fbeda96
		summarizeBy: none
		sourceColumn: Active Country 4

		annotation SummarizationSetBy = Automatic

	column 'Active Country Code 5'
		dataType: string
		lineageTag: 9faab9d7-6c75-49d3-8f88-d9bc6e2e76e1
		summarizeBy: none
		sourceColumn: Active Country Code 5

		annotation SummarizationSetBy = Automatic

	column 'Active Country 5'
		dataType: string
		lineageTag: 8b91584f-c084-4c75-9380-4191978e896e
		summarizeBy: none
		sourceColumn: Active Country 5

		annotation SummarizationSetBy = Automatic

	column 'Active Country Code 6'
		dataType: string
		lineageTag: 377c32e4-257e-43ae-88e7-b9c8824cdd82
		summarizeBy: none
		sourceColumn: Active Country Code 6

		annotation SummarizationSetBy = Automatic

	column 'Active Country 6'
		dataType: string
		lineageTag: bc9a9349-9b97-4365-8c46-524a288358c6
		summarizeBy: none
		sourceColumn: Active Country 6

		annotation SummarizationSetBy = Automatic

	column 'Active Country Code 7'
		dataType: string
		lineageTag: edc9b370-dae3-4e1b-9fc2-915cf034ab1a
		summarizeBy: none
		sourceColumn: Active Country Code 7

		annotation SummarizationSetBy = Automatic

	column 'Active Country 7'
		dataType: string
		lineageTag: 19d548cc-0bf8-410e-ab21-a3ada374c02c
		summarizeBy: none
		sourceColumn: Active Country 7

		annotation SummarizationSetBy = Automatic

	column 'Active Country Code 8'
		dataType: string
		lineageTag: a27a55c6-66a5-4218-8159-8fa92b0c82cf
		summarizeBy: none
		sourceColumn: Active Country Code 8

		annotation SummarizationSetBy = Automatic

	column 'Active Country 8'
		dataType: string
		lineageTag: 1a436d70-567d-4cf5-be31-1a4edb34f2a1
		summarizeBy: none
		sourceColumn: Active Country 8

		annotation SummarizationSetBy = Automatic

	column 'Active Country Code 9'
		dataType: string
		lineageTag: 8cbe61b5-5821-47a2-af58-7b8b4c931584
		summarizeBy: none
		sourceColumn: Active Country Code 9

		annotation SummarizationSetBy = Automatic

	column 'Active Country 9'
		dataType: string
		lineageTag: 5634b85a-5f05-47d0-a9e2-9cacdc9c4ba8
		summarizeBy: none
		sourceColumn: Active Country 9

		annotation SummarizationSetBy = Automatic

	column 'Active Country Code 10'
		dataType: string
		lineageTag: a1e4e7f3-60d7-4aed-a437-a47feb3ee414
		summarizeBy: none
		sourceColumn: Active Country Code 10

		annotation SummarizationSetBy = Automatic

	column 'Active Country 10'
		dataType: string
		lineageTag: 6511d176-b061-4efe-8aaa-42757d38531f
		summarizeBy: none
		sourceColumn: Active Country 10

		annotation SummarizationSetBy = Automatic

	column 'Target Country Code 1'
		dataType: string
		lineageTag: 441bd665-3387-42e2-9f7e-bb3557ef2dc4
		summarizeBy: none
		sourceColumn: Target Country Code 1

		annotation SummarizationSetBy = Automatic

	column 'Target Country 1'
		dataType: string
		lineageTag: 1fd5f464-86c5-4ea3-b5ce-edd9444f1991
		summarizeBy: none
		sourceColumn: Target Country 1

		annotation SummarizationSetBy = Automatic

	column 'Target Country Code 2'
		dataType: string
		lineageTag: 091d0bf1-2075-4b72-a7bf-77f6101d5318
		summarizeBy: none
		sourceColumn: Target Country Code 2

		annotation SummarizationSetBy = Automatic

	column 'Target Country 2'
		dataType: string
		lineageTag: 5cae171a-9012-498e-85ae-cd6c5e2173d0
		summarizeBy: none
		sourceColumn: Target Country 2

		annotation SummarizationSetBy = Automatic

	column 'Target Country Code 3'
		dataType: string
		lineageTag: 310019a0-b362-4f4c-9845-5198c98b0e86
		summarizeBy: none
		sourceColumn: Target Country Code 3

		annotation SummarizationSetBy = Automatic

	column 'Target Country 3'
		dataType: string
		lineageTag: 7f03649c-0e11-4877-8d39-6c85f7dd03e3
		summarizeBy: none
		sourceColumn: Target Country 3

		annotation SummarizationSetBy = Automatic

	column 'Target Country Code 4'
		dataType: string
		lineageTag: 8bb2bf96-e018-45c0-8e48-4df974b08da0
		summarizeBy: none
		sourceColumn: Target Country Code 4

		annotation SummarizationSetBy = Automatic

	column 'Target Country 4'
		dataType: string
		lineageTag: b00283a9-7044-4f6a-bba0-bd018790a6cd
		summarizeBy: none
		sourceColumn: Target Country 4

		annotation SummarizationSetBy = Automatic

	column 'Target Country Code 5'
		dataType: string
		lineageTag: fd032a93-7d36-490a-8927-e3f5383abe1d
		summarizeBy: none
		sourceColumn: Target Country Code 5

		annotation SummarizationSetBy = Automatic

	column 'Target Country 5'
		dataType: string
		lineageTag: 8fff885e-eb65-4371-bdf1-93f8ae12107e
		summarizeBy: none
		sourceColumn: Target Country 5

		annotation SummarizationSetBy = Automatic

	column 'Target Country Code 6'
		dataType: string
		lineageTag: 03789c82-16f4-45cd-a04b-569b530bcddd
		summarizeBy: none
		sourceColumn: Target Country Code 6

		annotation SummarizationSetBy = Automatic

	column 'Target Country 6'
		dataType: string
		lineageTag: bb1190c6-c258-413b-8d22-a23f7b68bcd5
		summarizeBy: none
		sourceColumn: Target Country 6

		annotation SummarizationSetBy = Automatic

	column 'Target Country Code 7'
		dataType: string
		lineageTag: e2077bb5-5018-4d5e-8487-4e4abd2daeb8
		summarizeBy: none
		sourceColumn: Target Country Code 7

		annotation SummarizationSetBy = Automatic

	column 'Target Country 7'
		dataType: string
		lineageTag: 8634d22a-abff-45e3-bf43-320f3c6ae6d2
		summarizeBy: none
		sourceColumn: Target Country 7

		annotation SummarizationSetBy = Automatic

	column 'Target Country Code 8'
		dataType: string
		lineageTag: 46f512ed-c8c1-4ea5-9493-59194692b24f
		summarizeBy: none
		sourceColumn: Target Country Code 8

		annotation SummarizationSetBy = Automatic

	column 'Target Country 8'
		dataType: string
		lineageTag: f3e68d08-81f6-4c8a-af81-cda207bed108
		summarizeBy: none
		sourceColumn: Target Country 8

		annotation SummarizationSetBy = Automatic

	column 'Target Country Code 9'
		dataType: string
		lineageTag: f9a7ecda-c23e-4f1c-9ba9-78abeaabf26e
		summarizeBy: none
		sourceColumn: Target Country Code 9

		annotation SummarizationSetBy = Automatic

	column 'Target Country 9'
		dataType: string
		lineageTag: 41bfc95e-d08a-4cd5-b825-3b35ba323953
		summarizeBy: none
		sourceColumn: Target Country 9

		annotation SummarizationSetBy = Automatic

	column 'Target Country Code10'
		dataType: string
		lineageTag: 97576c58-3492-49a6-b883-e95267f5936c
		summarizeBy: none
		sourceColumn: Target Country Code10

		annotation SummarizationSetBy = Automatic

	column 'Target Country 10'
		dataType: string
		lineageTag: 223258ea-5a70-4ffa-8822-d61c460088a0
		summarizeBy: none
		sourceColumn: Target Country 10

		annotation SummarizationSetBy = Automatic

	column 'NGO Code 1'
		dataType: string
		lineageTag: d20c92b6-a800-496c-bece-2e36e1a05ce2
		summarizeBy: none
		sourceColumn: NGO Code 1

		annotation SummarizationSetBy = Automatic

	column 'NGO Name 1'
		dataType: string
		lineageTag: e3e396e2-f480-4862-af6c-c0d5eb77210d
		summarizeBy: none
		sourceColumn: NGO Name 1

		annotation SummarizationSetBy = Automatic

	column 'NGO Country Code 1'
		dataType: string
		lineageTag: 1d4977e8-b78f-4a6c-8cdc-4d125499f2ed
		summarizeBy: none
		sourceColumn: NGO Country Code 1

		annotation SummarizationSetBy = Automatic

	column 'NGO Country 1'
		dataType: string
		lineageTag: 985a6cfe-a388-43e4-b9ea-4d228fadc9c8
		summarizeBy: none
		sourceColumn: NGO Country 1

		annotation SummarizationSetBy = Automatic

	column 'NGO Code 2'
		dataType: string
		lineageTag: d906ce46-c178-4572-9868-db898e8d0fb4
		summarizeBy: none
		sourceColumn: NGO Code 2

		annotation SummarizationSetBy = Automatic

	column 'NGO Name 2'
		dataType: string
		lineageTag: e463f857-54c1-4652-95fd-36716301ce61
		summarizeBy: none
		sourceColumn: NGO Name 2

		annotation SummarizationSetBy = Automatic

	column 'NGO Country Code 2'
		dataType: string
		lineageTag: 035cb89a-50ce-4a13-8ec9-d61c8bb2687b
		summarizeBy: none
		sourceColumn: NGO Country Code 2

		annotation SummarizationSetBy = Automatic

	column 'NGO Country 2'
		dataType: string
		lineageTag: baca1444-2fc2-4b38-b48e-65ef0617fbbd
		summarizeBy: none
		sourceColumn: NGO Country 2

		annotation SummarizationSetBy = Automatic

	column 'NGO Code 3'
		dataType: string
		lineageTag: 59f82ae8-2131-4690-90e1-5aa3da45cb14
		summarizeBy: none
		sourceColumn: NGO Code 3

		annotation SummarizationSetBy = Automatic

	column 'NGO Name 3'
		dataType: string
		lineageTag: 8599e2af-a7d7-4e8a-89c7-019444490281
		summarizeBy: none
		sourceColumn: NGO Name 3

		annotation SummarizationSetBy = Automatic

	column 'NGO Country Code 3'
		dataType: string
		lineageTag: 59744244-85c8-47ac-8e78-d348cdbdeca9
		summarizeBy: none
		sourceColumn: NGO Country Code 3

		annotation SummarizationSetBy = Automatic

	column 'NGO Country 3'
		dataType: string
		lineageTag: 0c8ef9c2-e9c5-46d7-b172-32a867130535
		summarizeBy: none
		sourceColumn: NGO Country 3

		annotation SummarizationSetBy = Automatic

	column 'NGO Code 4'
		dataType: string
		lineageTag: f0d9c393-6ebb-4b4a-819e-d36973dec4a5
		summarizeBy: none
		sourceColumn: NGO Code 4

		annotation SummarizationSetBy = Automatic

	column 'NGO Name 4'
		dataType: string
		lineageTag: 1f11217f-bc25-4d8c-b555-a8a72616b7e8
		summarizeBy: none
		sourceColumn: NGO Name 4

		annotation SummarizationSetBy = Automatic

	column 'NGO Country Code 4'
		dataType: string
		lineageTag: 738eecd4-1312-43bb-a594-dd745dcffcaf
		summarizeBy: none
		sourceColumn: NGO Country Code 4

		annotation SummarizationSetBy = Automatic

	column 'NGO Country 4'
		dataType: string
		lineageTag: e4b8c217-dc24-4562-ab28-157c7de0ba84
		summarizeBy: none
		sourceColumn: NGO Country 4

		annotation SummarizationSetBy = Automatic

	column 'NGO Code 5'
		dataType: string
		lineageTag: 45ea9786-3b0e-43f7-8644-9d0ed83b47ce
		summarizeBy: none
		sourceColumn: NGO Code 5

		annotation SummarizationSetBy = Automatic

	column 'NGO Name 5'
		dataType: string
		lineageTag: b287482a-e82e-4b7b-950b-6079652148e7
		summarizeBy: none
		sourceColumn: NGO Name 5

		annotation SummarizationSetBy = Automatic

	column 'NGO Country Code 5'
		dataType: string
		lineageTag: 21f5e6c7-2f97-436f-9c3d-9804af49adfc
		summarizeBy: none
		sourceColumn: NGO Country Code 5

		annotation SummarizationSetBy = Automatic

	column 'NGO Country 5'
		dataType: string
		lineageTag: 510f9d4f-ee17-4daa-bd0d-bfdf07cf465e
		summarizeBy: none
		sourceColumn: NGO Country 5

		annotation SummarizationSetBy = Automatic

	column 'Country Code Corp'
		dataType: string
		lineageTag: 0acce497-9321-4806-ab75-bff82d53a7ed
		summarizeBy: none
		sourceColumn: Country Code Corp

		annotation SummarizationSetBy = Automatic

	column 'Country Corp'
		dataType: string
		lineageTag: 5d8f6b26-45df-4233-9bd4-c84f99483d20
		summarizeBy: none
		sourceColumn: Country Corp

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector Code 1'
		dataType: string
		lineageTag: 7d6eeea3-b53a-44f5-abdb-8216dde98039
		summarizeBy: none
		sourceColumn: Corp Industry Sector Code 1

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector 1'
		dataType: string
		lineageTag: ceed9db2-af21-412e-a84c-ceb4b706627a
		summarizeBy: none
		sourceColumn: Corp Industry Sector 1

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector Code 2'
		dataType: string
		lineageTag: 180664fb-8740-4022-a524-7d0f53a497fd
		summarizeBy: none
		sourceColumn: Corp Industry Sector Code 2

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector 2'
		dataType: string
		lineageTag: 5c57e276-0ea6-4ed8-a833-78e1f0364219
		summarizeBy: none
		sourceColumn: Corp Industry Sector 2

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector Code 3'
		dataType: string
		lineageTag: 487451bc-108e-4827-afa7-24b4fd68ef4f
		summarizeBy: none
		sourceColumn: Corp Industry Sector Code 3

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector 3'
		dataType: string
		lineageTag: cf71d967-f553-4230-ad01-2f374b384aa4
		summarizeBy: none
		sourceColumn: Corp Industry Sector 3

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector Code 4'
		dataType: string
		lineageTag: 537e0e17-d9b9-41fb-9447-d0a4103cc8f6
		summarizeBy: none
		sourceColumn: Corp Industry Sector Code 4

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector 4'
		dataType: string
		lineageTag: 08e8bb22-8f8d-4b33-8999-2e4ff9909073
		summarizeBy: none
		sourceColumn: Corp Industry Sector 4

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector Code 5'
		dataType: string
		lineageTag: d9a6578c-8697-4a6f-95b7-73e7fb505df9
		summarizeBy: none
		sourceColumn: Corp Industry Sector Code 5

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector 5'
		dataType: string
		lineageTag: 2f881cb8-8d40-41bf-af52-419ae0487d5c
		summarizeBy: none
		sourceColumn: Corp Industry Sector 5

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector Code 6'
		dataType: string
		lineageTag: f590ae0c-496e-4dce-8072-686c7c7f87af
		summarizeBy: none
		sourceColumn: Corp Industry Sector Code 6

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector 6'
		dataType: string
		lineageTag: 285be941-77e1-4141-b0a5-64c288ceb493
		summarizeBy: none
		sourceColumn: Corp Industry Sector 6

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector Code 7'
		dataType: string
		lineageTag: 74119d84-f313-4f88-9561-62ae5a86fd57
		summarizeBy: none
		sourceColumn: Corp Industry Sector Code 7

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector 7'
		dataType: string
		lineageTag: 5b71c722-c84e-4635-8575-91c436917e71
		summarizeBy: none
		sourceColumn: Corp Industry Sector 7

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector Code 8'
		dataType: string
		lineageTag: 9710503b-b462-4723-a7fd-242a21fab592
		summarizeBy: none
		sourceColumn: Corp Industry Sector Code 8

		annotation SummarizationSetBy = Automatic

	column 'Corp Industry Sector 8'
		dataType: string
		lineageTag: f105613f-1ab7-4f95-b00f-71ca6f9454a1
		summarizeBy: none
		sourceColumn: Corp Industry Sector 8

		annotation SummarizationSetBy = Automatic

	column 'ISIN Corporate Name Official'
		dataType: string
		lineageTag: eb466b5d-831d-43b5-ad6f-828e6009f75d
		summarizeBy: none
		sourceColumn: ISIN Corporate Name Official

		annotation SummarizationSetBy = Automatic

	column 'ISIN Corporate Name Cleaned'
		dataType: string
		lineageTag: 28152866-29ff-401e-b660-656d43b2d850
		summarizeBy: none
		sourceColumn: ISIN Corporate Name Cleaned

		annotation SummarizationSetBy = Automatic

	column 'Issuer ID'
		dataType: string
		lineageTag: ec633c9b-45bc-418d-a55b-fa931b0fbbb6
		summarizeBy: none
		sourceColumn: Issuer ID

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 76ba7232-015f-4800-9a22-f9a770ec94ca
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Bloomberg Ticker'
		dataType: string
		lineageTag: c6d3982a-91f7-4d48-88d9-0ca33c79583c
		summarizeBy: none
		sourceColumn: Bloomberg Ticker

		annotation SummarizationSetBy = Automatic

	column 'ISIN 1'
		dataType: string
		lineageTag: 38a127ff-5ba9-490f-8fbb-c0af2d1dfc9e
		summarizeBy: none
		sourceColumn: ISIN 1

		annotation SummarizationSetBy = Automatic

	column 'ISIN 2'
		dataType: string
		lineageTag: a9970cf1-8d8e-4ce0-93f7-374f2b08c10c
		summarizeBy: none
		sourceColumn: ISIN 2

		annotation SummarizationSetBy = Automatic

	column 'ISIN 3'
		dataType: string
		lineageTag: 90e02b6b-ca5f-47cb-b9bb-aa1a04bf1ecd
		summarizeBy: none
		sourceColumn: ISIN 3

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector Code 1'
		dataType: string
		lineageTag: 05c4b6c8-4ca0-4a74-b826-13315090a01e
		summarizeBy: none
		sourceColumn: Industry Sector Code 1

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector 1'
		dataType: string
		lineageTag: 50a57fe6-aa07-475e-8258-de623b45e486
		summarizeBy: none
		sourceColumn: Industry Sector 1

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector Code 2'
		dataType: string
		lineageTag: e3513b11-2d94-4b8d-a936-ad765e3271e4
		summarizeBy: none
		sourceColumn: Industry Sector Code 2

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector 2'
		dataType: string
		lineageTag: 7f4f9f34-8903-49ff-84f1-20cc924fbe15
		summarizeBy: none
		sourceColumn: Industry Sector 2

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector Code 3'
		dataType: string
		lineageTag: 98fd0dae-b6f6-4551-8273-aab60423322d
		summarizeBy: none
		sourceColumn: Industry Sector Code 3

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector 3'
		dataType: string
		lineageTag: 00405490-c10a-4604-9a18-ba91dd4789ab
		summarizeBy: none
		sourceColumn: Industry Sector 3

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector Code 4'
		dataType: string
		lineageTag: 21a185c8-90dd-48ba-b3ec-57bf7ebc55fe
		summarizeBy: none
		sourceColumn: Industry Sector Code 4

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector 4'
		dataType: string
		lineageTag: 8f7823ac-a942-43f5-81a0-82ed56613102
		summarizeBy: none
		sourceColumn: Industry Sector 4

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector Code 5'
		dataType: string
		lineageTag: 88e7d213-de5b-4bf6-bc3e-5eb0bc94e98a
		summarizeBy: none
		sourceColumn: Industry Sector Code 5

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector 5'
		dataType: string
		lineageTag: 8a533dff-5e1d-4c5b-9df8-db159baf1ac7
		summarizeBy: none
		sourceColumn: Industry Sector 5

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector Code 6'
		dataType: string
		lineageTag: 1e7e2e27-4904-4682-a6ee-607387b782f9
		summarizeBy: none
		sourceColumn: Industry Sector Code 6

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector 6'
		dataType: string
		lineageTag: fb53eb9f-4294-4b62-9900-3301cef12d03
		summarizeBy: none
		sourceColumn: Industry Sector 6

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector Code 7'
		dataType: string
		lineageTag: a3fd2416-99d5-4791-b31e-b5df010bdf89
		summarizeBy: none
		sourceColumn: Industry Sector Code 7

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector 7'
		dataType: string
		lineageTag: 4c6bd151-1861-4ad9-8505-64e9a0fcf243
		summarizeBy: none
		sourceColumn: Industry Sector 7

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector Code 8'
		dataType: string
		lineageTag: 172a90d3-3248-4cf3-b8f0-6d8ee74c95e6
		summarizeBy: none
		sourceColumn: Industry Sector Code 8

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector 8'
		dataType: string
		lineageTag: 62d6ed5b-ed85-4062-989f-d45ed488fd37
		summarizeBy: none
		sourceColumn: Industry Sector 8

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector Code 9'
		dataType: string
		lineageTag: 1be52930-0add-4231-ba03-e00158c70cad
		summarizeBy: none
		sourceColumn: Industry Sector Code 9

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector 9'
		dataType: string
		lineageTag: 8e15df2d-8874-4f56-94b3-4f6f42bb744c
		summarizeBy: none
		sourceColumn: Industry Sector 9

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector Code 10'
		dataType: string
		lineageTag: 34eae3d9-a5e7-4a6f-a46f-6b407cfb8797
		summarizeBy: none
		sourceColumn: Industry Sector Code 10

		annotation SummarizationSetBy = Automatic

	column 'Industry Sector 10'
		dataType: string
		lineageTag: de8f6993-fdf5-417b-b42e-a2b1eef6d267
		summarizeBy: none
		sourceColumn: Industry Sector 10

		annotation SummarizationSetBy = Automatic

	column Report
		dataType: string
		lineageTag: f05a78e6-cdcd-4f28-af9e-c9952d879563
		summarizeBy: none
		sourceColumn: Report

		annotation SummarizationSetBy = Automatic

	column Headline
		dataType: string
		lineageTag: 38be89cb-d9e4-4d73-ab7a-773e39000d05
		summarizeBy: none
		sourceColumn: Headline

		annotation SummarizationSetBy = Automatic

	column 'Link 1'
		dataType: string
		lineageTag: 65db8c49-9d6c-421a-a7f3-02786007f616
		summarizeBy: none
		sourceColumn: Link 1

		annotation SummarizationSetBy = Automatic

	column 'Link 2'
		dataType: string
		lineageTag: bd09c4ca-f637-4a81-91d9-384ef8688a63
		summarizeBy: none
		sourceColumn: Link 2

		annotation SummarizationSetBy = Automatic

	column 'Link 3'
		dataType: string
		lineageTag: 140f42fe-052b-4d8d-bfa3-7f434e44ac9a
		summarizeBy: none
		sourceColumn: Link 3

		annotation SummarizationSetBy = Automatic

	column 'Link 4'
		dataType: string
		lineageTag: 3053334b-4cef-412c-9ec9-88fc72afc9f7
		summarizeBy: none
		sourceColumn: Link 4

		annotation SummarizationSetBy = Automatic

	column 'Link 5'
		dataType: string
		lineageTag: 51a15d7d-7836-420f-b8ab-2910500b1c3d
		summarizeBy: none
		sourceColumn: Link 5

		annotation SummarizationSetBy = Automatic

	column 'Generic Topic Code 1'
		dataType: string
		lineageTag: 5155904d-ebef-49bf-9a55-05377f023aef
		summarizeBy: none
		sourceColumn: Generic Topic Code 1

		annotation SummarizationSetBy = Automatic

	column 'Generic Topic Name 1'
		dataType: string
		lineageTag: 6ff8edf6-2c5b-41fd-9e73-cde9d2c9585b
		summarizeBy: none
		sourceColumn: Generic Topic Name 1

		annotation SummarizationSetBy = Automatic

	column 'Generic Topic Code 2'
		dataType: string
		lineageTag: 43421896-fdc4-413a-af6e-44e69f9c08a6
		summarizeBy: none
		sourceColumn: Generic Topic Code 2

		annotation SummarizationSetBy = Automatic

	column 'Generic Topic Name 2'
		dataType: string
		lineageTag: 9d1d4a1b-4410-4569-b0ed-0ecfad0e59f7
		summarizeBy: none
		sourceColumn: Generic Topic Name 2

		annotation SummarizationSetBy = Automatic

	column 'Generic Topic Code 3'
		dataType: string
		lineageTag: 23cbc671-0ebe-4ea8-b62f-98cf29676164
		summarizeBy: none
		sourceColumn: Generic Topic Code 3

		annotation SummarizationSetBy = Automatic

	column 'Generic Topic Name 3'
		dataType: string
		lineageTag: 67e24564-6309-4074-8030-5b37cc5a178b
		summarizeBy: none
		sourceColumn: Generic Topic Name 3

		annotation SummarizationSetBy = Automatic

	column 'Generic Topic Code 4'
		dataType: string
		lineageTag: b8b35331-56e7-4904-b23f-e926d6100873
		summarizeBy: none
		sourceColumn: Generic Topic Code 4

		annotation SummarizationSetBy = Automatic

	column 'Generic Topic Name 4'
		dataType: string
		lineageTag: c8e81a74-da97-4d1c-85f7-0a12d71e454c
		summarizeBy: none
		sourceColumn: Generic Topic Name 4

		annotation SummarizationSetBy = Automatic

	column 'Generic Topic Code 5'
		dataType: string
		lineageTag: 66f6fd14-a2d5-45fe-b51b-b8253f92c18f
		summarizeBy: none
		sourceColumn: Generic Topic Code 5

		annotation SummarizationSetBy = Automatic

	column 'Generic Topic Name 5'
		dataType: string
		lineageTag: 6d53b0e6-cb71-4b48-a703-354fe3bce7f3
		summarizeBy: none
		sourceColumn: Generic Topic Name 5

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: c94b3217-7688-4ba4-b5af-28e89233b66e
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: a8e68be0-8451-4e5b-88d0-897aab3cd444
			defaultHierarchy: LocalDateTable_ae6d0d11-1b79-4521-bcc0-64ac4d68bc88.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'NGO Power 1'
		dataType: int64
		formatString: 0
		lineageTag: 860919b8-38a7-4861-b3ec-5f488e5cd40e
		summarizeBy: none
		sourceColumn: NGO Power 1

		annotation SummarizationSetBy = User

	column 'NGO Power 2'
		dataType: int64
		formatString: 0
		lineageTag: 47044388-79f1-4101-bf21-b3bb1ed27112
		summarizeBy: none
		sourceColumn: NGO Power 2

		annotation SummarizationSetBy = User

	column 'NGO Power 3'
		dataType: int64
		formatString: 0
		lineageTag: 7cae77c7-f9aa-4f50-9a7d-e26c0bdc5405
		summarizeBy: none
		sourceColumn: NGO Power 3

		annotation SummarizationSetBy = User

	column 'NGO Power 4'
		dataType: int64
		formatString: 0
		lineageTag: 6d69a6af-3b52-489b-a512-c3ad63c085da
		summarizeBy: none
		sourceColumn: NGO Power 4

		annotation SummarizationSetBy = User

	column 'NGO Power 5'
		dataType: int64
		formatString: 0
		lineageTag: 63e7a6ec-9092-4de7-9406-745124c51b8a
		summarizeBy: none
		sourceColumn: NGO Power 5

		annotation SummarizationSetBy = User

	column LEI
		dataType: string
		lineageTag: 1b415f8d-e276-4c48-a3bf-b0df11cc04db
		summarizeBy: none
		sourceColumn: LEI

		annotation SummarizationSetBy = Automatic

	column FIGI
		dataType: string
		lineageTag: 148b33fc-e730-4caa-8934-0281840e930d
		summarizeBy: none
		sourceColumn: FIGI

		annotation SummarizationSetBy = Automatic

	column 'Sum NGO Power'
		dataType: int64
		formatString: 0
		lineageTag: 08067d76-0349-4909-937e-425f932d3221
		summarizeBy: none
		sourceColumn: Sum NGO Power

		annotation SummarizationSetBy = User

	column 'Sum Active Country'
		dataType: int64
		formatString: 0
		lineageTag: ddab7fa4-2909-4970-b23b-6247f0d41b57
		summarizeBy: none
		sourceColumn: Sum Active Country

		annotation SummarizationSetBy = User

	column 'Sum Issues'
		dataType: int64
		formatString: 0
		lineageTag: ad95fa3f-63ab-4ddb-831f-ff969b3ab4e8
		summarizeBy: none
		sourceColumn: Sum Issues

		annotation SummarizationSetBy = User

	column 'Reputational Impacts'
		dataType: double
		formatString: 0
		lineageTag: 2578b740-43b7-4230-b09e-b78007654ab7
		summarizeBy: sum
		sourceColumn: Reputational Impacts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Combined Topic Codes'
		dataType: string
		isHidden
		lineageTag: f16473d1-8637-4368-b5af-95f52cef1763
		summarizeBy: none
		sourceColumn: Combined Topic Codes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Combined Topic Names'
		dataType: string
		lineageTag: 375fc02f-2d62-4cf6-aa3d-5ba632f240b0
		summarizeBy: none
		sourceColumn: Combined Topic Names

		annotation SummarizationSetBy = Automatic

	column 'Combined Issue Codes'
		dataType: string
		isHidden
		lineageTag: 8336dcac-6abc-4371-bd5b-6af6cf8a2f61
		summarizeBy: none
		sourceColumn: Combined Issue Codes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Combined Issue Names'
		dataType: string
		lineageTag: 37a168e6-0773-4fff-9692-0594bc1df18b
		summarizeBy: none
		sourceColumn: Combined Issue Names

		annotation SummarizationSetBy = Automatic

	column 'Combined NGO Names'
		dataType: string
		lineageTag: 5b9fbd08-06b0-47c1-a588-e4d2d40a8752
		summarizeBy: none
		sourceColumn: Combined NGO Names

		annotation SummarizationSetBy = Automatic

	column 'Combined NGO Codes'
		dataType: string
		isHidden
		lineageTag: 0cdac689-42f7-4337-af29-d9ff90cb88c1
		summarizeBy: none
		sourceColumn: Combined NGO Codes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Is Reputational Impact Positive'
		dataType: string
		lineageTag: bce2df16-09e3-41ad-92bc-5740ce4eb006
		summarizeBy: none
		sourceColumn: Is Reputational Impact Positive

		annotation SummarizationSetBy = Automatic

	partition 'Sigwatch Fact Events' = m
		mode: import
		queryGroup: Sigwatch
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(#"p_databricks_host", #"p_databricks_path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=#"p_databricks_catalog",Kind="Database"]}[Data],
				    sigwatch_Schema = hive_metastore_Database{[Name=p_sigwatch_database,Kind="Schema"]}[Data],
				    sigwatch_fact_events = sigwatch_Schema{[Name="pub_fct_corporate_events",Kind="Table"]}[Data]
				      ,FilterLogic = 
				    if 
				         #"p_limit_rows" = "Y" 
				    then
				     Table.FirstN(
				      sigwatch_fact_events, 
				      100
				     )
				 else 
				     sigwatch_fact_events,
				    #"Renamed Columns" = Table.RenameColumns(FilterLogic,{{"sk_corporate_event", "SK Corporate Event"}, {"uid", "UID"}, {"uid_archive", "UID Archive"}, {"company_code", "Company Code"}, {"sentiment", "Sentiment"}, {"prominence", "Prominence"}, {"partnership", "Partnership"}, {"issue_code1", "Issue Code 1"}, {"issue_name1", "Issue Name 1"}, {"issue_code2", "Issue Code 2"}, {"issue_name2", "Issue Name 2"}, {"active_country_code1", "Active Country Code 1"}, {"active_country1", "Active Country 1"}, {"active_country_code2", "Active Country Code 2"}, {"active_country2", "Active Country 2"}, {"active_country_code3", "Active Country Code 3"}, {"active_country3", "Active Country 3"}, {"active_country_code4", "Active Country Code 4"}, {"active_country4", "Active Country 4"}, {"active_country_code5", "Active Country Code 5"}, {"active_country5", "Active Country 5"}, {"active_country_code6", "Active Country Code 6"}, {"active_country6", "Active Country 6"}, {"active_country_code7", "Active Country Code 7"}, {"active_country7", "Active Country 7"}, {"active_country_code8", "Active Country Code 8"}, {"active_country8", "Active Country 8"}, {"active_country_code9", "Active Country Code 9"}, {"active_country9", "Active Country 9"}, {"active_country_code10", "Active Country Code 10"}, {"active_country10", "Active Country 10"}, {"target_country_code1", "Target Country Code 1"}, {"target_country1", "Target Country 1"}, {"target_country_code2", "Target Country Code 2"}, {"target_country2", "Target Country 2"}, {"target_country_code3", "Target Country Code 3"}, {"target_country3", "Target Country 3"}, {"target_country_code4", "Target Country Code 4"}, {"target_country4", "Target Country 4"}, {"target_country_code5", "Target Country Code 5"}, {"target_country5", "Target Country 5"}, {"target_country_code6", "Target Country Code 6"}, {"target_country6", "Target Country 6"}, {"target_country_code7", "Target Country Code 7"}, {"target_country7", "Target Country 7"}, {"target_country_code8", "Target Country Code 8"}, {"target_country8", "Target Country 8"}, {"target_country_code9", "Target Country Code 9"}, {"target_country9", "Target Country 9"}, {"target_country_code10", "Target Country Code10"}, {"target_country10", "Target Country 10"}, {"ngo_code1", "NGO Code 1"}, {"ngo_name1", "NGO Name 1"}, {"ngo_country_code1", "NGO Country Code 1"}, {"ngo_country1", "NGO Country 1"}, {"ngo_code2", "NGO Code 2"}, {"ngo_name2", "NGO Name 2"}, {"ngo_country_code2", "NGO Country Code 2"}, {"ngo_country2", "NGO Country 2"}, {"ngo_code3", "NGO Code 3"}, {"ngo_name3", "NGO Name 3"}, {"ngo_country_code3", "NGO Country Code 3"}, {"ngo_country3", "NGO Country 3"}, {"ngo_code4", "NGO Code 4"}, {"ngo_name4", "NGO Name 4"}, {"ngo_country_code4", "NGO Country Code 4"}, {"ngo_country4", "NGO Country 4"}, {"ngo_code5", "NGO Code 5"}, {"ngo_name5", "NGO Name 5"}, {"ngo_country_code5", "NGO Country Code 5"}, {"ngo_country5", "NGO Country 5"}, {"country_code_corp", "Country Code Corp"}, {"country_corp", "Country Corp"}, {"corp_industry_sector_code1", "Corp Industry Sector Code 1"}, {"corp_industry_sector1", "Corp Industry Sector 1"}, {"corp_industry_sector_code2", "Corp Industry Sector Code 2"}, {"corp_industry_sector2", "Corp Industry Sector 2"}, {"corp_industry_sector_code3", "Corp Industry Sector Code 3"}, {"corp_industry_sector3", "Corp Industry Sector 3"}, {"corp_industry_sector_code4", "Corp Industry Sector Code 4"}, {"corp_industry_sector4", "Corp Industry Sector 4"}, {"corp_industry_sector_code5", "Corp Industry Sector Code 5"}, {"corp_industry_sector5", "Corp Industry Sector 5"}, {"corp_industry_sector_code6", "Corp Industry Sector Code 6"}, {"corp_industry_sector6", "Corp Industry Sector 6"}, {"corp_industry_sector_code7", "Corp Industry Sector Code 7"}, {"corp_industry_sector7", "Corp Industry Sector 7"}, {"corp_industry_sector8", "Corp Industry Sector 8"}, {"corp_industry_sector_code8", "Corp Industry Sector Code 8"}, {"isin_corporate_name_official", "ISIN Corporate Name Official"}, {"isin_corporate_name_cleaned", "ISIN Corporate Name Cleaned"}, {"issuer_id", "Issuer ID"}, {"country", "Country"}, {"bloomberg_ticker", "Bloomberg Ticker"}, {"isin_1", "ISIN 1"}, {"isin_2", "ISIN 2"}, {"isin_3", "ISIN 3"}, {"industry_sector_code1", "Industry Sector Code 1"}, {"industry_sector_code2", "Industry Sector Code 2"}, {"industry_sector_code3", "Industry Sector Code 3"}, {"industry_sector_code4", "Industry Sector Code 4"}, {"industry_sector_code5", "Industry Sector Code 5"}, {"industry_sector_code6", "Industry Sector Code 6"}, {"industry_sector_code7", "Industry Sector Code 7"}, {"industry_sector_code8", "Industry Sector Code 8"}, {"industry_sector_code9", "Industry Sector Code 9"}, {"industry_sector_code10", "Industry Sector Code 10"}, {"industry_sector10", "Industry Sector 10"}, {"industry_sector9", "Industry Sector 9"}, {"industry_sector8", "Industry Sector 8"}, {"industry_sector7", "Industry Sector 7"}, {"industry_sector6", "Industry Sector 6"}, {"industry_sector5", "Industry Sector 5"}, {"industry_sector4", "Industry Sector 4"}, {"industry_sector3", "Industry Sector 3"}, {"industry_sector2", "Industry Sector 2"}, {"industry_sector1", "Industry Sector 1"}, {"Link1", "Link 1"}, {"Link2", "Link 2"}, {"Link3", "Link 3"}, {"Link4", "Link 4"}, {"Link5", "Link 5"}, {"generic_topic_code1", "Generic Topic Code 1"}, {"generic_topic_code2", "Generic Topic Code 2"}, {"generic_topic_code3", "Generic Topic Code 3"}, {"generic_topic_code4", "Generic Topic Code 4"}, {"generic_topic_code5", "Generic Topic Code 5"}, {"generic_topic_name1", "Generic Topic Name 1"}, {"generic_topic_name2", "Generic Topic Name 2"}, {"generic_topic_name3", "Generic Topic Name 3"}, {"generic_topic_name4", "Generic Topic Name 4"}, {"generic_topic_name5", "Generic Topic Name 5"}, {"date", "Date"}, {"ngo_power1", "NGO Power 1"}, {"ngo_power2", "NGO Power 2"}, {"ngo_power3", "NGO Power 3"}, {"ngo_power4", "NGO Power 4"}, {"ngo_power5", "NGO Power 5"}, {"lei", "LEI"}, {"figi", "FIGI"}, {"sum_ngo_power", "Sum NGO Power"}, {"sum_active_country", "Sum Active Country"}, {"sum_issues", "Sum Issues"}, {"ri_corporate", "Reputational Impacts"}, {"company", "Company"}, {"company_type", "Company Type"}, {"company_parent_code", "Company Parent Code"}, {"company_parent", "Company Parent"}, {"company_parent_country_code", "Company Parent Country Code"}, {"company_parent_country", "Company Parent Country"}, {"combined_topic_codes", "Combined Topic Codes"}, {"combined_topic_names", "Combined Topic Names"}, {"combined_issue_codes", "Combined Issue Codes"}, {"combined_issue_names", "Combined Issue Names"}, {"combined_ngo_names", "Combined NGO Names"}, {"combined_ngo_codes", "Combined NGO Codes"}, {"is_ri_corporate_positive", "Is Reputational Impact Positive"}})
				in
				    #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

