table 'Sigwatch Corporate'
	lineageTag: f13510ff-2fe6-4594-ac02-6b47bcc72f20

	column 'Company Code'
		dataType: string
		lineageTag: f622318d-07ad-48a9-9cca-f89e80d08d38
		summarizeBy: none
		sourceColumn: Company Code

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 55cf634c-a531-46f2-ab56-7749191082ac
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column 'Company Type'
		dataType: string
		lineageTag: f7843adf-7b41-41c2-a899-0f13560cc1d1
		summarizeBy: none
		sourceColumn: Company Type

		annotation SummarizationSetBy = Automatic

	column 'Company Parent  Code'
		dataType: string
		lineageTag: 169ef94f-6c8f-4dd6-a9d0-170e8d28b3f8
		summarizeBy: none
		sourceColumn: Company Parent  Code

		annotation SummarizationSetBy = Automatic

	column 'Company Parent Country Code'
		dataType: string
		lineageTag: 3a7c9b6c-516a-453f-afe6-30539b4c7d2a
		summarizeBy: none
		sourceColumn: Company Parent Country Code

		annotation SummarizationSetBy = Automatic

	column 'Company Parent Country'
		dataType: string
		lineageTag: 1ca2a227-3a60-4a18-b475-dec2ee65036d
		summarizeBy: none
		sourceColumn: Company Parent Country

		annotation SummarizationSetBy = Automatic

	column 'Latest Date'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e9a994a3-1fea-4be8-8849-27465c2dafa7
		summarizeBy: none
		sourceColumn: Latest Date

		variation Variation
			isDefault
			relationship: b1af82c8-6698-4581-8a3b-d9de015f25dc
			defaultHierarchy: LocalDateTable_35232e12-2159-4242-8741-09ebfd7b120a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition 'Sigwatch Corporate' = m
		mode: import
		queryGroup: Sigwatch
		source = ```
				let
				    Source = DatabricksMultiCloud.Catalogs(#"p_databricks_host", #"p_databricks_path", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    hive_metastore_Database = Source{[Name=#"p_databricks_catalog",Kind="Database"]}[Data],
				    sigwatch_Schema = hive_metastore_Database{[Name=p_sigwatch_database,Kind="Schema"]}[Data],
				    sigwatch_dim_corporate = sigwatch_Schema{[Name="pub_dim_corporate",Kind="Table"]}[Data]
				      ,FilterLogic = 
				    if 
				         #"p_limit_rows" = "Y" 
				    then
				     Table.FirstN(
				      sigwatch_dim_corporate, 
				      100
				     )
				 else 
				     sigwatch_dim_corporate,
				    #"Renamed Columns" = Table.RenameColumns(FilterLogic,{{"company_code", "Company Code"}, {"company", "Company"}, {"company_type", "Company Type"}, {"company_parent_code", "Company Parent  Code"}, {"company_parent_country_code", "Company Parent Country Code"}, {"company_parent_country", "Company Parent Country"}, {"latest_date", "Latest Date"}})
				     in
				  #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

