INSERT INTO warehouse (w_warehouse_sk, w_warehouse_name, w_gmt_offset) VALUES (1000, 'WarehouseA', -5);
INSERT INTO warehouse (w_warehouse_sk, w_warehouse_name, w_gmt_offset) VALUES (1001, 'WarehouseB', -5);
INSERT INTO ship_mode (sm_ship_mode_sk, sm_type) VALUES (1000, 'LIBRARY');
INSERT INTO ship_mode (sm_ship_mode_sk, sm_type) VALUES (1001, 'LIBRARY');
INSERT INTO call_center (cc_call_center_sk, cc_class, cc_name) VALUES (1000, 'medium', 'Center1');
INSERT INTO call_center (cc_call_center_sk, cc_class, cc_name) VALUES (1001, 'medium', 'Center2');
INSERT INTO date_dim (d_date_sk, d_month_seq) VALUES (1000, 1191);
INSERT INTO date_dim (d_date_sk, d_month_seq) VALUES (1001, 1191);
INSERT INTO catalog_sales (cs_call_center_sk, cs_ship_mode_sk, cs_warehouse_sk, cs_ship_date_sk, cs_sold_date_sk, cs_list_price) VALUES (1000, 1000, 1000, 1000, 1000, 250);
INSERT INTO catalog_sales (cs_call_center_sk, cs_ship_mode_sk, cs_warehouse_sk, cs_ship_date_sk, cs_sold_date_sk, cs_list_price) VALUES (1001, 1001, 1001, 1001, 1001, 260);