INSERT INTO customer (c_customer_sk, c_customer_id, c_salutation, c_first_name, c_last_name, c_preferred_cust_flag, c_birth_day, c_birth_month, c_birth_year, c_birth_country, c_login, c_email_address, c_last_review_date_sk, c_current_addr_sk) VALUES (1000, 'C1000', 'Mr.', 'John', 'Doe', 'Y', 1, 1, 1986, 'USA', 'jdoe', 'jdoe@email.com', NULL, 2000);
INSERT INTO customer (c_customer_sk, c_customer_id, c_salutation, c_first_name, c_last_name, c_preferred_cust_flag, c_birth_day, c_birth_month, c_birth_year, c_birth_country, c_login, c_email_address, c_last_review_date_sk, c_current_addr_sk) VALUES (1001, 'C1001', 'Ms.', 'Jane', 'Smith', 'N', 2, 2, 1987, 'USA', 'jsmith', 'jsmith@email.com', NULL, 2001);
INSERT INTO customer_address (ca_address_sk, ca_state) VALUES (2000, 'OK');
INSERT INTO customer_address (ca_address_sk, ca_state) VALUES (2001, 'OK');
INSERT INTO date_dim (d_date_sk, d_year) VALUES (3000, 2002);
INSERT INTO item (i_item_sk, i_manager_id) VALUES (4000, 70);
INSERT INTO web_returns (wr_returning_customer_sk, wr_returning_addr_sk, wr_item_sk, wr_reason_sk, wr_return_amt, wr_return_quantity, wr_returned_date_sk) VALUES (1000, 2000, 4000, 20, 250.0, 1, 3000);
INSERT INTO web_returns (wr_returning_customer_sk, wr_returning_addr_sk, wr_item_sk, wr_reason_sk, wr_return_amt, wr_return_quantity, wr_returned_date_sk) VALUES (1000, 2000, 4000, 36, 2000.0, 1, 3000);
INSERT INTO web_returns (wr_returning_customer_sk, wr_returning_addr_sk, wr_item_sk, wr_reason_sk, wr_return_amt, wr_return_quantity, wr_returned_date_sk) VALUES (1001, 2001, 4000, 20, 242.0, 1, 3000);
INSERT INTO web_returns (wr_returning_customer_sk, wr_returning_addr_sk, wr_item_sk, wr_reason_sk, wr_return_amt, wr_return_quantity, wr_returned_date_sk) VALUES (1001, 2001, 4000, 36, 2000.0, 1, 3000);