"""Build GitHub PR review comments from optimization results.

Generates markdown tables showing original vs optimized SQL,
speedup ratios, and transforms applied.
"""

import logging
from typing import List, Dict, Any

logger = logging.getLogger(__name__)


def build_review_comment(results: List[Dict[str, Any]]) -> str:
    """Build a markdown PR review comment from optimization results.

    Args:
        results: List of per-file optimization results, each containing:
            - path: File path
            - status: WIN/IMPROVED/NEUTRAL/REGRESSION/ERROR
            - speedup: Float ratio (e.g., 2.5 = 2.5x faster)
            - optimized_sql: The optimized SQL (if successful)
            - transforms: List of transform names applied
            - error: Error message (if status is ERROR)

    Returns:
        Markdown-formatted comment body.
    """
    if not results:
        return _no_results_comment()

    wins = [r for r in results if r.get("status") in ("WIN", "IMPROVED")]
    errors = [r for r in results if r.get("status") == "ERROR"]
    neutrals = [r for r in results if r.get("status") in ("NEUTRAL", "REGRESSION")]

    lines = [
        "## QueryTorque SQL Optimization Report",
        "",
        f"Analyzed **{len(results)}** SQL file(s) in this PR.",
        "",
    ]

    # Summary table
    lines.append("| File | Status | Speedup | Transforms |")
    lines.append("|------|--------|---------|------------|")
    for r in results:
        status = r.get("status", "UNKNOWN")
        speedup = r.get("speedup")
        speedup_str = f"{speedup:.2f}x" if speedup and speedup > 0 else "—"
        transforms = ", ".join(r.get("transforms", [])) or "—"
        icon = _status_icon(status)
        lines.append(f"| `{r['path']}` | {icon} {status} | {speedup_str} | {transforms} |")
    lines.append("")

    # Detail sections for wins
    if wins:
        lines.append("### Optimization Suggestions")
        lines.append("")
        for r in wins:
            speedup = r.get("speedup", 0)
            lines.append(f"#### `{r['path']}` — {speedup:.2f}x faster")
            lines.append("")
            if r.get("optimized_sql"):
                lines.append("<details>")
                lines.append("<summary>View optimized SQL</summary>")
                lines.append("")
                lines.append("```sql")
                lines.append(r["optimized_sql"])
                lines.append("```")
                lines.append("</details>")
                lines.append("")

    # Error section
    if errors:
        lines.append("### Errors")
        lines.append("")
        for r in errors:
            lines.append(f"- `{r['path']}`: {r.get('error', 'Unknown error')}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [QueryTorque](https://querytorque.com) SQL Optimizer*")

    return "\n".join(lines)


def _no_results_comment() -> str:
    """Comment when no SQL files were found."""
    return (
        "## QueryTorque SQL Optimization Report\n\n"
        "No SQL files found in this PR to analyze.\n\n"
        "---\n"
        "*Generated by [QueryTorque](https://querytorque.com) SQL Optimizer*"
    )


def _status_icon(status: str) -> str:
    """Map status to a unicode indicator."""
    return {
        "WIN": "+",
        "IMPROVED": "+",
        "NEUTRAL": "~",
        "REGRESSION": "-",
        "ERROR": "!",
    }.get(status, "?")
