DEFINE 
---- MODEL MEASURES BEGIN ----
MEASURE 'ESG Trucost Climate'[Portfolio_Asset_Matrix MV CR Intensity Switch_BM] = CALCULATE( [Matrix MV CR Intensity Switch_BM] , 'Benchmark Portfolio Mapping'[Position_Type] = "Portfolio")
MEASURE 'ESG Trucost Climate'[Matrix MV CR Intensity Switch_BM] = 
          
            SWITCH  (TRUE()  , 
                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  1 , [Matrix MV CR Intensity (Scope 1 & 2)_BM],
                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  2 , [Matrix MV CR Intensity (Scope 1 & 2 & 3DS)_BM],
                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  3 , [Matrix MV CR Intensity (Scope 1 & 2 & 3US)_BM],
                    SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code]) =  4 , [Matrix MV CR Intensity (Scope 1 & 2 & 3DS & 3US)_BM],
                    [Matrix MV CR Intensity (Scope 1 & 2)_BM])
  
MEASURE 'ESG Trucost Climate'[Matrix MV CR Intensity (Scope 1 & 2)_BM] = 

         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
            Var Result  = 
            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 1 & 2) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
         
         //Else part below -use normal aggregations
              ,[Aggregate MV CR Intensity (Scope 1 & 2)_BM])

Return Result


MEASURE 'ESG Trucost Climate'[Matrix MV CR Intensity (Scope 1 & 2 & 3DS)_BM] = 

         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
            Var Result  = 
            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 1 & 2 & 3DS) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
         
         //Else part below -use normal aggregations
              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3DS)_BM])

Return Result
MEASURE 'ESG Trucost Climate'[Matrix MV CR Intensity (Scope 1 & 2 & 3US)_BM] = 

         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
            Var Result  = 
            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 1 & 2 & 3US) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
         
         //Else part below -use normal aggregations
              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3US)_BM])

Return Result
MEASURE 'ESG Trucost Climate'[Matrix MV CR Intensity (Scope 1 & 2 & 3DS & 3US)_BM] = 

         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
            Var Result  = 
            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,[Apportioned Carbon/CR (Scope 1 & 2 & 3DS & 3US) Sub_Sector_BM]/[Apportioned Revenue Sub_Sector_BM]
         
         //Else part below -use normal aggregations
              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3DS & 3US)_BM])

Return Result
MEASURE 'ESG Trucost Climate'[Aggregate MV CR Intensity (Scope 1 & 2)_BM] = 

DIVIDE([Aggregate MV Apportioned Carbon (Scope 1 & 2)_BM], SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM]))



MEASURE 'ESG Trucost Climate'[Apportioned Carbon/CR (Scope 1 & 2) Sub_Sector_BM] = 
           

         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
            Var Result  = 
            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
                                [Aggregate MV Apportioned Carbon (Scope 1 & 2)_BM])
                         
         
         //Else part below -use normal aggregations
              ,[Aggregate MV CR Intensity (Scope 1 & 2)_BM])

 Return Result    
MEASURE 'ESG Trucost Climate'[Apportioned Revenue Sub_Sector_BM] = SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]), [Apportioned MV Revenue AUD mn_BM])

              
              
MEASURE 'ESG Trucost Climate'[Aggregate MV CR Intensity (Scope 1 & 2 & 3DS)_BM] = 

VAR numerator = [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM]
VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM])

RETURN
DIVIDE(numerator, denominator)
MEASURE 'ESG Trucost Climate'[Apportioned Carbon/CR (Scope 1 & 2 & 3DS) Sub_Sector_BM] = 
           

         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
            Var Result  = 
            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
                                [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM])
                         
         
         //Else part below -use normal aggregations
              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3DS)_BM])

 Return Result   
MEASURE 'ESG Trucost Climate'[Aggregate MV CR Intensity (Scope 1 & 2 & 3US)_BM] = 

VAR numerator = [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM]
VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM])

RETURN
DIVIDE(numerator, denominator)
MEASURE 'ESG Trucost Climate'[Apportioned Carbon/CR (Scope 1 & 2 & 3US) Sub_Sector_BM] = 
           

         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
            Var Result  = 
            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
                                [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM])
                         
         
         //Else part below -use normal aggregations
              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3US)_BM])

 Return Result   
MEASURE 'ESG Trucost Climate'[Aggregate MV CR Intensity (Scope 1 & 2 & 3DS & 3US)_BM] = 

VAR numerator = [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM]
VAR denominator = SUMX('GS Asset', [Apportioned MV Revenue AUD mn_BM])

RETURN
DIVIDE(numerator, denominator)
MEASURE 'ESG Trucost Climate'[Apportioned Carbon/CR (Scope 1 & 2 & 3DS & 3US) Sub_Sector_BM] = 

         //For Benchmark and portfolio top level aggregate sum of sub-sector levels
            Var Result  = 
            IF( SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,
                   SUMX(GROUPBY('Benchmark Portfolio Mapping','Benchmark Portfolio Mapping'[Sub_Sector]),
                                [Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM])
                         
         
         //Else part below -use normal aggregations
              ,[Aggregate MV CR Intensity (Scope 1 & 2 & 3DS & 3US)_BM])

 Return Result   
MEASURE 'ESG Trucost Climate'[Aggregate MV Apportioned Carbon (Scope 1 & 2)_BM] = SUMX('GS Asset',[MV Apportioned Carbon (Scope 1 & 2)_BM])
        
MEASURE 'ESG Trucost Climate'[Apportioned MV Revenue AUD mn_BM] = 

Var Benchmark = CALCULATE ( SUMX('ESG Trucost Climate', [MV Ownership_BM]*'ESG Trucost Climate'[Revenue_AUD_mn] ),'Daily Position'[Position_Type] = "Benchmark")
Var Portfolio = CALCULATE ( SUMX('ESG Trucost Climate', [MV Ownership_BM]*'ESG Trucost Climate'[Revenue_AUD_mn] ),'Daily Position'[Position_Type] = "Portfolio")

        RETURN

        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
MEASURE 'ESG Trucost Climate'[Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM] = SUMX('GS Asset',[MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM])
MEASURE 'ESG Trucost Climate'[Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM] = SUMX('GS Asset',[MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM])
MEASURE 'ESG Trucost Climate'[Aggregate MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM] = SUMX('GS Asset',[MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM])
MEASURE 'ESG Trucost Climate'[MV Apportioned Carbon (Scope 1 & 2)_BM] = 

CALCULATE( [MV Ownership_BM]
            *(SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM])
            )
        ) 
MEASURE 'Daily Position'[MV Ownership_BM] = 

VAR Accounts_owning_asset = CALCULATE(DISTINCTCOUNT('Daily Position'[SK ASSET]), 'Daily Position'[Position_Type] = "Benchmark")

VAR asset_level_market_cap = DIVIDE([Market_Cap_BM], Accounts_owning_asset)

VAR Ownership_port = if (SELECTEDVALUE('Market Cap Type'[Market_Cap_Code]) = 1,  SUM('Daily Position'[MV_OWNERSHIP]),
                                        if ( [Market_Cap_BM] = BLANK() || [Market_Cap_BM] = 0 ,0,([MARKET_VALUE_BASE_SUM] / [Market_Cap_BM]) * 1000000000   ))


--SUM('Daily Position'[MV_OWNERSHIP]) 
VAR Ownership_bench_num = DIVIDE ([Benchmark_Weight_BM],100,0)*[Market_Value_BM]


--VAR Ownership_bench_denom = asset_level_market_cap

VAR Bloomberg_ownership = IF (
    SELECTEDVALUE('Daily Position'[Position_Type] )= "Portfolio", // if position_type = portfolio
    Ownership_port  / 1000000000  ,     DIVIDE( Ownership_bench_num, asset_level_market_cap,0) // else if position_type = benchmark
    )

RETURN 
IF (
    AND( Bloomberg_ownership = 0 || ISBLANK(Bloomberg_ownership), [Market_Value_BM] > 0), 
    [GS Ownership], // Taking GS ownership if bloomberg ownership is 0% AND MV is not 0
    Bloomberg_ownership
    ) 

MEASURE 'ESG Trucost Climate'[MV Apportioned Carbon (Scope 1 & 2 & 3DS)_BM] = 

CALCULATE( [MV Ownership_BM]
            *(SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM] + [Carbon_Scope_3_tonnes_CO2e_Downstream_BM])
            )
        ) 
MEASURE 'ESG Trucost Climate'[MV Apportioned Carbon (Scope 1 & 2 & 3US)_BM] = 

CALCULATE( [MV Ownership_BM]
            *(SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM] + [Carbon_Scope_3_tonnes_CO2e_Upstream_BM])
            )
        ) 
MEASURE 'ESG Trucost Climate'[MV Apportioned Carbon (Scope 1 & 2 & 3DS & 3US)_BM] = 

CALCULATE( [MV Ownership_BM]
            *(SUMX('ESG Trucost Climate', [Carbon_Scope_1_tonnes_CO2e_BM]+ [Carbon_Scope_2_tonnes_CO2e_BM] + [Carbon_Scope_3_tonnes_CO2e_Upstream_BM] + [Carbon_Scope_3_tonnes_CO2e_Downstream_BM])
            )
        ) 
MEASURE 'Daily Position'[Carbon_Scope_1_tonnes_CO2e_BM] = 
        Var Benchmark = CALCULATE(sum('ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]), 'Daily Position'[Position_Type]= "Benchmark" )
        Var Portfolio = CALCULATE(sum('ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]), 'Daily Position'[Position_Type] = "Portfolio")

        RETURN

        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
MEASURE 'Daily Position'[Carbon_Scope_2_tonnes_CO2e_BM] = 
        Var Benchmark = CALCULATE(sum('ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e]),'Daily Position'[Position_Type]= "Benchmark" )
        Var Portfolio = CALCULATE(sum('ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e]), 'Daily Position'[Position_Type] = "Portfolio")

        RETURN

        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
MEASURE 'Daily Position'[MARKET_VALUE_BASE_SUM] = SUM('Daily Position'[MARKET VALUE BASE]) // Explicit measure to used in Excel Pivot Table

MEASURE 'Daily Position'[GS Ownership] = 
VAR Ownership_port = DIVIDE([QUANTITY_SUM], [SHARES_OUTSTANDING_SUM],0)

RETURN
IF (
    SELECTEDVALUE('Daily Position'[Position_Type]) = "Portfolio", 
    Ownership_port 
    )


MEASURE 'Daily Position'[Market_Cap_BM] = 
        Var MC_Benchmark = CALCULATE(sum('Daily Position'[Market_Cap_Base]),'Daily Position'[Position_Type]= "Benchmark" )
        Var MC_Portfolio = CALCULATE(sum('Daily Position'[Market_Cap_Base]), 'Daily Position'[Position_Type] = "Portfolio")
        Var MC_Portfolio_MF = CALCULATE(MAX('Daily Position'[Market_Cap_Base]), 'Daily Position'[Position_Type] = "Portfolio")

        Var EVIC_MC_Benchmark = CALCULATE(sum('Daily Position'[EVIC_Base]),'Daily Position'[Position_Type]= "Benchmark" )
        Var EVIC_MC_Portfolio = CALCULATE(sum('Daily Position'[EVIC_Base]), 'Daily Position'[Position_Type] = "Portfolio")
        Var EVIC_MC_Portfolio_MF = CALCULATE(MAX('Daily Position'[EVIC_Base]), 'Daily Position'[Position_Type] = "Portfolio")

        RETURN

            SWITCH(TRUE,
                    SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" 
                        && [Market_Cap_Switch] =1 , MC_Benchmark/1000000,

                     SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio" 
                        && [Market_Cap_Switch] = 1 && [Market_Cap_BM_Fund_Count] = 1 ,MC_Portfolio,

                     SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio" 
                        && [Market_Cap_Switch] = 1 && [Market_Cap_BM_Fund_Count] > 1 ,MC_Portfolio_MF,

                     SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" 
                        && [Market_Cap_Switch] = 2  , EVIC_MC_Benchmark/1000000,

                    SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio" 
                        && [Market_Cap_Switch]= 2  && [Market_Cap_BM_Fund_Count] = 1, EVIC_MC_Portfolio,

                    SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Portfolio" 
                        && [Market_Cap_Switch]= 2  && [Market_Cap_BM_Fund_Count] > 1, EVIC_MC_Portfolio_MF   )
                        
            
MEASURE 'Daily Position'[Market_Value_BM] = 
        Var Benchmark = CALCULATE(sum('Daily Position'[MARKET VALUE BASE]),
                        ALLEXCEPT('Daily Position','Daily Position'[INVESTMENT OBJECT CODE],'Daily Position'[Valuation Date]),
                        'GS Asset'[CLIENT_INSTRUMENT_MAJOR_TYPE] IN {"Collective Investment", "Equity"},
                         NOT('GS Asset'[CLIENT_INSTRUMENT_ISSUE_TYPE] IN {"Cash", "Equity Index Futures", "Fee Accruals", "Money Market fund", "Recoverable Taxes", "Rights Issue", "Variation Margin"}))

       -- Var Benchmark = CALCULATE(sum('Daily Position'[MARKET VALUE BASE]),'Benchmark Portfolio Mapping'[Position_Type] = "Benchmark")                 

        Var Portfolio = CALCULATE(sum('Daily Position'[MARKET VALUE BASE]),'Benchmark Portfolio Mapping'[Position_Type] = "Portfolio")

        RETURN

        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark/1000000,Portfolio/1000000)
MEASURE 'Daily Position'[Benchmark_Weight_BM] = 
        Var Benchmark = CALCULATE(sum('Daily Position'[BENCHMARK_WEIGHT_EOD]),'Daily Position'[Position_Type]= "Benchmark" )
        Var Portfolio = CALCULATE(sum('Daily Position'[BENCHMARK_WEIGHT_EOD]), 'Daily Position'[Position_Type] = "Portfolio")

        RETURN

        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
MEASURE 'ESG Trucost Climate'[Carbon_Scope_3_tonnes_CO2e_Downstream_BM] = 
        Var Benchmark = CALCULATE(sum('ESG Trucost Climate'[Absolute_GHG_Scope_3_Downstream_Total]),'Daily Position'[Position_Type]= "Benchmark" )
        Var Portfolio = CALCULATE(sum('ESG Trucost Climate'[Absolute_GHG_Scope_3_Downstream_Total]), 'Daily Position'[Position_Type] = "Portfolio")

        RETURN

        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
MEASURE 'ESG Trucost Climate'[Carbon_Scope_3_tonnes_CO2e_Upstream_BM] = 
        Var Benchmark = CALCULATE(sum('ESG Trucost Climate'[Absolute_GHG_Scope_3_Upstream_Total]),'Daily Position'[Position_Type]= "Benchmark" )
        Var Portfolio = CALCULATE(sum('ESG Trucost Climate'[Absolute_GHG_Scope_3_Upstream_Total]), 'Daily Position'[Position_Type] = "Portfolio")

        RETURN

        if (SELECTEDVALUE('Benchmark Portfolio Mapping'[Position_Type]) = "Benchmark" ,Benchmark,Portfolio)
MEASURE 'Daily Position'[QUANTITY_SUM] = SUM('Daily Position'[QUANTITY]) // Explicit measure to be used in Excel Pivot Table
MEASURE 'GS Asset'[SHARES_OUTSTANDING_SUM] = SUM('GS Asset'[SHARES_OUTSTANDING_QUANTITY]) // Explicit measure to be used in Excel Pivot Table

MEASURE 'Market Cap Type'[Market_Cap_Switch] = SELECTEDVALUE('Market Cap Type'[Market_Cap_Code],1)
MEASURE 'Daily Position'[Market_Cap_BM_Fund_Count] = CALCULATE(DISTINCTCOUNT('Daily Position'[FUND] ),'Daily Position'[Position_Type] ="Portfolio")
---- MODEL MEASURES END ----


