Portfolio_Asset_Matrix MV CR Intensity Switch_BM New = 
VAR _ScopeSelect   = SELECTEDVALUE('Scope Emission Types'[Scope_Type_Code], 1)
VAR _MarketCapMode = SELECTEDVALUE('Market Cap Type'[Market_Cap_Code], 1)  // 1=MC, 2=EVIC

// 1) Ownership by Asset (ISIN), restricted to Portfolio positions
VAR OwnershipByAsset =
    CALCULATETABLE(
        ADDCOLUMNS(
            SUMMARIZE('Daily Position', 'GS Asset'[ISIN]),
            "@Ownership",
                IF(
                    _MarketCapMode = 2,
                    SUM('Daily Position'[Ownership_Factor_EVIC]),
                    SUM('Daily Position'[Ownership_Factor_MC])
                )
        ),
        KEEPFILTERS('Benchmark Portfolio Mapping'[Position_Type] = "Portfolio")
    )

// 2) Carbon + Revenue by Asset (compute once per ISIN using VARs to avoid repeated SUMs)
VAR CarbonRevByAsset =
    ADDCOLUMNS(
        VALUES('GS Asset'[ISIN]),
        "@Revenue", 
            CALCULATE(SUM('ESG Trucost Climate'[Revenue_AUD_mn])),
        "@Carbon",
            VAR _Base =
                CALCULATE(
                    SUM('ESG Trucost Climate'[Carbon_Scope_1_tonnes_CO2e]) +
                    SUM('ESG Trucost Climate'[Carbon_Scope_2_tonnes_CO2e])
                )
            VAR _Down =
                CALCULATE(SUM('ESG Trucost Climate'[Absolute_GHG_Scope_3_Downstream_Total]))
            VAR _Up   =
                CALCULATE(SUM('ESG Trucost Climate'[Absolute_GHG_Scope_3_Upstream_Total]))
            RETURN
                SWITCH(
                    _ScopeSelect,
                    1, _Base,
                    2, _Base + _Down,
                    3, _Base + _Up,
                    4, _Base + _Down + _Up,
                    _Base
                )
    )

// 3) Join once, then compute ratio of sums
VAR Joined =
    NATURALINNERJOIN(OwnershipByAsset, CarbonRevByAsset)

VAR Numerator =
    SUMX(
        Joined,
        VAR own = COALESCE([@Ownership], 0)
        RETURN IF(own > 0, own * COALESCE([@Carbon], 0))
    )

VAR Denominator =
    SUMX(
        Joined,
        VAR own = COALESCE([@Ownership], 0)
        RETURN IF(own > 0, own * COALESCE([@Revenue], 0))
    )

RETURN
    DIVIDE(Numerator, Denominator)