Ownership_Factor_MC = 
VAR _MC = 'Daily Position'[Market_Cap_Base]
VAR _Shares = RELATED('GS Asset'[SHARES_OUTSTANDING_QUANTITY])
RETURN
    IF( _MC > 0, 
        DIVIDE('Daily Position'[MARKET VALUE BASE], _MC),
        // Fallback logic from original code:
        IF('Daily Position'[MARKET VALUE BASE] > 0 && _Shares > 0, 
            DIVIDE('Daily Position'[QUANTITY], _Shares), 
            0
        )
    )