Ownership_Factor_EVIC = 
VAR _EVIC = 'Daily Position'[EVIC_Base]
VAR _Shares = RELATED('GS Asset'[SHARES_OUTSTANDING_QUANTITY])
RETURN
    IF( _EVIC > 0, 
        DIVIDE('Daily Position'[MARKET VALUE BASE], _EVIC),
        IF('Daily Position'[MARKET VALUE BASE] > 0 && _Shares > 0, 
            DIVIDE('Daily Position'[QUANTITY], _Shares), 
            0
        )
    )
